package Enhancement2;

import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

import org.testng.annotations.BeforeSuite;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;

public class codesnippet {
	WebDriver driver;
	ExtentHtmlReporter Htmlreporter;
	ExtentReports Extent;
	@BeforeSuite
	public void BeforeSuite() {
		Htmlreporter = new ExtentHtmlReporter("code snippet 1.html");
		Extent = new ExtentReports();
		Extent.attachReporter(Htmlreporter);
	}	
	@Test
	public void TC_01() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@type='password']")).sendKeys("123456");
		Thread.sleep(500);
		driver.manage().window().maximize();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='submit-wrap']")).click();
		Thread.sleep(3000);
		// search user asif
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("john");
		Thread.sleep(300);
		String a = driver.findElement(By.xpath("//div[@data-name='john']")).getText();
		Assert.assertEquals("John", a);
		Thread.sleep(300);
		driver.findElement(By.xpath("//div[@data-name='john']")).click();
		Thread.sleep(500);
		// click on three dots
		driver.findElement(By.xpath("//div[@class='conversation-header-options-btn']")).click();
		Thread.sleep(500);
		String b = driver.findElement(By.xpath("//div[@class='conversation-header-option code-header-btn']")).getText();
		Assert.assertEquals("Code Snippet", b);
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='conversation-header-option code-header-btn']")).click();
		Thread.sleep(500);
		WebElement a1 = driver.findElement(By.xpath("//div[@class='CodeMirror-lines']"));
		Actions act = new Actions(driver);
		act.moveToElement(a1).sendKeys("hii").build().perform();
		Thread.sleep(500);
		// search user asif
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).clear();
		Thread.sleep(300);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("asif");
		Thread.sleep(300);
		String c = driver.findElement(By.xpath("//div[@data-name='asif']")).getText();
		Assert.assertEquals("Asif", c);
		Thread.sleep(300);
		driver.findElement(By.xpath("//div[@data-name='asif']")).click();
		Thread.sleep(500);
		String d = driver.findElement(By.xpath("//input[@type='button']")).getText();
		Assert.assertEquals("", d);
		Thread.sleep(400);
		ExtentTest test= Extent.createTest("Click on code snippet enter data & click on other user");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Gmail: Maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("Search: john");
		test.pass(a);
		test.info("User: Click on john");
		test.info("Three dots: Click on three dots");
		test.pass(b);
		test.info("Code snippet: Click on code snippet");
		test.info("Text: Enter text hii");
		test.info("User: Click on other user");
		test.pass(c);
		test.info("User: Click on asif");			
		test.info("EXPECTED RESULT:: It should not display code snippet preview");
		test.pass(d);
		test.log(Status.PASS,"ACTUAL RESULT:: It is not displaying code snippet preview");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(500);
		driver.close();
	}
	@Test
	public void TC_02() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@type='password']")).sendKeys("123456");
		Thread.sleep(500);
		driver.manage().window().maximize();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='submit-wrap']")).click();
		Thread.sleep(3000);
		// search user asif
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("john");
		Thread.sleep(300);
		String a = driver.findElement(By.xpath("//div[@data-name='john']")).getText();
		Assert.assertEquals("John", a);
		Thread.sleep(300);
		driver.findElement(By.xpath("//div[@data-name='john']")).click();
		Thread.sleep(500);
		String b = driver.findElement(By.xpath("//span[@class='c-s-e-b']")).getText();
		Assert.assertEquals("Edit", b);
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='c-s-e-b']")).click();
		Thread.sleep(500);
		Thread.sleep(500);
		WebElement a1 = driver.findElement(By.xpath("//div[@class='CodeMirror-code']"));
		Actions act = new Actions(driver);
		act.moveToElement(a1).sendKeys("hii dvdv").build().perform();
		Thread.sleep(500);
		// search user asif
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).clear();
		Thread.sleep(300);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("asif");
		Thread.sleep(300);
		String c = driver.findElement(By.xpath("//div[@data-name='asif']")).getText();
		Assert.assertEquals("Asif", c);
		Thread.sleep(300);
		driver.findElement(By.xpath("//div[@data-name='asif']")).click();
		Thread.sleep(500);
		String d = driver.findElement(By.xpath("//input[@value='NO']")).getAttribute("value");
		Assert.assertEquals("NO", d);
		Thread.sleep(400);
		ExtentTest test= Extent.createTest("Click on edit code & click on other user");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Gmail: Maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("Search: john");
		test.pass(a);
		test.info("User: Click on john");
		test.info("Code snippet: Click on code snippet");
		test.pass(b);
		test.info("Edit: Click on edit");
		test.info("Text: Enter text how r u");
		test.pass(c);
		test.info("User: Click on asif");			
		test.info("EXPECTED RESULT:: It should display pop up: Changes made in snippet will not be saved, Do you want to continue");
		test.pass(d);
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying pop up: Changes made in snippet will not be saved, Do you want to continue");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(500);
		driver.close();
	}
	@Test
	public void TC_03() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@type='password']")).sendKeys("123456");
		Thread.sleep(500);
		driver.manage().window().maximize();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='submit-wrap']")).click();
		Thread.sleep(500);
		// search user asif
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("john");
		Thread.sleep(300);
		String a = driver.findElement(By.xpath("//div[@data-name='john']")).getText();
		Assert.assertEquals("John", a);
		Thread.sleep(300);
		driver.findElement(By.xpath("//div[@data-name='john']")).click();
		Thread.sleep(500);
		String b = driver.findElement(By.xpath("//span[@class='c-s-e-b']")).getText();
		Assert.assertEquals("Edit", b);
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='c-s-e-b']")).click();
		Thread.sleep(500);
		WebElement a1 = driver.findElement(By.xpath("//div[@class='CodeMirror-code']"));
		Actions act = new Actions(driver);
		act.moveToElement(a1).sendKeys("hii dvdv").build().perform();
		Thread.sleep(500);
		// search user asif
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).clear();
		Thread.sleep(300);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("asif");
		Thread.sleep(300);
		String c = driver.findElement(By.xpath("//div[@data-name='asif']")).getText();
		Assert.assertEquals("Asif", c);
		Thread.sleep(300);
		driver.findElement(By.xpath("//div[@data-name='asif']")).click();
		Thread.sleep(500);
		// click on cross symbol
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='close-modal-btn']")).click();
		Thread.sleep(500);
		String d = driver.findElement(By.xpath("//input[@value='SUBMIT']")).getAttribute("value");
		Assert.assertEquals("SUBMIT", d);
		Thread.sleep(400);
		ExtentTest test= Extent.createTest("Click on edit code & click on other user & click on close symbol");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Gmail: Maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("search: john");
		test.pass(a);
		test.info("User: Click on john");
		test.info("Code snippet: Click on code snippet");
		test.pass(b);
		test.info("Edit: Click on edit");
		test.info("Text: Enter text how r u");
		test.pass(c);
		test.info("User: Click on asif");	
		test.info("Close symbol: Click on close symbol");
		test.pass(d);
		test.info("Submit: Click on submit");
		test.info("EXPECTED RESULT:: It should display the code snippet preview");
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying the code snippet preview");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(500);
		driver.close();
	}
	@Test
	public void TC_04() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@type='password']")).sendKeys("123456");
		Thread.sleep(500);
		driver.manage().window().maximize();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='submit-wrap']")).click();
		Thread.sleep(500);
		// search user asif
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("john");
		Thread.sleep(300);
		String a = driver.findElement(By.xpath("//div[@data-name='john']")).getText();
		Assert.assertEquals("John", a);
		Thread.sleep(300);
		driver.findElement(By.xpath("//div[@data-name='john']")).click();
		Thread.sleep(500);
		String b = driver.findElement(By.xpath("//span[@class='c-s-e-b']")).getText();
		Assert.assertEquals("Edit", b);
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='c-s-e-b']")).click();
		Thread.sleep(500);
		WebElement a1 = driver.findElement(By.xpath("//div[@class='CodeMirror-code']"));
		Actions act = new Actions(driver);
		act.moveToElement(a1).sendKeys("hii dvdv").build().perform();
		Thread.sleep(500);
		// search user asif
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).clear();
		Thread.sleep(300);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("asif");
		Thread.sleep(300);
		String c = driver.findElement(By.xpath("//div[@data-name='asif']")).getText();
		Assert.assertEquals("Asif", c);
		Thread.sleep(300);
		driver.findElement(By.xpath("//div[@data-name='asif']")).click();
		Thread.sleep(500);
		Thread.sleep(500);
		String d = driver.findElement(By.xpath("//input[@class='btn btn-success btn-no']")).getAttribute("class");
		Assert.assertEquals("btn btn-success btn-no", d);
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@value='NO']")).click();
		Thread.sleep(500);
		String e = driver.findElement(By.xpath("//input[@value='SUBMIT']")).getAttribute("value");
		Assert.assertEquals("SUBMIT", e);
		Thread.sleep(400);
		ExtentTest test= Extent.createTest("Click on edit code & click on other user & click on NO");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Gmail: Maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("search: john");
		test.pass(a);
		test.info("User: Click on john");
		test.info("Code snippet: Click on code snippet");
		test.pass(b);
		test.info("Edit: Click on edit");
		test.info("Text: Enter text how r u");
		test.pass(c);
		test.info("User: Click on asif");		
		test.pass(d);
		test.info("No: Click on NO");
		test.info("EXPECTED RESULT:: It should display the code snippet preview");
		test.pass(e);
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying the code snippet preview");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(500);
		driver.close();
	}
	@Test
	public void TC_05() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@type='password']")).sendKeys("123456");
		Thread.sleep(500);
		driver.manage().window().maximize();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='submit-wrap']")).click();
		Thread.sleep(500);
		// search user asif
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("john");
		Thread.sleep(300);
		String a = driver.findElement(By.xpath("//div[@data-name='john']")).getText();
		Assert.assertEquals("John", a);
		Thread.sleep(300);
		driver.findElement(By.xpath("//div[@data-name='john']")).click();
		Thread.sleep(500);
		String b = driver.findElement(By.xpath("//span[@class='c-s-e-b']")).getText();
		Assert.assertEquals("Edit", b);
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='c-s-e-b']")).click();
		Thread.sleep(500);
		WebElement a1 = driver.findElement(By.xpath("//div[@class='CodeMirror-code']"));
		Actions act = new Actions(driver);
		act.moveToElement(a1).sendKeys("hii dvdv").build().perform();
		Thread.sleep(500);
		// search user asif
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).clear();
		Thread.sleep(300);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("asif");
		Thread.sleep(300);
		String c = driver.findElement(By.xpath("//div[@data-name='asif']")).getText();
		Assert.assertEquals("Asif", c);
		Thread.sleep(300);
		driver.findElement(By.xpath("//div[@data-name='asif']")).click();
		Thread.sleep(500);
		String d = driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).getAttribute("class");
		Assert.assertEquals("btn btn-success btn-yes", d);
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@value='YES']")).click();
		Thread.sleep(500);
		String e = driver.findElement(By.xpath("//div[@data-name='asif']")).getText();
		Assert.assertEquals("Asif", e);
		Thread.sleep(400);
		ExtentTest test= Extent.createTest("Click on edit code & click on other user & click on YES");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Gmail: Maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("search: john");
		test.pass(a);
		test.info("User: Click on john");
		test.info("Code snippet: Click on code snippet");
		test.pass(b);
		test.info("Edit: Click on edit");
		test.info("Text: Enter text how r u");
		test.pass(c);
		test.info("User: Click on asif");		
		test.pass(d);
		test.info("YES: Click on YES");
		test.info("EXPECTED RESULT:: It should display the other user name");
		test.pass(e);
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying the other user name");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(500);
		driver.close();
	}
	@Test
	public void TC_006() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@type='password']")).sendKeys("123456");
		Thread.sleep(500);
		driver.manage().window().maximize();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='submit-wrap']")).click();
		Thread.sleep(500);
		// search group codesnippet
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("code snippet grp");
		Thread.sleep(300);
		String a = driver.findElement(By.xpath("//div[@data-name='code snippet grp']")).getText();
		Assert.assertEquals("Code Snippet Grp", a);
		Thread.sleep(300);
		driver.findElement(By.xpath("//div[@data-name='code snippet grp']")).click();
		Thread.sleep(500);
		String b = driver.findElement(By.xpath("//span[@class='c-s-e-b']")).getText();
		Assert.assertEquals("Edit", b);
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='c-s-e-b']")).click();
		Thread.sleep(500);
		Thread.sleep(500);
		WebElement a1 = driver.findElement(By.xpath("//div[@class='CodeMirror-code']"));
		Actions act = new Actions(driver);
		act.moveToElement(a1).sendKeys("hii dvdv").build().perform();
		Thread.sleep(500);
		// search user asif
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).clear();
		Thread.sleep(300);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("asif");
		Thread.sleep(300);
		String c = driver.findElement(By.xpath("//div[@data-name='asif']")).getText();
		Assert.assertEquals("Asif", c);
		Thread.sleep(300);
		driver.findElement(By.xpath("//div[@data-name='asif']")).click();
		Thread.sleep(500);
		String d = driver.findElement(By.xpath("//input[@value='NO']")).getAttribute("value");
		Assert.assertEquals("NO", d);
		Thread.sleep(400);
		ExtentTest test= Extent.createTest("Click on group, Click on edit code & click on other user");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Gmail: Maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("search: code snippet grp");
		test.pass(a);
		test.info("Goup: Click on code snippet grp");
		test.info("Code snippet: Click on code snippet");
		test.pass(b);
		test.info("Edit: Click on edit");
		test.info("Text: Enter text how r u");
		test.pass(c);
		test.info("User: Click on asif");		
		test.info("EXPECTED RESULT:: It should display pop up: Changes made in snippet will not be saved, Do you want to continue");
		test.pass(d);
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying pop up: Changes made in snippet will not be saved, Do you want to continue");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(500);
		driver.close();
	}
	@Test
	public void TC_07() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@type='password']")).sendKeys("123456");
		Thread.sleep(500);
		driver.manage().window().maximize();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='submit-wrap']")).click();
		Thread.sleep(500);
		// search group codesnippet
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("code snippet grp");
		Thread.sleep(300);
		String a = driver.findElement(By.xpath("//div[@data-name='code snippet grp']")).getText();
		Assert.assertEquals("Code Snippet Grp", a);
		Thread.sleep(300);
		driver.findElement(By.xpath("//div[@data-name='code snippet grp']")).click();
		Thread.sleep(500);
		String b = driver.findElement(By.xpath("//span[@class='c-s-e-b']")).getText();
		Assert.assertEquals("Edit", b);
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='c-s-e-b']")).click();
		Thread.sleep(500);
		WebElement a1 = driver.findElement(By.xpath("//div[@class='CodeMirror-code']"));
		Actions act = new Actions(driver);
		act.moveToElement(a1).sendKeys("hii dvdv").build().perform();
		Thread.sleep(500);
		// search user asif
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).clear();
		Thread.sleep(300);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("asif");
		Thread.sleep(500);
		String c = driver.findElement(By.xpath("//div[@data-name='asif']")).getText();
		Assert.assertEquals("Asif", c);
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='asif']")).click();
		// click on cross symbol
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='close-modal-btn']")).click();
		Thread.sleep(500);
		String d = driver.findElement(By.xpath("//input[@value='SUBMIT']")).getAttribute("value");
		Assert.assertEquals("SUBMIT", d);
		Thread.sleep(400);
		ExtentTest test= Extent.createTest("Click on group, Click on edit code & click on other user & click on close symbol");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Gmail: Maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("search: code snippet grp");
		test.pass(a);
		test.info("Goup: Click on code snippet grp");
		test.info("Code snippet: Click on code snippet");
		test.pass(b);
		test.info("Edit: Click on edit");
		test.info("Text: Enter text how r u");
		test.pass(c);
		test.info("User: Click on asif");		
		test.info("Close symbol: Click on close symbol");
		test.info("EXPECTED RESULT:: It should display the code snippet preview");
		test.pass(d);
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying the code snippet preview");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(500);
		driver.close();
	}
	@Test
	public void TC_08() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@type='password']")).sendKeys("123456");
		Thread.sleep(500);
		driver.manage().window().maximize();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='submit-wrap']")).click();
		Thread.sleep(500);
		// search group codesnippet
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("code snippet grp");
		Thread.sleep(300);
		String a = driver.findElement(By.xpath("//div[@data-name='code snippet grp']")).getText();
		Assert.assertEquals("Code Snippet Grp", a);
		Thread.sleep(300);
		driver.findElement(By.xpath("//div[@data-name='code snippet grp']")).click();
		Thread.sleep(500);
		String b = driver.findElement(By.xpath("//span[@class='c-s-e-b']")).getText();
		Assert.assertEquals("Edit", b);
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='c-s-e-b']")).click();
		Thread.sleep(500);
		WebElement a1 = driver.findElement(By.xpath("//div[@class='CodeMirror-code']"));
		Actions act = new Actions(driver);
		act.moveToElement(a1).sendKeys("hii dvdv").build().perform();
		Thread.sleep(500);
		// search user asif
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).clear();
		Thread.sleep(300);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("asif");
		Thread.sleep(500);
		String c = driver.findElement(By.xpath("//div[@data-name='asif']")).getText();
		Assert.assertEquals("Asif", c);
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='asif']")).click();
		Thread.sleep(500);
		String d = driver.findElement(By.xpath("//input[@class='btn btn-success btn-no']")).getAttribute("class");
		Assert.assertEquals("btn btn-success btn-no", d);
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@value='NO']")).click();
		Thread.sleep(500);
		String e = driver.findElement(By.xpath("//input[@value='SUBMIT']")).getAttribute("value");
		Assert.assertEquals("SUBMIT", e);
		Thread.sleep(400);
		ExtentTest test= Extent.createTest("Click on group, Click on edit code & click on other user & click on NO");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Gmail: Maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("search: code snippet grp");
		test.pass(a);
		test.info("Goup: Click on code snippet grp");
		test.info("Code snippet: Click on code snippet");
		test.pass(b);
		test.info("Edit: Click on edit");
		test.info("Text: Enter text how r u");
		test.pass(c);
		test.info("User: Click on asif");		
		test.pass(d);
		test.info("No: Click on NO");
		test.info("EXPECTED RESULT:: It should display the code snippet preview");
		test.pass(e);
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying the code snippet preview");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(500);
		driver.close();
	}
	@Test
	public void TC_09() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@type='password']")).sendKeys("123456");
		Thread.sleep(500);
		driver.manage().window().maximize();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='submit-wrap']")).click();
		Thread.sleep(500);
		// search group codesnippet
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("code snippet grp");
		Thread.sleep(300);
		String a = driver.findElement(By.xpath("//div[@data-name='code snippet grp']")).getText();
		Assert.assertEquals("Code Snippet Grp", a);
		Thread.sleep(300);
		driver.findElement(By.xpath("//div[@data-name='code snippet grp']")).click();
		Thread.sleep(500);
		String b = driver.findElement(By.xpath("//span[@class='c-s-e-b']")).getText();
		Assert.assertEquals("Edit", b);
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='c-s-e-b']")).click();
		Thread.sleep(500);
		WebElement a1 = driver.findElement(By.xpath("//div[@class='CodeMirror-code']"));
		Actions act = new Actions(driver);
		act.moveToElement(a1).sendKeys("hii dvdv").build().perform();
		Thread.sleep(500);
		// search user asif
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).clear();
		Thread.sleep(300);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("asif");
		Thread.sleep(500);
		String c = driver.findElement(By.xpath("//div[@data-name='asif']")).getText();
		Assert.assertEquals("Asif", c);
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='asif']")).click();
		Thread.sleep(500);
		String d = driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).getAttribute("class");
		Assert.assertEquals("btn btn-success btn-yes", d);
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@value='YES']")).click();
		Thread.sleep(500);
		String e = driver.findElement(By.xpath("//div[@data-name='asif']")).getText();
		Assert.assertEquals("Asif", e);
		Thread.sleep(400);
		ExtentTest test= Extent.createTest("Click on group, Click on edit code & click on other user & click on YES");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Gmail: Maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("search: code snippet grp");
		test.pass(a);
		test.info("Goup: Click on code snippet grp");
		test.info("Code snippet: Click on code snippet");
		test.pass(b);
		test.info("Edit: Click on edit");
		test.info("Text: Enter text how r u");
		test.pass(c);
		test.info("User: Click on asif");
		test.pass(d);
		test.info("YES: Click on YES");
		test.info("EXPECTED RESULT:: It should display the other user name");
		test.pass(e);
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying the other user name");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(500);
		driver.close();
	}
	@AfterMethod
	public void aftersuite() {
		Extent.flush();  
	}

}
