package Enhancement2;

import java.awt.AWTException;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class QRPpanel {
	WebDriver driver;
	ExtentHtmlReporter htmlReporter;
	ExtentReports extent;

	String extentReportImage = System.getProperty("user.dir")+ "extentReportImage.png";
	@BeforeSuite
	public void StartTest() {
		htmlReporter = new ExtentHtmlReporter("QRPpanel.html");
		extent = new ExtentReports();
		extent.attachReporter(htmlReporter);
	}
	@Test
	public void test00() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		//driver.findElement(By.xpath("//div[@data-name='naga']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-floating-button']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='ibuzr-floating-buttons-container active']")).getAttribute("class");
		Assert.assertEquals(a, "ibuzr-floating-buttons-container active");
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on QRP panel");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on QRP panel");
		test.info("EXPECTED RESULT:: It should click on QRP panel");
		test.pass(a);
		test.log(Status.PASS,"ACTUAL RESULT::  It is clicking on QRP panel");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
    }
	@Test
	public void test01() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		//driver.findElement(By.xpath("//div[@data-name='naga']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-floating-button']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='ibuzr-floating-buttons-container active']")).getAttribute("class");
		Assert.assertEquals(a, "ibuzr-floating-buttons-container active");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-floating-button active']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='ibuzr-floating-buttons-container']")).getAttribute("class");
		Assert.assertEquals(a1, "ibuzr-floating-buttons-container");
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on QRP panel");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on QRP panel");
		test.info("Click on close button in QRP panel");
		test.info("EXPECTED RESULT:: It should close the QRP panel");
		test.pass(a);
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is closing the QRP panel");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
    }
	@Test
	public void test02() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		//driver.findElement(By.xpath("//div[@data-name='naga']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-floating-button']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='ibuzr-floating-buttons-container active']")).getAttribute("class");
		Assert.assertEquals(a, "ibuzr-floating-buttons-container active");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='ibuzr-doc-btn ibuzr-history-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='ibuzr-doc-btn ibuzr-history-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@data-type='2']")).getText();
		Assert.assertEquals(a1, "DOCUMENTS");
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on documents in QRP panel");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on QRP panel");
		test.info("Click on document icon");
		test.info("EXPECTED RESULT:: It should click on document icon in QRP panel");
		test.pass(a);
		Assert.assertEquals(a2, "ibuzr-doc-btn ibuzr-history-btn");
		test.pass(a2);
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is clicking on document icon in QRP panel");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
    }
	@Test
	public void test03() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		//driver.findElement(By.xpath("//div[@data-name='naga']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-floating-button']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='ibuzr-floating-buttons-container active']")).getAttribute("class");
		Assert.assertEquals(a, "ibuzr-floating-buttons-container active");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='ibuzr-doc-btn ibuzr-history-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='ibuzr-doc-btn ibuzr-history-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@data-type='2']")).getText();
		Assert.assertEquals(a1, "DOCUMENTS");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-canned-history-wrapper']")).click();
		Thread.sleep(2000);
		String a3=driver.findElement(By.xpath("//span[@class='messenger-attachment-link-name']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Send any doc from QRP panel");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on QRP panel");
		test.info("Click on document icon");
		test.info("Send any doc");
		test.info("EXPECTED RESULT:: It should send the doc from QRP panel");
		test.pass(a);
		Assert.assertEquals(a2, "ibuzr-doc-btn ibuzr-history-btn");
		test.pass(a2);
		test.pass(a1);
		Assert.assertEquals(a3, "VenkataReddy_Au.....zip");
		test.pass(a3);
		test.log(Status.PASS,"ACTUAL RESULT::  It is sending the doc from QRP panel");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
    }
	@Test
	public void test04() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		//driver.findElement(By.xpath("//div[@data-name='naga']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-floating-button']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='ibuzr-floating-buttons-container active']")).getAttribute("class");
		Assert.assertEquals(a, "ibuzr-floating-buttons-container active");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='ibuzr-doc-btn ibuzr-history-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='ibuzr-doc-btn ibuzr-history-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@data-type='2']")).getText();
		Assert.assertEquals(a1, "DOCUMENTS");
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//span[@class='close-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//span[@class='close-btn']")).click();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on documents & Click on close button in QRP panel");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on QRP panel");
		test.info("Click on document icon");
		test.info("Click on close button");
		test.info("EXPECTED RESULT:: It should click on close button in QRP panel");
		test.pass(a);
		Assert.assertEquals(a2, "ibuzr-doc-btn ibuzr-history-btn");
		test.pass(a2);
		test.pass(a1);
		Assert.assertEquals(a3, "close-btn");
		test.pass(a3);
		test.log(Status.PASS,"ACTUAL RESULT::  It is clicking on close button in QRP panel");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
    }
	@Test
	public void test05() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		//driver.findElement(By.xpath("//div[@data-name='naga']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-floating-button']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='ibuzr-floating-buttons-container active']")).getAttribute("class");
		Assert.assertEquals(a, "ibuzr-floating-buttons-container active");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='ibuzr-image-btn ibuzr-history-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='ibuzr-image-btn ibuzr-history-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@data-type='3']")).getText();
		Assert.assertEquals(a1, "IMAGES & VIDEOS");
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on image icon in QRP panel");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on QRP panel");
		test.info("Click on image icon");
		test.info("EXPECTED RESULT:: It should click on image icon in QRP panel");
		test.pass(a);
		Assert.assertEquals(a2, "ibuzr-image-btn ibuzr-history-btn");
		test.pass(a2);
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is clicking on image icon in QRP panel");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
    }
	@Test
	public void test06() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		//driver.findElement(By.xpath("//div[@data-name='naga']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-floating-button']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='ibuzr-floating-buttons-container active']")).getAttribute("class");
		Assert.assertEquals(a, "ibuzr-floating-buttons-container active");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='ibuzr-image-btn ibuzr-history-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='ibuzr-image-btn ibuzr-history-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@data-type='3']")).getText();
		Assert.assertEquals(a1, "IMAGES & VIDEOS");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-canned-history-wrapper']")).click();
		Thread.sleep(2000);
		String a3=driver.findElement(By.xpath("//img[@class='image_attachment']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Send any image/video from QRP panel");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on QRP panel");
		test.info("Click on image icon");
		test.info("Send any image/video");
		test.info("EXPECTED RESULT:: It should send the image/video from QRP panel");
		test.pass(a);
		Assert.assertEquals(a2, "ibuzr-image-btn ibuzr-history-btn");
		test.pass(a2);
		test.pass(a1);
		Assert.assertEquals(a3, "image_attachment");
		test.pass(a3);
		test.log(Status.PASS,"ACTUAL RESULT::  It is sending the image/video from QRP panel");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
    }
	@Test
	public void test07() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		//driver.findElement(By.xpath("//div[@data-name='naga']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-floating-button']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='ibuzr-floating-buttons-container active']")).getAttribute("class");
		Assert.assertEquals(a, "ibuzr-floating-buttons-container active");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='ibuzr-image-btn ibuzr-history-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='ibuzr-image-btn ibuzr-history-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@data-type='3']")).getText();
		Assert.assertEquals(a1, "IMAGES & VIDEOS");
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//span[@class='close-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//span[@class='close-btn']")).click();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on image icon & Click on close button in QRP panel");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on QRP panel");
		test.info("Click on image icon");
		test.info("Click on close button");
		test.info("EXPECTED RESULT:: It should click on close button in QRP panel");
		test.pass(a);
		Assert.assertEquals(a2, "ibuzr-image-btn ibuzr-history-btn");
		test.pass(a2);
		test.pass(a1);
		Assert.assertEquals(a3, "close-btn");
		test.pass(a3);
		test.log(Status.PASS,"ACTUAL RESULT::  It is clicking on close button in QRP panel");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
    }
	@Test
	public void test08() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		//driver.findElement(By.xpath("//div[@data-name='naga']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-floating-button']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='ibuzr-floating-buttons-container active']")).getAttribute("class");
		Assert.assertEquals(a, "ibuzr-floating-buttons-container active");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='ibuzr-link-btn ibuzr-history-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='ibuzr-link-btn ibuzr-history-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[13]/div[1]/div/div[3]/div[1]/div[1]/span[1]")).getText();
		Assert.assertEquals(a1, "LINKS");
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on link icon in QRP panel");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on QRP panel");
		test.info("Click on link icon");
		test.info("EXPECTED RESULT:: It should click on link icon in QRP panel");
		test.pass(a);
		Assert.assertEquals(a2, "ibuzr-link-btn ibuzr-history-btn");
		test.pass(a2);
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is clicking on link icon in QRP panel");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
    }
	@Test
	public void test09() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		//driver.findElement(By.xpath("//div[@data-name='naga']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-floating-button']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='ibuzr-floating-buttons-container active']")).getAttribute("class");
		Assert.assertEquals(a, "ibuzr-floating-buttons-container active");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='ibuzr-link-btn ibuzr-history-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='ibuzr-link-btn ibuzr-history-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[13]/div[1]/div/div[3]/div[1]/div[1]/span[1]")).getText();
		Assert.assertEquals(a1, "LINKS");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-canned-history-wrapper']")).click();
		Thread.sleep(2000);
		String a3=driver.findElement(By.xpath("//div[@class='conversation-message-meta-link']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Send any link from QRP panel");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on QRP panel");
		test.info("Click on link icon");
		test.info("Send any link");
		test.info("EXPECTED RESULT:: It should send the link from QRP panel");
		test.pass(a);
		Assert.assertEquals(a2, "ibuzr-link-btn ibuzr-history-btn");
		test.pass(a2);
		test.pass(a1);
		Assert.assertEquals(a3, "conversation-message-meta-link");
		test.pass(a3);
		test.log(Status.PASS,"ACTUAL RESULT::  It is sending the link from QRP panel");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
    }
	@Test
	public void test10() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		//driver.findElement(By.xpath("//div[@data-name='naga']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-floating-button']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='ibuzr-floating-buttons-container active']")).getAttribute("class");
		Assert.assertEquals(a, "ibuzr-floating-buttons-container active");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='ibuzr-link-btn ibuzr-history-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='ibuzr-link-btn ibuzr-history-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[13]/div[1]/div/div[3]/div[1]/div[1]/span[1]")).getText();
		Assert.assertEquals(a1, "LINKS");
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//span[@class='close-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//span[@class='close-btn']")).click();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on link icon & Click on close button in QRP panel");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on QRP panel");
		test.info("Click on link icon");
		test.info("Click on close button");
		test.info("EXPECTED RESULT:: It should click on close button in QRP panel");
		test.pass(a);
		Assert.assertEquals(a2, "ibuzr-link-btn ibuzr-history-btn");
		test.pass(a2);
		test.pass(a1);
		Assert.assertEquals(a3, "close-btn");
		test.pass(a3);
		test.log(Status.PASS,"ACTUAL RESULT::  It is clicking on close button in QRP panel");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
    }
	@Test
	public void test11() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		//driver.findElement(By.xpath("//div[@data-name='naga']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-floating-button']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='ibuzr-floating-buttons-container active']")).getAttribute("class");
		Assert.assertEquals(a, "ibuzr-floating-buttons-container active");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='ibuzr-contacts-btn ibuzr-history-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='ibuzr-contacts-btn ibuzr-history-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[13]/div[1]/div/div[3]/div[1]/div[1]/span[1]")).getText();
		Assert.assertEquals(a1, "CONTACTS");
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on contacts icon in QRP panel");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on QRP panel");
		test.info("Click on contacts icon");
		test.info("EXPECTED RESULT:: It should click on contacts icon in QRP panel");
		test.pass(a);
		Assert.assertEquals(a2, "ibuzr-contacts-btn ibuzr-history-btn");
		test.pass(a2);
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is clicking on contacts icon in QRP panel");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
    }
	@Test
	public void test12() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		//driver.findElement(By.xpath("//div[@data-name='naga']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-floating-button']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='ibuzr-floating-buttons-container active']")).getAttribute("class");
		Assert.assertEquals(a, "ibuzr-floating-buttons-container active");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='ibuzr-contacts-btn ibuzr-history-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='ibuzr-contacts-btn ibuzr-history-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[13]/div[1]/div/div[3]/div[1]/div[1]/span[1]")).getText();
		Assert.assertEquals(a1, "CONTACTS");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-canned-history-wrapper']")).click();
		Thread.sleep(2000);
		String a3=driver.findElement(By.xpath("//div[@class='conversation-message-contact']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Send any contact from QRP panel");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on QRP panel");
		test.info("Click on contacts icon");
		test.info("Send any contact");
		test.info("EXPECTED RESULT:: It should send the contact from QRP panel");
		test.pass(a);
		Assert.assertEquals(a2, "ibuzr-contacts-btn ibuzr-history-btn");
		test.pass(a2);
		test.pass(a1);
		Assert.assertEquals(a3, "conversation-message-contact");
		test.pass(a3);
		test.log(Status.PASS,"ACTUAL RESULT::  It is sending the contact from QRP panel");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
    }
	@Test
	public void test13() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		//driver.findElement(By.xpath("//div[@data-name='naga']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-floating-button']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='ibuzr-floating-buttons-container active']")).getAttribute("class");
		Assert.assertEquals(a, "ibuzr-floating-buttons-container active");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='ibuzr-contacts-btn ibuzr-history-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='ibuzr-contacts-btn ibuzr-history-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[13]/div[1]/div/div[3]/div[1]/div[1]/span[1]")).getText();
		Assert.assertEquals(a1, "CONTACTS");
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//span[@class='close-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//span[@class='close-btn']")).click();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on contact icon & Click on close button in QRP panel");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on QRP panel");
		test.info("Click on contacts icon");
		test.info("Click on close button");
		test.info("EXPECTED RESULT:: It should click on close button in QRP panel");
		test.pass(a);
		Assert.assertEquals(a2, "ibuzr-contacts-btn ibuzr-history-btn");
		test.pass(a2);
		test.pass(a1);
		Assert.assertEquals(a3, "close-btn");
		test.pass(a3);
		test.log(Status.PASS,"ACTUAL RESULT::  It is clicking on close button in QRP panel");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
    }
	@Test
	public void test14() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		//driver.findElement(By.xpath("//div[@data-name='naga']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-floating-button']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='ibuzr-floating-buttons-container active']")).getAttribute("class");
		Assert.assertEquals(a, "ibuzr-floating-buttons-container active");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='ibuzr-code-btn ibuzr-history-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='ibuzr-code-btn ibuzr-history-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[13]/div[1]/div/div[3]/div[1]/div[1]/span[1]")).getText();
		Assert.assertEquals(a1, "CODE");
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on code snippet icon in QRP panel");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on QRP panel");
		test.info("Click on code snippet icon");
		test.info("EXPECTED RESULT:: It should click on code snippet icon in QRP panel");
		test.pass(a);
		Assert.assertEquals(a2, "ibuzr-code-btn ibuzr-history-btn");
		test.pass(a2);
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is clicking on code snippet icon in QRP panel");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
    }
	@Test
	public void test15() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		//driver.findElement(By.xpath("//div[@data-name='naga']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-floating-button']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='ibuzr-floating-buttons-container active']")).getAttribute("class");
		Assert.assertEquals(a, "ibuzr-floating-buttons-container active");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='ibuzr-code-btn ibuzr-history-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='ibuzr-code-btn ibuzr-history-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[13]/div[1]/div/div[3]/div[1]/div[1]/span[1]")).getText();
		Assert.assertEquals(a1, "CODE");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-canned-history-wrapper']")).click();
		Thread.sleep(2000);
		String a3=driver.findElement(By.xpath("//div[@class='conversation-message-attachment']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Send any code snippet from QRP panel");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on QRP panel");
		test.info("Click on code snippet icon");
		test.info("Send any code snippet");
		test.info("EXPECTED RESULT:: It should send the code snippet from QRP panel");
		test.pass(a);
		Assert.assertEquals(a2, "ibuzr-code-btn ibuzr-history-btn");
		test.pass(a2);
		test.pass(a1);
		Assert.assertEquals(a3, "conversation-message-attachment");
		test.pass(a3);
		test.log(Status.PASS,"ACTUAL RESULT::  It is sending the code snippet from QRP panel");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
    }
	@Test
	public void test16() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		//driver.findElement(By.xpath("//div[@data-name='naga']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-floating-button']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='ibuzr-floating-buttons-container active']")).getAttribute("class");
		Assert.assertEquals(a, "ibuzr-floating-buttons-container active");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='ibuzr-code-btn ibuzr-history-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='ibuzr-code-btn ibuzr-history-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[13]/div[1]/div/div[3]/div[1]/div[1]/span[1]")).getText();
		Assert.assertEquals(a1, "CODE");
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//span[@class='close-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//span[@class='close-btn']")).click();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on code snippet icon & Click on close button in QRP panel");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on QRP panel");
		test.info("Click on code snippet icon");
		test.info("Click on close button");
		test.info("EXPECTED RESULT:: It should click on close button in QRP panel");
		test.pass(a);
		Assert.assertEquals(a2, "ibuzr-code-btn ibuzr-history-btn");
		test.pass(a2);
		test.pass(a1);
		Assert.assertEquals(a3, "close-btn");
		test.pass(a3);
		test.log(Status.PASS,"ACTUAL RESULT::  It is clicking on close button in QRP panel");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
    }
	@Test
	public void test17() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		//driver.findElement(By.xpath("//div[@data-name='naga']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-floating-button']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='ibuzr-floating-buttons-container active']")).getAttribute("class");
		Assert.assertEquals(a, "ibuzr-floating-buttons-container active");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='ibuzr-message-btn ibuzr-history-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='ibuzr-message-btn ibuzr-history-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[13]/div[1]/div/div[3]/div[1]/div[1]/span[1]")).getText();
		Assert.assertEquals(a1, "CANNED MESSAGES");
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on canned messages icon in QRP panel");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on QRP panel");
		test.info("Click on canned messages icon");
		test.info("EXPECTED RESULT:: It should click on canned messages icon in QRP panel");
		test.pass(a);
		Assert.assertEquals(a2, "ibuzr-message-btn ibuzr-history-btn");
		test.pass(a2);
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is clicking on canned messages icon in QRP panel");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
    }
	@Test
	public void test18() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		//driver.findElement(By.xpath("//div[@data-name='naga']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-floating-button']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='ibuzr-floating-buttons-container active']")).getAttribute("class");
		Assert.assertEquals(a, "ibuzr-floating-buttons-container active");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='ibuzr-message-btn ibuzr-history-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='ibuzr-message-btn ibuzr-history-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[13]/div[1]/div/div[3]/div[1]/div[1]/span[1]")).getText();
		Assert.assertEquals(a1, "CANNED MESSAGES");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='ibuzr-message-block-table-cell']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//span[@class='received-message-text']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Send any canned messages from QRP panel");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on QRP panel");
		test.info("Click on canned messages icon");
		test.info("Send any canned messages");
		test.info("EXPECTED RESULT:: It should send the canned messages from QRP panel");
		test.pass(a);
		Assert.assertEquals(a2, "ibuzr-message-btn ibuzr-history-btn");
		test.pass(a2);
		test.pass(a1);
		Assert.assertEquals(a3, "received-message-text");
		test.pass(a3);
		test.log(Status.PASS,"ACTUAL RESULT::  It is sending the canned messages from QRP panel");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
    }
	@Test
	public void test19() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		//driver.findElement(By.xpath("//div[@data-name='naga']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-floating-button']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='ibuzr-floating-buttons-container active']")).getAttribute("class");
		Assert.assertEquals(a, "ibuzr-floating-buttons-container active");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='ibuzr-message-btn ibuzr-history-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='ibuzr-message-btn ibuzr-history-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[13]/div[1]/div/div[3]/div[1]/div[1]/span[1]")).getText();
		Assert.assertEquals(a1, "CANNED MESSAGES");
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//div[@class='add-canned-message-btn']")).getText();
		Assert.assertEquals(a3, "Add");
		driver.findElement(By.xpath("//div[@class='add-canned-message-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='canned-message-input']")).sendKeys("test1");
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//div[@class='add-canned-message-btn'])[2]")).click();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Assert.assertEquals(a4, "Saved!");
		Thread.sleep(3000);
		driver.navigate().refresh();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@class='ibuzr-msgs-wrapper']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Add canned messages from QRP panel");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on QRP panel");
		test.info("Click on canned messages icon");
		test.info("Click on add button");
		test.info("Enter canned message");
		test.info("Click on add button");
		test.info("Refresh the page");
		test.info("EXPECTED RESULT:: It should add canned messages in QRP panel");
		test.pass(a);
		Assert.assertEquals(a2, "ibuzr-message-btn ibuzr-history-btn");
		test.pass(a2);
		test.pass(a1);
		test.pass(a3);
		test.pass(a4);
		Assert.assertEquals(a5, "hi\n"
				+ "test1");
		test.pass(a5);
		test.log(Status.PASS,"ACTUAL RESULT::  It is adding canned messages in QRP panel");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
    }
	@Test
	public void test20() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		//driver.findElement(By.xpath("//div[@data-name='naga']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='ibuzr-floating-button']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='ibuzr-floating-buttons-container active']")).getAttribute("class");
		Assert.assertEquals(a, "ibuzr-floating-buttons-container active");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='ibuzr-message-btn ibuzr-history-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='ibuzr-message-btn ibuzr-history-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[13]/div[1]/div/div[3]/div[1]/div[1]/span[1]")).getText();
		Assert.assertEquals(a1, "CANNED MESSAGES");
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//span[@class='close-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//span[@class='close-btn']")).click();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on canned messages icon & Click on close button in QRP panel");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on QRP panel");
		test.info("Click on canned messages icon");
		test.info("Click on close button");
		test.info("EXPECTED RESULT:: It should click on close button in QRP panel");
		test.pass(a);
		Assert.assertEquals(a2, "ibuzr-message-btn ibuzr-history-btn");
		test.pass(a2);
		test.pass(a1);
		Assert.assertEquals(a3, "close-btn");
		test.pass(a3);
		test.log(Status.PASS,"ACTUAL RESULT::  It is clicking on close button in QRP panel");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
    }
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
