package GroupView;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class Groupsprofile {
	WebDriver driver;
	ExtentHtmlReporter htmlReporter;
	ExtentReports extent;

	String extentReportImage = System.getProperty("user.dir")+ "extentReportImage.png";
	@BeforeSuite
	public void StartTest() {
		htmlReporter = new ExtentHtmlReporter("groupsprofile.html");
		extent = new ExtentReports();
		extent.attachReporter(htmlReporter);
	}
	@Test
	public void test00() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on group profile");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("EXPECTED RESULT ::  It should display group profile");
		String a=driver.findElement(By.xpath("(//div[@class='tab active'])[2]")).getText();
		Assert.assertEquals("INFO", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying group profile");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("0");
	}
	@Test
	public void test01() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@id='closeOuterRightContainer']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on close button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on close ");
		test.info("EXPECTED RESULT ::  It should close group profile");
		String a=driver.findElement(By.xpath("//div[@id='messengerConversationMessage']")).getAttribute("id");
		Assert.assertEquals("messengerConversationMessage", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is closing group profile");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("1");
	}
	@Test
	public void test02() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@class='edit-group-name']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='group-name-edit-save-btn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Edit the name without changing & Click on save button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on edit icon in name ");
		test.info("Click on save button");
		test.info("EXPECTED RESULT ::  It should display toast msg");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Group Name already exists!", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Group Name already exists!");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("2");
	}
	@Test
	public void test03() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@class='edit-group-name']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='group-name-edit-cancel-btn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Edit the name without changing & Click on cancel button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on edit icon in name ");
		test.info("Click on cancel button");
		test.info("EXPECTED RESULT ::  It should not change the name & It should display edit option");
		String a=driver.findElement(By.xpath("//span[@class='edit-group-name']")).getAttribute("class");
		Assert.assertEquals("edit-group-name", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//div[@class='group-name']")).getText();
		Assert.assertEquals("aaab", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not changing the name & It is displaying edit option");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("3");
	}
	@Test
	public void test04() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='ghfdh']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@class='edit-group-name']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='form-control group-name-edit-input']")).sendKeys("a");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='group-name-edit-save-btn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Edit the name & Click on save button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : ghfdh");
		test.info("Click on group icon");
		test.info("Click on edit icon in name ");
		test.info("Enter text : a");
		test.info("Click on save button");
		test.info("EXPECTED RESULT ::  It should display toast msg");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Group name updated!", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//div[@class='group-name']")).getText();
		Assert.assertEquals("ghfdha", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Group name updated!");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("4");
	}
	@Test
	public void test05() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='ghfdha']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@class='edit-group-name']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='form-control group-name-edit-input']")).clear();
		driver.findElement(By.xpath("//input[@class='form-control group-name-edit-input']")).sendKeys("a");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='group-name-edit-save-btn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Edit the name with single word & Click on save button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : ghfdha");
		test.info("Click on group icon");
		test.info("Click on edit icon in name ");
		test.info("Enter new group name : a");
		test.info("Click on save button");
		test.info("EXPECTED RESULT ::  It should display toast msg");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Group name updated!", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//div[@class='group-name']")).getText();
		Assert.assertEquals("a", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Group name updated!");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("5");
	}
	@Test
	public void test06() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='a']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@class='edit-group-name']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='form-control group-name-edit-input']")).sendKeys("a");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='group-name-edit-cancel-btn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Edit the name & Click on cancel button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : a");
		test.info("Click on group icon");
		test.info("Click on edit icon in name ");
		test.info("Enter text : a");
		test.info("Click on cancel button");
		test.info("EXPECTED RESULT ::  It should not change the name & It should display edit option");
		String a=driver.findElement(By.xpath("//span[@class='edit-group-name']")).getAttribute("class");
		Assert.assertEquals("edit-group-name", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//div[@class='group-name']")).getText();
		Assert.assertEquals("a", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not changing the name & It is displaying edit option");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("6");
	}
	@Test
	public void test07() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='a']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@class='edit-group-name']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='form-control group-name-edit-input']")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='group-name-edit-save-btn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Edit the name & Click on save button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : a");
		test.info("Click on group icon");
		test.info("Click on edit icon in name ");
		test.info("Clear the name");
		test.info("Click on save button");
		test.info("EXPECTED RESULT ::  It should display toast msg as please enter grop name");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Please enter group name", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying toast msg as Please enter group name");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("7");
	}
	@Test
	public void test08() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("//div[@class='group-avatar image-viewer']"));
		Actions ac=new Actions(driver);
		ac.moveToElement(e).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='edit-btn']")).click();
		Thread.sleep(1000);
		Robot rb = new Robot();
		Thread.sleep(1000);
		StringSelection str = new StringSelection("/home/tvisha/Pictures/Screenshot from 2022-07-21 14-42-50.png");
		Toolkit.getDefaultToolkit().getSystemClipboard().setContents(str, null);
		Thread.sleep(2000);
		rb.keyPress(KeyEvent.VK_CONTROL);
		rb.keyPress(KeyEvent.VK_V);

		// release Control+V for pasting
		rb.keyRelease(KeyEvent.VK_CONTROL);
		rb.keyRelease(KeyEvent.VK_V);
		// for pressing and releasing Enter
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(1000);
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("Add group avatar ");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on group avatar ");
		test.info("Click on edit in avatar");
		test.info("Select any attachment");
		test.info("Click on send");
		test.info("EXPECTED RESULT ::  It should add group avatar");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Group avatar updated!", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is adding group avatar");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("8");
	}
	@Test
	public void test09() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='group-avatar image-viewer']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@data-type='edit']")).click();
		Thread.sleep(2000);
		Robot rb = new Robot();
		Thread.sleep(1000);
		StringSelection str = new StringSelection("/home/tvisha/Pictures/airtime2.png");
		Toolkit.getDefaultToolkit().getSystemClipboard().setContents(str, null);
		Thread.sleep(2000);
		rb.keyPress(KeyEvent.VK_CONTROL);
		rb.keyPress(KeyEvent.VK_V);

		// release Control+V for pasting
		rb.keyRelease(KeyEvent.VK_CONTROL);
		rb.keyRelease(KeyEvent.VK_V);
		// for pressing and releasing Enter
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(1000);
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(4000);
		ExtentTest test=extent.createTest("Edit & Add group avatar ");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on group avatar ");
		test.info("Click on edit in avatar");
		test.info("Select any attachment");
		test.info("Click on send");
		test.info("EXPECTED RESULT ::  It should update group avatar");
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Assert.assertEquals("Group avatar updated!", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is updating group avatar");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("9");
	}
	@Test
	public void test10() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='group-avatar image-viewer']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@data-type='delete']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Remove group avatar ");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on group avatar ");
		test.info("Click on delete in avatar");
		test.info("EXPECTED RESULT ::  It should update group avatar");
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Assert.assertEquals("Avatar removed", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//div[@class='group-avatar image-viewer']")).getAttribute("data-image");
		Assert.assertEquals("", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is updating group avatar");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("10");
	}
	@Test
	public void test11() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//input[@id='groupProfileUserSearch']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Members count");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on search");
		test.info("EXPECTED RESULT ::  It should display members count ");
		String a1=driver.findElement(By.xpath("//input[@id='groupProfileUserSearch']")).getAttribute("placeholder");
		Assert.assertEquals("Members (6)", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying members count");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("11");
	}
	@Test
	public void test12() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//input[@id='groupProfileUserSearch']")).sendKeys("abc");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Search vaild username");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on search ");
		test.info("Enter text : abc");
		test.info("EXPECTED RESULT ::  It should display valid user names");
		String a1=driver.findElement(By.xpath("//div[@data-username='abc sai']")).getAttribute("data-username");
		Assert.assertEquals("abc sai", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying valid user names");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("12");
	}
	@Test
	public void test13() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//input[@id='groupProfileUserSearch']")).sendKeys("asdasfds");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Search invaild username");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on search ");
		test.info("Enter text : asdasfds");
		test.info("EXPECTED RESULT ::  It should display no data");
		test.log(Status.FAIL ,"ACTUAL RESULT ::  It is not displaying no data");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("13");
	}
	@Test
	public void test14() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//input[@id='groupProfileUserSearch']")).sendKeys("abc");
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@id='clearGroupProfileUserSearch']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on close button to searched username");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on search ");
		test.info("Enter text : abc");
		test.info("Click on close button");
		test.info("EXPECTED RESULT ::  It should display all username");
		String a1=driver.findElement(By.xpath("//input[@id='groupProfileUserSearch']")).getAttribute("placeholder");
		Assert.assertEquals("Members (6)", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all usernames");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("14");
	}
	@Test
	public void test15() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='group-profile-tab']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on logs");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on logs ");
		test.info("EXPECTED RESULT ::  It should display logs page");
		String a1=driver.findElement(By.xpath("//div[@class='group-profile-tab active']")).getText();
		Assert.assertEquals("Logs", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@class='info-box-heading']")).getText();
		Assert.assertEquals("Created", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying logs page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("15");
	}
	@Test
	public void test16() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@class='add-members-to-group']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on add button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on add button ");
		test.info("EXPECTED RESULT ::  It should display add members page");
		String a1=driver.findElement(By.xpath("//div[@class='tab active']")).getText();
		Assert.assertEquals("", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying add members page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("16");
	}
	@Test
	public void test17() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@class='add-members-to-group']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-userid='11']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("//input[@id='editGroupSubmitBtn']"));
		e.click();
		Thread.sleep(8000);
		ExtentTest test=extent.createTest("Add the User");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on add button ");
		test.info("Select the user ");
		test.info("Click on submit");
		test.info("EXPECTED RESULT ::  It should add user into the group");
		String a1="Group Members Added!";
		Assert.assertEquals("Group Members Added!", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//input[@id='groupProfileUserSearch']")).getAttribute("placeholder");
		Assert.assertEquals("Members (7)", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is adding user into the group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("17");
	}
	@Test
	public void test18() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@class='add-members-to-group']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-userid='7']")).click();
		driver.findElement(By.xpath("//div[@data-userid='31']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("//input[@id='editGroupSubmitBtn']"));
		e.click();
		Thread.sleep(8000);
		ExtentTest test=extent.createTest("Add multiple Users");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on add button ");
		test.info("Select the multiple users ");
		test.info("Click on submit");
		test.info("EXPECTED RESULT ::  It should add multiple users into the group");
		String a1="Group Members Added!";
		Assert.assertEquals("Group Members Added!", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//input[@id='groupProfileUserSearch']")).getAttribute("placeholder");
		Assert.assertEquals("Members (9)", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is adding multiple users into the group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("18");
	}
	@Test
	public void test19() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("(//span[@class='group-member-name'])[1]"));
		Actions ac=new Actions(driver);
		ac.moveToElement(e).perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='group-member-options-wrapper']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//span[@class='group-member-edit-option'])[1]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Make admin to the user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Select the user ");
		test.info("Click on 3 dots ");
		test.info("Click on admin");
		test.info("EXPECTED RESULT ::  It should make user as admin ");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Group member role updated!", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is making user as admin");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("19");
	}
	@Test
	public void test20() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("(//span[@class='group-member-name'])[1]"));
		Actions ac=new Actions(driver);
		ac.moveToElement(e).perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='group-member-options-wrapper']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//span[@class='group-member-edit-option'])[1]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Remove admin to the user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Select the user ");
		test.info("Click on 3 dots ");
		test.info("Remove as admin");
		test.info("EXPECTED RESULT ::  It should remove user as admin ");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Group member role updated!", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is removing user as admin");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("20");
	}
	@Test
	public void test21() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("(//span[@class='group-member-name'])[1]"));
		Actions ac=new Actions(driver);
		ac.moveToElement(e).perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='group-member-options-wrapper']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//span[@class='group-member-edit-option'])[2]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Make moderator to the user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Select the user ");
		test.info("Click on 3 dots ");
		test.info("Click on moderator");
		test.info("EXPECTED RESULT ::  It should make user as moderator ");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Group member role updated!", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is making user as moderator");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("21");
	}
	@Test
	public void test22() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("(//span[@class='group-member-name'])[1]"));
		Actions ac=new Actions(driver);
		ac.moveToElement(e).perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='group-member-options-wrapper']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//span[@class='group-member-edit-option'])[2]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Remove moderator to the user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Select the user ");
		test.info("Click on 3 dots ");
		test.info("Remove as moderator");
		test.info("EXPECTED RESULT ::  It should remove user as moderator ");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Group member role updated!", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is removing user as moderator");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("22");
	}
	@Test
	public void test23() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("(//span[@class='group-member-name'])[1]"));
		Actions ac=new Actions(driver);
		ac.moveToElement(e).perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='group-member-options-wrapper']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//span[@class='group-member-edit-option'])[3]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on view user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Select the user ");
		test.info("Click on 3 dots ");
		test.info("Click on view");
		test.info("EXPECTED RESULT ::  It should view the user profile ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is viewing the user profile");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("23");
	}
	@Test
	public void test24() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("(//span[@class='group-member-name'])[1]"));
		Actions ac=new Actions(driver);
		ac.moveToElement(e).perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='group-member-options-wrapper']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//span[@class='group-member-edit-option'])[4]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on message");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Select the user ");
		test.info("Click on 3 dots ");
		test.info("Click on message");
		test.info("EXPECTED RESULT ::  It should message the user profile ");
		String a=driver.findElement(By.xpath("//span[@id='chatUserName']")).getText();
		Assert.assertEquals("Abc", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is messaging the user profile");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("24");
	}
	@Test
	public void test25() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("(//span[@class='group-member-name'])[1]"));
		Actions ac=new Actions(driver);
		ac.moveToElement(e).perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='group-member-options-wrapper']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@class='group-member-edit-option class-red']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on remove from group");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Select the user ");
		test.info("Click on 3 dots ");
		test.info("Click on remove from group");
		test.info("EXPECTED RESULT ::  It should remove the user from group ");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Group member deleted!", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is removing the user from group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("25");
	}
	@Test
	public void test26() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]"));
		Actions ac=new Actions(driver);
		ac.click(e).perform();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on settings");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on settings");
		test.info("EXPECTED RESULT ::  It should click on settings in group view ");
		String a=driver.findElement(By.xpath("(//div[@class='tab active'])[2]")).getText();
		Assert.assertEquals("SETTINGS", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is clicking on settings in group view");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("26");
	}
	@Test
	public void test27() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]"));
		Actions ac=new Actions(driver);
		ac.click(e).perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//input[@id='groupDeleteRadioAll']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='groupDeleteSubmitBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-no']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Delete all msgs & files in everyone with no button ");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on settings");
		test.info("Click on radio button of all msgs & files");
		test.info("Click on submit");
		test.info("Click on no button");
		test.info("EXPECTED RESULT ::  It should not delete the msgs & files ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deleting the msgs & files");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("27");
	}
	@Test
	public void test28() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]"));
		Actions ac=new Actions(driver);
		ac.click(e).perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//input[@id='groupDeleteRadioAll']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='groupDeleteSubmitBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Delete all msgs & files in everyone with yes button ");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on settings");
		test.info("Click on radio button of all msgs & files");
		test.info("Click on submit");
		test.info("Click on yes button");
		test.info("EXPECTED RESULT ::  It should delete the msgs & files ");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Deleted chat history successfully", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//div[@class='group-notification-wrapper']")).getText();
		Assert.assertEquals("You deleted All Messages & Files", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is deleting the msgs & files");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("28");
	}
	@Test
	public void test29() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]"));
		Actions ac=new Actions(driver);
		ac.click(e).perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//input[@id='groupDeleteRadioMessages']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='groupDeleteSubmitBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-no']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Delete msgs in everyone with no button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on settings");
		test.info("Click on radio button of msgs");
		test.info("Click on submit");
		test.info("Click on no button");
		test.info("EXPECTED RESULT ::  It should not delete the msgs");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deleting the msgs");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("29");
	}
	@Test
	public void test30() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]"));
		Actions ac=new Actions(driver);
		ac.click(e).perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//input[@id='groupDeleteRadioMessages']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='groupDeleteSubmitBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Delete all msgs in everyone with yes button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on settings");
		test.info("Click on radio button of all msgs");
		test.info("Click on submit");
		test.info("Click on yes button");
		test.info("EXPECTED RESULT ::  It should delete the msgs ");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Deleted chat history successfully", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("(//div[@class='group-notification-wrapper'])[2]")).getText();
		Assert.assertEquals("You deleted All Messages", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is deleting the msgs");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("30");
	}
	@Test
	public void test31() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]"));
		Actions ac=new Actions(driver);
		ac.click(e).perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//input[@id='groupDeleteRadioFiles']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='groupDeleteSubmitBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-no']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Delete files in everyone with no button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on settings");
		test.info("Click on radio button of files");
		test.info("Click on submit");
		test.info("Click on no button");
		test.info("EXPECTED RESULT ::  It should not delete the files ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deleting the files");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("31");
	}
	@Test
	public void test32() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]"));
		Actions ac=new Actions(driver);
		ac.click(e).perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//input[@id='groupDeleteRadioFiles']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='groupDeleteSubmitBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Delete files in everyone with yes button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on settings");
		test.info("Click on radio button of files");
		test.info("Click on submit");
		test.info("Click on yes button");
		test.info("EXPECTED RESULT ::  It should delete the files ");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Deleted chat history successfully", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("(//div[@class='group-notification-wrapper'])[3]")).getText();
		Assert.assertEquals("You deleted All Files", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is deleting the files");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("32");
	}
	@Test
	public void test33() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='gdfgs']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]"));
		Actions ac=new Actions(driver);
		ac.click(e).perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//input[@id='groupDeleteRadioGroup']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='groupDeleteSubmitBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-no']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Delete group in everyone with no button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : gdfgs");
		test.info("Click on group icon");
		test.info("Click on settings");
		test.info("Click on radio button of delete group");
		test.info("Click on submit");
		test.info("Click on no button");
		test.info("EXPECTED RESULT ::  It should not delete the group ");
		String a=driver.findElement(By.xpath("//div[@data-name='gdfgs']")).getAttribute("data-name");
		Assert.assertEquals("gdfgs", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deleting the group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("33");
	}
	@Test
	public void test34() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='gdfgs']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]"));
		Actions ac=new Actions(driver);
		ac.click(e).perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//input[@id='groupDeleteRadioGroup']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='groupDeleteSubmitBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("gdfgs");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a1=driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[5]")).getText();
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[5]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Delete group in everyone with yes button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : gdfgs");
		test.info("Click on group icon");
		test.info("Click on settings");
		test.info("Click on radio button of delete group");
		test.info("Click on submit");
		test.info("Click on yes button");
		test.info("EXPECTED RESULT ::  It should delete the group ");
		
		Assert.assertEquals("Group deleted!", a);
		test.pass(a);
		System.out.println(a);
		Assert.assertEquals("Deleted/Exited Groups", a1);
		test.pass(a1);
		System.out.println(a1);
		String a2=driver.findElement(By.xpath("//div[@data-name='gdfgs']")).getAttribute("data-name");
		Assert.assertEquals("gdfgs", a2);
		test.pass(a2);
		System.out.println(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is deleting the group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("34");
	}
	@Test
	public void test35() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]"));
		Actions ac=new Actions(driver);
		ac.click(e).perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='group-delete-tab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='groupSelfDeleteRadioAll']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='groupDeleteSubmitBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-no']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Delete all msgs & files in self with no button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on settings");
		test.info("Click on self");
		test.info("Click on radio button of all msgs & files");
		test.info("Click on submit");
		test.info("Click on no button");
		test.info("EXPECTED RESULT ::  It should not delete the msgs & files ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deleting the msgs & files");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("35");
	}
	@Test
	public void test36() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]"));
		Actions ac=new Actions(driver);
		ac.click(e).perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='group-delete-tab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='groupSelfDeleteRadioAll']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='groupDeleteSubmitBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Delete all msgs & files in self with yes button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on settings");
		test.info("Click on self");
		test.info("Click on radio button of all msgs & files");
		test.info("Click on submit");
		test.info("Click on yes button");
		test.info("EXPECTED RESULT ::  It should delete the msgs & files ");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Deleted chat history successfully", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is deleting the msgs & files");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("36");
	}
	@Test
	public void test37() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]"));
		Actions ac=new Actions(driver);
		ac.click(e).perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='group-delete-tab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='groupSelfDeleteRadioMessages']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='groupDeleteSubmitBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-no']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Delete msgs in self with no button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on settings");
		test.info("Click on self");
		test.info("Click on radio button of msgs");
		test.info("Click on submit");
		test.info("Click on no button");
		test.info("EXPECTED RESULT ::  It should not delete the msgs");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deleting the msgs");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("37");
	}
	@Test
	public void test38() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]"));
		Actions ac=new Actions(driver);
		ac.click(e).perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='group-delete-tab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='groupSelfDeleteRadioMessages']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='groupDeleteSubmitBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Delete all msgs in self with yes button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on settings");
		test.info("Click on self");
		test.info("Click on radio button of all msgs");
		test.info("Click on submit");
		test.info("Click on yes button");
		test.info("EXPECTED RESULT ::  It should delete the msgs ");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Deleted chat history successfully", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is deleting the msgs");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("38");
	}
	@Test
	public void test39() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]"));
		Actions ac=new Actions(driver);
		ac.click(e).perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='group-delete-tab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='groupSelfDeleteRadioFiles']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='groupDeleteSubmitBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-no']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Delete files in self with no button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on settings");
		test.info("Click on self");
		test.info("Click on radio button of files");
		test.info("Click on submit");
		test.info("Click on no button");
		test.info("EXPECTED RESULT ::  It should not delete the files ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deleting the files");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("39");
	}
	@Test
	public void test40() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]"));
		Actions ac=new Actions(driver);
		ac.click(e).perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='group-delete-tab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='groupSelfDeleteRadioFiles']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='groupDeleteSubmitBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Delete files in self with yes button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on settings");
		test.info("Click on self");
		test.info("Click on radio button of files");
		test.info("Click on submit");
		test.info("Click on yes button");
		test.info("EXPECTED RESULT ::  It should delete the files ");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Deleted chat history successfully", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is deleting the files");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("40");
	}
	@Test
	public void test41() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]"));
		Actions ac=new Actions(driver);
		ac.click(e).perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//input[@id='groupExitRadio']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='groupExitSubmitBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-no']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Exit from group with no button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : aaab");
		test.info("Click on group icon");
		test.info("Click on settings");
		test.info("Click on exit from group");
		test.info("Click on radio button of exit");
		test.info("Click on submit");
		test.info("Click on no button");
		test.info("EXPECTED RESULT ::  It should not exit from group ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not exiting from group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("41");
	}
	@Test
	public void test42() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='ads']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]"));
		Actions ac=new Actions(driver);
		ac.click(e).perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//input[@id='groupExitRadio']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='groupExitSubmitBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Exit from group with yes button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : ads");
		test.info("Click on group icon");
		test.info("Click on settings");
		test.info("Click on exit from group");
		test.info("Click on radio button of exit");
		test.info("Click on submit");
		test.info("Click on yes button");
		test.info("EXPECTED RESULT ::  It should exit from group ");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Group Left!", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is exiting from group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("42");
	}
	@Test
	public void test43() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='asdfsadf']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]"));
		Actions ac=new Actions(driver);
		ac.click(e).perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//input[@id='groupExitRadio']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='groupExitSubmitBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Exit from group with yes button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Select group : asdfsadf");
		test.info("Click on group icon");
		test.info("Click on settings");
		test.info("Click on exit from group");
		test.info("Click on radio button of exit");
		test.info("Click on submit");
		test.info("Click on yes button");
		test.info("EXPECTED RESULT ::  It should not exit from group ");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Please ensure group has other admin.", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not exiting from group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("43");
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
