package Forkout;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Map;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class forkoutmsgsattachment {
	WebDriver driver;
	ExtentHtmlReporter htmlReporter;
	ExtentReports extent;

	String extentReportImage = System.getProperty("user.dir")+ "extentReportImage.png";
	@BeforeSuite
	public void StartTest() {
	htmlReporter = new ExtentHtmlReporter("forkoutmsgs&attachment.html");
	extent = new ExtentReports();
	extent.attachReporter(htmlReporter);
	}
	@Test
	public void test() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='Akash']")).click();
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-forkout-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forkoutUser-1-1-2']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='forkoutCloseBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//div[@class='forkout-selected-members-wrapper']")).getText();
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//span[@class='forkout-conversation-label-icon']")).getAttribute("class");
		String a1=driver.findElement(By.xpath("//span[@class='received-message-text']")).getText();
		String a2=driver.findElement(By.xpath("//div[@data-name='test']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Send the forkout msg to group");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Input:test");
		test.info("Click on forkout icon");
		test.info("Forkout:select group");
		test.info("Submit:Click on Send Button");
		test.info("EXPECTED RESULT:: It should display the forkout msg for selected group");
		Assert.assertEquals(a3, "1 group");
		test.pass(a3);
		Assert.assertEquals(a2, "Test");
		test.pass(a2);
		Assert.assertEquals(a, "forkout-conversation-label-icon");
		test.pass(a);
		Assert.assertEquals(a1, "test");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying the forkout msg for selected group");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test01() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-forkout-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forkoutUser-1-2-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='forkoutCloseBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//div[@class='forkout-selected-members-wrapper']")).getText();
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//span[@class='forkout-conversation-label-icon']")).getAttribute("class");
		String a1=driver.findElement(By.xpath("//span[@class='received-message-text']")).getText();
		String a2=driver.findElement(By.xpath("//div[@data-name='maneesh']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Send the forkout msg to user");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Input:test");
		test.info("Click on forkout icon");
		test.info("Forkout:select User");
		test.info("Submit:Click on Send Button");
		test.info("EXPECTED RESULT:: It should display the forkout msg for selected user");
		Assert.assertEquals(a3, "1 user");
		test.pass(a3);
		Assert.assertEquals(a2, "Maneesh");
		test.pass(a2);
		Assert.assertEquals(a, "forkout-conversation-label-icon");
		test.pass(a);
		Assert.assertEquals(a1, "test");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying the forkout msg for selected user");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test02() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-forkout-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forkoutUser-1-1-2']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forkoutMarkerCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='forkoutCloseBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//div[@class='forkout-selected-members-wrapper']")).getText();
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//span[@class='forkout-conversation-label-icon']")).getText();
		String a1=driver.findElement(By.xpath("//span[@class='received-message-text']")).getText();
		String a2=driver.findElement(By.xpath("//div[@data-name='test']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Send the forkout msg to group by deselecting the marker");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Input:test");
		test.info("Click on forkout icon");
		test.info("Forkout:select group");
		test.info("Deselect the marker");
		test.info("Submit:Click on Send Button");
		test.info("EXPECTED RESULT:: It should display the forkout msg for selected group without marker");
		Assert.assertEquals(a3, "1 group");
		test.pass(a3);
		Assert.assertEquals(a2, "Test");
		test.pass(a2);
		Assert.assertEquals(a, "");
		test.pass(a);
		Assert.assertEquals(a1, "test");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying the forkout msg for selected group without marker");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test03() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-forkout-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forkoutUser-1-2-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forkoutMarkerCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='forkoutCloseBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//div[@class='forkout-selected-members-wrapper']")).getText();
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//span[@class='forkout-conversation-label-icon']")).getText();
		String a1=driver.findElement(By.xpath("//span[@class='received-message-text']")).getText();
		String a2=driver.findElement(By.xpath("//div[@data-name='maneesh']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Send the forkout msg to user by deselecting the marker");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Input:test");
		test.info("Click on forkout icon");
		test.info("Forkout:select user");
		test.info("Deselect the marker");
		test.info("Submit:Click on Send Button");
		test.info("EXPECTED RESULT:: It should display the forkout msg for selected user without marker");
		Assert.assertEquals(a3, "1 user");
		test.pass(a3);
		Assert.assertEquals(a2, "Maneesh");
		test.pass(a2);
		Assert.assertEquals(a, "");
		test.pass(a);
		Assert.assertEquals(a1, "test");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying the forkout msg for selected user without marker");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test04() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-forkout-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forkoutUser-1-2-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forkoutUser-1-1-2']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forkoutMarkerCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='forkoutCloseBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//div[@class='forkout-selected-members-wrapper']")).getText();
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//span[@class='forkout-conversation-label-icon']")).getAttribute("class");
		String a1=driver.findElement(By.xpath("//span[@class='received-message-text']")).getText();
		String a2=driver.findElement(By.xpath("//div[@data-name='maneesh']")).getText();
		String a4=driver.findElement(By.xpath("//div[@data-name='test']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Send the forkout msg to user & group");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Input:test");
		test.info("Click on forkout icon");
		test.info("Forkout:select user & group");
		test.info("Submit:Click on Send Button");
		test.info("EXPECTED RESULT:: It should display the forkout msg for selected user & group");
		Assert.assertEquals(a3, "1 user + 1 group");
		test.pass(a3);
		Assert.assertEquals(a2, "Maneesh");
		test.pass(a2);
		Assert.assertEquals(a, "forkout-conversation-label-icon");
		test.pass(a);
		Assert.assertEquals(a1, "test");
		test.pass(a1);
		Assert.assertEquals(a4, "Test");
		test.pass(a4);
		Assert.assertEquals(a, "forkout-conversation-label-icon");
		test.pass(a);
		Assert.assertEquals(a1, "test");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying the forkout msg for selected user & group");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test05() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-forkout-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forkoutUser-1-2-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forkoutUser-1-1-2']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forkoutMarkerCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='forkoutCloseBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//div[@class='forkout-selected-members-wrapper']")).getText();
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//span[@class='forkout-conversation-label-icon']")).getText();
		String a1=driver.findElement(By.xpath("//span[@class='received-message-text']")).getText();
		String a2=driver.findElement(By.xpath("//div[@data-name='maneesh']")).getText();
		String a4=driver.findElement(By.xpath("//div[@data-name='test']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Send the forkout msg to user & group by deselecting the marker");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Input:test");
		test.info("Click on forkout icon");
		test.info("Forkout:select user & group");
		test.info("Deselect the marker");
		test.info("Submit:Click on Send Button");
		test.info("EXPECTED RESULT:: It should display the forkout msg for selected user & group without marker");
		Assert.assertEquals(a3, "1 user + 1 group");
		test.pass(a3);
		Assert.assertEquals(a2, "Maneesh");
		test.pass(a2);
		Assert.assertEquals(a, "");
		test.pass(a);
		Assert.assertEquals(a1, "test");
		test.pass(a1);
		Assert.assertEquals(a4, "Test");
		test.pass(a4);
		Assert.assertEquals(a, "");
		test.pass(a);
		Assert.assertEquals(a1, "test");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying the forkout msg for selected user & group without marker");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test06() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-forkout-btn input-action-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//input[@id='forkoutMembersSearch']")).getAttribute("placeholder");
		driver.findElement(By.xpath("//input[@id='forkoutMembersSearch']")).sendKeys("uppi");
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@data-username='uppi']")).getAttribute("data-username");
		Thread.sleep(1000);
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Search the user");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Input:test");
		test.info("Click on forkout icon");
		test.info("Click on search");
		test.info("Search the user");
		test.info("EXPECTED RESULT:: It should search the user");
		Assert.assertEquals(a1, "Search");
		test.pass(a1);
		Assert.assertEquals(a, "uppi");
		test.pass(a);
		test.log(Status.PASS,"ACTUAL RESULT::  It is searching the user");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test07() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-forkout-btn input-action-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//input[@id='forkoutMembersSearch']")).getAttribute("placeholder");
		driver.findElement(By.xpath("//input[@id='forkoutMembersSearch']")).sendKeys("uppi");
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@data-username='uppi']")).getAttribute("data-username");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='clear-search-icon']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//span[@class='clear-search-icon hidden']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Search the user");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Input:test");
		test.info("Click on forkout icon");
		test.info("Click on search");
		test.info("Search the user");
		test.info("Click on close button");
		test.info("EXPECTED RESULT:: It should click on close button in search");
		Assert.assertEquals(a1, "Search");
		test.pass(a1);
		Assert.assertEquals(a, "uppi");
		test.pass(a);
		Assert.assertEquals(a2, "clear-search-icon hidden");
		test.pass(a2);
		Assert.assertEquals(a1, "Search");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is clicking on close button in search");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test08() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-forkout-btn input-action-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//input[@id='forkoutMembersSearch']")).getAttribute("placeholder");
		driver.findElement(By.xpath("//input[@id='forkoutMembersSearch']")).sendKeys("maneesh");
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@data-username='maneesh']")).getAttribute("data-username");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forkoutUser-1-2-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='forkoutCloseBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//div[@class='forkout-selected-members-wrapper']")).getText();
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//span[@class='forkout-conversation-label-icon']")).getAttribute("class");
		String a4=driver.findElement(By.xpath("//span[@class='received-message-text']")).getText();
		String a5=driver.findElement(By.xpath("//div[@data-name='maneesh']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Search the user & send the forkout msg");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Input:test");
		test.info("Click on forkout icon");
		test.info("Click on search");
		test.info("Search the user");
		test.info("Select the searched user");
		test.info("Click on send");
		test.info("EXPECTED RESULT:: It should search the user & send the forkout msg");
		Assert.assertEquals(a1, "Search");
		test.pass(a1);
		Assert.assertEquals(a, "maneesh");
		test.pass(a);
		Assert.assertEquals(a3, "1 user");
		test.pass(a3);
		Assert.assertEquals(a5, "Maneesh");
		test.pass(a5);
		Assert.assertEquals(a2, "forkout-conversation-label-icon");
		test.pass(a2);
		Assert.assertEquals(a4, "test");
		test.pass(a4);
		test.log(Status.PASS,"ACTUAL RESULT::  It is searching the user & sending the forkout msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test09() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-forkout-btn input-action-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//input[@id='forkoutMembersSearch']")).getAttribute("placeholder");
		driver.findElement(By.xpath("//input[@id='forkoutMembersSearch']")).sendKeys("maneesh");
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@data-username='maneesh']")).getAttribute("data-username");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forkoutUser-1-2-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forkoutMarkerCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='forkoutCloseBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//div[@class='forkout-selected-members-wrapper']")).getText();
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//span[@class='forkout-conversation-label-icon']")).getText();
		String a4=driver.findElement(By.xpath("//span[@class='received-message-text']")).getText();
		String a5=driver.findElement(By.xpath("//div[@data-name='maneesh']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Search the user & send the forkout msg without marker");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Input:test");
		test.info("Click on forkout icon");
		test.info("Click on search");
		test.info("Search the user");
		test.info("Select the searched user");
		test.info("Deselect the forkout icon");
		test.info("Click on send");
		test.info("EXPECTED RESULT:: It should search the user & send the forkout msg without marker");
		Assert.assertEquals(a1, "Search");
		test.pass(a1);
		Assert.assertEquals(a, "maneesh");
		test.pass(a);
		Assert.assertEquals(a3, "1 user");
		test.pass(a3);
		Assert.assertEquals(a5, "Maneesh");
		test.pass(a5);
		Assert.assertEquals(a2, "");
		test.pass(a2);
		Assert.assertEquals(a4, "test");
		test.pass(a4);
		test.log(Status.PASS,"ACTUAL RESULT::  It is searching the user & sending the forkout msg without marker ");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test10() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-forkout-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forkoutUser-1-2-1']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//div[@class='forkout-selected-members-wrapper']")).getText();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@id='forkoutResetBtn']")).getAttribute("title");
		driver.findElement(By.xpath("//div[@id='forkoutResetBtn']")).click();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//div[@class='forkout-selected-members-wrapper hidden']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Click on refresh button");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Input:test");
		test.info("Click on forkout icon");
		test.info("Select the user");
		test.info("Click on refresh");
		test.info("EXPECTED RESULT:: It should refresh the forkout page");
		Assert.assertEquals(a3, "1 user");
		test.pass(a3);
		Assert.assertEquals(a2, "Reset");
		test.pass(a2);
		Assert.assertEquals(a4, "forkout-selected-members-wrapper hidden");
		test.pass(a4);
		test.log(Status.PASS,"ACTUAL RESULT::  It is refreshing the forkout page");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test11() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-forkout-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forkoutUser-1-2-1']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//div[@class='forkout-selected-members-wrapper']")).getText();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//span[@class='forkout-selected-members-wrapper-close']")).getAttribute("class");
		driver.findElement(By.xpath("//span[@class='forkout-selected-members-wrapper-close']")).click();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//div[@class='forkout-selected-members-wrapper hidden']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Click on close button");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Input:test");
		test.info("Click on forkout icon");
		test.info("Select the user");
		test.info("Click on close");
		test.info("EXPECTED RESULT:: It should close the forkout page");
		Assert.assertEquals(a3, "1 user");
		test.pass(a3);
		Assert.assertEquals(a2, "forkout-selected-members-wrapper-close");
		test.pass(a2);
		Assert.assertEquals(a4, "forkout-selected-members-wrapper hidden");
		test.pass(a4);
		test.log(Status.PASS,"ACTUAL RESULT::  It is closing the forkout page");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test12() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-forkout-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forkoutUser-1-2-1']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//div[@class='forkout-selected-members-wrapper']")).getText();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//div[@class='input-forkout-btn input-action-btn active highlight']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='input-forkout-btn input-action-btn active highlight']")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@class='forkout-selected-members-wrapper']")).getText();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='input-forkout-btn input-action-btn highlight']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Click on forkout active icon");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Input:test");
		test.info("Click on forkout icon");
		test.info("Select the user");
		test.info("Click on forkout active icon");
		test.info("EXPECTED RESULT:: It should close the forkout page");
		Assert.assertEquals(a3, "1 user");
		test.pass(a3);
		Assert.assertEquals(a4, "input-forkout-btn input-action-btn active highlight");
		test.pass(a4);
		Assert.assertEquals(a2, "input-forkout-btn input-action-btn highlight");
		test.pass(a2);
		Assert.assertEquals(a5, "1 user");
		test.pass(a5);
		test.log(Status.PASS,"ACTUAL RESULT::  It is closing the forkout page");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test13() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-forkout-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forkoutUser-1-2-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='forkoutCloseBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//div[@class='forkout-selected-members-wrapper']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-attachment-btn input-action-btn']")).click();
		Thread.sleep(1000);
		Robot rb = new Robot();
		Thread.sleep(1000);
		StringSelection str = new StringSelection("/home/tvisha/Pictures/Screenshot from 2022-07-21 14-42-50.png");
		Toolkit.getDefaultToolkit().getSystemClipboard().setContents(str, null);
		Thread.sleep(2000);
		rb.keyPress(KeyEvent.VK_CONTROL);
		rb.keyPress(KeyEvent.VK_V);

		// release Control+V for pasting
		rb.keyRelease(KeyEvent.VK_CONTROL);
		rb.keyRelease(KeyEvent.VK_V);
		// for pressing and releasing Enter
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(1000);
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		String a=driver.findElement(By.xpath("//span[@class='forkout-conversation-label-icon']")).getAttribute("class");
		String a1=driver.findElement(By.xpath("//img[@class='image_attachment']")).getAttribute("class");
		String a2=driver.findElement(By.xpath("//div[@data-name='test']")).getText();
		Thread.sleep(2000);
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Send the attachment with forkout");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on forkout icon");
		test.info("Select the user/group");
		test.info("Click on attachment");
		test.info("Select the attachment");
		test.info("Click on send");
		test.info("EXPECTED RESULT:: It should send the attachment with forkout icon");
		Assert.assertEquals(a3, "1 user");
		test.pass(a3);
		Assert.assertEquals(a2, "Test");
		test.pass(a2);
		Assert.assertEquals(a, "forkout-conversation-label-icon");
		test.pass(a);
		Assert.assertEquals(a1, "image_attachment");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is sending the attachment with forkout icon");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test14() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-forkout-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forkoutUser-1-2-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forkoutMarkerCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='forkoutCloseBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//div[@class='forkout-selected-members-wrapper']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-attachment-btn input-action-btn']")).click();
		Thread.sleep(1000);
		Robot rb = new Robot();
		Thread.sleep(1000);
		StringSelection str = new StringSelection("/home/tvisha/Pictures/Screenshot from 2022-11-25 15-53-51.png");
		Toolkit.getDefaultToolkit().getSystemClipboard().setContents(str, null);
		Thread.sleep(2000);
		rb.keyPress(KeyEvent.VK_CONTROL);
		rb.keyPress(KeyEvent.VK_V);

		// release Control+V for pasting
		rb.keyRelease(KeyEvent.VK_CONTROL);
		rb.keyRelease(KeyEvent.VK_V);
		// for pressing and releasing Enter
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(1000);
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		String a=driver.findElement(By.xpath("//span[@class='forkout-conversation-label-icon']")).getText();
		String a1=driver.findElement(By.xpath("//img[@class='image_attachment']")).getAttribute("class");
		String a2=driver.findElement(By.xpath("//div[@data-name='test']")).getText();
		Thread.sleep(2000);
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Send the attachment with forkout by deselecting the marker");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on forkout icon");
		test.info("Select the user/group");
		test.info("Deselect the checkbox of marker");
		test.info("Click on attachment");
		test.info("Select the attachment");
		test.info("Click on send");
		test.info("EXPECTED RESULT:: It should send the attachment without forkout icon");
		Assert.assertEquals(a3, "1 user");
		test.pass(a3);
		Assert.assertEquals(a2, "Test");
		test.pass(a2);
		Assert.assertEquals(a, "");
		test.pass(a);
		Assert.assertEquals(a1, "image_attachment");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is sending the attachment without forkout icon");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test15() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("chrome://flags");
		ChromeOptions options = new ChromeOptions()
				.addArguments("--unsafely-treat-insecure-origin-as-secure=http://192.168.2.55:8081");
		driver.manage().window().maximize();
		//for clicking allow  on notifications & microphone
		options.addArguments("use-fake-device-for-media-stream");
		options.addArguments("use-fake-ui-for-media-stream");
		Map<String, Object> prefs = new HashMap<String, Object>();
  		//Put this into prefs map to switch off browser notification
		prefs.put("profile.default_content_setting_values.notifications", 2);
		prefs.put("profile.default_content_setting_values.microphone", 2);
  		options.setExperimentalOption("prefs", prefs);
  		Thread.sleep(1000);
  		ChromeDriver driver=new ChromeDriver(options);
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-forkout-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forkoutUser-1-2-1']")).click();
		Thread.sleep(1000);
		//driver.findElement(By.xpath("//label[@for='forkoutMarkerCheckbox']")).click();
		//Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='forkoutCloseBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//div[@class='forkout-selected-members-wrapper']")).getText();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//div[@class='input-microphone-btn input-action-btn']")).getAttribute("title");
		driver.findElement(By.xpath("//div[@class='input-microphone-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='selectMicrophoneDeviceBtn']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//span[@class='forkout-conversation-label-icon']")).getText();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']")).getAttribute("class");
		String a2=driver.findElement(By.xpath("//div[@data-name='test']")).getText();
		Thread.sleep(2000);
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Send the voice message with forkout");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on forkout icon");
		test.info("Select the user/group");
		test.info("Click on voice message");
		test.info("Wait for some time");
		test.info("Click on send");
		test.info("EXPECTED RESULT:: It should send the voice message with forkout icon");
		Assert.assertEquals(a3, "1 user");
		test.pass(a3);
		Assert.assertEquals(a4, "Voice Message");
		test.pass(a4);
		Assert.assertEquals(a2, "Test");
		test.pass(a2);
		Assert.assertEquals(a, "");
		test.pass(a);
		Assert.assertEquals(a1, "audio-attachment-wrapper");
		test.pass(a1);
		test.log(Status.FAIL,"ACTUAL RESULT::  It is not sending the voice message with forkout icon");
		test.fail("Test Case:: TestCase FAILED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test16() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("chrome://flags");
		ChromeOptions options = new ChromeOptions()
				.addArguments("--unsafely-treat-insecure-origin-as-secure=http://192.168.2.55:8081");
		driver.manage().window().maximize();
		//for clicking allow  on notifications & microphone
		options.addArguments("use-fake-device-for-media-stream");
		options.addArguments("use-fake-ui-for-media-stream");
		Map<String, Object> prefs = new HashMap<String, Object>();
  		//Put this into prefs map to switch off browser notification
		prefs.put("profile.default_content_setting_values.notifications", 2);
		prefs.put("profile.default_content_setting_values.microphone", 2);
  		options.setExperimentalOption("prefs", prefs);
  		Thread.sleep(1000);
  		ChromeDriver driver=new ChromeDriver(options);
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-forkout-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forkoutUser-1-2-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forkoutMarkerCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='forkoutCloseBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//div[@class='forkout-selected-members-wrapper']")).getText();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//div[@class='input-microphone-btn input-action-btn']")).getAttribute("title");
		driver.findElement(By.xpath("//div[@class='input-microphone-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='selectMicrophoneDeviceBtn']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//span[@class='forkout-conversation-label-icon']")).getText();
		String a1=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']")).getAttribute("class");
		String a2=driver.findElement(By.xpath("//div[@data-name='test']")).getText();
		Thread.sleep(2000);
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Send the voice message with forkout by deselecting the marker");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:Click on Login");
		test.info("Click on user");
		test.info("Click on forkout icon");
		test.info("Select the user/group");
		test.info("Deselect the marker");
		test.info("Click on voice message");
		test.info("Wait for some time");
		test.info("Click on send");
		test.info("EXPECTED RESULT:: It should send the voice message without forkout icon");
		Assert.assertEquals(a3, "1 user");
		test.pass(a3);
		Assert.assertEquals(a4, "Voice Message");
		test.pass(a4);
		Assert.assertEquals(a2, "Test");
		test.pass(a2);
		Assert.assertEquals(a, "");
		test.pass(a);
		Assert.assertEquals(a1, "audio-attachment-wrapper");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is sending the voice message without forkout icon");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
