package DashboardGroups;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class Dashboardgroup {
	WebDriver driver;
	ExtentHtmlReporter htmlReporter;
	ExtentReports extent;

	String extentReportImage = System.getProperty("user.dir")+ "extentReportImage.png";
	@BeforeSuite
	public void StartTest() {
		htmlReporter = new ExtentHtmlReporter("DashboardgroupsAll.html");
		extent = new ExtentReports();
		extent.attachReporter(htmlReporter);
	}
	@Test
	public void test00() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='groupsFilterSearchInput']")).sendKeys("test");
		Thread.sleep(1000);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Search valid group name");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Search test");
		test.info("EXPECTED RESULT ::  It should display the Group name");
		String a=driver.findElement(By.xpath("//div[@data-id='1']")).getText();
		Assert.assertEquals("2\n"
				+ "Test\n"
				+ "N/A\n"
				+ "N/A\n"
				+ "5\n"
				+ "08 Dec 2021", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the groups name");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("0");
	}
	@Test
	public void test01() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='groupsFilterSearchInput']")).sendKeys("aasdsadfd");
		Thread.sleep(1000);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Search invalid group name");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Search aasdsadfd");
		test.info("EXPECTED RESULT ::  It should not display the Group name");
		String a=driver.findElement(By.xpath("//div[@class='no-results-found']")).getText();
		Assert.assertEquals("No results found..!", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not displaying the groups name");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("1");
	}
	@Test
	public void test02() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='groupsFilterSearchInput']")).sendKeys("aasdsadfd");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='groupsFilterSearchInput']")).clear();
		driver.findElement(By.xpath("//input[@id='groupsFilterSearchInput']")).sendKeys(Keys.ENTER);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Search invalid group name & clear the data");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Search aasdsadfd");
		test.info("EXPECTED RESULT ::  It should not display the Group name");
		String a=driver.findElement(By.xpath("//div[@class='table-head']")).getText();
		Assert.assertEquals("S.No\n"
				+ "Group Name\n"
				+ "Admin\n"
				+ "Moderator\n"
				+ "Total Users\n"
				+ "Created Date", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not displaying the groups name");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("2");
	}
	@Test
	public void test03() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='groupsSortFilter']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//option[@value='0']")).click();
		//driver.findElement(By.xpath("//option[@value='0']")).sendKeys(Keys.ENTER);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on sort by alphabet");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on sort filters");
		test.info("Select sort by alphabets");
		test.info("EXPECTED RESULT ::  It should display in alphabetical order");
		String a=driver.findElement(By.xpath("//div[@data-id='13']")).getText();
		Assert.assertEquals("1\n"
				+ "Aaaaa\n"
				+ "N/A\n"
				+ "N/A\n"
				+ "1\n"
				+ "27 Apr 2022", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//option[@value='0']")).getText();
		Assert.assertEquals("Sort By Alphabetical", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying in alphabetical order");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("3");
	}
	@Test
	public void test04() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='groupsSortFilter']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//option[@value='1']")).click();
		//driver.findElement(By.xpath("//option[@value='0']")).sendKeys(Keys.ENTER);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on sort by date of creation");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on sort filters");
		test.info("Select sort by date of creation");
		test.info("EXPECTED RESULT ::  It should display in date of creation");
		String a=driver.findElement(By.xpath("//div[@data-id='31']")).getText();
		Assert.assertEquals("1\n"
				+ "Abcd2\n"
				+ "N/A\n"
				+ "N/A\n"
				+ "3\n"
				+ "29 Jul 2022", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//option[@value='1']")).getText();
		Assert.assertEquals("Sort By Date of Creation", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying in date of creation");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("4");
	}
	@Test
	public void test05() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='groupsSortFilter']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//option[@value='2']")).click();
		//driver.findElement(By.xpath("//option[@value='0']")).sendKeys(Keys.ENTER);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on sort by most members");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on sort filters");
		test.info("Select Sort By Most members");
		test.info("EXPECTED RESULT ::  It should sort by most member");
		String a=driver.findElement(By.xpath("//div[@data-id='1']")).getText();
		Assert.assertEquals("1\n"
				+ "Test\n"
				+ "N/A\n"
				+ "N/A\n"
				+ "5\n"
				+ "08 Dec 2021", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//option[@value='2']")).getText();
		Assert.assertEquals("Sort By Most members", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is sorting in most members in first place");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("5");
	}
	@Test
	public void test06() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//option[@value='1'])[2]")).click();
		//driver.findElement(By.xpath("//option[@value='0']")).sendKeys(Keys.ENTER);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on Delete group in actions without selecting checkbox");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on actions");
		test.info("Select delete group");
		test.info("EXPECTED RESULT ::  It should not delete the group");
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Assert.assertEquals("Please select atleast one group", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("(//option[@value='1'])[2]")).getText();
		Assert.assertEquals("Delete Group", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::Please select atleast one group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("6");
	}
	@Test
	public void test07() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//option[@value='2'])[2]")).click();
		//driver.findElement(By.xpath("//option[@value='0']")).sendKeys(Keys.ENTER);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on Delete all msgs & files in actions without selecting checkbox");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on actions");
		test.info("Select delete all msgs & files");
		test.info("EXPECTED RESULT ::  It should not delete all msgs & files");
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Assert.assertEquals("Please select atleast one group", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("(//option[@value='2'])[2]")).getText();
		Assert.assertEquals("Delete All Messages & Files", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::Please select atleast one group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("7");
	}
	@Test
	public void test08() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//option[@value='3']")).click();
		//driver.findElement(By.xpath("//option[@value='0']")).sendKeys(Keys.ENTER);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on Delete all msgs in actions without selecting checkbox");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on actions");
		test.info("Select delete all msgs");
		test.info("EXPECTED RESULT ::  It should not delete only msgs");
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Assert.assertEquals("Please select atleast one group", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//option[@value='3']")).getText();
		Assert.assertEquals("Delete All Messages", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::Please select atleast one group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("8");
	}
	@Test
	public void test09() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//option[@value='4']")).click();
		//driver.findElement(By.xpath("//option[@value='0']")).sendKeys(Keys.ENTER);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on Delete all files in actions without selecting checkbox");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on actions");
		test.info("Select delete all files");
		test.info("EXPECTED RESULT ::  It should not delete only files");
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Assert.assertEquals("Please select atleast one group", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//option[@value='4']")).getText();
		Assert.assertEquals("Delete All Files", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::Please select atleast one group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("9");
	}
	@Test
	public void test10() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='groupsCheckbox-15']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//option[@value='2'])[2]")).click();
		Thread.sleep(500);
		//driver.findElement(By.xpath("//option[@value='0']")).sendKeys(Keys.ENTER);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-no']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Delete all msgs & files in actions with selecting checkbox");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on actions");
		test.info("Select delete all msgs & files");
		test.info("Click on no button in popup");
		test.info("EXPECTED RESULT ::  It should not delete all msgs & files");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deleting all msgs & files");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("10");
	}
	@Test
	public void test11() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='groupsCheckbox-15']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//option[@value='3']")).click();
		//driver.findElement(By.xpath("//option[@value='0']")).sendKeys(Keys.ENTER);
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-no']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Delete all msgs in actions without selecting checkbox");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on actions");
		test.info("Select delete all msgs");
		test.info("Click on no button");
		test.info("EXPECTED RESULT ::  It should not delete only msgs");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deleting msgs ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("11");
	}
	@Test
	public void test12() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='groupsCheckbox-15']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//option[@value='4']")).click();
		//driver.findElement(By.xpath("//option[@value='0']")).sendKeys(Keys.ENTER);
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-no']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Delete all files in actions without selecting checkbox");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on actions");
		test.info("Select delete all files");
		test.info("Click on no button");
		test.info("EXPECTED RESULT ::  It should not delete only files");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deleting files ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("12");
	}
	@Test
	public void test13() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='groupsCheckbox-15']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//option[@value='1'])[2]")).click();
		//driver.findElement(By.xpath("//option[@value='0']")).sendKeys(Keys.ENTER);
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-no']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Delete group in actions without selecting checkbox");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on actions");
		test.info("Select delete group");
		test.info("Click on no button");
		test.info("EXPECTED RESULT ::  It should not delete the group");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deleting group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("13");
	}
	@Test
	public void test14() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='groupsCheckbox-15']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//option[@value='2'])[2]")).click();
		Thread.sleep(1000);
		//driver.findElement(By.xpath("//option[@value='0']")).sendKeys(Keys.ENTER);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Delete all msgs & files in actions with selecting checkbox");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on actions");
		test.info("Select delete all msgs & files");
		test.info("Click on yes button in popup");
		test.info("EXPECTED RESULT ::  It should delete all msgs & files");
		Assert.assertEquals("Data deleted successfully", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//div[@class='group-notification-wrapper']")).getText();
		Assert.assertEquals("You deleted All Messages & Files", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is deleting all msgs & files");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("14");
	}
	@Test
	public void test15() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='groupsCheckbox-15']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//option[@value='3']")).click();
		//driver.findElement(By.xpath("//option[@value='0']")).sendKeys(Keys.ENTER);
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Delete all msgs in actions with selecting checkbox");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on actions");
		test.info("Select delete all msgs");
		test.info("Click on yes button");
		test.info("Click on chat");
		test.info("EXPECTED RESULT ::  It should delete only msgs");
		Assert.assertEquals("Data deleted successfully", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("(//div[@class='group-notification-wrapper'])[2]")).getText();
		Assert.assertEquals("You deleted All Messages", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is deleting msgs ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("15");
	}
	@Test
	public void test16() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='groupsCheckbox-15']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//option[@value='4']")).click();
		//driver.findElement(By.xpath("//option[@value='0']")).sendKeys(Keys.ENTER);
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Delete all files in actions with selecting checkbox");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on actions");
		test.info("Select delete all files");
		test.info("Click on yes button");
		test.info("Click on chat");
		test.info("EXPECTED RESULT ::  It should delete only files");
		Assert.assertEquals("Data deleted successfully", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("(//div[@class='group-notification-wrapper'])[3]")).getText();
		Assert.assertEquals("You deleted All Files", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is deleting files ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("16");
	}
	@Test
	public void test17() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='groupsCheckbox-31']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//option[@value='1'])[2]")).click();
		//driver.findElement(By.xpath("//option[@value='0']")).sendKeys(Keys.ENTER);
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("abcd");
		String a2=driver.findElement(By.xpath("//span[@class='no-recent-results-text']")).getText();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[5]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Delete group in actions with selecting checkbox");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on actions");
		test.info("Select delete group");
		test.info("Click on yes button");
		test.info("Click on chat ");
		test.info("Click on search");
		test.info("Search deleted group");
		test.info("Click on all members & files");
		test.info("Select deleted/exited groups");
		test.info("EXPECTED RESULT ::  It should delete the group");
		Assert.assertEquals("Group deleted successfully", a);
		test.pass(a);
		System.out.println(a);
		Assert.assertEquals("No Data", a2);
		test.pass(a2);
		System.out.println(a2);
		String a1=driver.findElement(By.xpath("//div[@data-name='abcd']")).getAttribute("data-name");
		Assert.assertEquals("abcd", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is deleting group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("17");
	}
	@Test
	public void test18() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='groupsFilterSearchInput']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='group-options-button']")).click();
		driver.findElement(By.xpath("//div[@data-type='1']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//span[@class='header-text']")).getText();
		String a1=driver.findElement(By.xpath("//div[@class='group-name-wrapper']")).getText();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='content-close-btn']")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Select any group view the profile");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Search test");
		test.info("Select any group");
		test.info("Click on view");
		test.info("Click on close button");
		test.info("EXPECTED RESULT ::  It should display the Group profile");
		Assert.assertEquals("GROUP", a);
		test.pass(a);
		System.out.println(a);
		Assert.assertEquals("Dev n test", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the groups profile");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("18");
	}
	@Test
	public void test19() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='groupsFilterSearchInput']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='group-options-button']")).click();
		driver.findElement(By.xpath("//div[@data-type='1']")).click();
		Thread.sleep(1000);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Select any group view the profile");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Search test");
		test.info("Select any group");
		test.info("Click on view");
		test.info("View the admin & users");
		test.info("EXPECTED RESULT ::  It should display the users");
		String a=driver.findElement(By.xpath("//span[@class='count-text']")).getText();
		Assert.assertEquals("0", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.FAIL ,"ACTUAL RESULT ::  It is not displaying the users");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("19");
	}
	@Test
	public void test20() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='groupsFilterSearchInput']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//div[@class='group-options-button'])[2]")).click();
		driver.findElement(By.xpath("(//div[@data-type='3'])[2]")).click();
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-no']")).click();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/nav/div/div/ul/li[7]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		Thread.sleep(1000);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Select group Delete all msg and Files");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Search test");
		test.info("Select any group");
		test.info("Click on Delete all msg & files");
		test.info("Click on no button");
		test.info("Click on refresh");
		test.info("Click on logout");
		test.info("Login with Group user");
		test.info("Click on Group");
		test.info("EXPECTED RESULT ::  It should not Deleted All Msg & files");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deleting the all msgs & files");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("20");
	}
	@Test
	public void test21() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='groupsFilterSearchInput']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//div[@class='group-options-button'])[2]")).click();
		driver.findElement(By.xpath("(//div[@data-type='4'])[2]")).click();
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-no']")).click();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/nav/div/div/ul/li[7]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		Thread.sleep(1000);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Select any group Delete all msg");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Search test");
		test.info("Select any group");
		test.info("Click on Delete all msg");
		test.info("Click on no button");
		test.info("Click on refresh");
		test.info("Click on logout");
		test.info("Login with Group user");
		test.info("Click on Group");
		test.info("EXPECTED RESULT ::  It should not Deleted All Msgs ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deleting all msgs");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("21");
	}
	@Test
	public void test22() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='groupsFilterSearchInput']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//div[@class='group-options-button'])[2]")).click();
		driver.findElement(By.xpath("(//div[@data-type='5'])[2]")).click();
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-no']")).click();
		Thread.sleep(1000);
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/nav/div/div/ul/li[7]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		Thread.sleep(1000);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Select any group Delete all Files");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Search test");
		test.info("Select any group");
		test.info("Click on Delete all files");
		test.info("Select no button");
		test.info("Click on refresh");
		test.info("Click on logout");
		test.info("Login with Group user");
		test.info("Click on Group");
		test.info("EXPECTED RESULT ::  It should not Deleted All files ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deleting all files");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("22");
	}
	@Test
	public void test23() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//div[@class='group-options-button'])[5]")).click();
		driver.findElement(By.xpath("(//div[@data-type='2'])[5]")).click();
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-no']")).click();
		Thread.sleep(1000);
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("acb");
		String a1=driver.findElement(By.xpath("//div[@data-name='acb']")).getAttribute("data-name");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[5]")).click();
		String a2=driver.findElement(By.xpath("//span[@class='no-recent-results-text']")).getText();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/nav/div/div/ul/li[7]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("acb");
		String a3=driver.findElement(By.xpath("//div[@data-name='acb']")).getAttribute("data-name");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[5]")).click();
		String a4=driver.findElement(By.xpath("//span[@class='no-recent-results-text']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select any group, Delete Group ");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Search test");
		test.info("Select any group");
		test.info("Click on Delete Group");
		test.info("Click on no button");
		test.info("Click on refresh");
		test.info("Click on logout");
		test.info("Login with Group user");
		test.info("EXPECTED RESULT ::  It should not delete the group");
		Assert.assertEquals("acb", a1);
		test.pass(a1);
		System.out.println(a1);
		Assert.assertEquals("No Data", a2);
		test.pass(a2);
		System.out.println(a2);
		Assert.assertEquals("acb", a3);
		test.pass(a3);
		System.out.println(a3);
		Assert.assertEquals("No Data", a4);
		test.pass(a4);
		System.out.println(a4);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deleting the group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("23");
	}
	@Test
	public void test24() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='groupsFilterSearchInput']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//div[@class='group-options-button'])[2]")).click();
		driver.findElement(By.xpath("(//div[@data-type='3'])[2]")).click();
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		String a1=driver.findElement(By.xpath("(//div[@class='group-notification-wrapper'])[1]")).getText();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/nav/div/div/ul/li[7]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("(//div[@class='group-notification-wrapper'])[1]")).getText();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Select group Delete all msg and Files");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Search test");
		test.info("Select any group");
		test.info("Click on Delete all msg & files");
		test.info("Click on yes button");
		test.info("Click on refresh");
		test.info("Click on logout");
		test.info("Login with Group user");
		test.info("Click on Group");
		test.info("EXPECTED RESULT ::  It should display the Deleted All Msg & files in particular Group");
		Assert.assertEquals("Data deleted successfully", a);
		test.pass(a);
		System.out.println(a);
		Assert.assertEquals("You deleted All Messages & Files", a1);
		test.pass(a1);
		System.out.println(a1);
		Assert.assertEquals("sharath deleted All Messages & Files", a2);
		test.pass(a2);
		System.out.println(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Data deleted successfully");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("24");
	}
	@Test
	public void test25() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='groupsFilterSearchInput']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//div[@class='group-options-button'])[2]")).click();
		driver.findElement(By.xpath("(//div[@data-type='4'])[2]")).click();
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		String a1=driver.findElement(By.xpath("(//div[@class='group-notification-wrapper'])[2]")).getText();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/nav/div/div/ul/li[7]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("(//div[@class='group-notification-wrapper'])[2]")).getText();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Select any group Delete all msg");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Search test");
		test.info("Select any group");
		test.info("Click on Delete all msg");
		test.info("Click on yes button");
		test.info("Click on refresh");
		test.info("Click on logout");
		test.info("Login with Group user");
		test.info("Click on Group");
		test.info("EXPECTED RESULT ::  It should Deleted All Msg in particular Group");
		Assert.assertEquals("Data deleted successfully", a);
		test.pass(a);
		System.out.println(a);
		Assert.assertEquals("You deleted All Messages", a1);
		test.pass(a1);
		System.out.println(a1);
		Assert.assertEquals("sharath deleted All Messages", a2);
		test.pass(a2);
		System.out.println(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Data deleted successfully");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("25");
	}
	@Test
	public void test26() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='groupsFilterSearchInput']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//div[@class='group-options-button'])[2]")).click();
		driver.findElement(By.xpath("(//div[@data-type='5'])[2]")).click();
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		String a1=driver.findElement(By.xpath("(//div[@class='group-notification-wrapper'])[3]")).getText();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/nav/div/div/ul/li[7]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("(//div[@class='group-notification-wrapper'])[3]")).getText();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Select any group Delete all Files");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Search test");
		test.info("Select any group");
		test.info("Click on Delete all files");
		test.info("Click on yes button");
		test.info("Click on refresh");
		test.info("Click on logout");
		test.info("Login with Group user");
		test.info("Click on Group");
		test.info("EXPECTED RESULT ::  It should Deleted All files in particular Group");
		Assert.assertEquals("Data deleted successfully", a);
		test.pass(a);
		System.out.println(a);
		Assert.assertEquals("You deleted All Files", a1);
		test.pass(a1);
		System.out.println(a1);
		Assert.assertEquals("sharath deleted All Files", a2);
		test.pass(a2);
		System.out.println(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Data deleted successfully");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("26");
	}
	@Test
	public void test27() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//div[@class='group-options-button'])[5]")).click();
		driver.findElement(By.xpath("(//div[@data-type='2'])[5]")).click();
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("acd");
		String a2=driver.findElement(By.xpath("//span[@class='no-recent-results-text']")).getText();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[5]")).click();
		String a1=driver.findElement(By.xpath("//div[@data-name='acd']")).getAttribute("data-name");
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/nav/div/div/ul/li[7]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("acd");
		String a3=driver.findElement(By.xpath("//span[@class='no-recent-results-text']")).getText();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[5]")).click();
		String a4=driver.findElement(By.xpath("//div[@data-name='acd']")).getAttribute("data-name");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select any group, Delete Group ");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Search test");
		test.info("Select any group");
		test.info("Click on Delete Group");
		test.info("Click on yes button");
		test.info("Click on refresh");
		test.info("Click on logout");
		test.info("Login with Group user");
		test.info("EXPECTED RESULT ::  System should not display the particular Group");
		Assert.assertEquals("Group deleted successfully", a);
		test.pass(a);
		System.out.println(a);
		Assert.assertEquals("No Data", a2);
		test.pass(a2);
		System.out.println(a2);
		Assert.assertEquals("acd", a1);
		test.pass(a1);
		System.out.println(a1);
		Assert.assertEquals("No Data", a3);
		test.pass(a3);
		System.out.println(a3);
		Assert.assertEquals("acd", a4);
		test.pass(a4);
		System.out.println(a4);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Group deleted successfully");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("27");
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
