package homepage;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class home {
	WebDriver driver;
	ExtentHtmlReporter HtmlReporter;
	ExtentReports extent;

	@BeforeSuite
	public void Starttest() {
		HtmlReporter = new ExtentHtmlReporter("homepage(dashboard).html");
		extent = new ExtentReports();
		extent.attachReporter(HtmlReporter);
	}
  @Test
  public void test() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("EXPECTED RESULT ::  It should display home page ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying home page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("home");
  }
  @Test
  public void test1() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div[1]/div[1]/span[3]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Users in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on users");
		test.info("EXPECTED RESULT ::  It should display only users ");
		String a=driver.findElement(By.xpath("//select[@id='membersFilterMembersSelection']")).getText();
		Assert.assertEquals("Users + Orange members\n"
				+ "Users\n"
				+ "Orange members\n"
				+ "De-activated Users + Orange Members\n"
				+ "Ex-users + Ex-orange Members", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying only users");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("1");
  }
  @Test
  public void test2() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div[1]/div[2]/span[3]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on orange members in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on orange members");
		test.info("EXPECTED RESULT ::  It should display only orange members ");
		String a=driver.findElement(By.xpath("//select[@id='membersFilterMembersSelection']")).getText();
		Assert.assertEquals("Users + Orange members\n"
				+ "Users\n"
				+ "Orange members\n"
				+ "De-activated Users + Orange Members\n"
				+ "Ex-users + Ex-orange Members", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying only orange members ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("2");
  }
  @Test
  public void test3() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div[1]/div[3]/span[3]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on groups in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on group");
		test.info("EXPECTED RESULT ::  It should not click on groups ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not clicking on groups ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("3");
  }
  @Test
  public void test4() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div[1]/div[4]/span[3]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on ex-members in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on ex-members");
		test.info("EXPECTED RESULT ::  It should display ex-members ");
		String a=driver.findElement(By.xpath("//select[@id='membersFilterMembersSelection']")).getText();
		Assert.assertEquals("Users + Orange members\n"
				+ "Users\n"
				+ "Orange members\n"
				+ "De-activated Users + Orange Members\n"
				+ "Ex-users + Ex-orange Members", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.FAIL ,"ACTUAL RESULT ::  It is display ex-members but the count in home page is ex-members & deactivated users ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("4");
  }
  @Test
  public void test5() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@data-value='1']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on today's msgs in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on exchange info");
		test.info("Click on todays date");
		test.info("EXPECTED RESULT ::  It should display todays msgs count ");
		String a=driver.findElement(By.xpath("//div[@class='user-selected-text']")).getText();
		Assert.assertEquals("Today", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is display todays msgs count ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("5");
  }
  @Test
  public void test6() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='date-filter-wrapper']")).click();
		driver.findElement(By.xpath("//div[@data-value='2']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on yesterday's msgs in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on exchange info");
		test.info("Click on yesterday's date");
		test.info("EXPECTED RESULT ::  It should display yesterday's msgs count ");
		String a=driver.findElement(By.xpath("//div[@class='user-selected-text']")).getText();
		Assert.assertEquals("Yesterday", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is display yesterday's msgs count ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("6");
  }
  @Test
  public void test7() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='date-filter-wrapper']")).click();
		driver.findElement(By.xpath("//div[@data-value='3']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on last 7days msgs in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on exchange info");
		test.info("Click on Last 7 days msgs");
		test.info("EXPECTED RESULT ::  It should display Last 7 days msgs count ");
		String a=driver.findElement(By.xpath("//div[@class='user-selected-text']")).getText();
		Assert.assertEquals("Last 7 Days", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is display Last 7 days msgs count ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("7");
  }
  @Test
  public void test8() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='date-filter-wrapper']")).click();
		driver.findElement(By.xpath("//div[@data-value='4']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Last 30 days msgs in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on exchange info");
		test.info("Click on last 30 days");
		test.info("EXPECTED RESULT ::  It should display Last 30 days msgs count ");
		String a=driver.findElement(By.xpath("//div[@class='user-selected-text']")).getText();
		Assert.assertEquals("Last 30 Days", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is display Last 30days msgs count ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("8");
  }
  @Test
  public void test9() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='date-filter-wrapper']")).click();
		driver.findElement(By.xpath("//div[@data-value='5']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on This month msgs in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on exchange info");
		test.info("Click on This month");
		test.info("EXPECTED RESULT ::  It should display This month msgs count ");
		String a=driver.findElement(By.xpath("//div[@class='user-selected-text']")).getText();
		Assert.assertEquals("This Month", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is display This month msgs count ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("9");
  }
  @Test
  public void testcase10() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='date-filter-wrapper']")).click();
		driver.findElement(By.xpath("//div[@data-value='6']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on This year msgs in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on exchange info");
		test.info("Click on This year");
		test.info("EXPECTED RESULT ::  It should display This year msgs count ");
		String a=driver.findElement(By.xpath("//div[@class='user-selected-text']")).getText();
		Assert.assertEquals("This Year", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is display This year msgs count ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("10");
  }
  @Test
  public void testcase11() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='date-filter-wrapper']")).click();
		driver.findElement(By.xpath("//div[@data-value='7']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Last Year msgs in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on exchange info");
		test.info("Click on Last Year");
		test.info("EXPECTED RESULT ::  It should display Last Year msgs count ");
		String a=driver.findElement(By.xpath("//div[@class='user-selected-text']")).getText();
		Assert.assertEquals("Last Year", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is display Last Year msgs count ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("11");
  }
  @Test
  public void testcase12() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='date-filter-wrapper']")).click();
		driver.findElement(By.xpath("//div[@data-value='8']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on All Dates msgs in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on exchange info");
		test.info("Click on All Dates");
		test.info("EXPECTED RESULT ::  It should display All Dates msgs count ");
		String a=driver.findElement(By.xpath("//div[@class='user-selected-text']")).getText();
		Assert.assertEquals("Date", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is display All Dates msgs count ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("12");
  }
  @Test
  public void testcase13() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='date-filter-wrapper']")).click();
		driver.findElement(By.xpath("//input[@value='Apply']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Date range msgs with out data in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on exchange info");
		test.info("Click on Date range");
		test.info("Click on apply");
		test.info("EXPECTED RESULT ::  It should display toast as Please select from date ");
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Assert.assertEquals("Please select from date", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Please select from date ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("13");
  }
  @Test
  public void testcase14() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='date-filter-wrapper']")).click();
		driver.findElement(By.xpath("//div[@data-value='9']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='dateRangeFilterFrom']")).click();
		driver.findElement(By.xpath(" /html/body/div[6]/div[1]/table/tbody/tr[2]/td[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@value='Apply']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		//driver.findElement(By.xpath(" /html/body/div[6]/div[1]/table/tbody/tr[2]/td[3]")).click();
		ExtentTest test=extent.createTest("Click on Date range msgs with only from date in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on exchange info");
		test.info("Click on Date range");
		test.info("Click on From date");
		test.info("Select any day");
		test.info("Click on apply");
		test.info("EXPECTED RESULT ::  It should display toast as Please select to date ");
		Assert.assertEquals("Please select to date", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Please select to date ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("14");
  }
  @Test
  public void testcase15() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='date-filter-wrapper']")).click();
		driver.findElement(By.xpath("//div[@data-value='9']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='dateRangeFilterTo']")).click();
		driver.findElement(By.xpath("/html/body/div[6]/div[1]/table/tbody/tr[2]/td[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@value='Apply']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		ExtentTest test=extent.createTest("Click on Date range msgs with only to date in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on exchange info");
		test.info("Click on Date range");
		test.info("Click on To date");
		test.info("Select any day");
		test.info("Click on apply");
		test.info("EXPECTED RESULT ::  It should display toast as Please select from date ");
		Assert.assertEquals("Please select from date", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Please select from date ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("15");
  }
  @Test
  public void testcase16() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='date-filter-wrapper']")).click();
		driver.findElement(By.xpath("//div[@data-value='9']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='dateRangeFilterFrom']")).click();
		driver.findElement(By.xpath("/html/body/div[6]/div[1]/table/tbody/tr[2]/td[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[6]/div[1]/table/tbody/tr[4]/td[2]")).click();
		driver.findElement(By.xpath("//input[@value='Apply']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@class='user-selected-text']")).getText();
		ExtentTest test=extent.createTest("Click on Date range msgs with from & To dates in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on exchange info");
		test.info("Click on Date range");
		test.info("Click on From date");
		test.info("Select any day");
		test.info("Click on To date");
		test.info("Select any day");
		test.info("Click on apply");
		test.info("EXPECTED RESULT ::  It should display date in the user selected text ");
		Assert.assertEquals("2022-04-05 - 2022-04-18", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  2022-04-05 - 2022-04-18 ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("16");
  }
  @Test
  public void testcase17() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//input[@id='addMembersSubmitBtn']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("/html/body/div[6]/div[2]")).getText();
		ExtentTest test=extent.createTest("Click on Add user without entering any data in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Add user");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should display Please enter name ");
		Assert.assertEquals("Please enter name", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Please enter name ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("17");
  }
  @Test
  public void testcase18() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//input[@id='addMemberName']")).sendKeys("aaa");
		driver.findElement(By.xpath("//input[@id='addMembersSubmitBtn']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("/html/body/div[6]/div[2]")).getText();
		ExtentTest test=extent.createTest("Click on Add user & enter name in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Add user");
		test.info("Enter user name : aaa");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should display Please enter email ");
		Assert.assertEquals("Please enter email", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Please enter email ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("18");
  }
  @Test
  public void testcase19() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//input[@id='addMemberEmail']")).sendKeys("aaa@google.com");
		driver.findElement(By.xpath("//input[@id='addMembersSubmitBtn']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("/html/body/div[6]/div[2]")).getText();
		ExtentTest test=extent.createTest("Click on Add user & enter email in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Add user");
		test.info("Enter user email : aaa@google.com");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should display Please enter name ");
		Assert.assertEquals("Please enter name", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Please enter name ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("19");
  }
  @Test
  public void testcase20() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//input[@id='addMemberName']")).sendKeys("aaa");
		driver.findElement(By.xpath("//input[@id='addMemberEmail']")).sendKeys("aaab@google.com");
		driver.findElement(By.xpath("//input[@id='addMembersSubmitBtn']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		ExtentTest test=extent.createTest("Click on Add user & enter name & email in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Add user");
		test.info("Enter user name : aaaa");
		test.info("Enter user email : aaaa@google.com");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should display toast as employee added successfully ");
		Assert.assertEquals("Employee added successfully", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Employee added successfully ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("20");
  }
  @Test
  public void testcase21() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//input[@id='addMemberName']")).sendKeys("aaa");
		driver.findElement(By.xpath("//input[@id='addMemberEmail']")).sendKeys("aa@google.com");
		driver.findElement(By.xpath("//input[@id='addMembersSubmitBtn']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		ExtentTest test=extent.createTest("Click on Add user & enter name & email in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Add user");
		test.info("Enter user name : aaa");
		test.info("Enter user email : aaa@google.com");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should display toast as Employee email already exists ");
		Assert.assertEquals("Employee email already exists", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Employee email already exists ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("21");
  }
  @Test
  public void testcase22() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//input[@id='addMemberName']")).sendKeys("aaa");
		driver.findElement(By.xpath("//input[@id='addMemberEmail']")).sendKeys("abdb@google.com");
		driver.findElement(By.xpath("//select[@id='addMemberDepartment']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//option[@value='2']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"addMemberDesignation\"]")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='2']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='addMemberLocation']")).click();
		Thread.sleep(1000);
		//driver.findElement(By.xpath("//option[@value='1']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberMobile']")).sendKeys("9876540232");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberLabel']")).sendKeys("TM-005");
		driver.findElement(By.xpath("//input[@id='addMembersSubmitBtn']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		ExtentTest test=extent.createTest("Click on Add user with optional field in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Add user");
		test.info("Enter user name : aaa");
		test.info("Enter user email : ab@google.com");
		test.info("Click on department");
		test.info("Select the department : testing");
		test.info("Click on designation");
		test.info("Select the designation : HR");
		test.info("Click on location");
		test.info("Select the location : Hyd");
		test.info("Enter mobile num : 9876540321");
		test.info("Enter label : TM-001");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should display toast as Employee added successfully ");
		Assert.assertEquals("Employee added successfully", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Employee added successfully ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("22");
  }
  @Test
  public void testcase23() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//input[@id='addMemberName']")).sendKeys("aaa");
		driver.findElement(By.xpath("//input[@id='addMemberEmail']")).sendKeys("aa@google.com");
		driver.findElement(By.xpath("//select[@id='addMemberDepartment']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//option[@value='2']")).click();
		driver.findElement(By.xpath("//select[@id='addMemberDesignation']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='2']")).click();
		driver.findElement(By.xpath("//select[@id='addMemberLocation']")).click();
		Thread.sleep(1000);
		//driver.findElement(By.xpath("//option[@value='1']")).click();
		driver.findElement(By.xpath("//input[@id='addMemberMobile']")).sendKeys("9876540322");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberLabel']")).sendKeys("TM-001");
		driver.findElement(By.xpath("//input[@id='addMembersSubmitBtn']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		ExtentTest test=extent.createTest("Click on Add user with same credential in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Add user");
		test.info("Enter user name : aaa");
		test.info("Enter user email : ab@google.com");
		test.info("Click on department");
		test.info("Select the department : testing");
		test.info("Click on designation");
		test.info("Select the designation : HR");
		test.info("Click on location");
		test.info("Select the location : Hyd");
		test.info("Enter mobile num : 9876540321");
		test.info("Enter label : TM-001");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should display toast as Employee email already exists ");
		Assert.assertEquals("Employee email already exists", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Employee email already exists ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("23");
  }
  @Test
  public void testcase24() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//input[@id='addMemberName']")).sendKeys("abc");
		driver.findElement(By.xpath("//input[@id='addMemberEmail']")).sendKeys("abdc@google.com");
		driver.findElement(By.xpath("//select[@id='addMemberDepartment']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//option[@value='2']")).click();
		driver.findElement(By.xpath("//select[@id='addMemberDesignation']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='2']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='addMemberLocation']")).click();
		Thread.sleep(200);
		//driver.findElement(By.xpath("//option[@value='1']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberMobile']")).sendKeys("9876540333");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberLabel']")).sendKeys("TM-006");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='addMemberAdminCheckbox']")).click();
		driver.findElement(By.xpath("//input[@id='addMembersSubmitBtn']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		ExtentTest test=extent.createTest("Click on Add user with TM-admin in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Add user");
		test.info("Enter user name : abc");
		test.info("Enter user email : abc@google.com");
		test.info("Click on department");
		test.info("Select the department : testing");
		test.info("Click on designation");
		test.info("Select the designation : HR");
		test.info("Click on location");
		test.info("Select the location : Hyd");
		test.info("Enter mobile num : 9876540331");
		test.info("Enter label : TM-002");
		test.info("Click on checkbox of TM-admin");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should display toast as Employee added successfully ");
		Assert.assertEquals("Employee added successfully", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Employee added successfully ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("24");
  }
  @Test
  public void testcase25() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//input[@id='addMemberName']")).sendKeys("abc");
		driver.findElement(By.xpath("//input[@id='addMemberEmail']")).sendKeys("abc@google.com");
		driver.findElement(By.xpath("//select[@id='addMemberDepartment']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//option[@value='2']")).click();
		driver.findElement(By.xpath("//select[@id='addMemberDesignation']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='2']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='addMemberLocation']")).click();
		Thread.sleep(200);
		//driver.findElement(By.xpath("//option[@value='2']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberMobile']")).sendKeys("9876540331");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberLabel']")).sendKeys("TM-001");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='addMemberAdminCheckbox']")).click();
		driver.findElement(By.xpath("//input[@id='addMembersSubmitBtn']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		ExtentTest test=extent.createTest("Click on Add user with same credential in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Add user");
		test.info("Enter user name : abc");
		test.info("Enter user email : abc@google.com");
		test.info("Click on department");
		test.info("Select the department : testing");
		test.info("Click on designation");
		test.info("Select the designation : HR");
		test.info("Click on location");
		test.info("Select the location : Hyd");
		test.info("Enter mobile num : 9876540331");
		test.info("Enter label : TM-002");
		test.info("Click on checkbox of TM-admin");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should display toast as Employee email already exists ");
		Assert.assertEquals("Employee email already exists", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Employee email already exists ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("25");
  }
  @Test
  public void testcase26() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//input[@id='addMemberName']")).sendKeys("abcd");
		driver.findElement(By.xpath("//input[@id='addMemberEmail']")).sendKeys("abdd@google.com");
		driver.findElement(By.xpath("//select[@id='addMemberDepartment']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//option[@value='2']")).click();
		driver.findElement(By.xpath("//select[@id='addMemberDesignation']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='2']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='addMemberLocation']")).click();
		Thread.sleep(200);
		driver.findElement(By.xpath("//option[@value='2']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberMobile']")).sendKeys("9876543032");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberLabel']")).sendKeys("TM-007");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='addMemberOrangeMemberCheckbox']")).click();
		driver.findElement(By.xpath("//input[@id='addMembersSubmitBtn']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		ExtentTest test=extent.createTest("Click on Add user with orange member in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Add user");
		test.info("Enter user name : abcd");
		test.info("Enter user email : abcd@google.com");
		test.info("Click on department");
		test.info("Select the department : testing");
		test.info("Click on designation");
		test.info("Select the designation : HR");
		test.info("Click on location");
		test.info("Select the location : Hyd");
		test.info("Enter mobile num : 9876540332");
		test.info("Enter label : TM-003");
		test.info("Click on checkbox of Orange member");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should display toast as Employee added successfully ");
		Assert.assertEquals("Employee added successfully", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Employee added successfully ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("26");
  }
  @Test
  public void testcase27() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//input[@id='addMemberName']")).sendKeys("abcd");
		driver.findElement(By.xpath("//input[@id='addMemberEmail']")).sendKeys("abcd@google.com");
		driver.findElement(By.xpath("//select[@id='addMemberDepartment']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//option[@value='2']")).click();
		driver.findElement(By.xpath("//select[@id='addMemberDesignation']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='2']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='addMemberLocation']")).click();
		Thread.sleep(200);
		driver.findElement(By.xpath("//option[@value='2']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberMobile']")).sendKeys("9876540332");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberLabel']")).sendKeys("TM-003");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='addMemberOrangeMemberCheckbox']")).click();
		driver.findElement(By.xpath("//input[@id='addMembersSubmitBtn']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		ExtentTest test=extent.createTest("Click on Add user with same credential in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Add user");
		test.info("Enter user name : abcd");
		test.info("Enter user email : abcd@google.com");
		test.info("Click on department");
		test.info("Select the department : testing");
		test.info("Click on designation");
		test.info("Select the designation : HR");
		test.info("Click on location");
		test.info("Select the location : Hyd");
		test.info("Enter mobile num : 9876540332");
		test.info("Enter label : TM-003");
		test.info("Click on checkbox of Orange member");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should display toast as Employee email already exists ");
		Assert.assertEquals("Employee email already exists", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Employee email already exists ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("27");
  }
  @Test
  public void testcase28() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='heading-text']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//input[@id='addDepartmentSubmitBtn']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("/html/body/div[6]/div[2]")).getText();
		ExtentTest test=extent.createTest("Click on Quick add with empty department name in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Quick add");
		test.info("Click on department");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should display toast as Please enter department ");
		Assert.assertEquals("Please enter department", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Please enter department ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("28");
  }
  @Test
  public void testcase29() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='heading-text']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='addDepartmentInput']")).sendKeys("test1");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addDepartmentSubmitBtn']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		ExtentTest test=extent.createTest("Click on Quick add with department name in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Quick add");
		test.info("Click on department");
		test.info("Enter department name : test");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should display toast as Department added successfully ");
		Assert.assertEquals("Department added successfully", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Department added successfully ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("29");
  }
  @Test
  public void testcase30() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='heading-text']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='addDepartmentInput']")).sendKeys("test");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addDepartmentSubmitBtn']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		ExtentTest test=extent.createTest("Click on Quick add with same department name in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Quick add");
		test.info("Click on department");
		test.info("Enter department name : test");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should not added the same department name ");
		Assert.assertEquals("Department name already exists, please use different name", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Department name already exists, please use different name ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("30");
  }
  @Test
  public void testcase31() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='heading-text']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='addDesignationSubmitBtn']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("/html/body/div[6]/div[2]")).getText();
		ExtentTest test=extent.createTest("Click on Quick add with empty designation name in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Quick add");
		test.info("Click on designation");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should display toast as Please enter designation ");
		Assert.assertEquals("Please enter designation", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Please enter designation ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("31");
  }
  @Test
  public void testcase32() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='heading-text']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='designationInput']")).sendKeys("QA");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addDesignationSubmitBtn']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("/html/body/div[6]/div[2]")).getText();
		ExtentTest test=extent.createTest("Click on Quick add with only designation name in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Quick add");
		test.info("Click on designation");
		test.info("Enter designation : test");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should display toast as Please select department ");
		Assert.assertEquals("Please select department", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Please select department ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("32");
  }
  @Test
  public void testcase33() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='heading-text']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='departmentSelection']")).click();
		driver.findElement(By.xpath("//option[@value='2']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addDesignationSubmitBtn']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("/html/body/div[6]/div[2]")).getText();
		ExtentTest test=extent.createTest("Click on Quick add with only department name in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Quick add");
		test.info("Click on department");
		test.info("Enter department : testing");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should display toast as Please enter designation ");
		Assert.assertEquals("Please enter designation", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Please enter designation ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("33");
  }
  @Test
  public void testcase34() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='heading-text']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='designationInput']")).sendKeys("abcd");
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='departmentSelection']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='2']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addDesignationSubmitBtn']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		ExtentTest test=extent.createTest("Click on Quick add with designation & department name in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Quick add");
		test.info("Click on designation");
		test.info("Enter designation : abc");
		test.info("Click on department");
		test.info("Enter department : testing");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should display toast as Designation added successfully ");
		Assert.assertEquals("Designation added successfully", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Designation added successfully ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("34");
  }
  @Test
  public void testcase35() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='heading-text']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='designationInput']")).sendKeys("abc");
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='departmentSelection']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='3']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addDesignationSubmitBtn']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		ExtentTest test=extent.createTest("Click on Quick add with same designation & department name in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Quick add");
		test.info("Click on designation");
		test.info("Enter designation : abc");
		test.info("Click on department");
		test.info("Enter department : testing");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should not add the designation name ");
		Assert.assertEquals("Designation name already exists, please use different name", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Designation name already exists, please use different name ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("35");
  }
  @Test
  public void testcase36() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='heading-text']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='addLocationSubmitBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Quick add with Location in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Quick add");
		test.info("Click on location");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should display the toast as please enter label ");
		test.log(Status.FAIL ,"ACTUAL RESULT ::  It is not displaying any toast ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("36");
  }
  @Test
  public void testcase37() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='heading-text']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='addLocationLabelInput']")).sendKeys("aa");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addLocationSubmitBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Quick add with Location label in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Quick add");
		test.info("Click on location");
		test.info("Enter label : aa");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should display the toast as please enter city ");
		test.log(Status.FAIL ,"ACTUAL RESULT ::  It is not displaying any toast ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("37");
  }
  @Test
  public void testcase38() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='heading-text']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='addLocationLabelInput']")).sendKeys("aa");
		Thread.sleep(500);
		driver.findElement(By.xpath("//textarea[@id='addLocationAddressInput']")).sendKeys("hyderabad");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addLocationCityInput']")).sendKeys("hyd");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addLocationSubmitBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Quick add with Location label,city in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Quick add");
		test.info("Click on location");
		test.info("Enter label : aa");
		test.info("Enter address : hyderabad");
		test.info("Enter city : hyd");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should display the toast as please enter state ");
		test.log(Status.FAIL ,"ACTUAL RESULT ::  It is not displaying any toast ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("38");
  }
  @Test
  public void testcase39() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='heading-text']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='addLocationLabelInput']")).sendKeys("aa");
		Thread.sleep(500);
		driver.findElement(By.xpath("//textarea[@id='addLocationAddressInput']")).sendKeys("hyderabad");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addLocationCityInput']")).sendKeys("hyd");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addLocationStateInput']")).sendKeys("abc");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addLocationSubmitBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Quick add with Location label,city,state in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Quick add");
		test.info("Click on location");
		test.info("Enter label : aa");
		test.info("Enter address : hyderabad");
		test.info("Enter city : hyd");
		test.info("Enter state : abc");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should display the toast as please enter country ");
		test.log(Status.FAIL ,"ACTUAL RESULT ::  It is not displaying any toast ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("39");
  }
  @Test
  public void testcase40() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='heading-text']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='addLocationLabelInput']")).sendKeys("aa");
		Thread.sleep(500);
		driver.findElement(By.xpath("//textarea[@id='addLocationAddressInput']")).sendKeys("hyderabad");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addLocationCityInput']")).sendKeys("hyd");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addLocationStateInput']")).sendKeys("abc");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addLocationCountryInput']")).sendKeys("abcd");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addLocationSubmitBtn']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		ExtentTest test=extent.createTest("Click on Quick add with Location label,city,state,country in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Quick add");
		test.info("Click on location");
		test.info("Enter label : aa");
		test.info("Enter address : hyderabad");
		test.info("Enter city : hyd");
		test.info("Enter state : abc");
		test.info("Enter country : abcd ");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should display the toast as Location Added successfully ");
		Assert.assertEquals("Location Added successfully", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Location Added successfully ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("40");
  }
  @Test
  public void testcase41() throws InterruptedException {
	  System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upi@google.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//div[@class='heading-text']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='addLocationLabelInput']")).sendKeys("aa");
		Thread.sleep(500);
		driver.findElement(By.xpath("//textarea[@id='addLocationAddressInput']")).sendKeys("hyderabad");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addLocationCityInput']")).sendKeys("hyd");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addLocationStateInput']")).sendKeys("abc");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addLocationCountryInput']")).sendKeys("abcd");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addLocationSubmitBtn']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		ExtentTest test=extent.createTest("Click on Quick add with same Location label,city,state,country in home page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on home");
		test.info("Click on Quick add");
		test.info("Click on location");
		test.info("Enter label : aa");
		test.info("Enter address : hyderabad");
		test.info("Enter city : hyd");
		test.info("Enter state : abc");
		test.info("Enter country : abcd ");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should not add the location ");
		Assert.assertEquals("Label already exists, please use different name", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Label already exists, please use different name ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("41");
  }
  @AfterSuite
  public void endTest() {
	  extent.flush();
  }
}
