package filters;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class groupfilter {
	WebDriver driver;
	ExtentHtmlReporter HtmlReporter;
	ExtentReports extent;

	@BeforeSuite
	public void Starttest() {
		HtmlReporter = new ExtentHtmlReporter("groupfilters.html");
		extent = new ExtentReports();
		extent.attachReporter(HtmlReporter);
	}
	@Test
	public void test() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("EXPECTED RESULT ::  It should click on filters icon ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is clicking on filters icon ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("filters");
	}
	@Test
	public void test1() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-image']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on image in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on image");
		test.info("EXPECTED RESULT ::  It should display only images in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("filter by Image", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying only images in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("1");
	}
	@Test
	public void test2() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-image']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-image active']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Double click on image in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on image");
		test.info("Again click on image");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("2");
	}
	@Test
	public void test3() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-image']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-refresh-icon']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on image & Click on refresh icon in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on image");
		test.info("Again click on refresh");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("Clear / Reset", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("3");
	}
	@Test
	public void test4() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-image']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-close-icon']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on image & Click on close icon in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on image");
		test.info("Again click on close");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//div[@class='filter-access-btn']")).getText();
		Assert.assertEquals("", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("4");
	}
	@Test
	public void test5() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-video']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on video in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on video");
		test.info("EXPECTED RESULT ::  It should display only videos in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("filter by Video", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying only videos in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("5");
	}
	@Test
	public void test6() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-video']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-video active']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Double click on video in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on video");
		test.info("Again click on video");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("6");
	}
	@Test
	public void test7() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-video']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-refresh-icon']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on video & Click on refresh icon in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on video");
		test.info("Again click on refresh");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("Clear / Reset", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("7");
	}
	@Test
	public void test8() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-video']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-close-icon']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on video & Click on close icon in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on video");
		test.info("Again click on close");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//div[@class='filter-access-btn']")).getText();
		Assert.assertEquals("", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("8");
	}
	@Test
	public void test9() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-doc']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on File in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on File");
		test.info("EXPECTED RESULT ::  It should display only docs in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("filter by File", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying only docs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("9");
	}
	@Test
	public void testcase10() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-doc']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-doc active']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Double click on File in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on File");
		test.info("Again click on File");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("10");
	}
	@Test
	public void testcase11() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-doc']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-refresh-icon']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on File & Click on refresh icon in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on File");
		test.info("Again click on refresh");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("Clear / Reset", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("11");
	}
	@Test
	public void testcase12() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-doc']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-close-icon']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on File & Click on close icon in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on File");
		test.info("Again click on close");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//div[@class='filter-access-btn']")).getText();
		Assert.assertEquals("", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("12");
	}
	@Test
	public void testcase13() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-link']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on link in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on link");
		test.info("EXPECTED RESULT ::  It should display only link in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("filter by Link", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying only link in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("13");
	}
	@Test
	public void testcase14() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-link']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-link active']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Double click on link in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on link");
		test.info("Again click on link");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("14");
	}
	@Test
	public void testcase15() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-link']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-refresh-icon']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on link & Click on refresh icon in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on link");
		test.info("Again click on refresh");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("Clear / Reset", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("15");
	}
	@Test
	public void testcase16() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-link']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-close-icon']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on link & Click on close icon in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on link");
		test.info("Again click on close");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//div[@class='filter-access-btn']")).getText();
		Assert.assertEquals("", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("16");
	}
	@Test
	public void testcase17() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-contact']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on contact in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on contact");
		test.info("EXPECTED RESULT ::  It should display only contact in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("filter by Contact", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying only contact in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("17");
	}
	@Test
	public void testcase18() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-contact']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-contact active']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Double click on contact in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on contact");
		test.info("Again click on contact");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("18");
	}
	@Test
	public void testcase19() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-contact']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-refresh-icon']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on contact & Click on refresh icon in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on contact");
		test.info("Again click on refresh");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("Clear / Reset", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("19");
	}
	@Test
	public void testcase20() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-contact']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-close-icon']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on contact & Click on close icon in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on contact");
		test.info("Again click on close");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//div[@class='filter-access-btn']")).getText();
		Assert.assertEquals("", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("20");
	}
	@Test
	public void testcase21() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-location']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on location in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on location");
		test.info("EXPECTED RESULT ::  It should display only location in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("filter by Location", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying only location in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("21");
	}
	@Test
	public void testcase22() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-location']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-location active']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Double click on location in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on location");
		test.info("Again click on location");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("22");
	}
	@Test
	public void testcase23() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-location']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-refresh-icon']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on location & Click on refresh icon in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on location");
		test.info("Again click on refresh");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("Clear / Reset", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("23");
	}
	@Test
	public void testcase24() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-location']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-close-icon']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on location & Click on close icon in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on location");
		test.info("Again click on close");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//div[@class='filter-access-btn']")).getText();
		Assert.assertEquals("", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("24");
	}
	@Test
	public void testcase25() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-read-receipt']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on read receipt in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on read receipt");
		test.info("EXPECTED RESULT ::  It should display only read receipt in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("filter by Read Receipt", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying only read receipt in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("25");
	}
	@Test
	public void testcase26() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-read-receipt']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-read-receipt active']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Double click on read receipt in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on read receipt");
		test.info("Again click on read receipt");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("26");
	}
	@Test
	public void testcase27() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-read-receipt']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-refresh-icon']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on read receipt & Click on refresh icon in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on read receipt");
		test.info("Again click on refresh");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("Clear / Reset", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("27");
	}
	@Test
	public void testcase28() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-read-receipt']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-close-icon']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on read receipt & Click on close icon in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on read receipt");
		test.info("Again click on close");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//div[@class='filter-access-btn']")).getText();
		Assert.assertEquals("", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("28");
	}
	@Test
	public void testcase29() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-flag']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on flag in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on flag");
		test.info("EXPECTED RESULT ::  It should display only flag msgs in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("filter by Flag", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying only flag msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("29");
	}
	@Test
	public void testcase30() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-flag']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-flag active']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Double click on flag in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on flag");
		test.info("Again click on flag");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("30");
	}
	@Test
	public void testcase31() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-flag']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-refresh-icon']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on flag & Click on refresh icon in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on flag");
		test.info("Again click on refresh");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("Clear / Reset", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("31");
	}
	@Test
	public void testcase32() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-flag']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-close-icon']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on flag & Click on close icon in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on flag");
		test.info("Again click on close");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//div[@class='filter-access-btn']")).getText();
		Assert.assertEquals("", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("32");
	}
	@Test
	public void testcase33() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-respond-later']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on respond later in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on respond later");
		test.info("EXPECTED RESULT ::  It should display only respond later msgs in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("filter by Respond Later", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying only respond later msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("33");
	}
	@Test
	public void testcase34() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-respond-later']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-respond-later active']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Double click on respond later in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on respond later");
		test.info("Again click on respond later");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("34");
	}
	@Test
	public void testcase35() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-respond-later']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-refresh-icon']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on respond later & Click on refresh icon in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on respond later");
		test.info("Again click on refresh");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//span[@class='new-filter-hover-text']")).getText();
		Assert.assertEquals("Clear / Reset", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("35");
	}
	@Test
	public void testcase36() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-respond-later']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@class='filter-close-icon']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on respond later & Click on close icon in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on respond later");
		test.info("Again click on close");
		test.info("EXPECTED RESULT ::  It should display all the msgs in that page ");
		String a=driver.findElement(By.xpath("//div[@class='filter-access-btn']")).getText();
		Assert.assertEquals("", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the msgs in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("36");
	}
	@Test
	public void testcase37() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-close-icon']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on filters & Click on close icon");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on group");
		test.info("Click on filters");
		test.info("Click on close icon");
		test.info("EXPECTED RESULT ::  It should not highlight the filter icon ");
		String a=driver.findElement(By.xpath("//div[@class='filter-access-btn']")).getText();
		Assert.assertEquals("", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not highlighting the filter icon ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("36");
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
