package controls;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class Access {
	WebDriver driver;
	ExtentHtmlReporter htmlReporter;
	ExtentReports extent;

	String extentReportImage = System.getProperty("user.dir")+ "extentReportImage.png";
	@BeforeSuite
	public void StartTest() {
	htmlReporter = new ExtentHtmlReporter("Access.html");
	extent = new ExtentReports();
	extent.attachReporter(htmlReporter);
	}
	@Test
	public void test() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Access']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='accessContainerIPCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[19]/div[2]/div[5]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//label[@for='ipAllowRadio']")).getText();
		String a1=driver.findElement(By.xpath("//label[@for='ipBlockRadio']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on checkbox of Restrict by IP");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Access");
		test.info("Select checkbox of Restrict by IP");
		test.info("Click on save button");
		test.info("EXPECTED RESULT ::  It should select the checkbox of restrict by IP");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a, "Allow");
		test.pass(a);
		Assert.assertEquals(a1, "Block");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is selecting the checkbox of restrict by IP");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test01() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Access']")).click();
		Thread.sleep(1000);
		//driver.findElement(By.xpath("//label[@for='accessContainerIPCheckbox']")).click();
		//Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='ipBlockRadio']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[19]/div[2]/div[5]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(500);
		String a1=driver.findElement(By.xpath("//label[@for='ipBlockRadio']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select the radio button of Block in restrict by IP");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Access");
		test.info("Select checkbox of Restrict by IP");
		test.info("Select the radio button block");
		test.info("Click on save button");
		test.info("EXPECTED RESULT ::  It should select the radio button block");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a1, "Block");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is selecting the radio button block");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test02() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Access']")).click();
		Thread.sleep(1000);
		//driver.findElement(By.xpath("//label[@for='accessContainerIPCheckbox']")).click();
		//Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='ipAllowRadio']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[19]/div[2]/div[5]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(500);
		String a1=driver.findElement(By.xpath("//label[@for='ipAllowRadio']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select the radio button of Allow in restrict by IP");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Access");
		test.info("Select checkbox of Restrict by IP");
		test.info("Select the radio button Allow");
		test.info("Click on save button");
		test.info("EXPECTED RESULT ::  It should select the radio button Allow");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a1, "Allow");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is selecting the radio button Allow");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test03() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Access']")).click();
		Thread.sleep(1000);
		//driver.findElement(By.xpath("//label[@for='accessContainerIPCheckbox']")).click();
		//Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='ipAllowRadio']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='ipTypeSelection']")).click();
		Thread.sleep(500);
		Actions ac=new Actions(driver);
		ac.sendKeys(Keys.ARROW_DOWN).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[19]/div[2]/div[5]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(500);
		String a1=driver.findElement(By.xpath("//label[@for='ipAllowRadio']")).getText();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//select[@id='ipTypeSelection']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on dropdown in restrict by IP");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Access");
		test.info("Select checkbox of Restrict by IP");
		test.info("Select the radio button Allow");
		test.info("Click on dropdown of IPv4");
		test.info("Select Subnet Ipv4");
		test.info("Click on save button");
		test.info("EXPECTED RESULT ::  It should select the subnet IPv4");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a1, "Allow");
		test.pass(a1);
		Assert.assertEquals(a2, "IPv4\n"
				+ "Subnet IPv4");
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is selecting the subnet IPv4");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test04() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Access']")).click();
		Thread.sleep(1000);
		//driver.findElement(By.xpath("//label[@for='accessContainerIPCheckbox']")).click();
		//Thread.sleep(1000);
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//span[@class='enter-btn'])[3]")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(500);
		String a1=driver.findElement(By.xpath("//label[@for='ipAllowRadio']")).getText();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//select[@id='ipTypeSelection']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on enter button without entering ip");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Access");
		test.info("Select checkbox of Restrict by IP");
		test.info("Select the radio button Allow");
		test.info("Click on IPv4");
		test.info("Click on enter button");
		test.info("EXPECTED RESULT ::  It should click on enter button");
		Assert.assertEquals(a1, "Allow");
		test.pass(a1);
		Assert.assertEquals(a2, "IPv4\n"
				+ "Subnet IPv4");
		test.pass(a2);
		Assert.assertEquals(actual, "Please enter IP address");
		test.pass(actual);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is clicking on enter button");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test05() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Access']")).click();
		Thread.sleep(1000);
		//driver.findElement(By.xpath("//label[@for='accessContainerIPCheckbox']")).click();
		//Thread.sleep(1000);
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='ipInput']")).sendKeys("192.168.1.1");
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//label[@for='ipAllowRadio']")).getText();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//select[@id='ipTypeSelection']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Enter IP address");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Access");
		test.info("Select checkbox of Restrict by IP");
		test.info("Select the radio button Allow");
		test.info("Click on IPv4");
		test.info("Enter IP address");
		test.info("EXPECTED RESULT ::  It should enter the IP address");
		Assert.assertEquals(a1, "Allow");
		test.pass(a1);
		Assert.assertEquals(a2, "IPv4\n"
				+ "Subnet IPv4");
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is entering the IP address");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test06() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Access']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='accessContainerIPCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[19]/div[2]/div[5]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Deselect the Restrict by IP");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Access");
		test.info("De-Select checkbox of Restrict by IP");
		test.info("Click on save button");
		test.info("EXPECTED RESULT ::  It should deselect the restrict by IP");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is deselecting the restrict by IP");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test07() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Access']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='accessContainerPlatformCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[19]/div[2]/div[5]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select the checkbox of Restrict by platform");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Access");
		test.info("Select checkbox of Restrict by Platform");
		test.info("Click on save button");
		test.info("EXPECTED RESULT ::  It should select the checkbox of restrict by Platform");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is selecting the checkbox of restrict by Platform");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test08() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Access']")).click();
		Thread.sleep(1000);
		//driver.findElement(By.xpath("//label[@for='accessContainerPlatformCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[19]/div[2]/div[4]/div/div/div[1]/div/div[1]/input\n"
				+ "")).sendKeys("dsaf");
		Thread.sleep(1000);
		//driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[19]/div[2]/div[5]/input")).click();
		//Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='no-results-found']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Enter invalid data in search");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Access");
		test.info("Select checkbox of Restrict by Platform");
		test.info("Click on search & Enter invalid text");
		test.info("EXPECTED RESULT ::  It should display no data found");
		Assert.assertEquals(actual, "No results found!");
		test.pass(actual);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying no data found");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test09() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Access']")).click();
		Thread.sleep(1000);
		//driver.findElement(By.xpath("//label[@for='accessContainerPlatformCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[19]/div[2]/div[4]/div/div/div[1]/div/div[1]/input\n"
				+ "")).sendKeys("browser");
		Thread.sleep(1000);
		//driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[19]/div[2]/div[5]/input")).click();
		//Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@data-search='browser']")).getAttribute("data-search");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Enter valid data in search");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Access");
		test.info("Select checkbox of Restrict by Platform");
		test.info("Click on search & Enter valid text");
		test.info("EXPECTED RESULT ::  It should search the browser");
		Assert.assertEquals(actual, "browser");
		test.pass(actual);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is searching the browser");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test10() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Access']")).click();
		Thread.sleep(1000);
		//driver.findElement(By.xpath("//label[@for='accessContainerPlatformCheckbox']")).click();
		//Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-platform='5']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[19]/div[2]/div[5]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		String a1=driver.findElement(By.xpath("//div[@data-search='browser']")).getAttribute("data-search");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on browser");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Access");
		test.info("Select checkbox of Restrict by Platform");
		test.info("Click on browser");
		test.info("Click on save button");
		test.info("EXPECTED RESULT ::  It should not click on chat");
		Assert.assertEquals(a1, "browser");
		test.pass(a1);
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not clicking on chat");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test11() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Access']")).click();
		Thread.sleep(1000);
		//driver.findElement(By.xpath("//label[@for='accessContainerPlatformCheckbox']")).click();
		//Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[19]/div[2]/div[4]/div/div/div[2]/div/div[2]/div/span[3]\n"
				+ "")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[19]/div[2]/div[5]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		String a1=driver.findElement(By.xpath("//div[@data-search='browser']")).getAttribute("data-search");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on close icon of browser");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Access");
		test.info("Select checkbox of Restrict by Platform");
		test.info("Click on close icon of browser");
		test.info("Click on save button");
		test.info("Refresh the page");
		test.info("EXPECTED RESULT ::  It should click on chat & It should display the users & groups");
		Assert.assertEquals(a1, "browser");
		test.pass(a1);
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is clicking on chat & It is displaying the users & groups");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test12() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Access']")).click();
		Thread.sleep(1000);
		//driver.findElement(By.xpath("//label[@for='accessContainerPlatformCheckbox']")).click();
		//Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-platform='5']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[19]/div[2]/div[5]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		String a1=driver.findElement(By.xpath("//div[@data-search='browser']")).getAttribute("data-search");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Count in Allow");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Access");
		test.info("Select checkbox of Restrict by Platform");
		test.info("Click on browser");
		test.info("Click on save button");
		test.info("EXPECTED RESULT ::  It should display the count");
		Assert.assertEquals(a1, "browser");
		test.pass(a1);
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		String a2=driver.findElement(By.xpath("(//span[@class='user-count'])[7]")).getText();
		Assert.assertEquals(a2, "6");
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the count");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test13() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Access']")).click();
		Thread.sleep(1000);
		//driver.findElement(By.xpath("//label[@for='accessContainerPlatformCheckbox']")).click();
		//Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-platform='5']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[19]/div[2]/div[5]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		String a1=driver.findElement(By.xpath("//div[@data-search='browser']")).getAttribute("data-search");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Count in block");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Access");
		test.info("Select checkbox of Restrict by Platform");
		test.info("Click on browser");
		test.info("Click on save button");
		test.info("EXPECTED RESULT ::  It should display the count");
		Assert.assertEquals(a1, "browser");
		test.pass(a1);
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		String a2=driver.findElement(By.xpath("(//span[@class='user-count'])[8]")).getText();
		Assert.assertEquals(a2, "1");
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the count");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test14() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Access']")).click();
		Thread.sleep(1000);
		//driver.findElement(By.xpath("//label[@for='accessContainerPlatformCheckbox']")).click();
		//Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-platform='5']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[19]/div[2]/div[5]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		String a1=driver.findElement(By.xpath("//div[@data-search='browser']")).getAttribute("data-search");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By clicking again on browser in allow");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Access");
		test.info("Select checkbox of Restrict by Platform");
		test.info("Click on browser");
		test.info("Click on save button");
		test.info("Again click on browser");
		test.info("EXPECTED RESULT ::  It should display only one time");
		Assert.assertEquals(a1, "browser");
		test.pass(a1);
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		String a2=driver.findElement(By.xpath("(//span[@class='user-count'])[8]")).getText();
		Assert.assertEquals(a2, "1");
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying only one time");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test15() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Access']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='accessContainerPlatformCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[19]/div[2]/div[5]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("De-Select the checkbox of Restrict by platform");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Access");
		test.info("De-Select checkbox of Restrict by Platform");
		test.info("Click on save button");
		test.info("EXPECTED RESULT ::  It should deselect the checkbox of restrict by Platform");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is deselecting the checkbox of restrict by Platform");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
