package controls;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class audio {
	WebDriver driver;
	ExtentHtmlReporter htmlReporter;
	ExtentReports extent;

	String extentReportImage = System.getProperty("user.dir")+ "extentReportImage.png";
	@BeforeSuite
	public void StartTest() {
		htmlReporter = new ExtentHtmlReporter("audio.html");
		extent = new ExtentReports();
		extent.attachReporter(htmlReporter);
	}
	@Test
	public void test() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Audio']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionAudioRadioEnable\"]\n")).click();
		driver.findElement(By.xpath("//label[@for='audioPermissionUser']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='audioPermissionOrangeMember']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='audioPermissionAdmin']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[6]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_15-2']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"modalForwardSendMessageBtn\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By selecting all the checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on audio");
		test.info("click on Enable button");
		test.info("click on checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on anyuser");
		test.info("click on any audio in the userpage");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  It should forward and Download the audio");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		String a1=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Assert.assertEquals(a1, "forward-conversation-label-icon");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding & downloading the audio");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test01() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Audio']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionAudioRadioEnable\"]\n")).click();
		driver.findElement(By.xpath("//label[@for='audioPermissionUser']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='audioPermissionOrangeMember']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='audioPermissionAdmin']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[6]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageCloseBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(500);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By de-selecting all the checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Audio");
		test.info("click on Enable button");
		test.info("de-select on checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on anyuser");
		test.info("click on any audio in the userpage");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  It should not forward and Download the audio");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a, "Forwarding Audio file is restricted");
		test.pass(a);
		Assert.assertEquals(a1, "Downloading Audio file is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Permissions applied");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test02() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Audio']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionAudioRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='audioPermissionUser']")).click();
		//Thread.sleep(1000);
		//driver.findElement(By.xpath("//label[@for='audioPermissionOrangeMember']")).click();
		//Thread.sleep(1000);
		//driver.findElement(By.xpath("//label[@for='audioPermissionAdmin']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[6]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[2]/nav/div/div/ul/li[9]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).clear();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("uppi@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_32-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"modalForwardSendMessageBtn\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='abc']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By selecting user checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Audio");
		test.info("click on Enable button");
		test.info("select on user checkbox");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on logout");
		test.info("Login with normal user");
		test.info("Click on user");
		test.info("Select any audio");
		test.info("click on any audio in the userpage");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  It should forward and Download the audio in user account");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		String a1=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Assert.assertEquals(a1, "forward-conversation-label-icon");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding & downloading the audio in only user");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test03() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Audio']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionAudioRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='audioPermissionUser']")).click();
		//Thread.sleep(1000);
		//driver.findElement(By.xpath("//label[@for='audioPermissionOrangeMember']")).click();
		//Thread.sleep(1000);
		//driver.findElement(By.xpath("//label[@for='audioPermissionAdmin']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[6]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[2]/nav/div/div/ul/li[9]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).clear();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("uppi@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageCloseBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(500);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By Deselecting the user checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Audio");
		test.info("click on Enable button");
		test.info("click on user checkbox");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Logout the user");
		test.info("Click on login");
		test.info("Login normal user");
		test.info("Click on user");
		test.info("Select the Audio");
		test.info("Right click on Audio & forward to the user");
		test.info("Click on Download");
		test.info("EXPECTED RESULT ::  It should not forward and Download the Audio for User");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a, "Forwarding Audio file is restricted");
		test.pass(a);
		Assert.assertEquals(a1, "Downloading Audio file is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding & downloading the Audio for User");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test04() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Audio']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionAudioRadioEnable\"]\n")).click();
		//driver.findElement(By.xpath("//label[@for='audioPermissionUser']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='audioPermissionOrangeMember']")).click();
		//Thread.sleep(1000);
		//driver.findElement(By.xpath("//label[@for='audioPermissionAdmin']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[6]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[2]/nav/div/div/ul/li[9]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).clear();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath35@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='workspace-wrapper']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.moveToElement(e).contextClick(e).perform();
		Thread.sleep(3000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_4-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"modalForwardSendMessageBtn\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='abc doo']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By selecting OrangeMember checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Audio");
		test.info("click on Enable button");
		test.info("de-select on checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on logout");
		test.info("Login with orange user");
		test.info("Click on user");
		test.info("Select any audio");
		test.info("Right click on audio & Click on forward");
		test.info("Send to the user");
		test.info("Click on Download for audio");
		test.info("EXPECTED RESULT ::  It should forward and Download the audio in orange users only");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		String a1=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Assert.assertEquals(a1, "forward-conversation-label-icon");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is downloading & forwarding the audio for only orange user");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test05() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Audio']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionAudioRadioEnable\"]\n")).click();
		//driver.findElement(By.xpath("//label[@for='audioPermissionUser']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='audioPermissionOrangeMember']")).click();
		//Thread.sleep(1000);
		//driver.findElement(By.xpath("//label[@for='audioPermissionAdmin']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[6]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[2]/nav/div/div/ul/li[9]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).clear();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath35@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='workspace-wrapper']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(3000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageCloseBtn']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(500);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By deselecting the OrangeMember checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on audio");
		test.info("click on Enable button");
		test.info("click on OrangeMember checkbox");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on logout");
		test.info("Login with orange user");
		test.info("Click on user");
		test.info("Select any audio");
		test.info("Right click on audio & Click on forward");
		test.info("Send to the user");
		test.info("Click on Download for audio");
		test.info("EXPECTED RESULT ::  It should forward and Download the audio in orange users only");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a, "Forwarding Audio file is restricted");
		test.pass(a);
		Assert.assertEquals(a1, "Downloading Audio file is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is downloading & forwarding the audio for only orange user");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test06() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Audio']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionAudioRadioEnable\"]\n")).click();
		//driver.findElement(By.xpath("//label[@for='audioPermissionUser']")).click();
		//Thread.sleep(1000);
		//driver.findElement(By.xpath("//label[@for='audioPermissionOrangeMember']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='audioPermissionAdmin']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[6]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.moveToElement(e).contextClick(e).perform();
		Thread.sleep(3000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_4-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"modalForwardSendMessageBtn\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='abc doo']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By selecting TM-Admin checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Audio");
		test.info("click on Enable button");
		test.info("select on TM-Admin checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on user");
		test.info("Select any audio");
		test.info("Right click on audio & Click on forward");
		test.info("Send to the user");
		test.info("Click on Download for audio");
		test.info("EXPECTED RESULT ::  It should forward and Download the audio in TM-admin users only");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		String a1=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Assert.assertEquals(a1, "forward-conversation-label-icon");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is downloading & forwarding the audio for only Tm-admin user");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test07() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Audio']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionAudioRadioEnable\"]\n")).click();
		//driver.findElement(By.xpath("//label[@for='audioPermissionUser']")).click();
		//Thread.sleep(1000);
		//driver.findElement(By.xpath("//label[@for='audioPermissionOrangeMember']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='audioPermissionAdmin']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[6]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(3000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageCloseBtn']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(500);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By deselecting TM-Admin in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on audio");
		test.info("click on Enable button");
		test.info("click on TM-Admin checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on user");
		test.info("click on audio in the userpage");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  It should forward and Download the audio in TM-Admin");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a, "Forwarding Audio file is restricted");
		test.pass(a);
		Assert.assertEquals(a1, "Downloading Audio file is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding & downloading the audio in TM-admin");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test08() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Audio']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionAudioRadioEnable\"]\n")).click();
		driver.findElement(By.xpath("//label[@for='audioPermissionUser']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='audioPermissionOrangeMember']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='audioPermissionAdmin']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[6]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_15-2']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"modalForwardSendMessageBtn\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By selecting all the checkbox in Enable radiobutton in Groups");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Audio");
		test.info("click on Enable button");
		test.info("select all the checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on anygroup");
		test.info("click on any Audio in the grouppage");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  It should forward and Download the Audio in any Group");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		String a1=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Assert.assertEquals(a1, "forward-conversation-label-icon");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding & downloading the Audio in any group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test09() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Audio']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionAudioRadioEnable\"]\n")).click();
		driver.findElement(By.xpath("//label[@for='audioPermissionUser']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='audioPermissionOrangeMember']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='audioPermissionAdmin']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[6]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageCloseBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(500);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By de-selecting all the checkbox in Enable radiobutton in Groups");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Audio");
		test.info("click on Enable button");
		test.info("de-select on checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on anyGroup");
		test.info("click on any Audio in the group page");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  It should not forward and Download the Audio in Group page");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a, "Forwarding Audio file is restricted");
		test.pass(a);
		Assert.assertEquals(a1, "Downloading Audio file is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding & downloading the Audio in Group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test10() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Audio']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"permissionAudioRadioDisable\"]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[6]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-attachment-btn input-action-btn']")).click();
		Thread.sleep(2000);
		Robot rb = new Robot();
		Thread.sleep(1000);
		//e.sendKeys("/home/tvisha/Pictures/Screenshot from 2022-06-04 18-47-59.png");
		StringSelection str = new StringSelection("/home/tvisha/Downloads/Instrumental.mp3");
		Toolkit.getDefaultToolkit().getSystemClipboard().setContents(str, null);
		Thread.sleep(2000);
		rb.keyPress(KeyEvent.VK_CONTROL);
		rb.keyPress(KeyEvent.VK_V);

		// release Control+V for pasting
		rb.keyRelease(KeyEvent.VK_CONTROL);
		rb.keyRelease(KeyEvent.VK_V);
		// for pressing and releasing Enter
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(1000);
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(500);
		String a2=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='remove-messenger-attachment']")).click();
		Thread.sleep(3000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(3000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageCloseBtn']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(500);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("By clicking on Disable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Audio");
		test.info("click on Disable button");
		test.info("click on save button");
		test.info("Click on anyuser");
		test.info("click on any Audio in the userpage");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  It should not forward and Download the Audio");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a2, "Audio file uploading is disabled");
		test.pass(a2);
		Assert.assertEquals(a, "Forwarding Audio file is restricted");
		test.pass(a);
		Assert.assertEquals(a1, "Downloading Audio file is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Permissions applied");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
