package controls;

import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;
import org.testng.annotations.BeforeSuite;

import java.io.IOException;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;

public class Group {
	WebDriver driver;
	ExtentHtmlReporter HtmlReporter;
	ExtentReports extent;

	@BeforeSuite
	public void Starttest() {
		HtmlReporter = new ExtentHtmlReporter("Group.html");
		extent = new ExtentReports();
		extent.attachReporter(HtmlReporter);
	}
	@Test
	public void test() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-value='Group']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		//All user close button
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[3]/div/div[2]/div/div[2]/div[1]/span[3]")).click();
		Thread.sleep(500);
		//All Orange members close button
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[3]/div/div[2]/div/div[2]/div/span[3]")).click();
		Thread.sleep(1000);
		//save button
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[9]/input")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on group enable with no users");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Deselect the All Users in Who can create the group");
		test.info("Deselect the All Orange members in Who can create the group");
		test.info("Click on save button");
		test.info("EXPECTED RESULT ::  It should display toast as please select atleast one user ");
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Assert.assertEquals("Please select at least one user", a);
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Please select at least one user ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("group");	
	}
	@Test
	public void test01() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-value='Group']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		//search field
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[3]/div/div[1]/div[2]/div[1]/input")).sendKeys("maneesh");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on group enable with search valid name");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Click on search in Who can create the group");
		test.info("Enter text : maneesh");
		test.info("EXPECTED RESULT ::  It should display the user name ");
		String a=driver.findElement(By.xpath("//div[@data-search='maneesh']")).getAttribute("data-search");
		Assert.assertEquals("maneesh", a);
		System.out.println(a);
		test.pass(a);
		String a1=driver.findElement(By.xpath("//div[@data-search='abc maneesh1']")).getAttribute("data-search");
		Assert.assertEquals("abc maneesh1", a1);
		System.out.println(a1);
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is display user name ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("1");	
	}
	@Test
	public void test02() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-value='Group']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		//search field
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[3]/div/div[1]/div[2]/div[1]/input")).sendKeys("aaaaa");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on group enable with search invalid name");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Click on search in Who can create the group");
		test.info("Enter text : aaaa");
		test.info("EXPECTED RESULT ::  It should not display the user name ");
		String a=driver.findElement(By.xpath("//div[@class='no-results-found']")).getText();
		Assert.assertEquals("No results found!", a);
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  No results found! ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("2");	
	}
	@Test
	public void test03() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-value='Group']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(1000);
		//Click on test user name
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[3]/div/div[2]/div/div[2]/div[1]/span[3]")).click();
		Thread.sleep(1000);
		//save button
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[9]/input")).click();
		Thread.sleep(2000);
		driver.navigate().refresh();
		driver.findElement(By.xpath("//div[@class='add-btn']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='add-group-btn']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='groupNameInput']")).sendKeys("aaaaaa");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-userid='32']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='createGroupSubmitBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on group enable with permission only orange members");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Deselect the all users in Who can create the group");
		test.info("Click on save button");
		test.info("Refresh the page");
		test.info("Click on add button");
		test.info("Click on add group button");
		test.info("Enter group name : test");
		test.info("Select user into group");
		test.info("Click on create button");
		test.info("EXPECTED RESULT ::  It should not create the group name ");
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Assert.assertEquals("You are not allowed to create group", a);
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  You are not allowed to create group ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("3");	
	}
	@Test
	public void test04() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-value='Group']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[3]/div/div[2]/div/div[2]/div[1]/span[3]")).click();
		Thread.sleep(1000);
		//Click on orange members icon
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[3]/div/div[1]/div[2]/div[2]/div[1]/span[2]")).click();
		//save button
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[9]/input")).click();
		Thread.sleep(2000);
		driver.navigate().refresh();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[2]/nav/div/div/ul/li[9]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).clear();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath35@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='workspace-wrapper']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='add-btn']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='groupNameInput']")).sendKeys("aaaaaabc");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-userid='32']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='createGroupSubmitBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on group enable with permission only orange members");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Deselect the all orange members in Who can create the group");
		test.info("Click on save button");
		test.info("Login into orange user");
		test.info("Click on add button");
		test.info("Enter group name : test");
		test.info("Select user into group");
		test.info("Click on create button");
		test.info("EXPECTED RESULT ::  It should not create the group name ");
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Assert.assertEquals("You are not allowed to create group", a);
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  You are not allowed to create group ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("4");	
	}
	@Test
	public void test05() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-value='Group']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(1000);
		//Click on only one user & one orange user 
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[3]/div/div[1]/div[2]/div[2]/div[9]/span[2]\n"
				+ "")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[3]/div/div[1]/div[1]/div[2]")).click();
		//save button
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[9]/input")).click();
		Thread.sleep(2000);
		driver.navigate().refresh();
		driver.findElement(By.xpath("//div[@class='add-btn']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='add-group-btn']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='groupNameInput']")).sendKeys("aaaa");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-userid='32']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='createGroupSubmitBtn']")).click();
		Thread.sleep(2000);
		String a1=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Assert.assertEquals("You are not allowed to create group", a1);
		Thread.sleep(1000);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on group enable with permission only one user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Click on user : test");
		test.info("Deselect the all orange members in Who can create the group");
		test.info("Click on orange member : krishna");
		test.info("Click on save button");
		test.info("Click on add button");
		test.info("Click on add group");
		test.info("Enter group name : aaa");
		test.info("Select any user");
		test.info("Click on create");
		test.pass(a1);
		test.info("EXPECTED RESULT ::  It should not create the group name ");
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not creating the group for user");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("5");	
	}
	@Test
	public void test06() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-value='Group']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(1000);
		//Click on orange user icon 
		driver.findElement(By.xpath("(//div[@class='orange-switch-btn'])[2]")).click();
		Thread.sleep(2000);
		//search in who can create group
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[3]/div/div[1]/div[2]/div[1]/input")).sendKeys("upendra");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on group enable and search in who can create group with valid user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Select the orange user : upendra");
		test.info("Search the valid username in Who can create group : upendra");
		test.info("EXPECTED RESULT ::  It should search the user name ");
		String a=driver.findElement(By.xpath("//div[@data-search='Upendra']")).getAttribute("data-search");
		Assert.assertEquals("Upendra", a);
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is searching the username ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("6");	
	}
	@Test
	public void test07() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-value='Group']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		//Click on only one user & one orange user 
		driver.findElement(By.xpath("(//div[@class='orange-switch-btn'])[2]")).click();
		Thread.sleep(2000);
		//search in who can create group
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[3]/div/div[1]/div[2]/div[1]/input")).sendKeys("test");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on group enable and search in who can create group with invalid user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Click on user : test");
		test.info("Select the orange user : krishna");
		test.info("Search the invalid user name in who can create the group");
		test.info("EXPECTED RESULT ::  It should not display the searched user name ");
		String a = driver.findElement(By.xpath("//div[@class='no-results-found']")).getText();
		Assert.assertEquals("No results found!", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  No results found! ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("7");	
	}
	@Test
	public void test08() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-value='Group']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		//Click on only one user & one orange user 
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[3]/div/div[2]/div/div[1]/input")).sendKeys("upendra");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on search icon in users who can create the group with valid user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Click on search icon in users who can create the group");
		test.info("Select the orange user : upendra");
		test.info("EXPECTED RESULT ::  It should display the username");
		String a=driver.findElement(By.xpath("//div[@data-search='Upendra']")).getAttribute("data-search");
		Assert.assertEquals("Upendra", a);
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the username ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("8");	
	}
	@Test
	public void test09() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-value='Group']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		//Click on only one user & one orange user 
		Thread.sleep(2000);
		//search in who can create group
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[3]/div/div[2]/div/div[1]/input")).sendKeys("test");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on group enable and search icon in users who can create group with invalid user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Click on search icon in users who can create the group");
		test.info("Select the orange user : krishna");
		test.info("Search the invalid user name in who can create the group");
		test.info("EXPECTED RESULT ::  It should not display the searched user name ");
		String a = driver.findElement(By.xpath("//div[@class='no-results-found']")).getText();
		Assert.assertEquals("No results found!", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  No results found! ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("9");	
	}
	@Test
	public void test10() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-value='Group']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[3]/div/div[1]/div[2]/div[1]/span[2]")).click();
		Thread.sleep(500);
		Thread.sleep(2000);		
		//Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on group enable and Count the users in members");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Count the users in members");
		test.info("EXPECTED RESULT ::  It should display the count of the user ");
		String a = driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[3]/div/div[1]/div[2]/div[1]/span[2]")).getText();
		Assert.assertEquals("28", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the user count ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("10");	
	}
	@Test
	public void test11() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-value='Group']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[3]/div/div[2]/div/div[1]/span[3]\n"
				+ "")).click();
		Thread.sleep(500);
		Thread.sleep(2000);		
		//Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on group enable and Count the users in members");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Count the users in members");
		test.info("EXPECTED RESULT ::  It should display the count of the user ");
		String a = driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[3]/div/div[2]/div/div[1]/span[3]\n"
				+ "")).getText();
		Assert.assertEquals("2", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the user count ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("11");	
	}
	@Test
	public void test12() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-value='Group']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		//Click on only one user & one orange user 
		driver.findElement(By.xpath("(//div[@class='orange-switch-btn'])[2]")).click();
		Thread.sleep(500);
		Thread.sleep(2000);		
		//Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on group enable and Count the orange members in members");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Count the orange members in members");
		test.info("EXPECTED RESULT ::  It should display the count of the orange user ");
		String a = driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[3]/div/div[1]/div[2]/div[1]/span[2]")).getText();
		Assert.assertEquals("7", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the orange user count ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("12");	
	}
	@Test
	public void test13() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-value='Group']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		//Click on checkbox of members name 
		driver.findElement(By.xpath("//label[@for='groupControlMemberListCheckbox']")).click();
		Thread.sleep(2000);		
		//save button
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[9]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(2000);
		driver.navigate().refresh();
		driver.findElement(By.xpath("//div[@data-name='Dev n test']")).click();
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on group enable & click on checkbox of member name in other group control ");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Goto other group controls");
		test.info("Click on checkbox of member names");
		test.info("Click on save button");
		test.info("Click on refresh");
		test.info("Click on non-admin group");
		test.info("EXPECTED RESULT ::  It should not display the users ");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not displaying the users ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("13");	
	}
	@Test
	public void test14() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-value='Group']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		//Click on checkbox of members name 
		driver.findElement(By.xpath("//label[@for='groupControlMemberCountCheckbox']")).click();
		Thread.sleep(2000);		
		//save button
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[9]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(2000);
		driver.navigate().refresh();
		driver.findElement(By.xpath("//div[@data-name='Dev n test']")).click();
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on group enable & click on checkbox of member count in other group control ");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Goto other group controls");
		test.info("Click on checkbox of member count");
		test.info("Click on save button");
		test.info("Click on refresh");
		test.info("Click on non-admin group");
		test.info("EXPECTED RESULT ::  It should not display the member count in group ");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		String a=driver.findElement(By.xpath("//input[@id='groupProfileUserSearch']")).getAttribute("value");
		Assert.assertEquals("", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not displaying member count in group ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("14");	
	}
	@Test
	public void test15() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-value='Group']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		//Click on checkbox of members name 
		driver.findElement(By.xpath("//label[@for='groupControlMemberListCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='groupControlMemberCountCheckbox']")).click();
		Thread.sleep(2000);		
		//save button
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[9]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(2000);
		driver.navigate().refresh();
		driver.findElement(By.xpath("//div[@data-name='Dev n test']")).click();
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on group enable & De-select on checkbox of member count & members names in other group control ");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Goto other group controls");
		test.info("Click on checkbox of member count");
		test.info("Click on checkbox of members names");
		test.info("Click on save button");
		test.info("Click on refresh");
		test.info("Click on non-admin group");
		test.info("EXPECTED RESULT ::  It should display the member count & members names in group ");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		String a=driver.findElement(By.xpath("//input[@id='groupProfileUserSearch']")).getAttribute("placeholder");
		Assert.assertEquals(a, "Members (4)");
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying member count & members names in group ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("15");	
	}
	@Test
	public void test16() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[11]/span")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='groupControlChatHistoryAdmin']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='groupControlChatHistoryModerator']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='groupControlChatHistoryTMAdmin']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='groupControlChatHistoryAll']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[9]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[11]/span")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Actions ac = new Actions(driver);
		ac.sendKeys(Keys.PAGE_DOWN).perform();
		ac.sendKeys(Keys.PAGE_DOWN).perform();
		Thread.sleep(500);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]\n"
				+ "")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on deselect all the options in who can delete chat history");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Goto other group controls");
		test.info("Deselect all the options in chat history");
		test.info("Deselect all the options in what can be deleted");
		test.info("Click on save button");
		test.info("Click on refresh");
		test.info("Click on admin group");
		test.info("Click on profile");
		test.info("Click on settings");
		test.info("EXPECTED RESULT ::  It should not display the everyone with all msgs & files");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		String a=driver.findElement(By.xpath("//div[@class='group-delete-data-wrapper clearfix-height']")).getText();
		Assert.assertEquals(a, "Group");
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not displaying the everyone with all msgs & files");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("16");	
	}
	@Test
	public void test17() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[11]/span")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryAdmin']")).click();
		//Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryModerator']")).click();
		//Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryTMAdmin']")).click();
		Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryAll']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[9]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]\n"
				+ "")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on deselect all the options in who can delete chat history");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Goto other group controls");
		test.info("Deselect all the options in chat history");
		test.info("Deselect all the options in what can be deleted");
		test.info("Click on save button");
		test.info("Click on refresh");
		test.info("Click on moderator group");
		test.info("Click on profile");
		test.info("Click on settings");
		test.info("EXPECTED RESULT ::  It should not display the everyone with All msgs & files");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not displaying the everyone with All msgs & files");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("17");	
	}
	@Test
	public void test18() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[11]/span")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryAdmin']")).click();
		//Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryModerator']")).click();
		//Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryTMAdmin']")).click();
		Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryAll']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[9]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='group-options-button']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//div[@class='group-option'])[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on deselect all the options in who can delete chat history");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Goto other group controls");
		test.info("Deselect all the options in chat history");
		test.info("Deselect all the options in what can be deleted");
		test.info("Click on save button");
		test.info("Click on refresh");
		test.info("Click on dashboard");
		test.info("Click on group page");
		test.info("Select any group");
		test.info("Click on 3 dots");
		test.info("Select all msgs & files");
		test.info("Click on yes button");
		test.info("EXPECTED RESULT ::  It should not delete all msgs & files");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a1, "You don't have permissions to delete chat history");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deleting all msgs & files");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("18");	
	}
	@Test
	public void test19() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[11]/span")).click();
		Thread.sleep(500);
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryAdmin']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='groupControlChatHistoryModerator']")).click();
		//Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryTMAdmin']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='groupControlChatHistoryAll']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[9]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[11]/span")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Actions a = new Actions(driver);
		a.sendKeys(Keys.PAGE_DOWN).perform();
		a.sendKeys(Keys.PAGE_DOWN).perform();
		Thread.sleep(500);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on moderator & All in who can delete chat history");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Goto other group controls");
		test.info("Click on moderator in chat history");
		test.info("Click on All in what can be deleted");
		test.info("Click on save button");
		test.info("Click on refresh");
		test.info("Click on moderator group");
		test.info("Click on profile");
		test.info("Click on settings");
		test.info("EXPECTED RESULT ::  It should display the everyone with All msgs & files");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		test.log(Status.FAIL ,"ACTUAL RESULT ::  It is not displaying the everyone with All msgs & files");
		test.pass("Test Case:: TestCase FAILED");
		driver.close();
		System.out.println("19");	
	}
	@Test
	public void test20() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[11]/span")).click();
		Thread.sleep(500);
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryAdmin']")).click();
		//Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryModerator']")).click();
		//Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryTMAdmin']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='groupControlChatHistoryMessages']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[9]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on moderator & only msgs in who can delete chat history");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Goto other group controls");
		test.info("Click on moderator in chat history");
		test.info("Click on Only messages in what can be deleted");
		test.info("Click on save button");
		test.info("Click on refresh");
		test.info("Click on moderator group");
		test.info("Click on profile");
		test.info("Click on settings");
		test.info("EXPECTED RESULT ::  It should display the everyone with only msgs");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		test.log(Status.FAIL ,"ACTUAL RESULT ::  It is not displaying the everyone with only msgs");
		test.pass("Test Case:: TestCase FAILED");
		driver.close();
		System.out.println("20");	
	}
	@Test
	public void test21() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[11]/span")).click();
		Thread.sleep(500);
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryAdmin']")).click();
		//Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryModerator']")).click();
		//Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryTMAdmin']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='groupControlChatHistoryFiles']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[9]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on moderator & only files in who can delete chat history");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Goto other group controls");
		test.info("Click on moderator in chat history");
		test.info("Click on Only files in what can be deleted");
		test.info("Click on save button");
		test.info("Click on refresh");
		test.info("Click on moderator group");
		test.info("Click on profile");
		test.info("Click on settings");
		test.info("EXPECTED RESULT ::  It should display the everyone with only files");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		test.log(Status.FAIL ,"ACTUAL RESULT ::  It is not displaying the everyone with only files");
		test.pass("Test Case:: TestCase FAILED");
		driver.close();
		System.out.println("21");	
	}
	@Test
	public void test22() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[11]/span")).click();
		Thread.sleep(500);
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='groupControlChatHistoryAdmin']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='groupControlChatHistoryModerator']")).click();
		//Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryTMAdmin']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='groupControlChatHistoryAll']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[9]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[11]/span")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Actions a = new Actions(driver);
		a.sendKeys(Keys.PAGE_DOWN).perform();
		a.sendKeys(Keys.PAGE_DOWN).perform();
		Thread.sleep(500);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on Group admin & All msgs & files in who can delete chat history");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Goto other group controls");
		test.info("Click on Group admin in chat history");
		test.info("Click on All in what can be deleted");
		test.info("Click on save button");
		test.info("Click on refresh");
		test.info("Click on admin group");
		test.info("Click on profile");
		test.info("Click on settings");
		test.info("EXPECTED RESULT ::  It should display the everyone with All msgs & files");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		String a1=driver.findElement(By.xpath("//div[@class='group-delete-data-container']")).getText();
		Assert.assertEquals(a1, "All Messages & Files\n"
				+ "Only Messages\n"
				+ "Only Files\n"
				+ "Group");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the everyone with All msgs & files");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("22");	
	}
	@Test
	public void test23() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[11]/span")).click();
		Thread.sleep(500);
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryAdmin']")).click();
		//Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryModerator']")).click();
		//Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryTMAdmin']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='groupControlChatHistoryMessages']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[9]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on group admin & only msgs in who can delete chat history");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Goto other group controls");
		test.info("Click on group admin in chat history");
		test.info("Click on Only messages in what can be deleted");
		test.info("Click on save button");
		test.info("Click on refresh");
		test.info("Click on admin group");
		test.info("Click on profile");
		test.info("Click on settings");
		test.info("EXPECTED RESULT ::  It should display the everyone with only msgs");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		String a1=driver.findElement(By.xpath("//div[@class='group-delete-data-container']")).getText();
		Assert.assertEquals(a1, "Only Messages\n"
				+ "Group");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the everyone with only msgs");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("23");	
	}
	@Test
	public void test24() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[11]/span")).click();
		Thread.sleep(500);
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryAdmin']")).click();
		//Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryModerator']")).click();
		//Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryTMAdmin']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='groupControlChatHistoryFiles']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[9]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[2]")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on group admin & only files in who can delete chat history");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Goto other group controls");
		test.info("Click on group admin in chat history");
		test.info("Click on Only files in what can be deleted");
		test.info("Click on save button");
		test.info("Click on refresh");
		test.info("Click on admin group");
		test.info("Click on profile");
		test.info("Click on settings");
		test.info("EXPECTED RESULT ::  It should display the everyone with only files");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		String a1=driver.findElement(By.xpath("//div[@class='group-delete-data-container']")).getText();
		Assert.assertEquals(a1, "Only Files\n"
				+ "Group");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the everyone with only files");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("24");	
	}
	@Test
	public void test25() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[11]/span")).click();
		Thread.sleep(500);
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='groupControlChatHistoryAdmin']")).click();
		Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryModerator']")).click();
		//Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='groupControlChatHistoryTMAdmin']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='groupControlChatHistoryAll']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[9]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='group-options-button']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//div[@class='group-option'])[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Tm-admin & all msgs & files in who can delete chat history");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Goto other group controls");
		test.info("Select the TM-admin in chat history");
		test.info("Select all the options in what can be deleted");
		test.info("Click on save button");
		test.info("Click on refresh");
		test.info("Click on dashboard");
		test.info("Click on group page");
		test.info("Select any group");
		test.info("Click on 3 dots");
		test.info("Select all msgs & files");
		test.info("Click on yes button");
		test.info("EXPECTED RESULT ::  It should delete all msgs & files");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a1, "Data deleted successfully");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is deleting all msgs & files");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("25");	
	}
	@Test
	public void test26() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[11]/span")).click();
		Thread.sleep(500);
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryAdmin']")).click();
		//Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryModerator']")).click();
		//Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryTMAdmin']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='groupControlChatHistoryMessages']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[9]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='group-options-button']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//div[@class='group-option'])[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Tm-admin & only msgs the options in who can delete chat history");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Goto other group controls");
		test.info("Select the TM-admin in chat history");
		test.info("Select only msgs in what can be deleted");
		test.info("Click on save button");
		test.info("Click on refresh");
		test.info("Click on dashboard");
		test.info("Click on group page");
		test.info("Select any group");
		test.info("Click on 3 dots");
		test.info("Select only msgs ");
		test.info("Click on yes button");
		test.info("EXPECTED RESULT ::  It should delete only msgs ");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a1, "Data deleted successfully");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is deleting only msgs");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("26");	
	}
	@Test
	public void test27() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[11]/span")).click();
		Thread.sleep(500);
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryAdmin']")).click();
		//Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryModerator']")).click();
		//Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryTMAdmin']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='groupControlChatHistoryFiles']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[9]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='group-options-button']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//div[@class='group-option'])[5]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Tm-admin & only files the options in who can delete chat history");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Goto other group controls");
		test.info("Select the TM-admin in chat history");
		test.info("Select only files in what can be deleted");
		test.info("Click on save button");
		test.info("Click on refresh");
		test.info("Click on dashboard");
		test.info("Click on group page");
		test.info("Select any group");
		test.info("Click on 3 dots");
		test.info("Select only files ");
		test.info("Click on yes button");
		test.info("EXPECTED RESULT ::  It should delete only files ");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a1, "Data deleted successfully");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is deleting only files");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("27");	
	}
	@Test
	public void test28() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[11]/span")).click();
		Thread.sleep(500);
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioEnable\"]")).click();
		Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryAdmin']")).click();
		//Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryModerator']")).click();
		//Thread.sleep(500);
		//driver.findElement(By.xpath("//label[@for='groupControlChatHistoryTMAdmin']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='groupControlChatHistoryFiles']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[9]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='group-options-button']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//div[@class='group-option'])[5]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Tm-admin without selecting the options in who can delete chat history");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button enable in groups");
		test.info("Goto other group controls");
		test.info("Select the TM-admin in chat history");
		test.info("De-Select only files in what can be deleted");
		test.info("Click on save button");
		test.info("Click on refresh");
		test.info("Click on dashboard");
		test.info("Click on group page");
		test.info("Select any group");
		test.info("Click on 3 dots");
		test.info("Select All msgs & files ");
		test.info("Click on yes button");
		test.info("EXPECTED RESULT ::  It should not delete all msgs & files ");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a1, "Data deleted successfully");
		test.pass(a1);
		test.log(Status.FAIL ,"ACTUAL RESULT ::  It is deleting all msgs & files");
		test.pass("Test Case:: TestCase FAILED");
		driver.close();
		System.out.println("28");	
	}
	@Test
	public void test29() throws InterruptedException, IOException {
		//Disable
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[11]/span")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"permissionGroupRadioDisable\"]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[12]/div[2]/div[9]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		driver.navigate().refresh();
		//Thread.sleep(1000);
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='add-btn']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='add-group-btn']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='groupNameInput']")).sendKeys("aaaaaa");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-userid='32']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='createGroupSubmitBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on disable");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on admin dashboard");
		test.info("Click on controls");
		test.info("Click on Groups");
		test.info("Select radio button disable in groups");
		test.info("Click on save button");
		test.info("Click on refresh");
		test.info("Click on add button");
		test.info("Click on add group");
		test.info("Enter text in group name");
		test.info("Select the user");
		test.info("Click on create button");
		test.info("EXPECTED RESULT ::  It should not create the group ");
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Assert.assertEquals(a, "You are not allowed to create group");
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not creating the group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
