package controls;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;

import java.awt.AWTException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class Mentions {
	WebDriver driver;
	ExtentHtmlReporter htmlReporter;
	ExtentReports extent;

	String extentReportImage = System.getProperty("user.dir")+ "extentReportImage.png";
	@BeforeSuite
	public void StartTest() {
		htmlReporter = new ExtentHtmlReporter("mention.html");
		extent = new ExtentReports();
		extent.attachReporter(htmlReporter);
	}
	@Test
	public void test00() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[19]/span")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[18]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='Dummy']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("@sha");
		Thread.sleep(1000);
		Actions ac=new Actions(driver);
		ac.sendKeys(Keys.ARROW_RIGHT).perform();
		ac.sendKeys(Keys.ARROW_RIGHT).sendKeys(Keys.ENTER).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(2000);
		String a2=driver.findElement(By.xpath("//span[@class='user-mention-trigger']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Mentions Enable");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Mentions");
		test.info("Select Enable");
		Assert.assertEquals(a, "Enable");
		test.pass(a);
		test.info("click on save");
		Assert.assertEquals(a1, "Permissions applied");
		test.pass(a1);
		test.info("Refresh the page");
		test.info("Select any user");
		test.info("Enter mention : @sha");
		test.info("EXPECTED RESULT ::  It should enter the mentions in chat page");
		Assert.assertEquals(a2, "user-mention-trigger");
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is entering mentions in chat page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test01() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[19]/span")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//label[@for='mentionsUserControlCheckbox']")).getText();
		driver.findElement(By.xpath("//label[@for='mentionsUserControlCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[18]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='Dummy']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("@sha");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='user-mentions-container hidden']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select the checkbox of Disable mention one-one chat in user chat");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Mentions");
		test.info("Select Enable");
		Assert.assertEquals(a, "Enable");
		test.pass(a);
		test.info("Select the checkbox of Disable one-one chat");
		Assert.assertEquals(a3, "Disable mentions in One-to-One chat");
		test.pass(a3);
		test.info("click on save");
		Assert.assertEquals(a1, "Permissions applied");
		test.pass(a1);
		test.info("Refresh the page");
		test.info("Select any user");
		test.info("Enter mention : @sha");
		test.info("EXPECTED RESULT ::  It should not display entered mentions in chat page");
		Assert.assertEquals(a2, "user-mentions-container hidden");
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not displaying entered mentions in chat page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test02() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[19]/span")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//label[@for='mentionsUserControlCheckbox']")).getText();
		//driver.findElement(By.xpath("//label[@for='mentionsUserControlCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[18]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='take over']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("@kri");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='user-mentions-container']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select the checkbox of Disable mention one-one chat in group chat");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Mentions");
		test.info("Select Enable");
		Assert.assertEquals(a, "Enable");
		test.pass(a);
		test.info("Select the checkbox of Disable one-one chat");
		Assert.assertEquals(a3, "Disable mentions in One-to-One chat");
		test.pass(a3);
		test.info("click on save");
		Assert.assertEquals(a1, "Permissions applied");
		test.pass(a1);
		test.info("Refresh the page");
		test.info("Select any group");
		test.info("Enter mention : @sha");
		test.info("EXPECTED RESULT ::  It should display entered mentions in chat page");
		Assert.assertEquals(a2, "user-mentions-container");
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying entered mentions in chat page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test03() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[19]/span")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//label[@for='mentionsUserControlCheckbox']")).getText();
		driver.findElement(By.xpath("//label[@for='mentionsUserControlCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[18]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='Dummy']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("@sha");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='user-mentions-container']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("De-select the checkbox of Disable mention one-one chat");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Mentions");
		test.info("Select Enable");
		Assert.assertEquals(a, "Enable");
		test.pass(a);
		test.info("De-Select the checkbox of Disable one-one chat");
		Assert.assertEquals(a3, "Disable mentions in One-to-One chat");
		test.pass(a3);
		test.info("click on save");
		Assert.assertEquals(a1, "Permissions applied");
		test.pass(a1);
		test.info("Refresh the page");
		test.info("Select any user");
		test.info("Enter mention : @sha");
		test.info("EXPECTED RESULT ::  It should display entered mentions in chat page");
		Assert.assertEquals(a2, "user-mentions-container");
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying entered mentions in chat page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test04() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[19]/span")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//label[@for='mentionsGroupControlCheckbox']")).getText();
		driver.findElement(By.xpath("//label[@for='mentionsGroupControlCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[18]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='Dummy']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("@sha");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='user-mentions-container']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select the checkbox of Disable mention in group chat in user chat");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Mentions");
		test.info("Select Enable");
		Assert.assertEquals(a, "Enable");
		test.pass(a);
		test.info("Select the checkbox of Disable Group chat");
		Assert.assertEquals(a3, "Disable mentions in Group Chat");
		test.pass(a3);
		test.info("click on save");
		Assert.assertEquals(a1, "Permissions applied");
		test.pass(a1);
		test.info("Refresh the page");
		test.info("Select any user");
		test.info("Enter mention : @sha");
		test.info("EXPECTED RESULT ::  It should display entered mentions in chat page");
		Assert.assertEquals(a2, "user-mentions-container");
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying entered mentions in chat page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test05() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[19]/span")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//label[@for='mentionsGroupControlCheckbox']")).getText();
		//driver.findElement(By.xpath("//label[@for='mentionsUserControlCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[18]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='take over']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("@kri");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='user-mentions-container hidden']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select the checkbox of Disable mention group chat in group chat page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Mentions");
		test.info("Select Enable");
		Assert.assertEquals(a, "Enable");
		test.pass(a);
		test.info("Select the checkbox of Disable Group chat");
		Assert.assertEquals(a3, "Disable mentions in Group Chat");
		test.pass(a3);
		test.info("click on save");
		Assert.assertEquals(a1, "Permissions applied");
		test.pass(a1);
		test.info("Refresh the page");
		test.info("Select any group");
		test.info("Enter mention : @sha");
		test.info("EXPECTED RESULT ::  It should display entered mentions in chat page");
		Assert.assertEquals(a2, "user-mentions-container hidden");
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying entered mentions in chat page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test06() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[19]/span")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//label[@for='mentionsGroupControlCheckbox']")).getText();
		driver.findElement(By.xpath("//label[@for='mentionsGroupControlCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[18]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='take over']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("@kri");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='user-mentions-container']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("De-select the checkbox of Disable mention Group chat");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Mentions");
		test.info("Select Enable");
		Assert.assertEquals(a, "Enable");
		test.pass(a);
		test.info("De-Select the checkbox of Disable Group chat");
		Assert.assertEquals(a3, "Disable mentions in Group Chat");
		test.pass(a3);
		test.info("click on save");
		Assert.assertEquals(a1, "Permissions applied");
		test.pass(a1);
		test.info("Refresh the page");
		test.info("Select any group");
		test.info("Enter mention : @kri");
		test.info("EXPECTED RESULT ::  It should display entered mentions in chat page");
		Assert.assertEquals(a2, "user-mentions-container");
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying entered mentions in chat page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test07() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[19]/span")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//label[@for='mentionsNonGroupUserControlCheckbox']")).getText();
		driver.findElement(By.xpath("//label[@for='mentionsNonGroupUserControlCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[18]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='take over']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("@sha");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='user-mentions-container']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select the checkbox of Can mention Non-Group users within a group");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Mentions");
		test.info("Select Enable");
		Assert.assertEquals(a, "Enable");
		test.pass(a);
		test.info("Select the checkbox of Can mention Non-Group users within a group");
		Assert.assertEquals(a3, "Can mention Non-Group users within a group");
		test.pass(a3);
		test.info("click on save");
		Assert.assertEquals(a1, "Permissions applied");
		test.pass(a1);
		test.info("Refresh the page");
		test.info("Select any group");
		test.info("Enter mention : @sha");
		test.info("EXPECTED RESULT ::  It should display non group mentions in that group chat page");
		Assert.assertEquals(a2, "user-mentions-container");
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying non group member mentions in that group chat page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test08() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[19]/span")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//label[@for='mentionsNonGroupUserControlCheckbox']")).getText();
		driver.findElement(By.xpath("//label[@for='mentionsNonGroupUserControlCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[18]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='take over']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("@sha");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='user-mentions-container hidden']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("De-select the checkbox of Can mention Non-Group users within a group");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Mentions");
		test.info("Select Enable");
		Assert.assertEquals(a, "Enable");
		test.pass(a);
		test.info("De-Select the checkbox of Can mention Non-Group users within a group");
		Assert.assertEquals(a3, "Can mention Non-Group users within a group");
		test.pass(a3);
		test.info("click on save");
		Assert.assertEquals(a1, "Permissions applied");
		test.pass(a1);
		test.info("Refresh the page");
		test.info("Select any group");
		test.info("Enter mention : @sha");
		test.info("EXPECTED RESULT ::  It should not display non group member mentions in that group chat page");
		Assert.assertEquals(a2, "user-mentions-container hidden");
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not displaying non group member mentions in that group chat page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test09() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[19]/span")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//label[@for='mentionsCharacterControlCheckbox']")).getText();
		driver.findElement(By.xpath("//label[@for='mentionsCharacterControlCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[18]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='take over']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("@k");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='user-mentions-container hidden']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select the checkbox of Enter Minimum 3 characters after @ to show mention users (Recommended)");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Mentions");
		test.info("Select Enable");
		Assert.assertEquals(a, "Enable");
		test.pass(a);
		test.info("Select the checkbox of Enter Minimum 3 characters after @ to show mention users (Recommended)");
		Assert.assertEquals(a3, "Enter Minimum 3 characters after @ to show mention users (Recommended)");
		test.pass(a3);
		test.info("click on save");
		Assert.assertEquals(a1, "Permissions applied");
		test.pass(a1);
		test.info("Refresh the page");
		test.info("Select any group");
		test.info("Enter mention with single character: @k");
		test.info("EXPECTED RESULT ::  It should not display entered mentions in group chat page");
		Assert.assertEquals(a2, "user-mentions-container hidden");
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not displaying entered mentions in group chat page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void testcase10() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[19]/span")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//label[@for='mentionsCharacterControlCheckbox']")).getText();
		driver.findElement(By.xpath("//label[@for='mentionsCharacterControlCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[18]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='take over']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("@k");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='user-mentions-container']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("De-select the checkbox of Enter Minimum 3 characters after @ to show mention users (Recommended)");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Mentions");
		test.info("Select Enable");
		Assert.assertEquals(a, "Enable");
		test.pass(a);
		test.info("De-Select the checkbox of Enter Minimum 3 characters after @ to show mention users (Recommended)");
		Assert.assertEquals(a3, "Enter Minimum 3 characters after @ to show mention users (Recommended)");
		test.pass(a3);
		test.info("click on save");
		Assert.assertEquals(a1, "Permissions applied");
		test.pass(a1);
		test.info("Refresh the page");
		test.info("Select any group");
		test.info("Enter mention with single character: @k");
		test.info("EXPECTED RESULT ::  It should display entered mentions in group chat page");
		Assert.assertEquals(a2, "user-mentions-container");
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying entered mentions in group chat page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void testcase11() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[19]/span")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//label[@for='mentionsCharacterControlCheckbox']")).getText();
		driver.findElement(By.xpath("//label[@for='mentionsCharacterControlCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[18]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='Dummy']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("@k");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='user-mentions-container hidden']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select the checkbox of Enter Minimum 3 characters after @ to show mention users (Recommended)");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Mentions");
		test.info("Select Enable");
		Assert.assertEquals(a, "Enable");
		test.pass(a);
		test.info("Select the checkbox of Enter Minimum 3 characters after @ to show mention users (Recommended)");
		Assert.assertEquals(a3, "Enter Minimum 3 characters after @ to show mention users (Recommended)");
		test.pass(a3);
		test.info("click on save");
		Assert.assertEquals(a1, "Permissions applied");
		test.pass(a1);
		test.info("Refresh the page");
		test.info("Select any User");
		test.info("Enter mention with single character: @k");
		test.info("EXPECTED RESULT ::  It should not display entered mentions in user chat page");
		Assert.assertEquals(a2, "user-mentions-container hidden");
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not displaying entered mentions in user chat page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void testcase12() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[19]/span")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMentionsEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//label[@for='mentionsCharacterControlCheckbox']")).getText();
		driver.findElement(By.xpath("//label[@for='mentionsCharacterControlCheckbox']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[18]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='Dummy']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("@k");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='user-mentions-container']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("De-select the checkbox of Enter Minimum 3 characters after @ to show mention users (Recommended)");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Mentions");
		test.info("Select Enable");
		Assert.assertEquals(a, "Enable");
		test.pass(a);
		test.info("De-Select the checkbox of Enter Minimum 3 characters after @ to show mention users (Recommended)");
		Assert.assertEquals(a3, "Enter Minimum 3 characters after @ to show mention users (Recommended)");
		test.pass(a3);
		test.info("click on save");
		Assert.assertEquals(a1, "Permissions applied");
		test.pass(a1);
		test.info("Refresh the page");
		test.info("Select any user");
		test.info("Enter mention with single character: @k");
		test.info("EXPECTED RESULT ::  It should display entered mentions in user chat page");
		Assert.assertEquals(a2, "user-mentions-container");
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying entered mentions in user chat page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void testcase13() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[19]/span")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//label[@for='permissionMentionsDisable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMentionsDisable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[18]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='Dummy']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("@sha");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='user-mentions-container hidden']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Mentions Disable");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Mentions");
		test.info("Select Disable");
		Assert.assertEquals(a, "Disable");
		test.pass(a);
		test.info("click on save");
		Assert.assertEquals(a1, "Permissions applied");
		test.pass(a1);
		test.info("Refresh the page");
		test.info("Select any user");
		test.info("Enter mention : @sha");
		test.info("EXPECTED RESULT ::  It should not display mention by entering username");
		Assert.assertEquals(a2, "user-mentions-container hidden");
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not displaying mention by entering username");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
