package controls;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class Metalink {
	WebDriver driver;
	ExtentHtmlReporter htmlReporter;
	ExtentReports extent;

	String extentReportImage = System.getProperty("user.dir")+ "extentReportImage.png";
	@BeforeSuite
	public void StartTest() {
		htmlReporter = new ExtentHtmlReporter("Metalink.html");
		extent = new ExtentReports();
		extent.attachReporter(htmlReporter);
	}
	@Test
	public void test() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[9]/span")).click();
		driver.findElement(By.xpath(" //*[@id=\"permissionLinkRadioEnable\"]")).click();
		driver.findElement(By.xpath("  /html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[3]/div[2]/div[1]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[3]/div[2]/div[2]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[3]/div[2]/div[3]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		driver.navigate().refresh();
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='conversation-message-meta-link']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		driver.findElement(By.xpath("//a[@data-action='forward']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageSendBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_15-2']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@id='modalForwardSendMessageBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By clicking all checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on metalink");
		test.info("click on Enable button");
		test.info("click on checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on user : sharath");
		test.info("Send the metalink");
		test.info("Right click on metalink");
		test.info("Click on forward");
		test.info("Select the user/group");
		test.info("Click on send button in forward");
		test.info("EXPECTED RESULT ::  It should forward the metalink");
		Assert.assertEquals("Permissions applied", a);
		System.out.println(a);
		test.pass(a);
		String a1=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Assert.assertEquals(a1, "forward-conversation-label-icon");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding the metalink");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test01() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[9]/span")).click();
		driver.findElement(By.xpath(" //*[@id=\"permissionLinkRadioEnable\"]")).click();
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[3]/div[2]/div[1]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[3]/div[2]/div[2]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[3]/div[2]/div[3]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		driver.navigate().refresh();
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='conversation-message-meta-link']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		driver.findElement(By.xpath("//a[@data-action='forward']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageSendBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageCloseBtn']")).click();
		Thread.sleep(1000);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("By deselecting all checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on metalink");
		test.info("click on Enable button");
		test.info("click on checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on user : sharath");
		test.info("Send the metalink");
		test.info("Right click on metalink");
		test.info("Click on forward");
		test.info("Click on forward button");
		test.info("EXPECTED RESULT ::  It should not forward the metalink");
		Assert.assertEquals("Permissions applied", a);
		System.out.println(a);
		test.pass(a);
		Assert.assertEquals(a1, "Forwarding Meta Link is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding the metalink");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test02() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[9]/span")).click();
		driver.findElement(By.xpath(" //*[@id=\"permissionLinkRadioEnable\"]")).click();
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[3]/div[2]/div[1]/div[1]/div/label")).click();
		Thread.sleep(1000);
		//driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[5]/div[2]/div[3]/div[2]/div[2]/div[1]/div/label ")).click();
		//Thread.sleep(1000);
		//driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[5]/div[2]/div[3]/div[2]/div[3]/div[1]/div/label ")).click();
		//Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[2]/nav/div/div/ul/li[9]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).clear();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("uppi@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='conversation-message-meta-link']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_32-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"modalForwardSendMessageBtn\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='abc']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By clicking on Users Checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on metalink");
		test.info("click on Enable button");
		test.info("click on User checkbox");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on logout");
		test.info("Login with normal user");
		test.info("Click on user");
		test.info("Right click on metalink in the userpage");
		test.info("Click on Forward");
		test.info("EXPECTED RESULT ::  It should forward the metalink in users only");
		Assert.assertEquals("Permissions applied", a);
		System.out.println(a);
		test.pass(a);
		String a1=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Assert.assertEquals(a1, "forward-conversation-label-icon");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding the metalink in users only");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test03() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[9]/span")).click();
		driver.findElement(By.xpath(" //*[@id=\"permissionLinkRadioEnable\"]")).click();
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[3]/div[2]/div[1]/div[1]/div/label")).click();
		Thread.sleep(1000);
		//driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[5]/div[2]/div[3]/div[2]/div[2]/div[1]/div/label ")).click();
		//Thread.sleep(1000);
		//driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[5]/div[2]/div[3]/div[2]/div[3]/div[1]/div/label ")).click();
		//Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[2]/nav/div/div/ul/li[9]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).clear();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("uppi@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='conversation-message-meta-link']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageCloseBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='abc']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By deselecting on Users Checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on metalink");
		test.info("click on Enable button");
		test.info("click on User checkbox");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on logout");
		test.info("Login with normal user");
		test.info("Click on user");
		test.info("Right click on metalink in the userpage");
		test.info("Click on Forward");
		test.info("EXPECTED RESULT ::  It should not forward the metalink in users only");
		Assert.assertEquals("Permissions applied", a);
		System.out.println(a);
		test.pass(a);
		Assert.assertEquals(a1, "Forwarding Meta Link is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding the metalink in users only");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test04() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[9]/span")).click();
		driver.findElement(By.xpath("  //*[@id=\"permissionLinkRadioEnable\"]")).click();
		//driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[3]/div[2]/div[1]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[3]/div[2]/div[2]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		//driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[5]/div[2]/div[3]/div[2]/div[3]/div[1]/div/label ")).click();
		//Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[2]/nav/div/div/ul/li[9]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).clear();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath35@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='workspace-wrapper']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='conversation-message-meta-link']"));
		Actions ac=new Actions(driver);
		ac.moveToElement(e).contextClick(e).perform();
		Thread.sleep(3000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_4-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"modalForwardSendMessageBtn\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='abc doo']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By clicking on OrangeMember checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on metalink");
		test.info("click on Enable button");
		test.info("click on OrangeMember checkbox");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on logout");
		test.info("Login with Orange user");
		test.info("Click on user");
		test.info("Right click on metalink in the userpage");
		test.info("Click on Forward");
		test.info("EXPECTED RESULT ::  It should forward the metalink in OrangeMember only");
		Assert.assertEquals("Permissions applied", a);
		System.out.println(a);
		test.pass(a);
		String a1=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Assert.assertEquals(a1, "forward-conversation-label-icon");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding the metalink only orangemember");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test05() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[9]/span")).click();
		driver.findElement(By.xpath("  //*[@id=\"permissionLinkRadioEnable\"]")).click();
		//driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[3]/div[2]/div[1]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[3]/div[2]/div[2]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		//driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[5]/div[2]/div[3]/div[2]/div[3]/div[1]/div/label ")).click();
		//Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[2]/nav/div/div/ul/li[9]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).clear();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath35@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='workspace-wrapper']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='conversation-message-meta-link']"));
		Actions ac=new Actions(driver);
		ac.moveToElement(e).contextClick(e).perform();
		Thread.sleep(3000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageCloseBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By deselecting on OrangeMember checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on metalink");
		test.info("click on Enable button");
		test.info("click on OrangeMember checkbox");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on logout");
		test.info("Login with Orange user");
		test.info("Click on user");
		test.info("Right click on metalink in the userpage");
		test.info("Click on Forward");
		test.info("EXPECTED RESULT ::  It should not forward the metalink in OrangeMember only");
		Assert.assertEquals("Permissions applied", a);
		System.out.println(a);
		test.pass(a);
		Assert.assertEquals(a1, "Forwarding Meta Link is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding the metalink only orangemember");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test06() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[9]/span")).click();
		driver.findElement(By.xpath("  //*[@id=\"permissionLinkRadioEnable\"]")).click();
		//driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[5]/div[2]/div[3]/div[2]/div[1]/div[1]/div/label")).click();
		//Thread.sleep(1000);
		//driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[3]/div[2]/div[2]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[3]/div[2]/div[3]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='conversation-message-meta-link']"));
		Actions ac=new Actions(driver);
		ac.moveToElement(e).contextClick(e).perform();
		Thread.sleep(3000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_4-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"modalForwardSendMessageBtn\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='abc doo']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By clicking TM-Admin in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on metalink");
		test.info("click on Enable button");
		test.info("click on TM-Admin checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on user");
		test.info("click on metalink in the userpage");
		test.info("Click on Forward");
		test.info("EXPECTED RESULT ::  It should forward the metalink in TM-Admin");
		Assert.assertEquals("Permissions applied", a);
		System.out.println(a);
		test.pass(a);
		String a1=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Assert.assertEquals(a1, "forward-conversation-label-icon");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding the metalink in TM-admin");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test07() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[9]/span")).click();
		driver.findElement(By.xpath("  //*[@id=\"permissionLinkRadioEnable\"]")).click();
		//driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[5]/div[2]/div[3]/div[2]/div[1]/div[1]/div/label")).click();
		//Thread.sleep(1000);
		//driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[3]/div[2]/div[2]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[3]/div[2]/div[3]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='conversation-message-meta-link']"));
		Actions ac=new Actions(driver);
		ac.moveToElement(e).contextClick(e).perform();
		Thread.sleep(3000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(500);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageCloseBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By deselecting TM-Admin in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on metalink");
		test.info("click on Enable button");
		test.info("click on TM-Admin checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on user");
		test.info("click on metalink in the userpage");
		test.info("Click on Forward");
		test.info("EXPECTED RESULT ::  It should not forward the metalink in TM-Admin");
		Assert.assertEquals("Permissions applied", a);
		System.out.println(a);
		test.pass(a);
		Assert.assertEquals(a1, "Forwarding Meta Link is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding the metalink in TM-admin");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test08() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[9]/span")).click();
		driver.findElement(By.xpath("  //*[@id=\"permissionLinkRadioEnable\"]")).click();
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[3]/div[2]/div[1]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[3]/div[2]/div[2]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[3]/div[2]/div[3]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("//div[@class='conversation-message-meta-link']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_15-2']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"modalForwardSendMessageBtn\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By clicking all checkbox in Enable radiobutton for Groups");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on metalink");
		test.info("click on Enable button");
		test.info("click on checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on any group");
		test.info("click on any metalink in group");
		test.info("Click on Forward");
		test.info("EXPECTED RESULT ::  It should forward the metalink in group");
		Assert.assertEquals("Permissions applied", a);
		System.out.println(a);
		test.pass(a);
		String a1=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Assert.assertEquals(a1, "forward-conversation-label-icon");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding the metalink in group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test09() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[9]/span")).click();
		driver.findElement(By.xpath(" //*[@id=\"permissionLinkRadioEnable\"]")).click();
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[3]/div[2]/div[1]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[3]/div[2]/div[2]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[3]/div[2]/div[3]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("//div[@class='conversation-message-meta-link']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(500);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageCloseBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By de-selecting all checkbox in Enable radiobutton for groups");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on metalink");
		test.info("click on Enable button");
		test.info("De-select checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on anyuser");
		test.info("Right click on any metalink in group");
		test.info("Click on Forward");
		test.info("EXPECTED RESULT ::  It should not forward the metalink in group");
		Assert.assertEquals("Permissions applied", a);
		System.out.println(a);
		test.pass(a);
		Assert.assertEquals(a1, "Forwarding Meta Link is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding the metalink in group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test10() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[9]/span")).click();
		driver.findElement(By.xpath(" //*[@id=\"permissionLinkRadioEnable\"]")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[10]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		driver.findElement(By.xpath("//div[@data-name='aaab']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("//div[@class='conversation-message-meta-link']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(500);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageCloseBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By clicking on Disable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on metalink");
		test.info("click on Disable button");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on anyuser");
		test.info("click on any metalink in the userpage");
		test.info("Click on Forward");
		test.info("EXPECTED RESULT ::  It should not forward the metalink");
		Assert.assertEquals("Permissions applied", a);
		System.out.println(a);
		test.pass(a);
		Assert.assertEquals(a1, "Forwarding Meta Link is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding the metalink");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
