package controls;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class MiscellaneousGroup {
	WebDriver driver;
	ExtentHtmlReporter HtmlReporter;
	ExtentReports extent;

	@BeforeSuite
	public void Starttest() {
		HtmlReporter = new ExtentHtmlReporter("MiscellaneousGroup.html");
		extent = new ExtentReports();
		extent.attachReporter(HtmlReporter);
	}
	@Test
	public void test00() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@psn.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[25]/div[2]/div[1]/div[1]/div[2]")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[25]/div[2]/div[1]/div[2]/div[2]/div/div[1]/span[2]")).getText();
		String a=driver.findElement(By.xpath("//label[@for='permissionMiscellaneousExitGroupsRadioDisable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMiscellaneousExitGroupsRadioDisable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[25]/div[2]/div[2]/input")).click();
		Thread.sleep(2000);
		String actual=driver.switchTo().alert().getText();
		driver.switchTo().alert().accept();
		Thread.sleep(1000);
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='recent-users-search-filter-text hidden']")).getAttribute("class");
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on miscellaneous group with hide in exited/deleted group");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@email.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		test.info("Click on groups tab");
		test.info("Click on radio button of hide");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on recent chat search");
		test.info("Click on all members & groups icon");
		test.info("EXPECTED RESULT ::  It should not display deleted/Exited groups");
		Assert.assertEquals(a3, "Exited / Deleted groups");
		test.pass(a3);
		Assert.assertEquals(a, "Hide");
		test.pass(a);
		Assert.assertEquals(actual, "Tm-Admin updated chat permissions.Reloading Browser..!");
		test.pass(actual);
		Assert.assertEquals(a2, "recent-users-search-filter-text hidden");
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not displaying deleted/Exited groups");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test01() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@psn.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[25]/div[2]/div[1]/div[1]/div[2]")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[25]/div[2]/div[1]/div[2]/div[2]/div/div[1]/span[2]")).getText();
		String a=driver.findElement(By.xpath("//label[@for='permissionMiscellaneousExitGroupsRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMiscellaneousExitGroupsRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[25]/div[2]/div[2]/input")).click();
		Thread.sleep(2000);
		String actual=driver.switchTo().alert().getText();
		driver.switchTo().alert().accept();
		Thread.sleep(1000);
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[1]/div[2]/div[2]/div[1]/div[3]/div[3]/div/div[6]")).getText();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on miscellaneous group with show in exited/deleted group");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@email.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		test.info("Click on groups tab");
		test.info("Click on radio button of show");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on recent chat search");
		test.info("Click on all members & groups icon");
		test.info("EXPECTED RESULT ::  It should display deleted/Exited groups");
		Assert.assertEquals(a3, "Exited / Deleted groups");
		test.pass(a3);
		Assert.assertEquals(a, "Show");
		test.pass(a);
		Assert.assertEquals(actual, "Tm-Admin updated chat permissions.Reloading Browser..!");
		test.pass(actual);
		Assert.assertEquals(a2, "Deleted/Exited Groups");
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying deleted/Exited groups");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test02() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@psn.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[25]/div[2]/div[1]/div[1]/div[2]")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[25]/div[2]/div[1]/div[2]/div[2]/div/div[3]/span[2]")).getText();
		String a=driver.findElement(By.xpath("//label[@for='permissionMiscellaneousGroupsHistoryRadioDisable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMiscellaneousGroupsHistoryRadioDisable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[25]/div[2]/div[2]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='dfss']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@title='Logs']")).click();
		String a2=driver.findElement(By.xpath("//div[@title='Logs']")).getAttribute("title");
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='groupOldChatHistoryBtn']")).getAttribute("id");
		String a4=driver.findElement(By.xpath("//div[@id='groupOldChatHistoryBtn']")).getAttribute("class");
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on miscellaneous group with disallow in chat history");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@email.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		test.info("Click on groups tab");
		test.info("Click on radio button of disallow in chat history");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on recent chat search");
		test.info("Click on group");
		test.info("Click on profile");
		test.info("Click on logs");
		test.info("EXPECTED RESULT ::  It should not display chat history");
		Assert.assertEquals(a3, "Group Chat History for new members");
		test.pass(a3);
		Assert.assertEquals(a, "Disallow");
		test.pass(a);
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a2, "Logs");
		test.pass(a2);
		Assert.assertEquals(a1, "groupOldChatHistoryBtn");
		test.pass(a1);
		Assert.assertEquals(a4, "hidden");
		test.pass(a4);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not displaying chat history");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test03() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@psn.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[25]/div[2]/div[1]/div[1]/div[2]")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[25]/div[2]/div[1]/div[2]/div[2]/div/div[3]/span[2]")).getText();
		String a=driver.findElement(By.xpath("//label[@for='permissionMiscellaneousGroupsHistoryRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMiscellaneousGroupsHistoryRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[25]/div[2]/div[2]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='dfss']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@title='Logs']")).click();
		String a2=driver.findElement(By.xpath("//div[@title='Logs']")).getAttribute("title");
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='groupOldChatHistoryBtn']")).getText();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on miscellaneous group with allow in chat history");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@email.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		test.info("Click on groups tab");
		test.info("Click on radio button of allow");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on recent chat search");
		test.info("Click on group");
		test.info("Click on profile");
		test.info("Click on logs");
		test.info("EXPECTED RESULT ::  It should display chat history");
		Assert.assertEquals(a3, "Group Chat History for new members");
		test.pass(a3);
		Assert.assertEquals(a, "Allow");
		test.pass(a);
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a2, "Logs");
		test.pass(a2);
		Assert.assertEquals(a1, "Chat History");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying chat history");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
