package controls;

import java.awt.AWTException;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class Notify {
	WebDriver driver;
	ExtentHtmlReporter htmlReporter;
	ExtentReports extent;

	String extentReportImage = System.getProperty("user.dir")+ "extentReportImage.png";
	@BeforeSuite
	public void StartTest() {
		htmlReporter = new ExtentHtmlReporter("notify.html");
		extent = new ExtentReports();
		extent.attachReporter(htmlReporter);
	}
	@Test
	public void test00() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Notify']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionNotifyRadioDisable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[22]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[5]/span[1]")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//button[@id='createNotifyBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Click on notify with disable");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on notify");
		test.info("Click on disable radio button");
		test.info("Click on save button");
		test.info("Goto notify page");
		test.info("Click on create button");
		test.info("EXPECTED RESULT:: It should not create the notify");
		Assert.assertEquals(a, "Permissions applied");
		test.pass(a);
		Assert.assertEquals(a1, "You don't have permission to create Notify..!");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is not creating the notify");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test01() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Notify']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionNotifyRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[22]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[5]/span[1]")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//button[@id='createNotifyBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='header-text']")).getText();
		//driver.findElement(By.xpath("//textarea[@id='notifyInput']")).sendKeys("test");
		//Thread.sleep(1000);
		//driver.findElement(By.xpath("//span[@class='username defualt-text']")).click();
		//Thread.sleep(1000);
		//driver.findElement(By.xpath("input[@id='notifySubmitBtn']")).click();
		//String a1=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Click on notify with enable");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on notify");
		test.info("Click on enable radio button");
		test.info("Click on save button");
		test.info("Goto notify page");
		test.info("Click on create button");
		test.info("EXPECTED RESULT:: It should create the notify");
		Assert.assertEquals(a, "Permissions applied");
		test.pass(a);
		Assert.assertEquals(a1, "Create New");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is creating the notify");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test02() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Notify']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionNotifyRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[22]/div[2]/div[3]/div/div[1]/div[2]/div[2]/div[4]/span[2]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[22]/div[2]/div[3]/div/div[1]/div[2]/div[2]/div[6]/span[2]")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[22]/div[2]/div[3]/div/div[2]/div/div[1]/span[3]")).getText();
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[22]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[5]/span[1]")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//button[@id='createNotifyBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(2000);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[2]/nav/div/div/ul/li[9]/a")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("akhil@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		String a4=driver.findElement(By.xpath("//div[@class='toolbar-name']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[5]/span[1]")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//button[@id='createNotifyBtn']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='header-text']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Click on notify with enable to selected users");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on notify");
		test.info("Click on enable radio button");
		test.info("Select the users & Give permissions");
		test.info("Click on save button");
		test.info("Goto notify page");
		test.info("Click on create button");
		test.info("Logout the user");
		test.info("Login with selected notify user : akhil");
		test.info("Click on notify");
		test.info("Click on create new");
		test.info("EXPECTED RESULT:: It should only create the notify to selected users");
		Assert.assertEquals(a3, "3");
		test.pass(a3);
		Assert.assertEquals(a, "Permissions applied");
		test.pass(a);
		Assert.assertEquals(a1, "You don't have permission to create Notify..!");
		test.pass(a1);
		Assert.assertEquals(a4, "Akhil");
		test.pass(a4);
		Assert.assertEquals(a2, "Create New");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is only creating the notify to selected users");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test03() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Notify']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionNotifyRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[22]/div[2]/div[3]/div/div[2]/div/div[2]/div[1]/span[3]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[22]/div[2]/div[3]/div/div[2]/div/div[2]/div[2]/span[3]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[22]/div[2]/div[3]/div/div[2]/div/div[2]/div[1]/span[3]")).click();
		Thread.sleep(500);
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[22]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Remove the permissions for all users & all orange users");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on notify");
		test.info("Click on enable radio button");
		test.info("remove the permission for all users & all orange users");
		test.info("Click on save button");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a, "Please select atleast one user");
		test.pass(a);
		test.log(Status.PASS,"ACTUAL RESULT::  Please select atleast one user");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test04() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Notify']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionNotifyRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[22]/div[2]/div[3]/div/div[2]/div/div[1]/input")).sendKeys("akhil");
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@data-search='akhil']")).getAttribute("data-search");
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Search the valid user in notify permission list");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on notify");
		test.info("Click on enable radio button");
		test.info("Click on search");
		test.info("Search the valid user");
		test.info("EXPECTED RESULT:: It should search the valid user name");
		Assert.assertEquals(a, "akhil");
		test.pass(a);
		test.log(Status.PASS,"ACTUAL RESULT::  It is searching the valid user name");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test05() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Notify']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionNotifyRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[22]/div[2]/div[3]/div/div[2]/div/div[1]/input")).sendKeys("sdafdsa");
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='no-results-found']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Search the invalid user in notify permission list");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on notify");
		test.info("Click on enable radio button");
		test.info("Click on search");
		test.info("Search the invalid user");
		test.info("EXPECTED RESULT:: It should display no result found");
		Assert.assertEquals(a, "No results found!");
		test.pass(a);
		test.log(Status.PASS,"ACTUAL RESULT::  No results found!");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test06() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Notify']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionNotifyRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[22]/div[2]/div[3]/div/div[2]/div/div[2]/div[3]/span[3]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[22]/div[2]/div[3]/div/div[2]/div/div[2]/div[2]/span[3]")).click();
		Thread.sleep(500);
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[22]/div[2]/div[3]/div/div[2]/div/div[1]/span[3]")).getText();
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[22]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[5]/span[1]")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//button[@id='createNotifyBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(2000);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[2]/nav/div/div/ul/li[9]/a")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maddy@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		String a4=driver.findElement(By.xpath("//div[@class='toolbar-name']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[5]/span[1]")).click();
		Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("//button[@id='createNotifyBtn']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='header-text']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Click on notify with enable to selected orange users");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on notify");
		test.info("Click on enable radio button");
		test.info("Select only orange users");
		test.info("Click on save button");
		test.info("Goto notify page");
		test.info("Click on create button");
		test.info("Click on logout");
		test.info("Login with the orange user : maddy");
		test.info("Click on notify");
		test.info("Click on create new");
		test.info("EXPECTED RESULT:: It should only create the notify to orange users");
		Assert.assertEquals(a3, "1");
		test.pass(a3);
		Assert.assertEquals(a, "Permissions applied");
		test.pass(a);
		Assert.assertEquals(a1, "You don't have permission to create Notify..!");
		test.pass(a1);
		Assert.assertEquals(a4, "Maddy");
		test.pass(a4);
		Assert.assertEquals(a2, "Create New");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is only creating the notify to orange users");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test07() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Notify']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionNotifyRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[22]/div[2]/div[3]/div/div[1]/div[2]/div[1]/input")).sendKeys("sharath");
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@data-search='sharath']")).getAttribute("data-search");
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Search the valid user in notify members list");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on notify");
		test.info("Click on enable radio button");
		test.info("Click on search");
		test.info("Search the valid user");
		test.info("EXPECTED RESULT:: It should search the valid user name");
		Assert.assertEquals(a, "sharath");
		test.pass(a);
		test.log(Status.PASS,"ACTUAL RESULT::  It is searching the valid user name");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test08() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Notify']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionNotifyRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[22]/div[2]/div[3]/div/div[1]/div[2]/div[1]/input")).sendKeys("sdafdsa");
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='no-results-found']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Search the invalid user in notify members list");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on notify");
		test.info("Click on enable radio button");
		test.info("Click on search");
		test.info("Search the invalid user");
		test.info("EXPECTED RESULT:: It should display no result found");
		Assert.assertEquals(a, "No results found!");
		test.pass(a);
		test.log(Status.PASS,"ACTUAL RESULT::  No results found!");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
