package controls;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class TextMessage {
	WebDriver driver;
	ExtentHtmlReporter HtmlReporter;
	ExtentReports extent;

	@BeforeSuite
	public void Starttest() {
		HtmlReporter = new ExtentHtmlReporter("TextMessage.html");
		extent = new ExtentReports();
		extent.attachReporter(HtmlReporter);
	}
	@Test
	public void test00() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@email.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Text Message']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='textPermissionAdmin']")).click();
		String a4=driver.findElement(By.xpath("//label[@for='textPermissionAdmin']")).getAttribute("for");
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(3000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac = new Actions(driver);
		ac.contextClick(e).build().perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//a[@data-action='copy']")).click();
		String a=driver.findElement(By.xpath("//a[@data-action='copy']")).getText();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@data-action='forward']")).click();
		String a2=driver.findElement(By.xpath("//a[@data-action='forward']")).getText();
		Thread.sleep(500);
		String a3=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("By deselecting TM-Admin in text msg");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@email.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on text message");
		test.info("Deselect the checkbox of TM-Admin");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on any user");
		test.info("Select the text message");
		test.info("Click on copy and Forward");
		test.info("EXPECTED RESULT ::  It should not copy the msg & It should not forward the msg");
		Assert.assertEquals(a4, "textPermissionAdmin");
		test.pass(a4);
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a, "Copy");
		test.pass(a);
		Assert.assertEquals(a1, "TM-Admin disabled this feature");
		test.pass(a1);
		Assert.assertEquals(a2, "Forward");
		test.pass(a2);
		Assert.assertEquals(a3, "TM-Admin disabled this feature");
		test.pass(a3);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding the msg & It is not copying the msg");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test01() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@email.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Text Message']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='textPermissionAdmin']")).click();
		String a4=driver.findElement(By.xpath("//label[@for='textPermissionAdmin']")).getAttribute("for");
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(3000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac = new Actions(driver);
		ac.doubleClick(e).build().perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='global-copy-icon']")).click();
		String a=driver.findElement(By.xpath("//div[@class='global-copy-icon']")).getAttribute("class");
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		ac.contextClick(e).build().perform();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//a[@data-action='forward']")).getText();
		driver.findElement(By.xpath("//a[@data-action='forward']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageSendBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_37-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='modalForwardSendMessageBtn']")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Thread.sleep(1000);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("By selecting TM-Admin in text msg");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@email.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on text message");
		test.info("Select the checkbox of TM-Admin");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on any user");
		test.info("Select the text message");
		test.info("Click on copy and Forward");
		test.info("EXPECTED RESULT ::  It should copy & forward the msg");
		Assert.assertEquals(a4, "textPermissionAdmin");
		test.pass(a4);
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a, "global-copy-icon");
		test.pass(a);
		Assert.assertEquals(a1, "Copied!");
		test.pass(a1);
		Assert.assertEquals(a2, "Forward");
		test.pass(a2);
		Assert.assertEquals(a5, "forward-conversation-label-icon");
		test.pass(a5);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding & copying the msg");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test02() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@email.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Text Message']")).click();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//label[@for='textPermissionAdmin']")).getAttribute("for");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='textPermissionAdminDownload']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(3000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac = new Actions(driver);
		ac.doubleClick(e).build().perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='global-copy-icon']")).click();
		String a=driver.findElement(By.xpath("//div[@class='global-copy-icon']")).getAttribute("class");
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		ac.contextClick(e).build().perform();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//a[@data-action='forward']")).getText();
		driver.findElement(By.xpath("//a[@data-action='forward']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageSendBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_37-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='modalForwardSendMessageBtn']")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Thread.sleep(1000);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("By deselecting the copy & Selecting the forward in TM-Admin in text msg");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@email.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on text message");
		test.info("Select the checkbox of TM-Admin");
		test.info("Deselect the checkbox of copy");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on any user");
		test.info("Select the text message");
		test.info("Click on copy and Forward");
		test.info("EXPECTED RESULT ::  It should not copy the msg & It should forward the msg");
		Assert.assertEquals(a4, "textPermissionAdmin");
		test.pass(a4);
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a, "global-copy-icon");
		test.pass(a);
		Assert.assertEquals(a1, "TM-Admin disabled this feature");
		test.pass(a1);
		Assert.assertEquals(a2, "Forward");
		test.pass(a2);
		Assert.assertEquals(a5, "forward-conversation-label-icon");
		test.pass(a5);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding the msg & It is not copying the msg");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test03() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@email.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Text Message']")).click();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//label[@for='textPermissionAdmin']")).getAttribute("for");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='textPermissionAdminDownload']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='textPermissionAdminForward']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(3000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac = new Actions(driver);
		ac.doubleClick(e).build().perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='global-copy-icon']")).click();
		String a=driver.findElement(By.xpath("//div[@class='global-copy-icon']")).getAttribute("class");
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		ac.contextClick(e).build().perform();
		Thread.sleep(1000);
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@data-action='forward']")).click();
		String a2=driver.findElement(By.xpath("//a[@data-action='forward']")).getText();
		Thread.sleep(500);
		String a3=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("By selecting the copy & deselecting the forward in TM-Admin in text msg");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@email.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on text message");
		test.info("Select the checkbox of TM-Admin");
		test.info("Select the checkbox of copy");
		test.info("Deselect the checkbox of forward");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on any user");
		test.info("Select the text message");
		test.info("Click on copy and Forward");
		test.info("EXPECTED RESULT ::  It should copy the msg & It should not forward the msg");
		Assert.assertEquals(a4, "textPermissionAdmin");
		test.pass(a4);
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a, "global-copy-icon");
		test.pass(a);
		Assert.assertEquals(a1, "Copied!");
		test.pass(a1);
		Assert.assertEquals(a2, "Forward");
		test.pass(a2);
		Assert.assertEquals(a3, "TM-Admin disabled this feature");
		test.pass(a3);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding the msg & It is copying the msg");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test04() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@email.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Text Message']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='textPermissionAdmin']")).click();
		driver.findElement(By.xpath("//label[@for='textPermissionOrangeMember']")).click();
		String a4=driver.findElement(By.xpath("//label[@for='textPermissionOrangeMember']")).getAttribute("for");
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[2]/nav/div/div/ul/li[9]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).clear();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("bhanu@email.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac = new Actions(driver);
		ac.contextClick(e).build().perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//a[@data-action='copy']")).click();
		String a=driver.findElement(By.xpath("//a[@data-action='copy']")).getText();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@data-action='forward']")).click();
		String a2=driver.findElement(By.xpath("//a[@data-action='forward']")).getText();
		Thread.sleep(500);
		String a3=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("By deselecting orange member in text msg");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@email.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on text message");
		test.info("Deselect the checkbox of Orange member");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on logout");
		test.info("Click on login button");
		test.info("Login the orange user");
		test.info("Click on any user");
		test.info("Select the text message");
		test.info("Click on copy and Forward");
		test.info("EXPECTED RESULT ::  It should not copy the msg & It should not forward the msg");
		Assert.assertEquals(a4, "textPermissionOrangeMember");
		test.pass(a4);
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a, "Copy");
		test.pass(a);
		Assert.assertEquals(a1, "TM-Admin disabled this feature");
		test.pass(a1);
		Assert.assertEquals(a2, "Forward");
		test.pass(a2);
		Assert.assertEquals(a3, "TM-Admin disabled this feature");
		test.pass(a3);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding the msg & It is not copying the msg");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	} 
	@Test
	public void test05() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@email.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Text Message']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='textPermissionAdmin']")).click();
		driver.findElement(By.xpath("//label[@for='textPermissionOrangeMember']")).click();
		String a4=driver.findElement(By.xpath("//label[@for='textPermissionOrangeMember']")).getAttribute("for");
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[2]/nav/div/div/ul/li[9]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).clear();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("bhanu@email.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac = new Actions(driver);
		ac.doubleClick(e).build().perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='global-copy-icon']")).click();
		String a=driver.findElement(By.xpath("//div[@class='global-copy-icon']")).getAttribute("class");
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		ac.contextClick(e).build().perform();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//a[@data-action='forward']")).getText();
		driver.findElement(By.xpath("//a[@data-action='forward']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageSendBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_37-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='modalForwardSendMessageBtn']")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Thread.sleep(1000);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("By selecting orange member in text msg");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@email.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on text message");
		test.info("Select the checkbox of Orange member");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on logout");
		test.info("Click on login button");
		test.info("Login the orange user");
		test.info("Click on any user");
		test.info("Select the text message");
		test.info("Click on copy and Forward");
		test.info("EXPECTED RESULT ::  It should copy & forward the msg");
		Assert.assertEquals(a4, "textPermissionOrangeMember");
		test.pass(a4);
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a, "global-copy-icon");
		test.pass(a);
		Assert.assertEquals(a1, "Copied!");
		test.pass(a1);
		Assert.assertEquals(a2, "Forward");
		test.pass(a2);
		Assert.assertEquals(a5, "forward-conversation-label-icon");
		test.pass(a5);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding & copying the msg");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	} 
	@Test
	public void test06() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@email.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Text Message']")).click();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//label[@for='textPermissionOrangeMember']")).getAttribute("for");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='textPermissionOrangeMemberDownload']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[2]/nav/div/div/ul/li[9]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).clear();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("bhanu@email.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac = new Actions(driver);
		ac.doubleClick(e).build().perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='global-copy-icon']")).click();
		String a=driver.findElement(By.xpath("//div[@class='global-copy-icon']")).getAttribute("class");
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		ac.contextClick(e).build().perform();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//a[@data-action='forward']")).getText();
		driver.findElement(By.xpath("//a[@data-action='forward']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageSendBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_37-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='modalForwardSendMessageBtn']")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Thread.sleep(1000);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("By deselecting the copy & Selecting the forward in orange member in text msg");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@email.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on text message");
		test.info("Select the checkbox of Orange member");
		test.info("Deselect the checkbox of copy");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on logout");
		test.info("Click on login button");
		test.info("Login the orange user");
		test.info("Click on any user");
		test.info("Select the text message");
		test.info("Click on copy and Forward");
		test.info("EXPECTED RESULT ::  It should not copy the msg & It should forward the msg");
		Assert.assertEquals(a4, "textPermissionOrangeMember");
		test.pass(a4);
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a, "global-copy-icon");
		test.pass(a);
		Assert.assertEquals(a1, "TM-Admin disabled this feature");
		test.pass(a1);
		Assert.assertEquals(a2, "Forward");
		test.pass(a2);
		Assert.assertEquals(a5, "forward-conversation-label-icon");
		test.pass(a5);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding the msg & It is not copying the msg");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test07() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@email.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Text Message']")).click();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//label[@for='textPermissionOrangeMember']")).getAttribute("for");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='textPermissionOrangeMemberDownload']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='textPermissionOrangeMemberForward']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[2]/nav/div/div/ul/li[9]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).clear();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("bhanu@email.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac = new Actions(driver);
		ac.doubleClick(e).build().perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='global-copy-icon']")).click();
		String a=driver.findElement(By.xpath("//div[@class='global-copy-icon']")).getAttribute("class");
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		ac.contextClick(e).build().perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//a[@data-action='forward']")).click();
		String a2=driver.findElement(By.xpath("//a[@data-action='forward']")).getText();
		Thread.sleep(500);
		String a3=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("By selecting the copy & deselecting the forward in Orange member in text msg");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@email.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on text message");
		test.info("Select the checkbox of Orange member");
		test.info("Select the checkbox of copy");
		test.info("Deselect the checkbox of forward");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on logout");
		test.info("Click on login button");
		test.info("Login the orange user");
		test.info("Click on any user");
		test.info("Select the text message");
		test.info("Click on copy and Forward");
		test.info("EXPECTED RESULT ::  It should copy the msg & It should not forward the msg");
		Assert.assertEquals(a4, "textPermissionOrangeMember");
		test.pass(a4);
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a, "global-copy-icon");
		test.pass(a);
		Assert.assertEquals(a1, "Copied!");
		test.pass(a1);
		Assert.assertEquals(a2, "Forward");
		test.pass(a2);
		Assert.assertEquals(a3, "TM-Admin disabled this feature");
		test.pass(a3);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding the msg & It is copying the msg");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test08() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@email.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Text Message']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='textPermissionOrangeMember']")).click();
		driver.findElement(By.xpath("//label[@for='textPermissionUser']")).click();
		String a4=driver.findElement(By.xpath("//label[@for='textPermissionUser']")).getAttribute("for");
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[2]/nav/div/div/ul/li[9]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).clear();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("vinay@email.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac = new Actions(driver);
		ac.contextClick(e).build().perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//a[@data-action='copy']")).click();
		String a=driver.findElement(By.xpath("//a[@data-action='copy']")).getText();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@data-action='forward']")).click();
		String a2=driver.findElement(By.xpath("//a[@data-action='forward']")).getText();
		Thread.sleep(500);
		String a3=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("By deselecting user in text msg");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@email.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on text message");
		test.info("Deselect the checkbox of user");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on logout");
		test.info("Click on login button");
		test.info("Login the orange user");
		test.info("Click on any user");
		test.info("Select the text message");
		test.info("Click on copy and Forward");
		test.info("EXPECTED RESULT ::  It should not copy the msg & It should not forward the msg");
		Assert.assertEquals(a4, "textPermissionUser");
		test.pass(a4);
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a, "Copy");
		test.pass(a);
		Assert.assertEquals(a1, "TM-Admin disabled this feature");
		test.pass(a1);
		Assert.assertEquals(a2, "Forward");
		test.pass(a2);
		Assert.assertEquals(a3, "TM-Admin disabled this feature");
		test.pass(a3);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding the msg & It is not copying the msg");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	} 
	@Test
	public void test09() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@email.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Text Message']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='textPermissionOrangeMember']")).click();
		driver.findElement(By.xpath("//label[@for='textPermissionUser']")).click();
		String a4=driver.findElement(By.xpath("//label[@for='textPermissionUser']")).getAttribute("for");
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[2]/nav/div/div/ul/li[9]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).clear();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("vinay@email.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac = new Actions(driver);
		ac.doubleClick(e).build().perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='global-copy-icon']")).click();
		String a=driver.findElement(By.xpath("//div[@class='global-copy-icon']")).getAttribute("class");
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		ac.contextClick(e).build().perform();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//a[@data-action='forward']")).getText();
		driver.findElement(By.xpath("//a[@data-action='forward']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageSendBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_37-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='modalForwardSendMessageBtn']")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Thread.sleep(1000);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("By selecting user in text msg");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@email.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on text message");
		test.info("Select the checkbox of user");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on logout");
		test.info("Click on login button");
		test.info("Login the orange user");
		test.info("Click on any user");
		test.info("Select the text message");
		test.info("Click on copy and Forward");
		test.info("EXPECTED RESULT ::  It should copy & forward the msg");
		Assert.assertEquals(a4, "textPermissionUser");
		test.pass(a4);
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a, "global-copy-icon");
		test.pass(a);
		Assert.assertEquals(a1, "Copied!");
		test.pass(a1);
		Assert.assertEquals(a2, "Forward");
		test.pass(a2);
		Assert.assertEquals(a5, "forward-conversation-label-icon");
		test.pass(a5);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding & copying the msg");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	} 
	@Test
	public void test10() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@email.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Text Message']")).click();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//label[@for='textPermissionUser']")).getAttribute("for");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='textPermissionUserDownload']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[2]/nav/div/div/ul/li[9]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).clear();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("vinay@email.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac = new Actions(driver);
		ac.doubleClick(e).build().perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='global-copy-icon']")).click();
		String a=driver.findElement(By.xpath("//div[@class='global-copy-icon']")).getAttribute("class");
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		ac.contextClick(e).build().perform();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//a[@data-action='forward']")).getText();
		driver.findElement(By.xpath("//a[@data-action='forward']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageSendBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_37-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='modalForwardSendMessageBtn']")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Thread.sleep(1000);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("By deselecting the copy & Selecting the forward in user in text msg");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@email.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on text message");
		test.info("Select the checkbox of user");
		test.info("Deselect the checkbox of copy");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on logout");
		test.info("Click on login button");
		test.info("Login the orange user");
		test.info("Click on anyuser");
		test.info("Select the text message");
		test.info("Click on copy and Forward");
		test.info("EXPECTED RESULT ::  It should not copy the msg & It should forward the msg");
		Assert.assertEquals(a4, "textPermissionUser");
		test.pass(a4);
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a, "global-copy-icon");
		test.pass(a);
		Assert.assertEquals(a1, "TM-Admin disabled this feature");
		test.pass(a1);
		Assert.assertEquals(a2, "Forward");
		test.pass(a2);
		Assert.assertEquals(a5, "forward-conversation-label-icon");
		test.pass(a5);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding the msg & It is not copying the msg");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test11() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@email.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Text Message']")).click();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//label[@for='textPermissionUser']")).getAttribute("for");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='textPermissionUserDownload']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='textPermissionUserForward']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[2]/nav/div/div/ul/li[9]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).clear();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("vinay@email.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac = new Actions(driver);
		ac.doubleClick(e).build().perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='global-copy-icon']")).click();
		String a=driver.findElement(By.xpath("//div[@class='global-copy-icon']")).getAttribute("class");
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		ac.contextClick(e).build().perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//a[@data-action='forward']")).click();
		String a2=driver.findElement(By.xpath("//a[@data-action='forward']")).getText();
		Thread.sleep(500);
		String a3=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("By selecting the copy & deselecting the forward in user in text msg");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@email.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on text message");
		test.info("Select the checkbox of user");
		test.info("Select the checkbox of copy");
		test.info("Deselect the checkbox of forward");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on logout");
		test.info("Click on login button");
		test.info("Login the orange user");
		test.info("Click on anyuser");
		test.info("Select the text message");
		test.info("Click on copy and Forward");
		test.info("EXPECTED RESULT ::  It should copy the msg & It should not forward the msg");
		Assert.assertEquals(a4, "textPermissionUser");
		test.pass(a4);
		Assert.assertEquals(actual, "Permissions applied");
		test.pass(actual);
		Assert.assertEquals(a, "global-copy-icon");
		test.pass(a);
		Assert.assertEquals(a1, "Copied!");
		test.pass(a1);
		Assert.assertEquals(a2, "Forward");
		test.pass(a2);
		Assert.assertEquals(a3, "TM-Admin disabled this feature");
		test.pass(a3);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding the msg & It is copying the msg");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
