package controls;

import java.awt.AWTException;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class Trumpet {
	WebDriver driver;
	ExtentHtmlReporter htmlReporter;
	ExtentReports extent;

	String extentReportImage = System.getProperty("user.dir")+ "extentReportImage.png";
	@BeforeSuite
	public void StartTest() {
		htmlReporter = new ExtentHtmlReporter("Trumpet.html");
		extent = new ExtentReports();
		extent.attachReporter(htmlReporter);
	}
	@Test
	public void test00() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioDisable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[10]/input")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='uppi']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-trumpet-btn input-action-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='input-trumpet-btn input-action-btn']")).getAttribute("title");
		String a2=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Click on Trumpet with disable");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on trumpet");
		test.info("Click on disable radio button");
		test.info("Click on save button");
		test.info("Goto chat page");
		test.info("Click on user");
		test.info("Click on trumpet");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a, "Permissions applied");
		test.pass(a);
		Assert.assertEquals(a1, "Trumpet");
		test.pass(a1);
		Assert.assertEquals(a2, "TM-Admin has disabled Trumpet!");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test01() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[10]/input")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='uppi']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='input-trumpet-btn input-action-btn']")).getAttribute("title");
		driver.findElement(By.xpath("//div[@class='input-trumpet-btn input-action-btn']")).click();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Click on Trumpet with enable");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on trumpet");
		test.info("Click on enable radio button");
		test.info("Click on save button");
		test.info("Goto chat page");
		test.info("Click on user");
		test.info("Click on trumpet");
		test.info("EXPECTED RESULT:: It should click on trumpet icon");
		Assert.assertEquals(a, "Permissions applied");
		test.pass(a);
		Assert.assertEquals(a1, "Trumpet");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is clicking on trumpet icon");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test02() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[2]/div[1]/input")).sendKeys("sharath");
		String a1=driver.findElement(By.xpath("//div[@data-search='sharath']")).getAttribute("data-search");
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Click on search in members with valid username");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on trumpet");
		test.info("Click on enable radio button");
		test.info("Click on search in members");
		test.info("Enter valid user name");
		test.info("EXPECTED RESULT:: It should display the username");
		Assert.assertEquals(a1, "sharath");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying the username");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test03() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[2]/div[1]/input")).sendKeys("sadfd");
		String a1=driver.findElement(By.xpath("//div[@class='no-results-found']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Click on search in members with invalid username");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on trumpet");
		test.info("Click on enable radio button");
		test.info("Click on search in members");
		test.info("Enter invalid user name");
		test.info("EXPECTED RESULT:: It should not display the username");
		Assert.assertEquals(a1, "No results found!");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying no results found");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test04() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[2]/div/div[2]/div[1]/span[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[2]/div/div[2]/div[1]/span[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[10]/input")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Remove all users & all orange users in users who can initiate the trumpet");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on trumpet");
		test.info("Click on enable radio button");
		test.info("Remove the all users & all orange users in who can initiate trumpet");
		test.info("Click on save button");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a1, "Please select atleast one user");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test05() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[2]/div[2]/div[3]/span[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[2]/div[2]/div[4]/span[2]")).click();
		String a5=driver.findElement(By.xpath("//div[@data-search='Sai Teja']")).getAttribute("data-search");
		Thread.sleep(1000);
		String a6=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[2]/div/div[1]/span[3]")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[10]/input")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='uppi']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-trumpet-btn input-action-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='input-trumpet-btn input-action-btn']")).getAttribute("title");
		String a2=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[2]/nav/div/div/ul/li[9]/a")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("saiteja@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		String a4=driver.findElement(By.xpath("//div[@class='toolbar-name']")).getText();
		driver.findElement(By.xpath("//div[@data-name='uppi']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-trumpet-btn input-action-btn']")).click();
		Thread.sleep(1000);
		//String a3=driver.findElement(By.xpath("//div[@class='input-trumpet-btn input-action-btn']")).getAttribute("title");
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Select the users & Give permission");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on trumpet");
		test.info("Click on enable radio button");
		test.info("Select the users");
		test.info("Click on save button");
		test.info("Goto chat");
		test.info("Click on user & Click on trumpet");
		test.info("Logout the user");
		test.info("Login the selected user");
		test.info("Click on user");
		test.info("Click on trumpet");
		test.info("EXPECTED RESULT:: It should highlight the trumpet icon for selected users");
		Assert.assertEquals(a6, "3");
		test.pass(a6);
		Assert.assertEquals(a, "Permissions applied");
		test.pass(a);
		Assert.assertEquals(a5, "Sai Teja");
		test.pass(a5);
		Assert.assertEquals(a1, "Trumpet");
		test.pass(a1);
		Assert.assertEquals(a2, "You don't have permissions to do Trumpet!");
		test.pass(a2);
		Assert.assertEquals(a4, "Sai Teja");
		test.pass(a4);
		Assert.assertEquals(a1, "Trumpet");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is highlighting the trumpet icon for selected users");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test06() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[1]/div[2]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[1]/div[2]")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Click on orange member icon");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on trumpet");
		test.info("Click on enable radio button");
		test.info("Select the all orange users tab in members");
		test.info("EXPECTED RESULT:: It should switch to orange users tab");
		Assert.assertEquals(a, "orange-switch-btn active");
		test.pass(a);
		test.log(Status.PASS,"ACTUAL RESULT::  It is switching to all orange users tab");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test07() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[1]/div[2]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[1]/div[2]")).getAttribute("class");
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[2]/div[1]/input")).sendKeys("maneesh");
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@data-search='maneesh']")).getAttribute("data-search");
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Click on orange member icon & search with valid username");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on trumpet");
		test.info("Click on enable radio button");
		test.info("Select the all orange users tab in members");
		test.info("Search valid username");
		test.info("EXPECTED RESULT:: It should search valid username in orange users tab");
		Assert.assertEquals(a, "orange-switch-btn active");
		test.pass(a);
		Assert.assertEquals(a1, "maneesh");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is searching valid username in orange users tab");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test08() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[1]/div[2]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[1]/div[2]")).getAttribute("class");
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[2]/div[1]/input")).sendKeys("sadasd");
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='no-results-found']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Click on orange member icon & search with invalid username");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on trumpet");
		test.info("Click on enable radio button");
		test.info("Select the all orange users tab in members");
		test.info("Search valid username");
		test.info("EXPECTED RESULT:: It should search valid username in orange users tab");
		Assert.assertEquals(a, "orange-switch-btn active");
		test.pass(a);
		Assert.assertEquals(a1, "No results found!");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is searching valid username in orange users tab");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test09() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[1]/div[2]")).click();
		Thread.sleep(1000);
		String a7=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[1]/div[2]")).getAttribute("class");
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[2]/div[2]/div[10]/span[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[2]/div[2]/div[21]/span[2]")).click();
		String a5=driver.findElement(By.xpath("//div[@data-search='sharath']")).getAttribute("data-search");
		Thread.sleep(1000);
		String a6=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[2]/div/div[1]/span[3]")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[10]/input")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='uppi']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-trumpet-btn input-action-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='input-trumpet-btn input-action-btn']")).getAttribute("title");
		String a2=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[2]/nav/div/div/ul/li[9]/a")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		String a4=driver.findElement(By.xpath("//div[@class='toolbar-name']")).getText();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[2]/div[1]/div/div[3]")).click();
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[2]/div[1]/div/div[3]")).getText();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='Teja']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-trumpet-btn input-action-btn']")).click();
		Thread.sleep(1000);
		//String a3=driver.findElement(By.xpath("//div[@class='input-trumpet-btn input-action-btn']")).getAttribute("title");
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Select the users & Give permission");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on trumpet");
		test.info("Click on enable radio button");
		test.info("Select the only orange users");
		test.info("Click on save button");
		test.info("Goto chat");
		test.info("Click on user & Click on trumpet");
		test.info("Logout the user");
		test.info("Login the selected orange user");
		test.info("Change the workspace id");
		test.info("Click on user");
		test.info("Click on trumpet");
		test.info("EXPECTED RESULT:: It should highlight the trumpet icon for selected orange user");
		Assert.assertEquals(a7, "orange-switch-btn active");
		test.pass(a7);
		Assert.assertEquals(a6, "4");
		test.pass(a6);
		Assert.assertEquals(a, "Permissions applied");
		test.pass(a);
		Assert.assertEquals(a5, "sharath");
		test.pass(a5);
		Assert.assertEquals(a1, "Trumpet");
		test.pass(a1);
		Assert.assertEquals(a2, "You don't have permissions to do Trumpet!");
		test.pass(a2);
		Assert.assertEquals(a4, "Sharath");
		test.pass(a4);
		Assert.assertEquals(a3, "tez");
		test.pass(a3);
		Assert.assertEquals(a1, "Trumpet");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is highlighting the trumpet icon for selected orange user");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test10() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[2]/div/div[1]/input")).sendKeys("sai teja");
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@data-search='Sai Teja']")).getAttribute("data-search");
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Search valid user name in who can initiate trumpet");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on trumpet");
		test.info("Click on enable radio button");
		test.info("Select the users");
		test.info("Click on search in who can initiate trumpet");
		test.info("Search with valid username");
		test.info("EXPECTED RESULT:: It should display the username in who can initiate the trumpet");
		Assert.assertEquals(a, "Sai Teja");
		test.pass(a);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying the username in who can initiate trumpet");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test11() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[2]/div/div[1]/input")).sendKeys("saiteja");
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='no-results-found']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Search invalid user name in who can initiate trumpet");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on trumpet");
		test.info("Click on enable radio button");
		test.info("Select the users");
		test.info("Click on search in who can initiate trumpet");
		test.info("Search with invalid username");
		test.info("EXPECTED RESULT:: It should not display the username in who can initiate the trumpet");
		Assert.assertEquals(a, "No results found!");
		test.pass(a);
		test.log(Status.PASS,"ACTUAL RESULT::  It is not displaying the username in who can initiate trumpet");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test12() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='canned-message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-canned-message-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[10]/input")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='trumpetAddedCannedMessagesWrapper']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Enter text in iburz trumpet responses");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on trumpet");
		test.info("Click on enable radio button");
		test.info("Click on trumpet iburz responses");
		test.info("Enter text : test");
		test.info("Click on add button");
		test.info("EXPECTED RESULT:: It should display added trumpet iburz responses");
		Assert.assertEquals(a1, "Permissions applied");
		test.pass(a1);
		Assert.assertEquals(a, "Noted\n"
				+ "Ok\n"
				+ "Sure\n"
				+ "Roger that\n"
				+ "Thank you\n"
				+ "👍\n"
				+ "test");
		test.pass(a);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying added trumpet iburz responses");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test13() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='canned-message-emoji-preview-icon']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='emojione emojione-32-people _1f642 row-visible']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-canned-message-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[10]/input")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='trumpetAddedCannedMessagesWrapper']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Enter emoji's in iburz trumpet responses");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on trumpet");
		test.info("Click on enable radio button");
		test.info("Click on trumpet iburz responses");
		test.info("Enter emoji's");
		test.info("Click on add button");
		test.info("EXPECTED RESULT:: It should display added emoji's in trumpet iburz responses");
		Assert.assertEquals(a1, "Permissions applied");
		test.pass(a1);
		Assert.assertEquals(a, "Noted\n"
				+ "Ok\n"
				+ "Sure\n"
				+ "Roger that\n"
				+ "Thank you\n"
				+ "👍\n"
				+ "test\n"
				+ "🙂");
		test.pass(a);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying added emoji's in trumpet iburz responses");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test14() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//span[@class='remove-canned-message'])[7]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[10]/input")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='trumpetAddedCannedMessagesWrapper']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Remove entered text in iburz trumpet responses");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on trumpet");
		test.info("Click on enable radio button");
		test.info("Click on trumpet iburz responses");
		test.info("Remove previous text");
		test.info("EXPECTED RESULT:: It should remove the previous text in trumpet iburz responses");
		Assert.assertEquals(a1, "Permissions applied");
		test.pass(a1);
		Assert.assertEquals(a, "Noted\n"
				+ "Ok\n"
				+ "Sure\n"
				+ "Roger that\n"
				+ "Thank you\n"
				+ "👍\n"
				+ "🙂");
		test.pass(a);
		test.log(Status.PASS,"ACTUAL RESULT::  It is removing the previous text in trumpet iburz responses");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test15() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
		Thread.sleep(1000);
		//driver.findElement(By.xpath("(//span[@class='remove-canned-message'])[7]")).click();
		driver.findElement(By.xpath("(//span[@class='remove-canned-message'])[7]")).click();
		driver.findElement(By.xpath("(//span[@class='remove-canned-message'])[6]")).click();
		driver.findElement(By.xpath("(//span[@class='remove-canned-message'])[5]")).click();
		driver.findElement(By.xpath("(//span[@class='remove-canned-message'])[4]")).click();
		driver.findElement(By.xpath("(//span[@class='remove-canned-message'])[3]")).click();
		driver.findElement(By.xpath("(//span[@class='remove-canned-message'])[2]")).click();
		driver.findElement(By.xpath("(//span[@class='remove-canned-message'])[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[10]/input")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='trumpetAddedCannedMessagesWrapper']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Remove all the iburz trumpet responses");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on trumpet");
		test.info("Click on enable radio button");
		test.info("Click on trumpet iburz responses");
		test.info("Remove all the trumpet iburz responses");
		test.info("EXPECTED RESULT:: It should remove all the trumpet iburz responses");
		Assert.assertEquals(a1, "Permissions applied");
		test.pass(a1);
		Assert.assertEquals(a, "");
		test.pass(a);
		test.log(Status.PASS,"ACTUAL RESULT::  It is removing all the trumpet iburz responses");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test16() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='canned-message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-canned-message-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='canned-message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-canned-message-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[10]/input")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='trumpetAddedCannedMessagesWrapper']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Enter same text & add two times in iburz trumpet responses");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on trumpet");
		test.info("Click on enable radio button");
		test.info("Click on trumpet iburz responses");
		test.info("Enter text : test");
		test.info("Click on add button");
		test.info("Again Enter text : test");
		test.info("Click on add button");
		test.info("EXPECTED RESULT:: It should display only one time in trumpet iburz responses");
		Assert.assertEquals(a1, "Permissions applied");
		test.pass(a1);
		Assert.assertEquals(a, "test");
		test.pass(a);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying only one time in trumpet iburz responses");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test17() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='canned-message-input']")).sendKeys("asdfghjkl asdfghjkl asdfghjkl asdfghjkl zxcvbnm qwertyuiop asdfgh");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-canned-message-btn']")).click();
		Thread.sleep(1000);
		//driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[10]/input")).click();
		//Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='trumpetAddedCannedMessagesWrapper']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Enter text with more than 50 characters in iburz trumpet responses");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on trumpet");
		test.info("Click on enable radio button");
		test.info("Click on trumpet iburz responses");
		test.info("Enter text with more than 50 charaters");
		test.info("Click on add button");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a1, "Maximum 50 characters are allowed for a Canned Response!");
		test.pass(a1);
		Assert.assertEquals(a, "test");
		test.pass(a);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test18() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='trumpetMusicInputWrapper']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[10]/input")).click();
		Thread.sleep(1000);
		//String a1=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//select[@id='trumpetMusicInputWrapper']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Click on Buzz music");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on trumpet");
		test.info("Click on enable radio button");
		test.info("Click on buzz music");
		test.info("Remove previous text");
		test.info("EXPECTED RESULT:: It should click on Buzz music");
		//Assert.assertEquals(a1, "Permissions applied");
		//test.pass(a1);
		Assert.assertEquals(a, "Music Tone\n"
				+ "Tone 1\n"
				+ "Tone 2\n"
				+ "Tone 3\n"
				+ "Tone 4");
		test.pass(a);
		test.log(Status.PASS,"ACTUAL RESULT::  It is clicking on Buzz music");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test19() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//select[@id='trumpetMusicInputWrapper']"));
		e.click();
		e.sendKeys(Keys.ARROW_UP);
		e.sendKeys(Keys.ENTER);
  		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[10]/input")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Click on music tone & save it");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on trumpet");
		test.info("Click on enable radio button");
		test.info("Click on buzz music");
		test.info("Select music Tone & Save it");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a1, "Please select Buzz music");
		test.pass(a1);
		//Assert.assertEquals(a, "");
		//test.pass(a);
		test.log(Status.PASS,"ACTUAL RESULT::  Please select Buzz music");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test20() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@tez.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//select[@id='trumpetMusicInputWrapper']"));
		e.click();
		e.sendKeys(Keys.ARROW_DOWN);
		e.sendKeys(Keys.ARROW_DOWN);
		e.sendKeys(Keys.ENTER);
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//select[@id='trumpetMusicInputWrapper']")).getText();
  		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[10]/input")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(2000);
		ExtentTest test = extent.createTest("Change the tone");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath@tez.com");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on trumpet");
		test.info("Click on enable radio button");
		test.info("Click on buzz music");
		test.info("Select tones & Change it");
		test.info("Click on save button");
		test.info("EXPECTED RESULT:: It should change the tone");
		Assert.assertEquals(a1, "Permissions applied");
		test.pass(a1);
		Assert.assertEquals(a, "Music Tone\n"
				+ "Tone 1\n"
				+ "Tone 2\n"
				+ "Tone 3\n"
				+ "Tone 4");
		test.pass(a);
		test.log(Status.PASS,"ACTUAL RESULT::  It is changing the tone");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
