package controls;

import java.io.File;
import java.io.IOException;

import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;
import com.google.common.io.Files;

public class video {
	WebDriver driver;
	ExtentHtmlReporter htmlReporter;
	ExtentReports extent;

	String extentReportImage = System.getProperty("user.dir")+ "extentReportImage.png";
	@BeforeSuite
	public void StartTest() {
		htmlReporter = new ExtentHtmlReporter("video.html");
		extent = new ExtentReports();
		extent.attachReporter(htmlReporter);
	}
	@Test
	public void test() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("abcd@gmail.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("sai@123");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[7]/span")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVideoRadioEnable\"]")).click();
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[3]/div[2]/div[1]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[3]/div[2]/div[2]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[3]/div[2]/div[3]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		driver.navigate().refresh();
		driver.findElement(By.xpath("//div[@data-name='sai1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[11]/div/div/div[2]/div[4]/div[2]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[6]/div[5]/div[2]/div/div/span[2]/a\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[6]/div[5]/div[2]/div/div/span[3]")).click();
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		ExtentTest test=extent.createTest("By clicking all checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:abcd@gmail.com");
		test.info("Password:sai@123");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on video");
		test.info("click on Enable button");
		test.info("click on checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on anyuser");
		test.info("click on any video in the userpage");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  System should forward and Download the Video");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Permissions applied");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test1() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("abcd@gmail.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("sai@123");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[7]/span")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVideoRadioEnable\"]")).click();
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[3]/div[2]/div[1]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[3]/div[2]/div[2]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[3]/div[2]/div[3]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		driver.navigate().refresh();
		driver.findElement(By.xpath("//div[@data-name='sai1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[11]/div/div/div[2]/div[4]/div[2]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[6]/div[5]/div[2]/div/div/span[2]/a\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[6]/div[5]/div[2]/div/div/span[3]")).click();
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		ExtentTest test=extent.createTest("By De-selecting all checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:abcd@gmail.com");
		test.info("Password:sai@123");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on video");
		test.info("click on Enable button");
		test.info("De-select on checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on anyuser");
		test.info("click on any video in the userpage");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  System should not forward and Download the Video");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Permissions applied");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test2() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("abcd@gmail.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("sai@123");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[7]/span")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVideoRadioEnable\"]")).click();
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[3]/div[2]/div[1]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[3]/div[2]/div[2]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[3]/div[2]/div[3]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		driver.navigate().refresh();
		driver.findElement(By.xpath("//div[@data-name='sai1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[11]/div/div/div[2]/div[4]/div[2]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[6]/div[5]/div[2]/div/div/span[2]/a\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[6]/div[5]/div[2]/div/div/span[3]")).click();
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		ExtentTest test=extent.createTest("By clicking on Users Checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sai23@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on video");
		test.info("click on Enable button");
		test.info("click on User checkbox");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on selected user");
		test.info("click on video in the userpage");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  System should forward and Download the Video in users only");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Permissions applied");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test3() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("abcd@gmail.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("sai@123");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[7]/span")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVideoRadioEnable\"]")).click();
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[3]/div[2]/div[1]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[3]/div[2]/div[2]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[3]/div[2]/div[3]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		driver.navigate().refresh();
		driver.findElement(By.xpath("//div[@data-name='sai1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[11]/div/div/div[2]/div[4]/div[2]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[6]/div[5]/div[2]/div/div/span[2]/a\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[6]/div[5]/div[2]/div/div/span[3]")).click();
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		ExtentTest test=extent.createTest("By clicking on OrangeMember checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:user@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on video");
		test.info("click on Enable button");
		test.info("click on OrangeMember checkbox");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on OrangeMember");
		test.info("click on any video in the userpage");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  System should forward and Download the Video for OrangeMember");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Permissions applied");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test4() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("abcd@gmail.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("sai@123");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[7]/span")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVideoRadioEnable\"]")).click();
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[3]/div[2]/div[1]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[3]/div[2]/div[2]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[3]/div[2]/div[3]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		driver.navigate().refresh();
		driver.findElement(By.xpath("//div[@data-name='sai1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[11]/div/div/div[2]/div[4]/div[2]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[6]/div[5]/div[2]/div/div/span[2]/a\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[6]/div[5]/div[2]/div/div/span[3]")).click();
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		ExtentTest test=extent.createTest("By clicking TM-Admin in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:abcd@gmail.com");
		test.info("Password:sai@123");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on video");
		test.info("click on Enable button");
		test.info("click on TM-Admin checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on user");
		test.info("click on video in the userpage");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  System should forward and Download the Video in TM-Admin");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Permissions applied");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test5() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("abcd@gmail.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("sai@123");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[7]/span")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVideoRadioEnable\"]")).click();
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[3]/div[2]/div[1]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[3]/div[2]/div[2]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[3]/div[2]/div[3]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		driver.navigate().refresh();
		driver.findElement(By.xpath("//div[@data-name='test1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[11]/div/div/div[4]/div[4]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[6]/div[5]/div[2]/div/div/span[2]/a")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[6]/div[5]/div[2]/div/div/span[3]")).click();
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		ExtentTest test=extent.createTest("By clicking all checkbox in Enable radiobutton for Groups");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:abcd@gmail.com");
		test.info("Password:sai@123");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on video");
		test.info("click on Enable button");
		test.info("click on checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on any group");
		test.info("click on any video in the page");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  System should forward and Download the Video");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Permissions applied");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test6() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("abcd@gmail.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("sai@123");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[7]/span")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVideoRadioEnable\"]")).click();
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[3]/div[2]/div[1]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[3]/div[2]/div[2]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[3]/div[2]/div[3]/div[1]/div/label ")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		driver.navigate().refresh();
		driver.findElement(By.xpath("//div[@data-name='test1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[11]/div/div/div[4]/div[4]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[6]/div[5]/div[2]/div/div/span[2]/a")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[6]/div[5]/div[2]/div/div/span[3]")).click();
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		ExtentTest test=extent.createTest("By de-selecting all checkbox in Enable radiobutton for groups");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:abcd@gmail.com");
		test.info("Password:sai@123");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on video");
		test.info("click on Enable button");
		test.info("De-select checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on anyuser");
		test.info("click on any video in the userpage");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  System should not forward and Download the Video");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Permissions applied");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test7() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("abcd@gmail.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("sai@123");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[7]/span")).click();
		driver.findElement(By.xpath(" //*[@id=\"permissionAudioRadioEnable\"]")).click();
		ExtentTest test=extent.createTest("By adding roles ");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:abcd@gmail.com");
		test.info("Password:sai@123");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("Click on User");
		test.info("click on Roles");
		test.info("Add the roles");
		test.info("click on controls");
		test.info("Click on video");
		test.info("click on Enable button");
		test.info("select all the checkboxes");
		test.info("click on save button");
		test.info("EXPECTED RESULT ::  System is not showing the scroll bar option ");
		File src=((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
		Files.copy(src, new File("video.png"));
		test.addScreenCaptureFromPath("/home/tvisha/Downloads/eclipse-inst-jre-linux64/maven/video.png");
		test.log(Status.FAIL ,"ACTUAL RESULT ::  Permissions applied");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test8() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("abcd@gmail.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("sai@123");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[7]/span")).click();
		driver.findElement(By.xpath(" //*[@id=\"permissionVideoRadioDisable\"]")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[7]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("By clicking on Disable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:abcd@gmail.com");
		test.info("Password:sai@123");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on video");
		test.info("click on Disable button");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on anyuser");
		test.info("click on any video in the userpage");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  System should not forward and Download the Video");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Permissions applied");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
