package usersdashboard;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class Adduser {
	WebDriver driver;
	ExtentHtmlReporter HtmlReporter;
	ExtentReports extent;

	@BeforeSuite
	public void Starttest() {
		HtmlReporter = new ExtentHtmlReporter("adduser(dashboard).html");
		extent = new ExtentReports();
		extent.attachReporter(HtmlReporter);
	}
	@Test
	public void test() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-member-btn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on add user button in user page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on add button");
		test.info("EXPECTED RESULT ::  It should display add user page ");
		String a=driver.findElement(By.xpath("//div[@class='add-member-btn']")).getText();
		Assert.assertEquals("ADD USER", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying add user page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("add button");
	}
	@Test
	public void test1() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-member-btn']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberSubmitBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on add user button & add employee button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on add button");
		test.info("Click on add employee");
		test.info("EXPECTED RESULT ::  It should display toast msg ");
		String a=driver.findElement(By.xpath("/html/body/div[6]/div[2]")).getText();
		Assert.assertEquals("Please enter name", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Please enter name");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("1");
	}
	@Test
	public void test2() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-member-btn']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberNameInput']")).sendKeys("abc");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberSubmitBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on add user button & enter only user name");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on add button");
		test.info("Enter username : mani");
		test.info("Click on add employee");
		test.info("EXPECTED RESULT ::  It should display the toast msg ");
		String a=driver.findElement(By.xpath("/html/body/div[6]/div[2]")).getText();
		Assert.assertEquals("Please enter email", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Please enter email");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("2");
	}
	@Test
	public void test3() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-member-btn']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberEmailInput']")).sendKeys("abc@trends.com");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberSubmitBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on add user button & enter only email");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on add button");
		test.info("Enter email : abc@trends.com");
		test.info("Click on add employee");
		test.info("EXPECTED RESULT ::  It should display the toast msg ");
		String a=driver.findElement(By.xpath("/html/body/div[6]/div[2]")).getText();
		Assert.assertEquals("Please enter name", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Please enter name");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("3");
	}
	@Test
	public void test4() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-member-btn']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberNameInput']")).sendKeys("abc");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberEmailInput']")).sendKeys("abc@trends.com");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberSubmitBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on add user button & enter username & email");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on add button");
		test.info("Enter name : abc");
		test.info("Enter email : abc@trends.com");
		test.info("Click on add employee");
		test.info("EXPECTED RESULT ::  It should add the user ");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Employee added successfully", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Employee added successfully");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("4");
	}
	@Test
	public void test5() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-member-btn']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberNameInput']")).sendKeys("abc");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberEmailInput']")).sendKeys("abc@trends.com");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberSubmitBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on add user button & enter with same username & email");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on add button");
		test.info("Enter name : abc");
		test.info("Enter email : abc@trends.com");
		test.info("Click on add employee");
		test.info("EXPECTED RESULT ::  It should not add the existing user ");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Employee email already exists", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Employee email already exists");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("5");
	}
	@Test
	public void test6() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-member-btn']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberNameInput']")).sendKeys("abcd");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberEmailInput']")).sendKeys("abcd@trends.com");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberAdminCheckbox']")).click();
		driver.findElement(By.xpath("//input[@id='addMemberSubmitBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on add user button & Add user as TM-admin");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on add button");
		test.info("Enter name : abcd");
		test.info("Enter email : abcd@trends.com");
		test.info("Click on checkbox of TM-admin");
		test.info("Click on add employee");
		test.info("EXPECTED RESULT ::  It should add the user as TM-admin ");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Employee added successfully", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Employee added successfully");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("6");
	}
	@Test
	public void test7() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-member-btn']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberNameInput']")).sendKeys("abcd");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberEmailInput']")).sendKeys("abcd@trends.com");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberAdminCheckbox']")).click();
		driver.findElement(By.xpath("//input[@id='addMemberSubmitBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on add user button & Add existing user as TM-admin");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on add button");
		test.info("Enter name : abcd");
		test.info("Enter email : abcd@trends.com");
		test.info("Click on checkbox of TM-admin");
		test.info("Click on add employee");
		test.info("EXPECTED RESULT ::  It should not add the existing user as TM-admin ");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Employee email already exists", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Employee email already exists");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("7");
	}
	@Test
	public void test8() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-member-btn']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='info-text']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on add user button & add employee button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on add button");
		test.info("Click on add employee");
		test.info("EXPECTED RESULT ::  It should click on info & display info msg ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is clicking on info & displaying info msg");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("8");
	}
	@Test
	public void test9() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-member-btn']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberNameInput']")).sendKeys("abcd");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberEmailInput']")).sendKeys("aa@trends.com");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberOrangeMemberCheckbox']")).click();
		driver.findElement(By.xpath("//input[@id='addMemberNextBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='addMemberPermissionSubmitBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on add user button & Add user as orange member");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on add button");
		test.info("Enter name : abcd");
		test.info("Enter email : aa@trends.com");
		test.info("Click on checkbox of orange member");
		test.info("Click on next button");
		test.info("Click on save button");
		test.info("EXPECTED RESULT ::  It should add the user as orange member ");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Employee added successfully", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Employee added successfully");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("9");
	}
	@Test
	public void testcase10() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-member-btn']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberNameInput']")).sendKeys("abcd");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberEmailInput']")).sendKeys("aa@trends.com");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberOrangeMemberCheckbox']")).click();
		driver.findElement(By.xpath("//input[@id='addMemberNextBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='addMemberPermissionSubmitBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on add user button & Add existing user as orange member");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on add button");
		test.info("Enter name : abcd");
		test.info("Enter email : aa@trends.com");
		test.info("Click on checkbox of orange member");
		test.info("Click on next button");
		test.info("Click on save button");
		test.info("EXPECTED RESULT ::  It should not add the existing user as orange member ");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Employee email already exists", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Employee email already exists");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("10");
	}
	@Test
	public void testcase11() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-member-btn']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberNameInput']")).sendKeys("abcd");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberEmailInput']")).sendKeys("aa@trends.com");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberOrangeMemberCheckbox']")).click();
		driver.findElement(By.xpath("//input[@id='addMemberNextBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionUsersSearchInput']")).sendKeys("test");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on add user button & Add user as orange member & Search the user after clicking on next button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on add button");
		test.info("Enter name : abcd");
		test.info("Enter email : abcd@trends.com");
		test.info("Click on checkbox of orange member");
		test.info("Click on Next button");
		test.info("search the valid username");
		test.info("EXPECTED RESULT ::  It should search the username ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the searched username");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("11");
	}
	@Test
	public void testcase12() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-member-btn']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberNameInput']")).sendKeys("abcd");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberEmailInput']")).sendKeys("aa@trends.com");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberOrangeMemberCheckbox']")).click();
		driver.findElement(By.xpath("//input[@id='addMemberNextBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionUsersSearchInput']")).sendKeys("aaaaaa");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on add user button & Add user as orange member & Search the user after clicking on next button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on add button");
		test.info("Enter name : abcd");
		test.info("Enter email : abcd@trends.com");
		test.info("Click on checkbox of orange member");
		test.info("Click on Next button");
		test.info("search the valid username");
		test.info("EXPECTED RESULT ::  It should display no data ");
		test.log(Status.FAIL ,"ACTUAL RESULT ::  It is displaying as empty");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("12");
	}
	@Test
	public void testcase13() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-member-btn']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberNameInput']")).sendKeys("abcd");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberEmailInput']")).sendKeys("aa@trends.com");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberOrangeMemberCheckbox']")).click();
		driver.findElement(By.xpath("//input[@id='addMemberNextBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionUsersSearchInput']")).sendKeys("test");
		driver.findElement(By.xpath("//input[@id='permissionUsersSearchInput']")).click();
		Actions a1=new Actions(driver);
		a1.sendKeys(Keys.ARROW_DOWN).build().perform();
		a1.sendKeys(Keys.ENTER).build().perform();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on add user button & Add user as orange member & Search the user after clicking on next button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on add button");
		test.info("Enter name : abcd");
		test.info("Enter email : abcd@trends.com");
		test.info("Click on checkbox of orange member");
		test.info("Click on Next button");
		test.info("search the valid username");
		test.info("Click on that searched user");
		test.info("EXPECTED RESULT ::  It should display in selected members ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the selected members ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("13");
	}
	@Test
	public void testcase14() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-member-btn']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberNameInput']")).sendKeys("abcd");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberEmailInput']")).sendKeys("aa@trends.com");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberOrangeMemberCheckbox']")).click();
		driver.findElement(By.xpath("//input[@id='addMemberNextBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionUsersSearchInput']")).sendKeys("test");
		driver.findElement(By.xpath("//span[@id='clearPermissionUsersSearchInput']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on close button & Search the user ");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on add button");
		test.info("Enter name : abcd");
		test.info("Enter email : abcd@trends.com");
		test.info("Click on checkbox of orange member");
		test.info("Click on Next button");
		test.info("search the username");
		test.info("Click on close button");
		test.info("EXPECTED RESULT ::  It should clear the searched username ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is clearing the searched username");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("14");
	}
	@Test
	public void testcase15() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-member-btn']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberNameInput']")).sendKeys("abcd");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberEmailInput']")).sendKeys("aa@trends.com");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberOrangeMemberCheckbox']")).click();
		driver.findElement(By.xpath("//input[@id='addMemberNextBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='close-icon']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='close-icon']")).click();
		driver.findElement(By.xpath("//input[@id='addMemberPermissionSubmitBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on close button of All users & All orange members ");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on add button");
		test.info("Enter name : abcd");
		test.info("Enter email : abcd@trends.com");
		test.info("Click on checkbox of orange member");
		test.info("Click on Next button");
		test.info("Click on selected members");
		test.info("Click on close button of all users");
		test.info("Click on close button of All orange members");
		test.info("Click on save button");
		test.info("EXPECTED RESULT ::  It should display toast as Please select atleast one user ");
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Assert.assertEquals("Please select atleast one user", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Please select atleast one user ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("15");
	}
	@Test
	public void testcase16() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-member-btn']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberNameInput']")).sendKeys("abcd");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberEmailInput']")).sendKeys("aa@trends.com");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberOrangeMemberCheckbox']")).click();
		driver.findElement(By.xpath("//input[@id='addMemberNextBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionUsersSearchInput']")).sendKeys("test");
		driver.findElement(By.xpath("//input[@id='permissionUsersSearchInput']")).click();
		Actions a1=new Actions(driver);
		a1.sendKeys(Keys.ARROW_DOWN).build().perform();
		a1.sendKeys(Keys.ENTER).build().perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionUsersSearchInput']")).sendKeys("krishna");
		driver.findElement(By.xpath("//input[@id='permissionUsersSearchInput']")).click();
		a1.sendKeys(Keys.ARROW_DOWN).build().perform();
		a1.sendKeys(Keys.ENTER).build().perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionUsersSearchInput']")).sendKeys("akhil");
		driver.findElement(By.xpath("//input[@id='permissionUsersSearchInput']")).click();
		a1.sendKeys(Keys.ARROW_DOWN).build().perform();
		a1.sendKeys(Keys.ENTER).build().perform();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on users & orange user in search field");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on add button");
		test.info("Enter name : abcd");
		test.info("Enter email : abcd@trends.com");
		test.info("Click on checkbox of orange member");
		test.info("Click on Next button");
		test.info("Click on user : test");
		test.info("Click on user : akhil");
		test.info("Click on orange user : krishna");
		test.info("EXPECTED RESULT ::  It should display the count as 3 in selected members ");
		String a=driver.findElement(By.xpath("//span[@class='count-text']")).getText();
		Assert.assertEquals("3", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the count as 3 in selected members ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("16");
	}
	@Test
	public void testcase17() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-member-btn']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberNameInput']")).sendKeys("abcd");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberEmailInput']")).sendKeys("aa@trends.com");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='addMemberOrangeMemberCheckbox']")).click();
		driver.findElement(By.xpath("//input[@id='addMemberNextBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='content-close-btn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on close button of the add user page ");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: upi@google.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on add button");
		test.info("Enter name : abcd");
		test.info("Enter email : abcd@trends.com");
		test.info("Click on checkbox of orange member");
		test.info("Click on Next button");
		test.info("Click on selected members");
		test.info("EXPECTED RESULT ::  It should not add the user in that page ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not adding the user in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("17");
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
