package usersdashboard;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class dashboarduserpage {
	WebDriver driver;
	ExtentHtmlReporter HtmlReporter;
	ExtentReports extent;

	@BeforeSuite
	public void Starttest() {
		HtmlReporter = new ExtentHtmlReporter("userpage.html");
		extent = new ExtentReports();
		extent.attachReporter(HtmlReporter);
	}
	@Test
	public void test() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		ExtentTest test=extent.createTest("Click on user page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("EXPECTED RESULT ::  It should display user page ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying user page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("user");
	}
	@Test
	public void test1() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//input[@id='membersFilterSearchInput']")).sendKeys("test");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Enter valid username in search bar");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on search");
		test.info("Enter search : test");
		test.info("EXPECTED RESULT ::  It should display particular username ");
		String a=driver.findElement(By.xpath("//input[@id='membersFilterSearchInput']")).getText();
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the particular username ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("1");
	}
	@Test
	public void test2() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//input[@id='membersFilterSearchInput']")).sendKeys("aaaaaa");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Enter invalid username in search bar");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on search");
		test.info("Enter search : aaaaa");
		test.info("EXPECTED RESULT ::  It should display No results found ");
		String a=driver.findElement(By.xpath("//div[@class='no-results-found']")).getText();
		Assert.assertEquals("No results found..!", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  No results found ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("2");
	}
	@Test
	public void test3() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//input[@id='membersFilterSearchInput']")).sendKeys("aaaaaa");
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='reset-btn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Enter username in search bar and click on reset button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on search");
		test.info("Enter search : aaaaa");
		test.info("Click on reset button");
		test.info("EXPECTED RESULT ::  It should display all users in that page ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all users in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("3");
	}
	@Test
	public void test4() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterMembersSelection']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value='1']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on users + orange members");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on user+orange members");
		test.info("Select users+orange members");
		test.info("EXPECTED RESULT ::  It should display all users & orange members in that page ");
		String a=driver.findElement(By.xpath("//option[@value='1']")).getText();
		Assert.assertEquals("Users + Orange members", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all users & orange members in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("4");
	}
	@Test
	public void test5() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterMembersSelection']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value='2']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on users");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on user+orange members");
		test.info("Select users");
		test.info("EXPECTED RESULT ::  It should display only users in that page ");
		String a=driver.findElement(By.xpath("//option[@value='2']")).getText();
		Assert.assertEquals("Users", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying only users in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("5");
	}
	@Test
	public void test6() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterMembersSelection']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value='3']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on orange members");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on user+orange members");
		test.info("Select orange members");
		test.info("EXPECTED RESULT ::  It should display only orange members in that page ");
		String a=driver.findElement(By.xpath("//option[@value='3']")).getText();
		Assert.assertEquals("Orange members", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying only orange members in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("6");
	}
	@Test
	public void test7() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterMembersSelection']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value='4']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on deactivated users & orange members");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on user+orange members");
		test.info("Select deactivated users & orange members");
		test.info("EXPECTED RESULT ::  It should display only deactivated users & orange members in that page ");
		String a1=driver.findElement(By.xpath("//option[@value='4']")).getText();
		Assert.assertEquals("De-activated Users + Orange Members", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//div[@class='no-results-found']")).getText();
		Assert.assertEquals("No results found..!", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying only deactivated users & orange members in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("7");
	}
	@Test
	public void test8() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterMembersSelection']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value='5']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Ex-users & Ex-orange members");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on user+orange members");
		test.info("Select Ex-users & Ex-orange members");
		test.info("EXPECTED RESULT ::  It should display only Ex-users & Ex-orange members in that page ");
		String a1=driver.findElement(By.xpath("//option[@value='5']")).getText();
		Assert.assertEquals("Ex-users + Ex-orange Members", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//div[@class='no-results-found']")).getText();
		Assert.assertEquals("No results found..!", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying only Ex-users & Ex-orange members in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("8");
	}
	@Test
	public void test9() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterMembersSelection']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value='4']")).click();
		Thread.sleep(500);
		String a1=driver.findElement(By.xpath("//option[@value='4']")).getText();
		driver.findElement(By.xpath("//div[@class='reset-btn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on reset button in user page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on user+orange members");
		test.info("Select deactivated users & orange members");
		test.info("Click on reset button");
		test.info("EXPECTED RESULT ::  It should display all the users in that page ");
		Assert.assertEquals("De-activated Users + Orange Members", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//option[@value='1']")).getText();
		Assert.assertEquals("Users + Orange members", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the users in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("9");
	}
	@Test
	public void testcase10() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterAction']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value='0']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on action & select deactivate");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on Action");
		test.info("Select De-activate");
		test.info("EXPECTED RESULT ::  It should display toast as Please select atleast one employee ");
		Assert.assertEquals("Please select atleast one employee", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Please select atleast one employee ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("10");
	}
	@Test
	public void testcase11() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='membersCheckbox-19']")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterAction']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value='0']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-no']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select on checkbox of user & select deactivate with no button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Select on checkbox of user");
		test.info("Click on Action");
		test.info("Select De-activate");
		test.info("Click on no button");
		test.info("EXPECTED RESULT ::  It should not deactivate the user ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deactivating the user ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("11");
	}
	@Test
	public void testcase12() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='membersCheckbox-19']")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterAction']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value='0']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select on checkbox of user & select deactivate with yes button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Select on checkbox of user");
		test.info("Click on Action");
		test.info("Select De-activate");
		test.info("Click on yes button");
		test.info("EXPECTED RESULT ::  It should deactivate the user ");
		Assert.assertEquals("Status updated successfully!", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Status updated successfully ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("12");
	}
	@Test
	public void testcase13() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterAction']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value='2']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on action & select Terminate");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on Action");
		test.info("Select Terminate");
		test.info("EXPECTED RESULT ::  It should display toast as Please select atleast one employee ");
		Assert.assertEquals("Please select atleast one employee", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Please select atleast one employee ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("13");
	}
	@Test
	public void testcase14() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='membersCheckbox-5']")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterAction']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value='2']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-no']")).click();
		Thread.sleep(500);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select on checkbox of user & select Terminate");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Select on checkbox of user");
		test.info("Click on Action");
		test.info("Select Terminate");
		test.info("Click on no button");
		test.info("EXPECTED RESULT ::  It should not Terimate the user ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not terminating the user ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("14");
	}
	@Test
	public void testcase15() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='membersCheckbox-5']")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterAction']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value='2']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select on checkbox of user & select Terminate");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Select on checkbox of user");
		test.info("Click on Action");
		test.info("Select Terminate");
		test.info("Click on yes button");
		test.info("EXPECTED RESULT ::  It should Terimate the user ");
		Assert.assertEquals("Status updated successfully!", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Status updated successfully ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("15");
	}
	@Test
	public void testcase16() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterAction']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value='2']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='reset-btn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on action & Click on reset button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on Action");
		test.info("Select Terminate");
		test.info("Click on reset button");
		test.info("EXPECTED RESULT ::  It should display all the users in that page ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the users in that page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("16");
	}
	@Test
	public void testcase17() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterDepartment']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='1']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Department & select any department");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on Department");
		test.info("Select any department name");
		test.info("EXPECTED RESULT ::  It should display particular department users ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying particular department users ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("17");
	}
	@Test
	public void testcase18() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterDesignation']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='1']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on designation & select any designation");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on Designation");
		test.info("Select any designation name");
		test.info("EXPECTED RESULT ::  It should not display any designation ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not displaying any designation ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("18");
	}
	@Test
	public void testcase19() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterDepartment']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='1']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//select[@id='membersFilterDesignation']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='1']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Combination of department & designation ");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on department");
		test.info("Select any department name");
		test.info("Click on Designation");
		test.info("Select any designation name");
		test.info("EXPECTED RESULT ::  It should display particular department & designation users ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying particular department & designation users ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("19");
	}
	@Test
	public void testcase20() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterDepartment']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='1']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//select[@id='membersFilterDesignation']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='1']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='reset-btn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Combination of department & designation & Click on reset button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on department");
		test.info("Select any department name");
		test.info("Click on Designation");
		test.info("Select any designation name");
		test.info("Click on reset button");
		test.info("EXPECTED RESULT ::  It should display all the users ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the users ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("20");
	}
	@Test
	public void testcase21() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterLocation']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='1']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on location & select the location name");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on location");
		test.info("Select any location");
		test.info("EXPECTED RESULT ::  It should display location users ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying location users ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("21");
	}
	@Test
	public void testcase22() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterLocation']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='1']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='reset-btn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on location & Click on reset button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on location");
		test.info("Select any location");
		test.info("Click on reset button");
		test.info("EXPECTED RESULT ::  It should display all the users ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the users ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("22");
	}
	@Test
	public void testcase23() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//input[@id='membersFilterSearchInput']")).sendKeys("ak");
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='membersFilterMembersSelection']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value='1']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Enter username in search bar & Click on users+orange member");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on search");
		test.info("Enter search : ak");
		test.info("Click on users+orange members");
		test.info("Select users + orange members");
		test.info("EXPECTED RESULT ::  It should display particular username in users + orange members");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the particular username in users + orange members");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("23");
	}
	@Test
	public void testcase24() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//input[@id='membersFilterSearchInput']")).sendKeys("ak");
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='membersFilterMembersSelection']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value='2']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Enter username in search bar & Click on users");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on search");
		test.info("Enter search : ak");
		test.info("Click on users+orange members");
		test.info("Select users");
		test.info("EXPECTED RESULT ::  It should display particular username in users ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the particular username in users ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("24");
	}
	@Test
	public void testcase25() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//input[@id='membersFilterSearchInput']")).sendKeys("ak");
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='membersFilterMembersSelection']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value='3']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Enter username in search bar & Click on orange members");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on search");
		test.info("Enter search : ak");
		test.info("Click on users+orange members");
		test.info("Select orange members");
		test.info("EXPECTED RESULT ::  It should display particular username in orange members ");
		String a=driver.findElement(By.xpath("//div[@class='no-results-found']")).getText();
		Assert.assertEquals("No results found..!", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the particular username in orange member ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("25");
	}
	@Test
	public void testcase26() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//input[@id='membersFilterSearchInput']")).sendKeys("ak");
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='membersFilterMembersSelection']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value='4']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Enter username in search bar & Click on deactivated users & orange members");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on search");
		test.info("Enter search : ak");
		test.info("Click on users+orange members");
		test.info("Select deactivated users & orange members");
		test.info("EXPECTED RESULT ::  It should display particular username in deactivated users & orange members ");
		String a=driver.findElement(By.xpath("//div[@class='no-results-found']")).getText();
		Assert.assertEquals("No results found..!", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the particular username in deactivated users & orange member ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("26");
	}
	@Test
	public void testcase27() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//input[@id='membersFilterSearchInput']")).sendKeys("ak");
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='membersFilterMembersSelection']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value='5']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Enter username in search bar & Click on Ex-users & Ex-orange members");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on search");
		test.info("Enter search : ak");
		test.info("Click on users+orange members");
		test.info("Select Ex-users & Ex-orange members");
		test.info("EXPECTED RESULT ::  It should display particular username in Ex-users & Ex-orange members ");
		String a=driver.findElement(By.xpath("//div[@class='no-results-found']")).getText();
		Assert.assertEquals("No results found..!", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the particular username in Ex-users & Ex-orange member ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("27");
	}
	@Test
	public void testcase28() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//input[@id='membersFilterSearchInput']")).sendKeys("ak");
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='membersFilterMembersSelection']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value='1']")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterDepartment']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='1']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Combination of search, users + orange members & department");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on search");
		test.info("Enter search : ak");
		test.info("Click on users+orange members");
		test.info("Select deactivated users & orange members");
		test.info("Click on department");
		test.info("Select department name");
		test.info("EXPECTED RESULT ::  It should display particular username in the list ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the particular username in the list ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("28");
	}
	@Test
	public void testcase29() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//input[@id='membersFilterSearchInput']")).sendKeys("ak");
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='membersFilterMembersSelection']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value='1']")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterDepartment']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='1']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//select[@id='membersFilterDesignation']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='1']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Combination of search, users + orange members, department & designation");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on search");
		test.info("Enter search : ak");
		test.info("Click on users+orange members");
		test.info("Select deactivated users & orange members");
		test.info("Click on department");
		test.info("Select department name");
		test.info("Click on designation");
		test.info("Select designation name");
		test.info("EXPECTED RESULT ::  It should display particular username in the list ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the particular username in the list ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("29");
	}
	@Test
	public void testcase30() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//input[@id='membersFilterSearchInput']")).sendKeys("ak");
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='membersFilterMembersSelection']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value='1']")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterDepartment']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='1']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//select[@id='membersFilterDesignation']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='1']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//select[@id='membersFilterLocation']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='1']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Combination of search, users + orange members, department, designation & location");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on search");
		test.info("Enter search : ak");
		test.info("Click on users+orange members");
		test.info("Select deactivated users & orange members");
		test.info("Click on department");
		test.info("Select department name");
		test.info("Click on designation");
		test.info("Select designation name");
		test.info("Click on location");
		test.info("Select the location ");
		test.info("EXPECTED RESULT ::  It should display particular username in the list ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the particular username in the list ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("30");
	}
	@Test
	public void testcase31() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//input[@id='membersFilterSearchInput']")).sendKeys("ak");
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='membersFilterMembersSelection']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value='1']")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterDepartment']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='1']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//select[@id='membersFilterDesignation']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='1']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//select[@id='membersFilterLocation']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//option[@value='1']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='reset-btn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Combination of search, users + orange members, department, designation & location & Click on reset button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on search");
		test.info("Enter search : ak");
		test.info("Click on users+orange members");
		test.info("Select deactivated users & orange members");
		test.info("Click on department");
		test.info("Select department name");
		test.info("Click on designation");
		test.info("Select designation name");
		test.info("Click on location");
		test.info("Select the location ");
		test.info("EXPECTED RESULT ::  It should display all the username in the list ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all the username in the list ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("31");
	}
	@Test
	public void testcase32() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='user-avatar orange-dot']")).click();
		Thread.sleep(5000);
		ExtentTest test=extent.createTest("Click any user to view");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Select any user ");
		test.info("Click on it to view the user");
		test.info("EXPECTED RESULT ::  It should display user view page ");
		String a=driver.findElement(By.xpath("//span[@class='header-text']")).getText();
		Assert.assertEquals("VIEW USER", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying user view page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("32");
	}
	@Test
	public void testcase33() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("(//div[@class='member-options-button'])[2]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div[1]/div/div[1]/div[2]/div[1]/div[2]/div[2]/div[8]/div/div[2]/div[1]/span")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on menu bar & click on view");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Select any user ");
		test.info("Click on three dots");
		test.info("Click on view");
		test.info("EXPECTED RESULT ::  It should display user view page ");
		String a=driver.findElement(By.xpath("//span[@class='header-text']")).getText();
		Assert.assertEquals("VIEW USER", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying user view page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("33");
	}
	@Test
	public void testcase34() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("(//div[@class='member-options-button'])[2]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div[1]/div/div[1]/div[2]/div[1]/div[2]/div[2]/div[8]/div/div[2]/div[2]/span")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on menu bar & click on edit");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Select any user ");
		test.info("Click on three dots");
		test.info("Click on edit");
		test.info("EXPECTED RESULT ::  It should display user edit page ");
		String a=driver.findElement(By.xpath("//span[@class='header-text']")).getText();
		Assert.assertEquals("EDIT USER", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying user edit page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("34");
	}
	@Test
	public void testcase35() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("(//div[@class='member-options-button'])[2]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div[1]/div/div[1]/div[2]/div[1]/div[2]/div[2]/div[8]/div/div[2]/div[3]/span")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on menu bar & click on Resend invite");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Select any user ");
		test.info("Click on three dots");
		test.info("Click on resend invite");
		test.info("EXPECTED RESULT ::  It should send the invite to the user ");
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Assert.assertEquals("Mail sent successfully!", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Mail sent successfully");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("35");
	}
	@Test
	public void testcase36() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("(//div[@class='member-options-button'])[2]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div[1]/div/div[1]/div[2]/div[1]/div[2]/div[2]/div[8]/div/div[2]/div[4]/span")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-no']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on menu bar & click on Deactivate");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Select any user ");
		test.info("Click on three dots");
		test.info("Click on Deactivate");
		test.info("Click on no button");
		test.info("EXPECTED RESULT ::  It should not deactivate the user ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deactivating the user ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("36");
	}
	@Test
	public void testcase37() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("(//div[@class='member-options-button'])[2]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div[1]/div/div[1]/div[2]/div[1]/div[2]/div[2]/div[8]/div/div[2]/div[4]/span")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on menu bar & click on Deactivate");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Select any user ");
		test.info("Click on three dots");
		test.info("Click on Deactivate");
		test.info("EXPECTED RESULT ::  It should deactivate the user ");
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Assert.assertEquals("Status updated successfully!", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Status updated successfully");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("37");
	}
	@Test
	public void testcase38() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("(//div[@class='member-options-button'])[2]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div[1]/div/div[1]/div[2]/div[1]/div[2]/div[2]/div[8]/div/div[2]/div[1]/span")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='viewEditEmployeeButton']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on menu bar & click on view & Click on edit symbol");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Select any user ");
		test.info("Click on three dots");
		test.info("Click on view");
		test.info("Click on edit symbol");
		test.info("EXPECTED RESULT ::  It should display Edit user page ");
		String a=driver.findElement(By.xpath("//span[@class='header-text']")).getText();
		Assert.assertEquals("EDIT USER", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying Edit user page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("38");
	}
	@Test
	public void testcase39() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("(//div[@class='member-options-button'])[2]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div[1]/div/div[1]/div[2]/div[1]/div[2]/div[2]/div[8]/div/div[2]/div[1]/span")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='viewDeactivateEmployeeButton']")).click();
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-no']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on menu bar & click on view & Click on deactivate symbolwith no");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Select any user ");
		test.info("Click on three dots");
		test.info("Click on view");
		test.info("Click on deactivate symbol");
		test.info("Click on yes button");
		test.info("EXPECTED RESULT ::  It should not deactivate the user ");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deactivating the user");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("39");
	}
	@Test
	public void testcase40() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("(//div[@class='member-options-button'])[2]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div[1]/div/div[1]/div[2]/div[1]/div[2]/div[2]/div[8]/div/div[2]/div[1]/span")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='viewDeactivateEmployeeButton']")).click();
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on menu bar & click on view & Click on deactivate symbol with yes");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Select any user ");
		test.info("Click on three dots");
		test.info("Click on view");
		test.info("Click on deactivate symbol");
		test.info("Click on yes button");
		test.info("EXPECTED RESULT ::  It should deactivate the user ");
		String a=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Assert.assertEquals("Status updated successfully!", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Status updated successfully ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("40");
	}
	@Test
	public void testcase41() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='page-right']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on user page & move to other user page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on page right");
		test.info("EXPECTED RESULT ::  It should display 2nd page ");
		String a=driver.findElement(By.xpath("//span[@class='row-count']")).getText();
		Assert.assertEquals("2 of 2", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying 2nd page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("41");
	}
	@Test
	public void testcase42() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='page-right']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='page-left']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on user page & come back to 1st page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on page right");
		test.info("Click on left page");
		test.info("EXPECTED RESULT ::  It should display 1st page ");
		String a=driver.findElement(By.xpath("//span[@class='row-count']")).getText();
		Assert.assertEquals("1 of 2", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying 1st page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("42");
	}
	@Test
	public void testcase43() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='page-right']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='reset-btn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on user page & Goto 2nd page & click on reset button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on page right");
		test.info("Click on reset button");
		test.info("EXPECTED RESULT ::  It should display 1st page ");
		String a=driver.findElement(By.xpath("//span[@class='row-count']")).getText();
		Assert.assertEquals("1 of 2", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying 1st page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("43");
	}
	@Test
	public void testcase44() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterMembersSelection']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value='4']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='membersFilterAction']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='reset-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='membersFilterAction']")).click();
		Thread.sleep(500);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on reset button in user page & Check in action");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on user+orange members");
		test.info("Select deactivated users & orange members");
		test.info("Click on action");
		test.info("Click on reset button");
		test.info("Again click on action");
		test.info("EXPECTED RESULT ::  It should display deactivate & Terminate ");
		test.log(Status.FAIL ,"ACTUAL RESULT ::  It is displaying only activate ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("44");
	}
	@Test
	public void testcase45() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[6]/span[1]")).click();
		//Thread.sleep(1000);
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[2]")).click();
		driver.findElement(By.xpath("//select[@id='membersFilterMembersSelection']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value='5']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//select[@id='membersFilterAction']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='reset-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='membersFilterAction']")).click();
		Thread.sleep(500);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on reset button in user page & Check in action");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on user");
		test.info("Click on user+orange members");
		test.info("Select Ex-users & Ex-orange members");
		test.info("Click on action");
		test.info("Click on reset button");
		test.info("Again click on action");
		test.info("EXPECTED RESULT ::  It should display deactivate & Terminate ");
		test.log(Status.FAIL ,"ACTUAL RESULT ::  It is displaying only activate ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("45");
	}
	@AfterSuite
	public void endtest() {
		extent.flush();
	}
}
