package usersdashboard;

import java.io.File;
import java.io.IOException;

import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;
import com.google.common.io.Files;

public class orangemember {
	WebDriver driver;
	ExtentHtmlReporter htmlReporter;
	ExtentReports extent;

	String extentReportImage = System.getProperty("user.dir")+ "extentReportImage.png";
	@BeforeSuite
	public void StartTest() {
		htmlReporter = new ExtentHtmlReporter("orangemember(dashboard).html");
		extent = new ExtentReports();
		extent.attachReporter(htmlReporter);
	}
	@Test
	public void test() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.19:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@gmail.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/span[1]")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Add department");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Users");
		test.info("Click on orange members");
		test.info("EXPECTED RESULT ::  System should display Orange member page");
		test.log(Status.PASS ,"ACTUAL RESULT ::  System is displaying orange member page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test1() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.19:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@gmail.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-orange-member-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='addMemberNameInput']")).sendKeys("krishna");
		driver.findElement(By.xpath("//input[@id='addMemberEmailInput']")).sendKeys("krishna1@gmail.com");
		driver.findElement(By.xpath("//input[@id='addMemberNextBtn']")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("click on next in add button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Users");
		test.info("Click on orange member");
		test.info("Click on Add icon");
		test.info("Enter name");
		test.info("Enter email");
		test.info("click on next");
		test.info("EXPECTED RESULT ::  System should display 2nd page in orange member");
		test.log(Status.PASS ,"ACTUAL RESULT ::  The 2nd page is displaying in orange member page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test2() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.19:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@gmail.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-orange-member-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='addMemberNameInput']")).sendKeys("krishna");
		driver.findElement(By.xpath("//input[@id='addMemberEmailInput']")).sendKeys("krishna1@gmail.com");
		driver.findElement(By.xpath("//input[@id='addMemberNextBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='addMemberPermissionSubmitBtn']")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Added orange member");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Users");
		test.info("Click on orange member");
		test.info("Click on Add icon");
		test.info("Enter name");
		test.info("Enter email");
		test.info("click on next");
		test.info("Give permission");
		test.info("EXPECTED RESULT ::  System should display orange member");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Employee added successfully");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	/*@Test
	public void test3() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.19:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@gmail.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-orange-member-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='addMemberNameInput']")).sendKeys("krishna");
		driver.findElement(By.xpath("//input[@id='addMemberEmailInput']")).sendKeys("krishna1@gmail.com");
		driver.findElement(By.xpath("//input[@id='addMemberNextBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='addMemberPermissionSubmitBtn']")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("By refreshing the page orange user is visible");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Users");
		test.info("Click on orange member");
		test.info("Click on Add icon");
		test.info("Enter name");
		test.info("Enter email");
		test.info("click on next");
		test.info("Give permission");
		test.info("EXPECTED RESULT ::  System should display orange user in orange member page");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Employee added successfully & By refreshing the page orange user is visible");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}*/
	@Test
	public void test4() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.19:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@gmail.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='add-orange-member-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='addMemberNameInput']")).sendKeys("krishna");
		driver.findElement(By.xpath("//input[@id='addMemberEmailInput']")).sendKeys("krishna1@gmail.com");
		driver.findElement(By.xpath("//input[@id='addMemberNextBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='addMemberPermissionSubmitBtn']")).click();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("By refreshing the page orange user is visible");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Users");
		test.info("Click on orange member");
		test.info("Click on Add icon");
		test.info("Enter name");
		test.info("Enter email");
		test.info("click on next");
		test.info("Give permission");
		test.info("EXPECTED RESULT ::  System should display orange user in orange member page");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Employee added successfully & By refreshing the page orange user is visible");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test5() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.19:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@gmail.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='orangeMemberUsersSearchInput']")).sendKeys("krishna");
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("By searching valid user name");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Users");
		test.info("Click on orange member");
		test.info("Click on Search");
		test.info("Enter name with krishna");
		test.info("EXPECTED RESULT ::  System should display orange user");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Orange user is visible");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test6() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.19:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@gmail.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='orangeMemberUsersSearchInput']")).sendKeys("adfgf");
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("By searching with invalid data");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Users");
		test.info("Click on orange member");
		test.info("Click on Search");
		test.info("Enter name with fadsf");
		test.info("EXPECTED RESULT ::  No result found");
		test.log(Status.FAIL ,"ACTUAL RESULT ::  It is displaying empty page");
		File src=((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
		Files.copy(src, new File("/home/tvisha/Downloads/eclipse-inst-jre-linux64/maven/screenshot6.png"));
		test.addScreenCaptureFromPath("/home/tvisha/Downloads/eclipse-inst-jre-linux64/maven/screenshot6.png");
		Thread.sleep(1000);
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test7() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.19:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@gmail.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='name-text']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-search='Akhil 1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-search='akhil']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-search='maneesh']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='userPermissionSubmitBtn']")).click();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		driver.findElement(By.xpath("/html/body/div[1]/nav/div[2]/ul/li[8]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("upendra@gmail.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By giving permission to orange user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Users");
		test.info("Click on orange member");
		test.info("Click on orange user");
		test.info("Select the user who can chat with orange user");
		test.info("Click on save");
		test.info("Click on logout");
		test.info("Login with orange user");
		test.info("EXPECTED RESULT ::  System should display permission for only particular users");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Permission applied");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test8() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.19:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@gmail.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-search='hemanth']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='orange-switch-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div[6]/div/div[2]/div[1]/div/div[1]/div[2]/div[2]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div[6]/div/div[2]/div[1]/div/div[1]/div[2]/div[2]/div[7]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div[6]/div/div[2]/div[1]/div/div[1]/div[2]/div[2]/div[8]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='userPermissionSubmitBtn']")).click();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		driver.findElement(By.xpath("/html/body/div[1]/nav/div[2]/ul/li[8]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("hemanth@gmail.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By giving permission to orange user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Users");
		test.info("Click on orange member");
		test.info("Click on orange user");
		test.info("Select the user who can chat with orange user");
		test.info("Click on save");
		test.info("Click on logout");
		test.info("Login with orange user");
		test.info("EXPECTED RESULT ::  System should display permission for only particular orange users");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Permission applied");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test9() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.19:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@gmail.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-search='arun']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='username defualt-text']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='orange-switch-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div[6]/div/div[2]/div[1]/div/div[1]/div[2]/div[2]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='userPermissionSubmitBtn']")).click();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[6]/div/span[1]")).click();
		driver.findElement(By.xpath("/html/body/div[1]/nav/div[2]/ul/li[8]/a")).click();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("arun@gmail.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By giving permission to orange user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Users");
		test.info("Click on orange member");
		test.info("Click on orange user");
		test.info("Select the user who can chat with orange user");
		test.info("Click on save");
		test.info("Click on logout");
		test.info("Login with orange user");
		test.info("EXPECTED RESULT ::  System should display permission for all users & all orange users");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Permission applied");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void testcase10() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.19:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@gmail.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[1]/div[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-search='uppi']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='close-icon']")).click();
		driver.findElement(By.xpath("//input[@id='userPermissionSubmitBtn']")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Without giving permission to orange user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@gmail.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Users");
		test.info("Click on orange member");
		test.info("Click on orange user");
		test.info("Select the user who can chat with orange user");
		test.info("Click on save");
		test.info("EXPECTED RESULT ::  System should display please select atleast one user");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Please select atleast one user");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
