package Recentchatusersearch;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class customdates {
	WebDriver driver;
	ExtentHtmlReporter htmlReporter;
	ExtentReports extent;

	String extentReportImage = System.getProperty("user.dir")+ "extentReportImage.png";
	@BeforeSuite
	public void StartTest() {
		htmlReporter = new ExtentHtmlReporter("recentchatsearchwithcustomdates.html");
		extent = new ExtentReports();
		extent.attachReporter(htmlReporter);
	}
	@Test
	public void test00() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[1]")).getText();
		driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[1]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on custom dates & Click on today");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Click on custom dates");
		test.info("Click on today");
		test.info("EXPECTED RESULT ::  It should display Enter minimum 3 characters to search");
		Assert.assertEquals("Today", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@class='search-messages-info-text']")).getText();
		Assert.assertEquals("Enter minimum 3 characters to search", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying Enter minimum 3 characters to search");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("0");
	}
	@Test
	public void test01() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[1]")).getText();
		driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[1]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on today & Enter valid text");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : test");
		test.info("Click on custom dates");
		test.info("Click on today");
		test.info("EXPECTED RESULT ::  It should display Todays msgs");
		Assert.assertEquals("Today", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//div[@data-name='ads']")).getAttribute("data-name");
		Assert.assertEquals("ads", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying Todays msgs");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("1");
	}
	@Test
	public void test02() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("adsfasd");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[1]")).getText();
		driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[1]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Todays & Enter invalid text");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : adsfasd");
		test.info("Click on custom dates");
		test.info("Click on Todays");
		test.info("EXPECTED RESULT ::  It should display no data");
		Assert.assertEquals("Today", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@class='no-recent-results-text']")).getText();
		Assert.assertEquals("No Data", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying No data");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("2");
	}
	@Test
	public void test03() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[2]")).getText();
		driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[2]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on custom dates & Click on Yesterday");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Click on custom dates");
		test.info("Click on yesterday");
		test.info("EXPECTED RESULT ::  It should display Enter minimum 3 characters to search");
		Assert.assertEquals("Yesterday", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@class='search-messages-info-text']")).getText();
		Assert.assertEquals("Enter minimum 3 characters to search", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying Enter minimum 3 characters to search");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("3");
	}
	@Test
	public void test04() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[2]")).getText();
		driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[2]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on yesterday & Enter text");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : test");
		test.info("Click on custom dates");
		test.info("Click on yesterday");
		test.info("EXPECTED RESULT ::  It should display yesterdays msgs");
		Assert.assertEquals("Yesterday", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@class='no-recent-results-text']")).getText();
		Assert.assertEquals("No Data", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying yesterdays msgs");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("4");
	}
	@Test
	public void test05() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[3]")).getText();
		driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[3]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on custom dates & Click on Last 7 days");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Click on custom dates");
		test.info("Click on Last 7 days");
		test.info("EXPECTED RESULT ::  It should display Enter minimum 3 characters to search");
		String a=driver.findElement(By.xpath("//span[@class='search-messages-info-text']")).getText();
		Assert.assertEquals("Last 7 Days", a1);
		test.pass(a1);
		System.out.println(a1);
		Assert.assertEquals("Enter minimum 3 characters to search", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying Enter minimum 3 characters to search");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("5");
	}
	@Test
	public void test06() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[3]")).getText();
		driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[3]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Last 7 days & Enter valid text");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : test");
		test.info("Click on custom dates");
		test.info("Click on Last 7 days");
		test.info("EXPECTED RESULT ::  It should display Last 7 days msgs");
		Assert.assertEquals("Last 7 Days", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//div[@data-name='ads']")).getAttribute("data-name");
		Assert.assertEquals("ads", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying Last 7 days msgs");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("6");
	}
	@Test
	public void test07() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("adsfasd");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[3]")).getText();
		driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[3]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Last 7 days & Enter invalid text");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : adsfasd");
		test.info("Click on custom dates");
		test.info("Click on Last 7 days");
		test.info("EXPECTED RESULT ::  It should display no data");
		Assert.assertEquals("Last 7 Days", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@class='no-recent-results-text']")).getText();
		Assert.assertEquals("No Data", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying No data");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("7");
	}
	@Test
	public void test08() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='cutom-date-filter-option active']")).getText();
		driver.findElement(By.xpath("//div[@class='cutom-date-filter-option active']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on custom dates & Click on Last 30 days");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Click on custom dates");
		test.info("Click on Last 30 days");
		test.info("EXPECTED RESULT ::  It should display Enter minimum 3 characters to search");
		Assert.assertEquals("Last 30 Days", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@class='search-messages-info-text']")).getText();
		Assert.assertEquals("Enter minimum 3 characters to search", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying Enter minimum 3 characters to search");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("8");
	}
	@Test
	public void test09() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='cutom-date-filter-option active']")).getText();
		driver.findElement(By.xpath("//div[@class='cutom-date-filter-option active']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Last 30 days & Enter text");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : test");
		test.info("Click on custom dates");
		test.info("Click on Last 30 days");
		test.info("EXPECTED RESULT ::  It should display Last 30 days msgs");
		Assert.assertEquals("Last 30 Days", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//div[@data-name='ads']")).getAttribute("data-name");
		Assert.assertEquals("ads", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying Last 30 days msgs");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("9");
	}
	@Test
	public void test10() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("adsfasd");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='cutom-date-filter-option active']")).getText();
		driver.findElement(By.xpath("//div[@class='cutom-date-filter-option active']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Last 30 days & Enter invalid text");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : adsfasd");
		test.info("Click on custom dates");
		test.info("Click on Last 30 days");
		test.info("EXPECTED RESULT ::  It should display no data");
		Assert.assertEquals("Last 30 Days", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@class='no-recent-results-text']")).getText();
		Assert.assertEquals("No Data", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying No data");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("10");
	}
	@Test
	public void test11() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[4]")).getText();
		driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[4]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on custom dates & Click on This month");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Click on custom dates");
		test.info("Click on This month");
		test.info("EXPECTED RESULT ::  It should display Enter minimum 3 characters to search");
		Assert.assertEquals("This Month", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@class='search-messages-info-text']")).getText();
		Assert.assertEquals("Enter minimum 3 characters to search", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying Enter minimum 3 characters to search");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("11");
	}
	@Test
	public void test12() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[4]")).getText();
		driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[4]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on This month & Enter text");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : test");
		test.info("Click on custom dates");
		test.info("Click on This month");
		test.info("EXPECTED RESULT ::  It should display This month msgs");
		Assert.assertEquals("This Month", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//div[@data-name='ads']")).getAttribute("data-name");
		Assert.assertEquals("ads", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying This month msgs");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("12");
	}
	@Test
	public void test13() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("adsfasd");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[4]")).getText();
		driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[4]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on This month & Enter invalid text");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : adsfasd");
		test.info("Click on custom dates");
		test.info("Click on This month");
		test.info("EXPECTED RESULT ::  It should display no data");
		Assert.assertEquals("This Month", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@class='no-recent-results-text']")).getText();
		Assert.assertEquals("No Data", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying No data");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("13");
	}
	@Test
	public void test14() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[5]")).getText();
		driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[5]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on custom dates & Click on This year");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Click on custom dates");
		test.info("Click on This year");
		test.info("EXPECTED RESULT ::  It should display Enter minimum 3 characters to search");
		Assert.assertEquals("This Year", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@class='search-messages-info-text']")).getText();
		Assert.assertEquals("Enter minimum 3 characters to search", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying Enter minimum 3 characters to search");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("14");
	}
	@Test
	public void test15() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[5]")).getText();
		driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[5]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on This year & Enter text");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : test");
		test.info("Click on custom dates");
		test.info("Click on This year");
		test.info("EXPECTED RESULT ::  It should display This year msgs");
		Assert.assertEquals("This Year", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//div[@data-name='ads']")).getAttribute("data-name");
		Assert.assertEquals("ads", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying This year msgs");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("15");
	}
	@Test
	public void test16() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("adsfasd");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[5]")).getText();
		driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[5]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on This year & Enter invalid text");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : adsfasd");
		test.info("Click on custom dates");
		test.info("Click on This year");
		test.info("EXPECTED RESULT ::  It should display no data");
		Assert.assertEquals("This Year", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@class='no-recent-results-text']")).getText();
		Assert.assertEquals("No Data", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying No data");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("16");
	}
	@Test
	public void test17() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[6]")).getText();
		driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[6]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on custom dates & Click on Last year");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Click on custom dates");
		test.info("Click on Last year");
		test.info("EXPECTED RESULT ::  It should display Enter minimum 3 characters to search");
		Assert.assertEquals("Last Year", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@class='search-messages-info-text']")).getText();
		Assert.assertEquals("Enter minimum 3 characters to search", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying Enter minimum 3 characters to search");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("17");
	}
	@Test
	public void test18() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[6]")).getText();
		driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[6]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Last year & Enter text");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : test");
		test.info("Click on custom dates");
		test.info("Click on Last year");
		test.info("EXPECTED RESULT ::  It should display Last year msgs");
		Assert.assertEquals("Last Year", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//div[@data-name='abc sai 1']")).getAttribute("data-name");
		Assert.assertEquals("abc sai 1", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying Last year msgs");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("18");
	}
	@Test
	public void test19() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("adsfasd");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[6]")).getText();
		driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[6]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on Last year & Enter invalid text");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : adsfasd");
		test.info("Click on custom dates");
		test.info("Click on Last year");
		test.info("EXPECTED RESULT ::  It should display no data");
		Assert.assertEquals("Last Year", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@class='no-recent-results-text']")).getText();
		Assert.assertEquals("No Data", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying No data");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("19");
	}
	@Test
	public void test20() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[7]")).getText();
		driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[7]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on custom dates & Click on All dates");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Click on custom dates");
		test.info("Click on All dates");
		test.info("EXPECTED RESULT ::  It should display Enter minimum 3 characters to search");
		Assert.assertEquals("All Dates", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@class='search-messages-info-text']")).getText();
		Assert.assertEquals("Enter minimum 3 characters to search", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying Enter minimum 3 characters to search");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("20");
	}
	@Test
	public void test21() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[7]")).getText();
		driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[7]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on All dates & Enter text");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : test");
		test.info("Click on custom dates");
		test.info("Click on All dates");
		test.info("EXPECTED RESULT ::  It should display All dates msgs");
		Assert.assertEquals("All Dates", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//div[@data-name='abc sai 1']")).getAttribute("data-name");
		Assert.assertEquals("abc sai 1", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying All dates msgs");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("21");
	}
	@Test
	public void test22() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("adsfasd");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[7]")).getText();
		driver.findElement(By.xpath("(//div[@class='cutom-date-filter-option'])[7]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on All dates & Enter invalid text");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : adsfasd");
		test.info("Click on custom dates");
		test.info("Click on All dates");
		test.info("EXPECTED RESULT ::  It should display no data");
		Assert.assertEquals("All Dates", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@class='no-recent-results-text']")).getText();
		Assert.assertEquals("No Data", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying No data");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("22");
	}
	@Test
	public void test23() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='custom-option-label']")).getText();
		driver.findElement(By.xpath("//span[@class='custom-option-label']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='customDateRangeFilterApply']")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on apply withot dates");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : adsfasd");
		test.info("Click on custom dates");
		test.info("Click on date range");
		test.info("Click on apply");
		test.info("EXPECTED RESULT ::  It should display toast msg");
		Assert.assertEquals("Date Range", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Assert.assertEquals("Please select from date", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying Please enter from date");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("23");
	}
	@Test
	public void test24() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-chat-filter-container']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='custom-option-label']")).getText();
		driver.findElement(By.xpath("//span[@class='custom-option-label']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='customDateRangeFilterFrom']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//tr//td[@class='day']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='customDateRangeFilterApply']")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on apply withot dates");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : adsfasd");
		test.info("Click on custom dates");
		test.info("Click on date range");
		test.info("Click on apply");
		test.info("EXPECTED RESULT ::  It should display toast msg");
		Assert.assertEquals("Date Range", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Assert.assertEquals("Please select from date", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying Please enter from date");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("24");
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
