package Recentchatusersearch;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class recentchatusersearch {
	WebDriver driver;
	ExtentHtmlReporter htmlReporter;
	ExtentReports extent;

	String extentReportImage = System.getProperty("user.dir")+ "extentReportImage.png";
	@BeforeSuite
	public void StartTest() {
		htmlReporter = new ExtentHtmlReporter("recentchatusersearch.html");
		extent = new ExtentReports();
		extent.attachReporter(htmlReporter);
	}
	@Test
	public void test00() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("test");
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Search the user/group");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : test");
		test.info("EXPECTED RESULT ::  It should display the user/group name");
		String a=driver.findElement(By.xpath("//div[@data-name='Dev n test']")).getText();
		Assert.assertEquals("Dev N Test", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the user/group name");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("0");
	}
	@Test
	public void test01() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("adsfdsg");
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Search invalid user/group");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : adsfdsg");
		test.info("EXPECTED RESULT ::  It should not display the user/group name");
		String a=driver.findElement(By.xpath("//span[@class='no-recent-results-text']")).getText();
		Assert.assertEquals("No Data", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not displaying the user/group name");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("1");
	}
	@Test
	public void test02() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='clearRecentUserSearch']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on close button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : test");
		test.info("Click on close button");
		test.info("EXPECTED RESULT ::  It should close the searched user/group name");
		String a=driver.findElement(By.xpath("//div[@data-name='maneesh']")).getText();
		Assert.assertEquals("Maneesh", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is closing the searched user/group name");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("2");
	}
	@Test
	public void test03() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a2=driver.findElement(By.xpath("//div[@class='recent-users-search-filter-text active']")).getText();
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-text active']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select all members & groups");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Click on all members & groups icon");
		test.info("Select all members & groups icon");
		test.info("EXPECTED RESULT ::  It should select all members & groups icon");
		Assert.assertEquals("All Members/Groups", a2);
		test.pass(a2);
		System.out.println(a2);
		String a=driver.findElement(By.xpath("//div[@data-name='maneesh']")).getText();
		Assert.assertEquals("Maneesh", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//div[@data-name='Dev n test']")).getText();
		Assert.assertEquals("Dev N Test", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is selecting all members & groups icon");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("3");
	}
	@Test
	public void test04() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a2=driver.findElement(By.xpath("//div[@class='recent-users-search-filter-text active']")).getText();
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-text active']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select all members & groups with input");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : test");
		test.info("Click on all members & groups icon");
		test.info("Select all members & groups icon");
		test.info("EXPECTED RESULT ::  It should search input data of users & groups ");
		Assert.assertEquals("All Members/Groups", a2);
		test.pass(a2);
		System.out.println(a2);
		String a1=driver.findElement(By.xpath("//div[@data-name='Dev n test']")).getText();
		Assert.assertEquals("Dev N Test", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is searching input data of users & groups ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("4");
	}
	@Test
	public void test05() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("asdasddsf");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a2=driver.findElement(By.xpath("//div[@class='recent-users-search-filter-text active']")).getText();
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-text active']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select all members & groups with invalid input");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : asdasddsf");
		test.info("Click on all members & groups icon");
		test.info("Select all members & groups icon");
		test.info("EXPECTED RESULT ::  It should not search input data of users & groups ");
		Assert.assertEquals("All Members/Groups", a2);
		test.pass(a2);
		System.out.println(a2);
		String a=driver.findElement(By.xpath("//span[@class='no-recent-results-text']")).getText();
		Assert.assertEquals("No Data", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not searching input data of users & groups ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("5");
	}
	@Test
	public void test06() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a2=driver.findElement(By.xpath("//div[@class='recent-users-search-filter-text active']")).getText();
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-text active']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@id='clearRecentUserSearch']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on close button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : test");
		test.info("Click on all members & groups icon");
		test.info("Select all members & groups icon");
		test.info("Click on close button");
		test.info("EXPECTED RESULT ::  It should close the searched data & It should display unread msg icon ");
		Assert.assertEquals("All Members/Groups", a2);
		test.pass(a2);
		System.out.println(a2);
		String a=driver.findElement(By.xpath("//div[@data-name='maneesh']")).getText();
		Assert.assertEquals("Maneesh", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//span[@id='unreadMessageFilterBtn']")).getAttribute("title");
		Assert.assertEquals("Unread Messages", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is closing the searched data & It is displaying unread msg icon ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("6");
	}
	@Test
	public void test07() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a2=driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[1]")).getText();
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[1]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select members ");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Click on all members & groups icon");
		test.info("Select members icon");
		test.info("EXPECTED RESULT ::  It should select members icon & It should display only users");
		Assert.assertEquals("Members", a2);
		test.pass(a2);
		System.out.println(a2);
		String a=driver.findElement(By.xpath("//div[@data-name='maneesh']")).getText();
		Assert.assertEquals("Maneesh", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is selecting members icon & It is displaying only users");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("7");
	}
	@Test
	public void test08() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("sai");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a2=driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[1]")).getText();
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[1]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select members with input");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : sai");
		test.info("Click on all members & groups icon");
		test.info("Select members icon");
		test.info("EXPECTED RESULT ::  It should search input data of users ");
		Assert.assertEquals("Members", a2);
		test.pass(a2);
		System.out.println(a2);
		String a1=driver.findElement(By.xpath("//div[@data-name='sai']")).getText();
		Assert.assertEquals("Sai", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is searching input data of users ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("8");
	}
	@Test
	public void test09() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("asdasddsf");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a2=driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[1]")).getText();
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[1]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select members with invalid input");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : asdasddsf");
		test.info("Click on all members & groups icon");
		test.info("Select members icon");
		test.info("EXPECTED RESULT ::  It should not search input data of users ");
		Assert.assertEquals("Members", a2);
		test.pass(a2);
		System.out.println(a2);
		String a=driver.findElement(By.xpath("//span[@class='no-recent-results-text']")).getText();
		Assert.assertEquals("No Data", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not searching input data of users ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("9");
	}
	@Test
	public void test10() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("sai");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a2=driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[1]")).getText();
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[1]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@id='clearRecentUserSearch']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on close button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : sai");
		test.info("Click on all members & groups icon");
		test.info("Select members icon");
		test.info("Click on close button");
		test.info("EXPECTED RESULT ::  It should close the data & It should display unread msg icon ");
		Assert.assertEquals("Members", a2);
		test.pass(a2);
		System.out.println(a2);
		String a1=driver.findElement(By.xpath("//div[@data-name='maneesh']")).getText();
		Assert.assertEquals("Maneesh", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@id='unreadMessageFilterBtn']")).getAttribute("title");
		Assert.assertEquals("Unread Messages", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is closing the data & it is displaying unread msg icon ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("10");
	}
	@Test
	public void test11() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a4=driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[2]")).getText();
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[2]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select groups ");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Click on all members & groups icon");
		test.info("Select groups icon");
		test.info("EXPECTED RESULT ::  It should select groups icon & It should display only groups");
		Assert.assertEquals("Groups", a4);
		test.pass(a4);
		System.out.println(a4);
		String a=driver.findElement(By.xpath("//div[@data-name='aaab']")).getText();
		Assert.assertEquals("Aaab", a);
		test.pass(a);
		System.out.println(a);
		String a3=driver.findElement(By.xpath("//span[@class='group-icon']")).getAttribute("class");
		Assert.assertEquals("group-icon", a3);
		test.pass(a3);
		System.out.println(a3);
		String a1=driver.findElement(By.xpath("//div[@data-name='Dev n test']")).getText();
		Assert.assertEquals("Dev N Test", a1);
		test.pass(a1);
		System.out.println(a1);
		String a2=driver.findElement(By.xpath("//span[@class='group-icon']")).getAttribute("class");
		Assert.assertEquals("group-icon", a2);
		test.pass(a2);
		System.out.println(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is selecting groups icon & It is displaying only groups");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("11");
	}
	@Test
	public void test12() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a4=driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[2]")).getText();
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[2]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select groups with input");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : test");
		test.info("Click on all members & groups icon");
		test.info("Select groups icon");
		test.info("EXPECTED RESULT ::  It should search input data of groups ");
		Assert.assertEquals("Groups", a4);
		test.pass(a4);
		System.out.println(a4);
		String a1=driver.findElement(By.xpath("//div[@data-name='Dev n test']")).getText();
		Assert.assertEquals("Dev N Test", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@class='group-icon']")).getAttribute("class");
		Assert.assertEquals("group-icon", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is searching input data of groups ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("12");
	}
	@Test
	public void test13() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("asdasddsf");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a4=driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[2]")).getText();
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[2]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select groups with invalid input");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : asdasddsf");
		test.info("Click on all members & groups icon");
		test.info("Select groups icon");
		test.info("EXPECTED RESULT ::  It should not search input data of groups ");
		Assert.assertEquals("Groups", a4);
		test.pass(a4);
		System.out.println(a4);
		String a=driver.findElement(By.xpath("//span[@class='no-recent-results-text']")).getText();
		Assert.assertEquals("No Data", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not searching input data of groups ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("13");
	}
	@Test
	public void test14() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("sai");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a2=driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[2]")).getText();
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[2]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@id='clearRecentUserSearch']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on close button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : sai");
		test.info("Click on all members & groups icon");
		test.info("Select members icon");
		test.info("Click on close button");
		test.info("EXPECTED RESULT ::  It should close the data & It should display unread msg icon ");
		Assert.assertEquals("Groups", a2);
		test.pass(a2);
		System.out.println(a2);
		String a1=driver.findElement(By.xpath("//div[@data-name='maneesh']")).getText();
		Assert.assertEquals("Maneesh", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@id='unreadMessageFilterBtn']")).getAttribute("title");
		Assert.assertEquals("Unread Messages", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is closing the data & It is displaying unread msg icon ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("14");
	}
	@Test
	public void test15() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a1=driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[3]")).getText();
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[3]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select orange members ");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Click on all members & groups icon");
		test.info("Select orange members icon");
		test.info("EXPECTED RESULT ::  It should select orange members icon & It should display only orange members");
		Assert.assertEquals("Orange Member", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//div[@data-name='browser']")).getText();
		Assert.assertEquals("Browser", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is selecting orange members icon & It is displaying only orange members");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("15");
	}
	@Test
	public void test16() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("browser");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[3]")).getText();
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[3]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select orange members with input");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : browser");
		test.info("Click on all members & groups icon");
		test.info("Select orange members icon");
		test.info("EXPECTED RESULT ::  It should search input data of orange members ");
		Assert.assertEquals("Orange Member", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//div[@data-name='browser']")).getText();
		Assert.assertEquals("Browser", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is searching input data of orange members ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("16");
	}
	@Test
	public void test17() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("asdasddsf");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a1=driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[3]")).getText();
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[3]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select orange members with invalid input");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : asdasddsf");
		test.info("Click on all members & groups icon");
		test.info("Select orange members icon");
		test.info("EXPECTED RESULT ::  It should not search input data of orange members ");
		Assert.assertEquals("Orange Member", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@class='no-recent-results-text']")).getText();
		Assert.assertEquals("No Data", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not searching input data of orange members ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("17");
	}
	@Test
	public void test18() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("browser");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a2=driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[3]")).getText();
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[3]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@id='clearRecentUserSearch']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on close button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : browser");
		test.info("Click on all members & groups icon");
		test.info("Select members icon");
		test.info("Click on close button");
		test.info("EXPECTED RESULT ::  It should close the data & It should display unread msg icon ");
		Assert.assertEquals("Orange Member", a2);
		test.pass(a2);
		System.out.println(a2);
		String a1=driver.findElement(By.xpath("//div[@data-name='maneesh']")).getText();
		Assert.assertEquals("Maneesh", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@id='unreadMessageFilterBtn']")).getAttribute("title");
		Assert.assertEquals("Unread Messages", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is closing the data & It is displaying unread msg icon ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("18");
	}
	@Test
	public void test19() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a1=driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[4]")).getText();
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[4]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select De-Activated Users ");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Click on all members & groups icon");
		test.info("Select De-Activated Users icon");
		test.info("EXPECTED RESULT ::  It should select De-Activated Users icon & It should display only De-Activated Users");
		Assert.assertEquals("De-Activated Users", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//div[@data-name='user b']")).getText();
		Assert.assertEquals("User B", a);
		test.pass(a);
		System.out.println(a);
		String a2=driver.findElement(By.xpath("//span[@class='deactivated-user-text']")).getText();
		Assert.assertEquals("De-Activated", a2);
		test.pass(a2);
		System.out.println(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is selecting De-Activated Users icon & It is displaying only De-Activated Users");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("19");
	}
	@Test
	public void test20() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("user");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[4]")).getText();
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[4]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select De-Activated Users with input");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : browser");
		test.info("Click on all members & groups icon");
		test.info("Select De-Activated Users icon");
		test.info("EXPECTED RESULT ::  It should search input data of De-Activated Users ");
		Assert.assertEquals("De-Activated Users", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//div[@data-name='user b']")).getText();
		Assert.assertEquals("User B", a1);
		test.pass(a1);
		System.out.println(a1);
		String a2=driver.findElement(By.xpath("//span[@class='deactivated-user-text']")).getAttribute("class");
		Assert.assertEquals("deactivated-user-text", a2);
		test.pass(a2);
		System.out.println(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is searching input data of De-Activated Users ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("20");
	}
	@Test
	public void test21() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("asdasddsf");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a1=driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[4]")).getText();
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[4]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select De-Activated Users with invalid input");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : asdasddsf");
		test.info("Click on all members & groups icon");
		test.info("Select De-Activated Users icon");
		test.info("EXPECTED RESULT ::  It should not search input data of De-Activated Users ");
		Assert.assertEquals("De-Activated Users", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@class='no-recent-results-text']")).getText();
		Assert.assertEquals("No Data", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not searching input data of De-Activated Users ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("21");
	}
	@Test
	public void test22() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("browser");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a2=driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[4]")).getText();
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[4]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@id='clearRecentUserSearch']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on close button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : browser");
		test.info("Click on all members & groups icon");
		test.info("Select De-Activated Users icon");
		test.info("Click on close button");
		test.info("EXPECTED RESULT ::  It should close the data & It should display unread msg icon ");
		Assert.assertEquals("De-Activated Users", a2);
		test.pass(a2);
		System.out.println(a2);
		String a1=driver.findElement(By.xpath("//div[@data-name='maneesh']")).getText();
		Assert.assertEquals("Maneesh", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@id='unreadMessageFilterBtn']")).getAttribute("title");
		Assert.assertEquals("Unread Messages", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is closing the data & It is displaying unread msg icon ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("22");
	}
	@Test
	public void test23() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a1=driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[5]")).getText();
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[5]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select Deleted/Exited Groups ");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Click on all members & groups icon");
		test.info("Select Deleted/Exited Groups icon");
		test.info("EXPECTED RESULT ::  It should select Deleted/Exited Groups icon & It should display only Deleted/Exited Groups");
		Assert.assertEquals("Deleted/Exited Groups", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//div[@data-name='asdf']")).getText();
		Assert.assertEquals("Asdf", a);
		test.pass(a);
		System.out.println(a);
		String a3=driver.findElement(By.xpath("//span[@class='group-icon']")).getAttribute("class");
		Assert.assertEquals("group-icon", a3);
		test.pass(a3);
		System.out.println(a3);
		String a2=driver.findElement(By.xpath("//span[@class='deactivated-group-text']")).getAttribute("class");
		Assert.assertEquals("deactivated-group-text", a2);
		test.pass(a2);
		System.out.println(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is selecting Deleted/Exited Groups icon & It is displaying only Deleted/Exited Groups");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("23");
	}
	@Test
	public void test24() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("asdf");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[5]")).getText();
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[5]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select Deleted/Exited Groups with input");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : asdf");
		test.info("Click on all members & groups icon");
		test.info("Select Deleted/Exited Groups icon");
		test.info("EXPECTED RESULT ::  It should search input data of Deleted/Exited Groups ");
		Assert.assertEquals("Deleted/Exited Groups", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//div[@data-name='asdf']")).getText();
		Assert.assertEquals("Asdf", a1);
		test.pass(a1);
		System.out.println(a1);
		String a3=driver.findElement(By.xpath("//span[@class='group-icon']")).getAttribute("class");
		Assert.assertEquals("group-icon", a3);
		test.pass(a3);
		System.out.println(a3);
		String a2=driver.findElement(By.xpath("//span[@class='deactivated-group-text']")).getAttribute("class");
		Assert.assertEquals("deactivated-group-text", a2);
		test.pass(a2);
		System.out.println(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is searching input data of Deleted/Exited Groups ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("24");
	}
	@Test
	public void test25() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("asdasddsf");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a1=driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[5]")).getText();
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[5]")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Select Deleted/Exited Groups with invalid input");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : asdasddsf");
		test.info("Click on all members & groups icon");
		test.info("Select Deleted/Exited Groups icon");
		test.info("EXPECTED RESULT ::  It should not search input data of Deleted/Exited Groups ");
		Assert.assertEquals("Deleted/Exited Groups", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@class='no-recent-results-text']")).getText();
		Assert.assertEquals("No Data", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not searching input data of Deleted/Exited Groups ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("25");
	}
	@Test
	public void test26() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8081/messenger");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("asdf");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(2000);
		String a2=driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[5]")).getText();
		driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[5]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@id='clearRecentUserSearch']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on close button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath@trends.com");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on recentUserSearch");
		test.info("Enter text : asdf");
		test.info("Click on all members & groups icon");
		test.info("Select Deleted/Exited Groups icon");
		test.info("Click on close button");
		test.info("EXPECTED RESULT ::  It should close the data & It should display unread msg icon ");
		Assert.assertEquals("Deleted/Exited Groups", a2);
		test.pass(a2);
		System.out.println(a2);
		String a1=driver.findElement(By.xpath("//div[@data-name='maneesh']")).getText();
		Assert.assertEquals("Maneesh", a1);
		test.pass(a1);
		System.out.println(a1);
		String a=driver.findElement(By.xpath("//span[@id='unreadMessageFilterBtn']")).getAttribute("title");
		Assert.assertEquals("Unread Messages", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is closing the data & It is displaying unread msg icon ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("26");
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
