package readreceipt;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class receipt {
	WebDriver driver;
	ExtentHtmlReporter HtmlReporter;
	ExtentReports extent;

	@BeforeSuite
	public void Starttest() {
		HtmlReporter = new ExtentHtmlReporter("readreceipt.html");
		extent = new ExtentReports();
		extent.attachReporter(HtmlReporter);
	}
	@Test
	public void test00() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='input-read-receipt-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on read receipt & send msg to the user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("click on user");
		test.info("Click on read receipt");
		test.info("Enter text : test");
		test.info("Click on send");
		test.info("EXPECTED RESULT ::  It should display read receipt symbol for sended msg ");
		String a=driver.findElement(By.xpath("//div[@class='read-receipt-chat-button']")).getAttribute("title");
		Assert.assertEquals("Read Receipt", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//span[@class='received-message-text']")).getText();
		Assert.assertEquals("test", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying read receipt symbol for sended msg ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("receipt");
	}
	@Test
	public void test01() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='input-read-receipt-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-attachment-btn input-action-btn']")).click();
		Robot rb = new Robot();
		Thread.sleep(1000);
		//e.sendKeys("/home/tvisha/Pictures/Screenshot from 2022-06-04 18-47-59.png");
		StringSelection str = new StringSelection("/home/tvisha/Pictures/Screenshot from 2022-07-21 14-42-50.png");
		Toolkit.getDefaultToolkit().getSystemClipboard().setContents(str, null);
		Thread.sleep(2000);
		rb.keyPress(KeyEvent.VK_CONTROL);
		rb.keyPress(KeyEvent.VK_V);

		// release Control+V for pasting
		rb.keyRelease(KeyEvent.VK_CONTROL);
		rb.keyRelease(KeyEvent.VK_V);
		// for pressing and releasing Enter
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(1000);
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(8000);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on read receipt & send image to the user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("click on user");
		test.info("Click on read receipt");
		test.info("Click on attachment");
		test.info("Search image");
		test.info("Click on it");
		test.info("Click on send");
		test.info("EXPECTED RESULT ::  It should display read receipt symbol for sended image ");
		String a=driver.findElement(By.xpath("//div[@class='read-receipt-chat-button']")).getAttribute("title");
		Assert.assertEquals("Read Receipt", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//span[@class='image-attachment-span']")).getAttribute("class");
		Assert.assertEquals("image-attachment-span", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying read receipt symbol for sended image ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("1");
	}
	@Test
	public void test02() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='input-read-receipt-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-attachment-btn input-action-btn']")).click();
		Robot rb = new Robot();
		Thread.sleep(1000);
		//e.sendKeys("/home/tvisha/Pictures/Screenshot from 2022-06-04 18-47-59.png");
		StringSelection str = new StringSelection("/home/tvisha/Downloads/20210827_180112.mp4");
		Toolkit.getDefaultToolkit().getSystemClipboard().setContents(str, null);
		Thread.sleep(2000);
		rb.keyPress(KeyEvent.VK_CONTROL);
		rb.keyPress(KeyEvent.VK_V);

		// release Control+V for pasting
		rb.keyRelease(KeyEvent.VK_CONTROL);
		rb.keyRelease(KeyEvent.VK_V);
		// for pressing and releasing Enter
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(1000);
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(8000);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on read receipt & send video to the user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("click on user");
		test.info("Click on read receipt");
		test.info("Click on attachment");
		test.info("Search video");
		test.info("Click on search video");
		test.info("Click on send");
		test.info("EXPECTED RESULT ::  It should display read receipt symbol for sended video ");
		String a=driver.findElement(By.xpath("//div[@class='read-receipt-chat-button']")).getAttribute("title");
		Assert.assertEquals("Read Receipt", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//div[@class='video-attachment-wrapper']")).getAttribute("class");
		Assert.assertEquals("video-attachment-wrapper", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying read receipt symbol for sended video ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("2");
	}
	@Test
	public void test03() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='input-read-receipt-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-attachment-btn input-action-btn']")).click();
		Robot rb = new Robot();
		Thread.sleep(1000);
		//e.sendKeys("/home/tvisha/Pictures/Screenshot from 2022-06-04 18-47-59.png");
		StringSelection str = new StringSelection("/home/tvisha/Documents/Untitledtestcasesforlogin&signup.xlsx");
		Toolkit.getDefaultToolkit().getSystemClipboard().setContents(str, null);
		Thread.sleep(2000);
		rb.keyPress(KeyEvent.VK_CONTROL);
		rb.keyPress(KeyEvent.VK_V);

		// release Control+V for pasting
		rb.keyRelease(KeyEvent.VK_CONTROL);
		rb.keyRelease(KeyEvent.VK_V);
		// for pressing and releasing Enter
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(1000);
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(8000);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on read receipt & send document to the user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("click on user");
		test.info("Click on read receipt");
		test.info("Click on attachment");
		test.info("Search document");
		test.info("Click on searched document");
		test.info("Click on send");
		test.info("EXPECTED RESULT ::  It should display read receipt symbol for sended document ");
		String a=driver.findElement(By.xpath("//div[@class='read-receipt-chat-button']")).getAttribute("title");
		Assert.assertEquals("Read Receipt", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//span[@class='messenger-attachment-link-name']")).getAttribute("title");
		Assert.assertEquals("Untitledtestcasesforlogin_signup.xlsx", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying read receipt symbol for sended document ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("3");
	}
	@Test
	public void test04() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='input-read-receipt-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-attachment-btn input-action-btn']")).click();
		Robot rb = new Robot();
		Thread.sleep(1000);
		//e.sendKeys("/home/tvisha/Pictures/Screenshot from 2022-06-04 18-47-59.png");
		StringSelection str = new StringSelection("/home/tvisha/Downloads/Instrumental.mp3");
		Toolkit.getDefaultToolkit().getSystemClipboard().setContents(str, null);
		Thread.sleep(2000);
		rb.keyPress(KeyEvent.VK_CONTROL);
		rb.keyPress(KeyEvent.VK_V);

		// release Control+V for pasting
		rb.keyRelease(KeyEvent.VK_CONTROL);
		rb.keyRelease(KeyEvent.VK_V);
		// for pressing and releasing Enter
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(1000);
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(8000);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on read receipt & send audio file to the user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("click on user");
		test.info("Click on read receipt");
		test.info("Click on attachment");
		test.info("Search audio file");
		test.info("Click on searched audio file");
		test.info("Click on send");
		test.info("EXPECTED RESULT ::  It should display read receipt symbol for sended audio file ");
		String a=driver.findElement(By.xpath("//div[@class='read-receipt-chat-button']")).getAttribute("title");
		Assert.assertEquals("Read Receipt", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']")).getAttribute("class");
		Assert.assertEquals("audio-attachment-wrapper", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying read receipt symbol for sended audio file ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("4");
	}
	@Test
	public void test05() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='input-read-receipt-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-microphone-btn input-action-btn']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on read receipt & send voice msg to the user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("click on user");
		test.info("Click on read receipt");
		test.info("Click on voice message");
		test.info("Wait for few seconds");
		test.info("Click on send");
		test.info("EXPECTED RESULT ::  It should display read receipt symbol for sended voice msg ");
		String a=driver.findElement(By.xpath("//div[@class='read-receipt-chat-button']")).getAttribute("title");
		Assert.assertEquals("Read Receipt", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']")).getAttribute("class");
		Assert.assertEquals("audio-attachment-wrapper", a1);
		test.pass(a1);
		System.out.println(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying read receipt symbol for sended voice msg ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("5");
	}
	@Test
	public void test06() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='input-read-receipt-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='readReceiptSelectAllCheckbox']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='read-receipt-selected-members-wrapper']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on read receipt & send msg to the group");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("click on group: test");
		test.info("Click on read receipt");
		test.info("Click on select all in read receipt");
		test.info("Enter text : test");
		test.info("Click on send");
		test.info("EXPECTED RESULT ::  It should display read receipt symbol for sended msg ");
		String a=driver.findElement(By.xpath("//div[@class='read-receipt-chat-button']")).getAttribute("title");
		Assert.assertEquals("Read Receipt", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//span[@class='received-message-text']")).getText();
		Assert.assertEquals("test", a1);
		test.pass(a1);
		System.out.println(a1);
		Assert.assertEquals("4 users", a2);
		test.pass(a2);
		System.out.println(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying read receipt symbol for sended msg ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("6");
	}
	@Test
	public void test07() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='input-read-receipt-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='readReceipt-32-1']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='readReceipt-6-1']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='read-receipt-selected-members-wrapper']")).getText();
		driver.findElement(By.xpath("//div[@class='input-attachment-btn input-action-btn']")).click();
		Robot rb = new Robot();
		Thread.sleep(1000);
		//e.sendKeys("/home/tvisha/Pictures/Screenshot from 2022-06-04 18-47-59.png");
		StringSelection str = new StringSelection("/home/tvisha/Pictures/Screenshot from 2022-07-21 14-42-50.png");
		Toolkit.getDefaultToolkit().getSystemClipboard().setContents(str, null);
		Thread.sleep(2000);
		rb.keyPress(KeyEvent.VK_CONTROL);
		rb.keyPress(KeyEvent.VK_V);

		// release Control+V for pasting
		rb.keyRelease(KeyEvent.VK_CONTROL);
		rb.keyRelease(KeyEvent.VK_V);
		// for pressing and releasing Enter
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(1000);
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(8000);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on read receipt & send image to the group");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("click on group : test");
		test.info("Click on read receipt");
		test.info("Select the checkbox of the users");
		test.info("Click on attachment");
		test.info("Search image");
		test.info("Click on it");
		test.info("Click on send");
		test.info("EXPECTED RESULT ::  It should display read receipt symbol for sended image ");
		String a=driver.findElement(By.xpath("//div[@class='read-receipt-chat-button']")).getAttribute("title");
		Assert.assertEquals("Read Receipt", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//span[@class='image-attachment-span']")).getAttribute("class");
		Assert.assertEquals("image-attachment-span", a1);
		test.pass(a1);
		System.out.println(a1);
		Assert.assertEquals("2 users", a2);
		test.pass(a2);
		System.out.println(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying read receipt symbol for sended image ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("7");
	}
	@Test
	public void test08() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='input-read-receipt-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='readReceiptMembersSearch']")).sendKeys("akshay");
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='readReceipt-6-1']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='read-receipt-selected-members-wrapper']")).getText();
		driver.findElement(By.xpath("//div[@class='input-attachment-btn input-action-btn']")).click();
		Robot rb = new Robot();
		Thread.sleep(1000);
		//e.sendKeys("/home/tvisha/Pictures/Screenshot from 2022-06-04 18-47-59.png");
		StringSelection str = new StringSelection("/home/tvisha/Downloads/20210827_180112.mp4");
		Toolkit.getDefaultToolkit().getSystemClipboard().setContents(str, null);
		Thread.sleep(2000);
		rb.keyPress(KeyEvent.VK_CONTROL);
		rb.keyPress(KeyEvent.VK_V);

		// release Control+V for pasting
		rb.keyRelease(KeyEvent.VK_CONTROL);
		rb.keyRelease(KeyEvent.VK_V);
		// for pressing and releasing Enter
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(1000);
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(8000);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on read receipt & send video to the group");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("click on group : test");
		test.info("Click on read receipt");
		test.info("Click on search");
		test.info("Enter text in search : akshay");
		test.info("Click on that checkbox of the user");
		test.info("Click on attachment");
		test.info("Search video");
		test.info("Click on search video");
		test.info("Click on send");
		test.info("EXPECTED RESULT ::  It should display read receipt symbol for sended video ");
		String a=driver.findElement(By.xpath("//div[@class='read-receipt-chat-button']")).getAttribute("title");
		Assert.assertEquals("Read Receipt", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//div[@class='video-attachment-wrapper']")).getAttribute("class");
		Assert.assertEquals("video-attachment-wrapper", a1);
		test.pass(a1);
		System.out.println(a1);
		Assert.assertEquals("1 user", a2);
		test.pass(a2);
		System.out.println(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying read receipt symbol for sended video ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("8");
	}
	@Test
	public void test09() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='input-read-receipt-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='readReceiptMembersSearch']")).sendKeys("adsffdgfdg");
		Thread.sleep(500);
		String a3=driver.findElement(By.xpath("//div[@class='no-results-found']")).getAttribute("class");
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='readReceiptMembersSearch']")).clear();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='readReceiptSelectAllCheckbox']")).click();
		String a2=driver.findElement(By.xpath("//div[@class='read-receipt-selected-members-wrapper']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-attachment-btn input-action-btn']")).click();
		Robot rb = new Robot();
		Thread.sleep(1000);
		//e.sendKeys("/home/tvisha/Pictures/Screenshot from 2022-06-04 18-47-59.png");
		StringSelection str = new StringSelection("/home/tvisha/Documents/Untitledtestcasesforlogin&signup.xlsx");
		Toolkit.getDefaultToolkit().getSystemClipboard().setContents(str, null);
		Thread.sleep(2000);
		rb.keyPress(KeyEvent.VK_CONTROL);
		rb.keyPress(KeyEvent.VK_V);

		// release Control+V for pasting
		rb.keyRelease(KeyEvent.VK_CONTROL);
		rb.keyRelease(KeyEvent.VK_V);
		// for pressing and releasing Enter
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(1000);
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(8000);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on read receipt & send document to the group");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("click on group : test");
		test.info("Click on read receipt");
		test.info("Click on search");
		test.info("Search invalid user");
		test.info("Clear the search ");
		test.info("Click on all the checkboxes");
		test.info("Click on attachment");
		test.info("Search document");
		test.info("Click on searched document");
		test.info("Click on send");
		test.info("EXPECTED RESULT ::  It should display read receipt symbol for sended document ");
		String a=driver.findElement(By.xpath("//div[@class='read-receipt-chat-button']")).getAttribute("title");
		Assert.assertEquals("Read Receipt", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//span[@class='messenger-attachment-link-name']")).getAttribute("title");
		Assert.assertEquals("Untitledtestcasesforlogin_signup.xlsx", a1);
		test.pass(a1);
		System.out.println(a1);
		Assert.assertEquals("no-results-found", a3);
		test.pass(a3);
		System.out.println(a3);
		Assert.assertEquals("4 users", a2);
		test.pass(a2);
		System.out.println(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying read receipt symbol for sended document ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("9");
	}
	@Test
	public void test10() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='input-read-receipt-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='readReceipt-32-1']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='readReceipt-6-1']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='readReceipt-23-1']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='readReceipt-2-1']")).click();
		String a2=driver.findElement(By.xpath("//div[@class='read-receipt-selected-members-wrapper']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-attachment-btn input-action-btn']")).click();
		Robot rb = new Robot();
		Thread.sleep(1000);
		//e.sendKeys("/home/tvisha/Pictures/Screenshot from 2022-06-04 18-47-59.png");
		StringSelection str = new StringSelection("/home/tvisha/Downloads/Instrumental.mp3");
		Toolkit.getDefaultToolkit().getSystemClipboard().setContents(str, null);
		Thread.sleep(2000);
		rb.keyPress(KeyEvent.VK_CONTROL);
		rb.keyPress(KeyEvent.VK_V);

		// release Control+V for pasting
		rb.keyRelease(KeyEvent.VK_CONTROL);
		rb.keyRelease(KeyEvent.VK_V);
		// for pressing and releasing Enter
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(1000);
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(8000);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on read receipt & send audio file to the group");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("click on group : test");
		test.info("Click on read receipt");
		test.info("Click on users all the checkboxes");
		test.info("Click on attachment");
		test.info("Search audio file");
		test.info("Click on searched audio file");
		test.info("Click on send");
		test.info("EXPECTED RESULT ::  It should display read receipt symbol for sended audio file ");
		String a=driver.findElement(By.xpath("//div[@class='read-receipt-chat-button']")).getAttribute("title");
		Assert.assertEquals("Read Receipt", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']")).getAttribute("class");
		Assert.assertEquals("audio-attachment-wrapper", a1);
		test.pass(a1);
		System.out.println(a1);
		Assert.assertEquals("4 users", a2);
		test.pass(a2);
		System.out.println(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying read receipt symbol for sended audio file ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("10");
	}
	@Test
	public void test11() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='input-read-receipt-btn input-action-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='readReceiptSelectAllCheckbox']")).click();
		Thread.sleep(500);
		String a2=driver.findElement(By.xpath("//div[@class='read-receipt-selected-members-wrapper']")).getText();
		driver.findElement(By.xpath("//div[@class='input-microphone-btn input-action-btn']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on read receipt & send voice msg to the group");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("click on group : test");
		test.info("Click on read receipt");
		test.info("Click on voice message");
		test.info("Wait for few seconds");
		test.info("Click on send");
		test.info("EXPECTED RESULT ::  It should display read receipt symbol for sended voice msg ");
		String a=driver.findElement(By.xpath("//div[@class='read-receipt-chat-button']")).getAttribute("title");
		Assert.assertEquals("Read Receipt", a);
		test.pass(a);
		System.out.println(a);
		String a1=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']")).getAttribute("class");
		Assert.assertEquals("audio-attachment-wrapper", a1);
		test.pass(a1);
		System.out.println(a1);
		Assert.assertEquals("4 users", a2);
		test.pass(a2);
		System.out.println(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying read receipt symbol for sended voice msg ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("11");
	}
	@Test
	public void test12() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-read-receipt']")).click();
		Thread.sleep(1000);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on read receipt in filters in the user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("click on user");
		test.info("Click on filters");
		test.info("Click on read receipt");
		test.info("EXPECTED RESULT ::  It should display all read receipt sended msg ");
		String a=driver.findElement(By.xpath("//div[@class='read-receipt-chat-button']")).getAttribute("title");
		Assert.assertEquals("Read Receipt", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all read receipt sended msg ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("12");
	}
	@Test
	public void test13() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("sharath@trends.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='test']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='filter-access-btn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='filter-icon filter-icon-read-receipt']")).click();
		Thread.sleep(1000);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on read receipt in filters in the group");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: sharath@trends.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("click on group : test");
		test.info("Click on filters");
		test.info("Click on read receipt");
		test.info("EXPECTED RESULT ::  It should display all read receipt sended msg ");
		String a=driver.findElement(By.xpath("//div[@class='read-receipt-chat-button']")).getAttribute("title");
		Assert.assertEquals("Read Receipt", a);
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying all read receipt sended msg ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("13");
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
	
}
