package EmojiandBold;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class EmojiandFonts {
	WebDriver driver;
	ExtentHtmlReporter HtmlReporter;
	ExtentReports Extent;
	@BeforeSuite
	public void Starttest() {
		HtmlReporter = new ExtentHtmlReporter("emoji & fonts.html");
		Extent = new ExtentReports();
		Extent.attachReporter(HtmlReporter);
	}
	//Emoji's
	@Test
	public void tests00() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='emoji-content-preview-wrapper']")).getAttribute("class");
		Thread.sleep(1000);
		ExtentTest test= Extent.createTest("Click on emoji");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: android@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("Click on user");
		test.info("Click on emoji");
		test.info("EXPECTED RESULT:: It should display emoji's");
		Assert.assertEquals(a, "input-emoji-btn input-action-btn");
		test.pass(a);
		Assert.assertEquals(a1, "emoji-content-preview-wrapper");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying emoji's");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();	
	}
	@Test
	public void tests01() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='emoji-content-preview-wrapper']")).getAttribute("class");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//span[@data-category='popular']")).getText();
		driver.findElement(By.xpath("//span[@class='emojione emojione-32-people _1f642 row-visible']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//div[@class='emojione emojione-32-people _1f642']")).getText();
		Thread.sleep(1000);
		ExtentTest test= Extent.createTest("Send emoji");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: android@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("Click on user");
		test.info("Click on emoji");
		test.info("Send the emoji");
		test.info("EXPECTED RESULT:: It should send emoji's");
		Assert.assertEquals(a, "input-emoji-btn input-action-btn");
		test.pass(a);
		Assert.assertEquals(a1, "emoji-content-preview-wrapper");
		test.pass(a1);
		Assert.assertEquals(a2, "Popular");
		test.pass(a2);
		Assert.assertEquals(a3, "🙂");
		test.pass(a3);
		test.log(Status.PASS,"ACTUAL RESULT:: It is sending emoji's");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();	
	}
	@Test
	public void tests02() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='emoji-content-preview-wrapper']")).getAttribute("class");
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//div[@class='emoji-filter-btn'])[1]")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//span[@data-category='people']")).getText();
		Thread.sleep(1000);
		ExtentTest test= Extent.createTest("Click on People icon");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: android@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("Click on user");
		test.info("Click on emoji");
		test.info("Click on people icon");
		test.info("EXPECTED RESULT:: It should click on people icon");
		Assert.assertEquals(a, "input-emoji-btn input-action-btn");
		test.pass(a);
		Assert.assertEquals(a1, "emoji-content-preview-wrapper");
		test.pass(a1);
		Assert.assertEquals(a2, "People");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT:: It is clicking on people icon");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();	
	}
	@Test
	public void tests03() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='emoji-content-preview-wrapper']")).getAttribute("class");
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//div[@class='emoji-filter-btn'])[2]")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//span[@data-category='nature']")).getText();
		Thread.sleep(1000);
		ExtentTest test= Extent.createTest("Click on nature icon");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: android@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("Click on user");
		test.info("Click on emoji");
		test.info("Click on nature icon");
		test.info("EXPECTED RESULT:: It should click on nature icon");
		Assert.assertEquals(a, "input-emoji-btn input-action-btn");
		test.pass(a);
		Assert.assertEquals(a1, "emoji-content-preview-wrapper");
		test.pass(a1);
		Assert.assertEquals(a2, "Nature");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT:: It is clicking on nature icon");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();	
	}
	@Test
	public void tests04() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='emoji-content-preview-wrapper']")).getAttribute("class");
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//div[@class='emoji-filter-btn'])[3]")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//span[@data-category='food']")).getText();
		Thread.sleep(1000);
		ExtentTest test= Extent.createTest("Click on food icon");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: android@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("Click on user");
		test.info("Click on emoji");
		test.info("Click on food icon");
		test.info("EXPECTED RESULT:: It should click on food icon");
		Assert.assertEquals(a, "input-emoji-btn input-action-btn");
		test.pass(a);
		Assert.assertEquals(a1, "emoji-content-preview-wrapper");
		test.pass(a1);
		Assert.assertEquals(a2, "Food");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT:: It is clicking on food icon");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();	
	}
	@Test
	public void tests05() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='emoji-content-preview-wrapper']")).getAttribute("class");
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//div[@class='emoji-filter-btn'])[4]")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//span[@data-category='activity']")).getText();
		Thread.sleep(1000);
		ExtentTest test= Extent.createTest("Click on activity icon");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: android@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("Click on user");
		test.info("Click on emoji");
		test.info("Click on activity icon");
		test.info("EXPECTED RESULT:: It should click on activity icon");
		Assert.assertEquals(a, "input-emoji-btn input-action-btn");
		test.pass(a);
		Assert.assertEquals(a1, "emoji-content-preview-wrapper");
		test.pass(a1);
		Assert.assertEquals(a2, "Activity");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT:: It is clicking on activity icon");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();	
	}
	@Test
	public void tests06() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='emoji-content-preview-wrapper']")).getAttribute("class");
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//div[@class='emoji-filter-btn'])[5]")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//span[@data-category='objects']")).getText();
		Thread.sleep(1000);
		ExtentTest test= Extent.createTest("Click on objects icon");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: android@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("Click on user");
		test.info("Click on emoji");
		test.info("Click on objects icon");
		test.info("EXPECTED RESULT:: It should click on objects icon");
		Assert.assertEquals(a, "input-emoji-btn input-action-btn");
		test.pass(a);
		Assert.assertEquals(a1, "emoji-content-preview-wrapper");
		test.pass(a1);
		Assert.assertEquals(a2, "Objects");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT:: It is clicking on objects icon");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();	
	}
	@Test
	public void tests07() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='emoji-content-preview-wrapper']")).getAttribute("class");
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//div[@class='emoji-filter-btn'])[6]")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//span[@data-category='flags']")).getText();
		Thread.sleep(1000);
		ExtentTest test= Extent.createTest("Click on flags icon");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: android@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("Click on user");
		test.info("Click on emoji");
		test.info("Click on flags icon");
		test.info("EXPECTED RESULT:: It should click on flags icon");
		Assert.assertEquals(a, "input-emoji-btn input-action-btn");
		test.pass(a);
		Assert.assertEquals(a1, "emoji-content-preview-wrapper");
		test.pass(a1);
		Assert.assertEquals(a2, "Flags");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT:: It is clicking on flags icon");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();	
	}
	@Test
	public void tests08() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='emoji-content-preview-wrapper']")).getAttribute("class");
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//div[@class='emoji-filter-btn'])[7]")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//span[@data-category='regional']")).getText();
		Thread.sleep(1000);
		ExtentTest test= Extent.createTest("Click on regional icon");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: android@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("Click on user");
		test.info("Click on emoji");
		test.info("Click on regional icon");
		test.info("EXPECTED RESULT:: It should click on regional icon");
		Assert.assertEquals(a, "input-emoji-btn input-action-btn");
		test.pass(a);
		Assert.assertEquals(a1, "emoji-content-preview-wrapper");
		test.pass(a1);
		Assert.assertEquals(a2, "Regional");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT:: It is clicking on regional icon");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();	
	}
	@Test
	public void tests09() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='emoji-content-preview-wrapper']")).getAttribute("class");
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//div[@class='emoji-filter-btn'])[8]")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//span[@data-category='symbols']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='emojione emojione-32-symbols _002a-20e3 row-visible']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//div[@class='emojione emojione-32-symbols _002a-20e3']")).getText();
		Thread.sleep(1000);
		ExtentTest test= Extent.createTest("Click on symbols icon");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: android@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("Click on user");
		test.info("Click on emoji");
		test.info("Click on symbols icon");
		test.info("EXPECTED RESULT:: It should click on symbols icon");
		Assert.assertEquals(a, "input-emoji-btn input-action-btn");
		test.pass(a);
		Assert.assertEquals(a1, "emoji-content-preview-wrapper");
		test.pass(a1);
		Assert.assertEquals(a2, "Symbols");
		test.pass(a2);
		Assert.assertEquals(a3, "*️⃣");
		test.pass(a3);
		test.log(Status.PASS,"ACTUAL RESULT:: It is clicking on symbols icon");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();	
	}
	@Test
	public void tests010() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='emoji-content-preview-wrapper']")).getAttribute("class");
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//div[@class='emoji-filter-btn'])[9]")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//span[@data-category='travel']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='emojione emojione-32-travel _1f6e9 row-visible']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//div[@class='emojione emojione-32-travel _1f6e9']")).getText();
		Thread.sleep(1000);
		ExtentTest test= Extent.createTest("Click on travel icon");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: android@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("Click on user");
		test.info("Click on emoji");
		test.info("Click on travel icon");
		test.info("EXPECTED RESULT:: It should click on travel icon");
		Assert.assertEquals(a, "input-emoji-btn input-action-btn");
		test.pass(a);
		Assert.assertEquals(a1, "emoji-content-preview-wrapper");
		test.pass(a1);
		Assert.assertEquals(a2, "Travel");
		test.pass(a2);
		Assert.assertEquals(a3, "🛩️");
		test.pass(a3);
		test.log(Status.PASS,"ACTUAL RESULT:: It is clicking on travel icon");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();	
	}
	@Test
	public void tests011() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='emoji-content-preview-wrapper']")).getAttribute("class");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//input[@id='emojiSearchWrapper']")).getAttribute("id");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='emojiSearchWrapper']")).sendKeys("happy");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='emojione emojione-32-travel _1f3d6 row-visible']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//div[@class='emojione emojione-32-travel _1f3d6']")).getText();
		Thread.sleep(1000);
		ExtentTest test= Extent.createTest("Search valid related emoji");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: android@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("Click on user");
		test.info("Click on emoji");
		test.info("Click on search");
		test.info("Enter valid related text");
		test.info("EXPECTED RESULT:: It should display related emoji's");
		Assert.assertEquals(a, "input-emoji-btn input-action-btn");
		test.pass(a);
		Assert.assertEquals(a1, "emoji-content-preview-wrapper");
		test.pass(a1);
		Assert.assertEquals(a2, "emojiSearchWrapper");
		test.pass(a2);
		Assert.assertEquals(a3, "🏖️");
		test.pass(a3);
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying related emoji's");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();	
	}
	@Test
	public void tests012() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='emoji-content-preview-wrapper']")).getAttribute("class");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//input[@id='emojiSearchWrapper']")).getAttribute("id");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='emojiSearchWrapper']")).sendKeys("adsfds");
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//div[@class='no-results-found']")).getText();
		Thread.sleep(1000);
		ExtentTest test= Extent.createTest("Search invalid related emoji");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: android@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("Click on user");
		test.info("Click on emoji");
		test.info("Click on search");
		test.info("Enter invalid related text");
		test.info("EXPECTED RESULT:: It should not display related emoji's");
		Assert.assertEquals(a, "input-emoji-btn input-action-btn");
		test.pass(a);
		Assert.assertEquals(a1, "emoji-content-preview-wrapper");
		test.pass(a1);
		Assert.assertEquals(a2, "emojiSearchWrapper");
		test.pass(a2);
		Assert.assertEquals(a3, "No results Found!");
		test.pass(a3);
		test.log(Status.PASS,"ACTUAL RESULT:: It is not displaying related emoji's");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();	
	}
	@Test
	public void tests013() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='input-emoji-btn input-action-btn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='emoji-content-preview-wrapper']")).getAttribute("class");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//input[@id='emojiSearchWrapper']")).getAttribute("id");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='emojiSearchWrapper']")).sendKeys("adsfds");
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//div[@class='no-results-found']")).getText();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//div[@id='clearEmojiSearchWrapper']")).getAttribute("id");
		driver.findElement(By.xpath("//div[@id='clearEmojiSearchWrapper']")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//input[@id='emojiSearchWrapper']")).getText();
		String a6=driver.findElement(By.xpath("//div[@class='emoji-content-preview-wrapper']")).getAttribute("class");
		Thread.sleep(1000);
		ExtentTest test= Extent.createTest("Clear the search content");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: android@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("Click on user");
		test.info("Click on emoji");
		test.info("Click on search");
		test.info("Enter invalid related text");
		test.info("Click on esc");
		test.info("EXPECTED RESULT:: It should clear the entered search");
		Assert.assertEquals(a, "input-emoji-btn input-action-btn");
		test.pass(a);
		Assert.assertEquals(a1, "emoji-content-preview-wrapper");
		test.pass(a1);
		Assert.assertEquals(a2, "emojiSearchWrapper");
		test.pass(a2);
		Assert.assertEquals(a3, "No results Found!");
		test.pass(a3);
		Assert.assertEquals(a4, "clearEmojiSearchWrapper");
		test.pass(a4);
		Assert.assertEquals(a5, "");
		test.pass(a5);
		Assert.assertEquals(a6, "emoji-content-preview-wrapper");
		test.pass(a6);
		test.log(Status.PASS,"ACTUAL RESULT:: It is clearing the entered search");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();	
	}
	//Fonts & format
	@Test
	public void tests014() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='input-bold-btn input-action-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='input-bold-btn input-action-btn']")).click();
		String a2=driver.findElement(By.xpath("//div[@class='input-bold-btn input-action-btn active']")).getAttribute("class");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//span[@class='received-message-text'])[13]")).getText();
		Thread.sleep(1000);
		ExtentTest test= Extent.createTest("Click on Bold & Enter text");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: android@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("Click on user");
		test.info("Click on Bold");
		test.info("Enter text");
		test.info("Send the msg");
		test.info("EXPECTED RESULT:: It should send the msg with bold");
		Assert.assertEquals(a, "input-bold-btn input-action-btn");
		test.pass(a);
		Assert.assertEquals(a2, "input-bold-btn input-action-btn active");
		test.pass(a2);
		Assert.assertEquals(a1, "Test");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT:: It is sending the msg with bold");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();	
	}
	@Test
	public void tests015() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[14]/div[2]/div[1]/div[4]/span[2]"));
		Actions ac=new Actions(driver);
		ac.doubleClick(e).build().perform();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='input-bold-btn input-action-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='input-bold-btn input-action-btn']")).click();
		String a2=driver.findElement(By.xpath("//div[@class='input-bold-btn input-action-btn active']")).getAttribute("class");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//span[@class='received-message-text'])[13]")).getText();
		Thread.sleep(1000);
		ExtentTest test= Extent.createTest("Enter text & Click on Bold");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: android@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("Click on user");
		test.info("Enter text & double click on entered msg");
		test.info("Click on Bold");
		test.info("Send the msg");
		test.info("EXPECTED RESULT:: It should send the msg with bold");
		Assert.assertEquals(a, "input-bold-btn input-action-btn");
		test.pass(a);
		Assert.assertEquals(a2, "input-bold-btn input-action-btn active");
		test.pass(a2);
		Assert.assertEquals(a1, "Abcdefghijklmnopqrstuvwxyz");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT:: It is sending the msg with bold");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();	
	}
	@Test
	public void tests016() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='input-italic-btn input-action-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='input-italic-btn input-action-btn']")).click();
		String a2=driver.findElement(By.xpath("//div[@class='input-italic-btn input-action-btn active']")).getAttribute("class");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("hi");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//span[@class='received-message-text'])[9]")).getText();
		Thread.sleep(1000);
		ExtentTest test= Extent.createTest("Click on italic & Enter text");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: android@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("Click on user");
		test.info("Click on italic");
		test.info("Enter text");
		test.info("Send the msg");
		test.info("EXPECTED RESULT:: It should send the msg with italic");
		Assert.assertEquals(a, "input-italic-btn input-action-btn");
		test.pass(a);
		Assert.assertEquals(a2, "input-italic-btn input-action-btn active");
		test.pass(a2);
		Assert.assertEquals(a1, "hii");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT:: It is sending the msg with italic");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();	
	}
	@Test
	public void tests017() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='Added By']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='input-underline-btn input-action-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='input-underline-btn input-action-btn']")).click();
		String a2=driver.findElement(By.xpath("//div[@class='input-underline-btn input-action-btn active']")).getAttribute("class");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//span[@class='received-message-text'])[4]")).getText();
		Thread.sleep(1000);
		ExtentTest test= Extent.createTest("Click on underline & Enter text");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: android@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("Click on user");
		test.info("Click on underline");
		test.info("Enter text");
		test.info("Send the msg");
		test.info("EXPECTED RESULT:: It should send the msg with underline");
		Assert.assertEquals(a, "input-underline-btn input-action-btn");
		test.pass(a);
		Assert.assertEquals(a2, "input-underline-btn input-action-btn active");
		test.pass(a2);
		Assert.assertEquals(a1, "test");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT:: It is sending the msg with underline");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();	
	}
	@Test
	public void tests018() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='Added By']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@class='input-strikethrough-btn input-action-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='input-strikethrough-btn input-action-btn']")).click();
		String a2=driver.findElement(By.xpath("//div[@class='input-strikethrough-btn input-action-btn active']")).getAttribute("class");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//span[@class='received-message-text'])[6]")).getText();
		Thread.sleep(1000);
		ExtentTest test= Extent.createTest("Click on strike through & Enter text");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: android@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("Click on user");
		test.info("Click on strike through");
		test.info("Enter text");
		test.info("Send the msg");
		test.info("EXPECTED RESULT:: It should send the msg with strike through");
		Assert.assertEquals(a, "input-strikethrough-btn input-action-btn");
		test.pass(a);
		Assert.assertEquals(a2, "input-strikethrough-btn input-action-btn active");
		test.pass(a2);
		Assert.assertEquals(a1, "test");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT:: It is sending the msg with strike through");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();	
	}
	@Test
	public void tests019() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("android@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='Added By']")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@class='input-bold-btn input-action-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='input-bold-btn input-action-btn']")).click();
		String a=driver.findElement(By.xpath("//div[@class='input-bold-btn input-action-btn active']")).getAttribute("class");
		Thread.sleep(1000);
		String a6=driver.findElement(By.xpath("//div[@class='input-italic-btn input-action-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='input-italic-btn input-action-btn']")).click();
		String a4=driver.findElement(By.xpath("//div[@class='input-italic-btn input-action-btn active']")).getAttribute("class");
		Thread.sleep(1000);
		String a7=driver.findElement(By.xpath("//div[@class='input-underline-btn input-action-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='input-underline-btn input-action-btn']")).click();
		String a2=driver.findElement(By.xpath("//div[@class='input-underline-btn input-action-btn active']")).getAttribute("class");
		Thread.sleep(1000);
		String a8=driver.findElement(By.xpath("//div[@class='input-strikethrough-btn input-action-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//div[@class='input-strikethrough-btn input-action-btn']")).click();
		String a3=driver.findElement(By.xpath("//div[@class='input-strikethrough-btn input-action-btn active']")).getAttribute("class");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("(//span[@class='received-message-text'])[6]")).getText();
		Thread.sleep(1000);
		ExtentTest test= Extent.createTest("Click on strike through & Enter text");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Email: android@tm.com");
		test.info("Password: 123456");
		test.info("Login: Click on login");
		test.info("Click on user");
		test.info("Click on strike through");
		test.info("Enter text");
		test.info("Send the msg");
		test.info("EXPECTED RESULT:: It should send the msg with strike through");
		Assert.assertEquals(a5, "input-bold-btn input-action-btn");
		test.pass(a5);
		Assert.assertEquals(a, "input-bold-btn input-action-btn active");
		test.pass(a);
		Assert.assertEquals(a6, "input-italic-btn input-action-btn");
		test.pass(a6);
		Assert.assertEquals(a4, "input-italic-btn input-action-btn active");
		test.pass(a4);
		Assert.assertEquals(a7, "input-underline-btn input-action-btn");
		test.pass(a7);
		Assert.assertEquals(a2, "input-underline-btn input-action-btn active");
		test.pass(a2);
		Assert.assertEquals(a8, "input-strikethrough-btn input-action-btn");
		test.pass(a8);
		Assert.assertEquals(a3, "input-strikethrough-btn input-action-btn active");
		test.pass(a3);
		Assert.assertEquals(a1, "test");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT:: It is sending the msg with strike through");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();	
	}
	@AfterSuite
	public void endTest() {
		Extent.flush();
	}
}
