package msgwithrightclick;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class msg1 {
	WebDriver driver;
	ExtentHtmlReporter HtmlReporter;
	ExtentReports Extent;

	@BeforeSuite
	public void Starttest() {
		HtmlReporter = new ExtentHtmlReporter("msgwithrightclick1.html");
		Extent = new ExtentReports();
		Extent.attachReporter(HtmlReporter);
	}
	@Test
	public void testcase0143() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("siddhu");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='siddhu']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions a1=new Actions(driver);
		a1.contextClick(e).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li//a[@data-action='copy']")).click();
		Thread.sleep(500);
		WebElement e1=driver.findElement(By.xpath("//span[@id='copyMessageSendBtn']"));
		a1.doubleClick(e1).perform();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Assert.assertEquals("", a);
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@id='messageInput']")).click();
		//a1.contextClick(e1).build().perform();
		Thread.sleep(500);
		a1.sendKeys(Keys.CONTROL+"v").build().perform();
		Thread.sleep(2000);
		ExtentTest test=Extent.createTest("Click on copy in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user : siddhu");
		test.info("Select any msg");
		test.info("Right click on selected msg");
		test.info("Click on copy");
		test.info("Click on copy icon");
		test.info("EXPECTED RESULT ::  It should copy the selected msg ");	
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Message copied! ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("copy");
	}
	@Test
	public void testcase0144() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("siddhu");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='siddhu']")).click();
		Thread.sleep(500);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions a1=new Actions(driver);
		a1.contextClick(e).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li//a[@data-action='copy']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@id='copyMessageCloseBtn']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Assert.assertEquals("", a);
		Thread.sleep(2000);
		ExtentTest test=Extent.createTest("Click on copy with cancel button in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user : siddhu");
		test.info("Select any msg");
		test.info("Right click on selected msg");
		test.info("Click on copy");
		test.info("Click on cancel icon");
		test.info("EXPECTED RESULT ::  It should not copy the selected msg ");
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not copied the selected msg ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("1");
	}
	@Test
	public void testcase0145() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("siddhu");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='siddhu']")).click();
		Thread.sleep(500);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions a1=new Actions(driver);
		a1.contextClick(e).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li//a[@data-action='copy']")).click();
		Thread.sleep(500);
		//select another checkbox
		driver.findElement(By.xpath("//label[@for='copyMessage_11918']")).click();
		Thread.sleep(1000);
		WebElement e2=driver.findElement(By.xpath("//*[@id=\"copyMessageSendBtn\"]"));
		a1.click(e2).build().perform();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Assert.assertEquals("", a);
		Thread.sleep(2000);
		ExtentTest test=Extent.createTest("Click on copy of multiple msgs in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user : siddhu");
		test.info("Select any msg");
		test.info("Right click on selected msg");
		test.info("Click on copy");
		test.info("Select multiple msgs");
		test.info("Click on copy icon");
		test.info("EXPECTED RESULT ::  It should copy the selected msg ");
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Message Copied ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("2");
	}
	@Test
	public void testcase0146() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("siddhu");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='siddhu']")).click();
		Thread.sleep(500);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions a1=new Actions(driver);
		a1.contextClick(e).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li//a[@data-action='copy']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='copyMessage_11918']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='copyMessageCloseBtn']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Assert.assertEquals("", a);
		Thread.sleep(2000);
		ExtentTest test=Extent.createTest("Click on copy with cancel button in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user : siddhu");
		test.info("Select any msg");
		test.info("Right click on selected msg");
		test.info("Click on copy");
		test.info("Select multiple msgs checkbox");
		test.info("Click on cancel icon");
		test.info("EXPECTED RESULT ::  It should not copy the selected msg ");
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not copied the selected msg ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("3");
	}
	@Test
	public void testcase0147() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("siddhu");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='siddhu']")).click();
		Thread.sleep(500);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions a1=new Actions(driver);
		a1.contextClick(e).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li//a[@data-action='reply']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("1");
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//span[@class='reply-sender-name']")).getText();
		Assert.assertEquals(a, "You");
		Thread.sleep(2000);
		ExtentTest test=Extent.createTest("Click on reply to msg in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user : siddhu");
		test.info("Select any msg");
		test.info("Right click on selected msg");
		test.info("Click on reply");
		test.info("Enter any text");
		test.info("Click on send button");
		test.info("EXPECTED RESULT ::  It should send reply msg to the user ");
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is sending reply msg to the user ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("4");
	}
	@Test
	public void testcase0148() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("siddhu");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='siddhu']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='text-reply-name']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//span[@class='reply-sender-name']")).getText();
		Thread.sleep(500);
		System.out.println(a);
		Thread.sleep(2000);
		ExtentTest test=Extent.createTest("Click on replied msg in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user : siddhu");
		test.info("Select replied msg");
		test.info("Click on it");
		test.info("EXPECTED RESULT ::  It should display the msg ");
		Assert.assertEquals("You", a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the msg ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("5");
	}
	@Test
	public void testcase0149() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("siddhu");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='siddhu']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions a1=new Actions(driver);
		a1.contextClick(e).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li//a[@data-action='delete']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//span[@id='deleteMessageSendBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='deleteMessageSendBtn']")).click();
		Thread.sleep(500);
		String a3=driver.findElement(By.xpath("//input[@id='deleteConfirmationNoBtn']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='deleteConfirmationNoBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=Extent.createTest("Click on delete msg with no button in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user : mahi");
		test.info("Select any msg");
		test.info("Right click on selected msg");
		test.info("Click on delete");
		test.info("Click on delete button");
		test.info("Click on no button");
		test.info("EXPECTED RESULT ::  It should not delete the msg ");
		Assert.assertEquals(a, "DEL");
		test.pass(a);
		Assert.assertEquals(a3, "deleteConfirmationNoBtn");
		test.pass(a3);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deleting the msg ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("6");
	}
	@Test
	public void testcase0150() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("siddhu");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='siddhu']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions a1=new Actions(driver);
		a1.contextClick(e).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li//a[@data-action='delete']")).click();
		Thread.sleep(500);
		String a2=driver.findElement(By.xpath("//span[@id='deleteMessageSendBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='deleteMessageSendBtn']")).click();
		Thread.sleep(500);
		String a3=driver.findElement(By.xpath("//input[@id='deleteConfirmationYesBtn']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='deleteConfirmationYesBtn']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Assert.assertEquals("Message Deleted!", a);
		Thread.sleep(2000);
		ExtentTest test=Extent.createTest("Click on delete msg with yes button ");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user : mahi");
		test.info("Select any msg");
		test.info("Right click on selected msg");
		test.info("Click on delete");
		test.info("Click on delete button");
		test.info("Click on yes button");
		test.info("EXPECTED RESULT ::  It should delete the msg in the user chat page ");
		Assert.assertEquals(a2, "DEL");
		test.pass(a2);
		Assert.assertEquals(a3, "deleteConfirmationYesBtn");
		test.pass(a3);
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Message Deleted! ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("7");
	}
	@Test
	public void testcase0151() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("mahi");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='mahi']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions a1=new Actions(driver);
		a1.contextClick(e).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li//a[@data-action='delete']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//span[@id='deleteMessageCloseBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='deleteMessageCloseBtn']")).click();
		Thread.sleep(500);
		Thread.sleep(2000);
		ExtentTest test=Extent.createTest("Click on delete msg with cancel button in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user : mahi");
		test.info("Select any msg");
		test.info("Right click on selected msg");
		test.info("Click on delete");
		test.info("Click on cancel button");
		test.info("EXPECTED RESULT ::  It should click on cancel button ");
		Assert.assertEquals(a, "CANCEL");
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is clicking on cancel button ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("8");
	}
	@Test
	public void testcase0152() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("mahi");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='mahi']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions a1=new Actions(driver);
		a1.contextClick(e).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li//a[@data-action='delete']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='deleteMessage_11952']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//span[@id='deleteMessageSendBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='deleteMessageSendBtn']")).click();
		Thread.sleep(500);
		String a3=driver.findElement(By.xpath("//input[@id='deleteConfirmationNoBtn']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='deleteConfirmationNoBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=Extent.createTest("Select multiple msgs to delete with no button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user : mahi");
		test.info("Select any msg");
		test.info("Right click on selected msg");
		test.info("Click on delete");
		test.info("Click on delete button");
		test.info("Click on no button");
		test.info("EXPECTED RESULT ::  It should not delete the multiple msgs ");
		Assert.assertEquals(a, "DEL");
		test.pass(a);
		Assert.assertEquals(a3, "deleteConfirmationNoBtn");
		test.pass(a3);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deleting the multiple msgs ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("9");
	}
	@Test
	public void testcase0153() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("mahi");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='mahi']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions a1=new Actions(driver);
		a1.contextClick(e).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li//a[@data-action='delete']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='deleteMessage_11952']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//span[@id='deleteMessageSendBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='deleteMessageSendBtn']")).click();
		Thread.sleep(500);
		String a3=driver.findElement(By.xpath("//input[@id='deleteConfirmationYesBtn']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='deleteConfirmationYesBtn']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Assert.assertEquals("Messages Deleted!", a);
		Thread.sleep(2000);
		ExtentTest test=Extent.createTest("Delete multiple msgs with yes button in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user : Mahi");
		test.info("Select any msg");
		test.info("Right click on selected msg");
		test.info("Click on delete");
		test.info("Click on delete button");
		test.info("Click on yes button");
		test.info("EXPECTED RESULT ::  It should delete the multiple msgs in the user chat page ");
		Assert.assertEquals(a2, "DEL");
		test.pass(a2);
		Assert.assertEquals(a3, "deleteConfirmationYesBtn");
		test.pass(a3);
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Messages Deleted! ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("10");
	}
	@Test
	public void testcase0154() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("mahi");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='mahi']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions a1=new Actions(driver);
		a1.contextClick(e).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li//a[@data-action='flag']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//span[@class='flag-conversation-label-icon']")).getAttribute("class");
		Assert.assertEquals(a,"flag-conversation-label-icon");
		Thread.sleep(2000);
		ExtentTest test=Extent.createTest("Click on flag to the msg in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user : mahi");
		test.info("Select any msg");
		test.info("Right click on selected msg");
		test.info("Click on flag");
		test.info("EXPECTED RESULT ::  It should display flag symbol to the msg ");
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying flag symbol to the msg ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("11");
	}
	@Test
	public void testcase0155() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("mahi");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='mahi']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions a1=new Actions(driver);
		a1.contextClick(e).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li//a[@data-action='flag']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//span[@class='flag-conversation-label-icon']")).getText();
		Assert.assertEquals(a,"");
		Thread.sleep(2000);
		ExtentTest test=Extent.createTest("Click on Unflag to the msg in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user : mahi");
		test.info("Select any msg");
		test.info("Right click on selected msg");
		test.info("Click on Unflag");
		test.info("EXPECTED RESULT ::  It should not display flag symbol to the msg ");
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not displaying flag symbol to the msg ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("12");
	}
	@Test
	public void testcase0156() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("mahi");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='mahi']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions a1=new Actions(driver);
		a1.contextClick(e).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li//a[@data-action='info']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//div[@class='message-content-wrapper']")).getAttribute("class");
		Assert.assertEquals("message-content-wrapper", a);
		Thread.sleep(2000);
		ExtentTest test=Extent.createTest("Click on info to the msg in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user : mahi");
		test.info("Select any msg");
		test.info("Right click on selected msg");
		test.info("Click on info");
		test.info("EXPECTED RESULT ::  It should display details of the msg ");
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying details of the msg ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("13");
	}
	@Test
	public void testcase0157() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("mahi");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='mahi']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions a1=new Actions(driver);
		a1.contextClick(e).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li//a[@data-action='info']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//span[@id='messageInfoModalCloseBtn']")).getAttribute("id");
		driver.findElement(By.xpath("//span[@id='messageInfoModalCloseBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=Extent.createTest("Click on info & Click on close button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user : mahi");
		test.info("Select any msg");
		test.info("Right click on selected msg");
		test.info("Click on info");
		test.info("Click on close button");
		test.info("EXPECTED RESULT ::  It should close the info of the msg ");
		Assert.assertEquals(a, "messageInfoModalCloseBtn");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is closing the info of the msg ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("14");
	}
	@Test
	public void testcase0158() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("siddhu");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='siddhu']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("(//span[@class='received-message-text'])[2]"));
		Actions a1=new Actions(driver);
		a1.contextClick(e).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li//a[@data-action='respond_later']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//div[@class='respond-later-chat-icon']")).getAttribute("title");
		Assert.assertEquals("Respond Later", a);
		Thread.sleep(2000);
		ExtentTest test=Extent.createTest("Click on respond later to user msg");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user : siddhu");
		test.info("Select any msg");
		test.info("Right click on selected msg");
		test.info("Click on respond later");
		test.info("EXPECTED RESULT ::  It should display respond later icon ");		
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying respond later icon ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("15");
	}
	@Test
	public void testcase0159() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("siddhu");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='siddhu']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("(//span[@class='received-message-text'])[2]"));
		Actions a1=new Actions(driver);
		a1.contextClick(e).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li//a[@data-action='respond_later']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//div[@class='respond-later-chat-icon']")).getText();
		Assert.assertEquals("", a);
		Thread.sleep(2000);
		ExtentTest test=Extent.createTest("Click on clear to the respond later to user msg");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user : siddhu");
		test.info("Select any msg");
		test.info("Right click on selected msg");
		test.info("Click on clear");
		test.info("EXPECTED RESULT ::  It should clear respond later icon ");		
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is clearing respond later icon ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("16");
	}
	@Test
	public void testcase0160() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("siddhu");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='siddhu']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions a1=new Actions(driver);
		a1.contextClick(e).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li//a[@data-action='respond_later']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Assert.assertEquals("Not applicable for self message", a);
		Thread.sleep(2000);
		ExtentTest test=Extent.createTest("Click on respond later for self message");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user : siddhu");
		test.info("Select self msg");
		test.info("Right click on selected msg");
		test.info("Click on respond later");
		test.info("EXPECTED RESULT ::  It should not click on respond later  ");
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Not applicable for self message ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("17");
	}
	@Test
	public void testcase0161() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("jack");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='jack']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions a1=new Actions(driver);
		a1.contextClick(e).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li//a[@data-action='recall']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//span[@id='recallMessageSendBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='recallMessageSendBtn']")).click();
		Thread.sleep(500);
		String a3=driver.findElement(By.xpath("//input[@id='recallConfirmationNoBtn']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='recallConfirmationNoBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=Extent.createTest("Click on RECALL with no button in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user : jack");
		test.info("Select any msg");
		test.info("Right click on selected msg");
		test.info("Click on RECALL");
		test.info("Click on recall button");
		test.info("Click on no button");
		test.info("EXPECTED RESULT ::  It should not recall the msg ");
		Assert.assertEquals(a, "RECALL");
		test.pass(a);
		Assert.assertEquals(a3, "recallConfirmationNoBtn");
		test.pass(a3);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not recalling the msg ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("18");
	}
	@Test
	public void testcase0162() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("jack");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='jack']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions a1=new Actions(driver);
		a1.contextClick(e).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li//a[@data-action='recall']")).click();
		Thread.sleep(500);
		String a2=driver.findElement(By.xpath("//span[@id='recallMessageSendBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='recallMessageSendBtn']")).click();
		Thread.sleep(500);
		String a3=driver.findElement(By.xpath("//input[@id='recallConfirmationYesBtn']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='recallConfirmationYesBtn']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Assert.assertEquals("Message Recalled!", a);
		Thread.sleep(2000);
		ExtentTest test=Extent.createTest("Click on RECALL msg with yes button ");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user : jack");
		test.info("Select any msg");
		test.info("Right click on selected msg");
		test.info("Click on RECALL");
		test.info("Click on recall button");
		test.info("Click on yes button");
		test.info("EXPECTED RESULT ::  It should recall the msg in the user chat page ");
		Assert.assertEquals(a2, "RECALL");
		test.pass(a2);
		Assert.assertEquals(a3, "recallConfirmationYesBtn");
		test.pass(a3);
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Message Recalled! ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("19");
	}
	@Test
	public void testcase0163() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("jack");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='jack']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions a1=new Actions(driver);
		a1.contextClick(e).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li//a[@data-action='recall']")).click();
		Thread.sleep(500);
		String a2=driver.findElement(By.xpath("//span[@id='recallMessageCloseBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='recallMessageCloseBtn']")).click();
		Thread.sleep(500);
		Thread.sleep(500);
		Thread.sleep(2000);
		ExtentTest test=Extent.createTest("Click on recall msg with cancel button in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user : mahi");
		test.info("Select any msg");
		test.info("Right click on selected msg");
		test.info("Click on recall");
		test.info("Click on cancel button");
		test.info("EXPECTED RESULT ::  It should click on cancel button ");
		Assert.assertEquals(a2, "CANCEL");
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is clicking on cancel button ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("20");
	}
	@Test
	public void testcase0164() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("jack");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='jack']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions a1=new Actions(driver);
		a1.contextClick(e).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li//a[@data-action='recall']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='recallMessage_11950']")).click();
		Thread.sleep(500);
		String a2=driver.findElement(By.xpath("//span[@id='recallMessageSendBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='recallMessageSendBtn']")).click();
		Thread.sleep(500);
		String a3=driver.findElement(By.xpath("//input[@id='recallConfirmationNoBtn']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='recallConfirmationNoBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=Extent.createTest("Select multiple msgs to RECALL with no button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user : mahi");
		test.info("Select any msg");
		test.info("Right click on selected msg");
		test.info("Click on RECALL");
		test.info("Click on recall button");
		test.info("Click on no button");
		test.info("EXPECTED RESULT ::  It should not recall the multiple msgs ");
		Assert.assertEquals(a2, "RECALL");
		test.pass(a2);
		Assert.assertEquals(a3, "recallConfirmationNoBtn");
		test.pass(a3);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not recalling the multiple msgs ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("21");
	}
	@Test
	public void testcase0165() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("jack");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='jack']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions a1=new Actions(driver);
		a1.contextClick(e).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li//a[@data-action='recall']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='recallMessage_11950']")).click();
		Thread.sleep(500);
		String a2=driver.findElement(By.xpath("//span[@id='recallMessageSendBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='recallMessageSendBtn']")).click();
		Thread.sleep(500);
		String a3=driver.findElement(By.xpath("//input[@id='recallConfirmationYesBtn']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='recallConfirmationYesBtn']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Assert.assertEquals("Message Recalled!", a);
		Thread.sleep(2000);
		ExtentTest test=Extent.createTest("RECALL multiple msgs with yes button in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user : Mahi");
		test.info("Select any msg");
		test.info("Right click on selected msg");
		test.info("Click on RECALL");
		test.info("Click on recall button");
		test.info("Click on yes button");
		test.info("EXPECTED RESULT ::  It should recall the multiple msgs in the user chat page ");
		Assert.assertEquals(a2, "RECALL");
		test.pass(a2);
		Assert.assertEquals(a3, "recallConfirmationYesBtn");
		test.pass(a3);
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Message Recalled! ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("22");
	}
	@AfterSuite
	public void endTest() {
		Extent.flush();
	}
}
