package msgwithrightclick;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class msgwithdropdown {
	WebDriver driver;
	ExtentHtmlReporter HtmlReporter;
	ExtentReports extent;

	@BeforeSuite
	public void Starttest() {
		HtmlReporter = new ExtentHtmlReporter("msgwithdropdown.html");
		extent = new ExtentReports();
		extent.attachReporter(HtmlReporter);
	}
	@Test
	public void testcase0166() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("siddhu");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='siddhu']")).click();
		Thread.sleep(1000);
		Actions act = new Actions(driver);		
		WebElement a1 = driver.findElement(By.xpath("//div[@class='conversation-option-wrapper']"));
		act.moveToElement(a1).build().perform();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='conversation-option-button']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='conversation-copy-button conversation-option']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"copyMessageSendBtn\"]")).click();
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Assert.assertEquals("", a);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on copy in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user");
		test.info("Select any msg");
		test.info("click on dropdown of selected msg");
		test.info("Click on copy");
		test.info("Click on copy icon");
		test.info("EXPECTED RESULT ::  It should copy the selected msg ");	
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Message copied! ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("copy");
	}
	@Test
	public void testcase0167() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("siddhu");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='siddhu']")).click();
		Thread.sleep(1000);
		Actions act = new Actions(driver);		
		WebElement a1 = driver.findElement(By.xpath("//div[@class='conversation-option-wrapper']"));
		act.moveToElement(a1).build().perform();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='conversation-option-button']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='conversation-copy-button conversation-option']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//span[@id='copyMessageCloseBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='copyMessageCloseBtn']")).click();
		Thread.sleep(500);		
		Assert.assertEquals("CANCEL", a);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on copy with cancel in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user");
		test.info("Select any msg");
		test.info("click on dropdown of selected msg");
		test.info("Click on copy");
		test.info("Click on cancel icon");
		test.info("EXPECTED RESULT ::  It should not copy the selected msg ");	
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not copying the selected msg ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("1");
	}
	@Test
	public void testcase0168() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("siddhu");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='siddhu']")).click();
		Thread.sleep(1000);
		Actions act = new Actions(driver);		
		WebElement a1 = driver.findElement(By.xpath("//div[@class='conversation-option-wrapper']"));
		act.moveToElement(a1).build().perform();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='conversation-option-button']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='conversation-copy-button conversation-option']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='copyMessage_11918']")).click();
		driver.findElement(By.xpath("//*[@id=\"copyMessageSendBtn\"]")).click();
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Assert.assertEquals("", a);
		Thread.sleep(2000);
		//driver.findElement(By.xpath("//div[@id='messageInput']")).click();
		//a1.contextClick(e1).build().perform();
		Thread.sleep(500);
		//a1.sendKeys(Keys.CONTROL+"v").build().perform();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on copy multiple msgs in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user");
		test.info("Select any msg");
		test.info("click on dropdown of selected msg");
		test.info("Click on copy");
		test.info("Select another msg");
		test.info("Click on copy icon");
		test.info("EXPECTED RESULT ::  It should copy the selected msgs ");	
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Messages copied! ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("2");
	}
	@Test
	public void testcase0169() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("siddhu");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='siddhu']")).click();
		Thread.sleep(1000);
		Actions act = new Actions(driver);		
		WebElement a1 = driver.findElement(By.xpath("//div[@class='conversation-option-wrapper']"));
		act.moveToElement(a1).build().perform();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='conversation-option-button']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='conversation-copy-button conversation-option']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//span[@id='copyMessageCloseBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='copyMessageCloseBtn']")).click();
		Thread.sleep(500);		
		Assert.assertEquals("CANCEL", a);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on copy with cancel in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user");
		test.info("Select any msg");
		test.info("click on dropdown of selected msg");
		test.info("Click on copy");
		test.info("Select another msg");
		test.info("Click on copy icon");
		test.info("EXPECTED RESULT ::  It should not copy the selected msgs ");	
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not copying the selected msgs ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("3");
	}
	@Test
	public void testcase0170() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("siddhu");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='siddhu']")).click();
		Thread.sleep(1000);
		Actions act = new Actions(driver);		
		WebElement a1 = driver.findElement(By.xpath("//div[@class='conversation-option-wrapper']"));
		act.moveToElement(a1).build().perform();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='conversation-option-button']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='conversation-reply-button conversation-option']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("1");
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(500);		
		String a=driver.findElement(By.xpath("//span[@class='reply-sender-name']")).getText();
		Assert.assertEquals("You", a);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on reply in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user");
		test.info("Select any msg");
		test.info("click on dropdown of selected msg");
		test.info("Click on reply");
		test.info("Enter text : 1");
		test.info("Click on send button");
		test.info("EXPECTED RESULT ::  It should reply to the selected msg ");	
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is replying to the selected msg ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("4");
	}
	@Test
	public void testcase0171() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("siddhu");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='siddhu']")).click();
		Thread.sleep(1000);
		Thread.sleep(500);		
		driver.findElement(By.xpath("//span[@class='reply-sender-name']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//span[@class='reply-sender-name']")).getText();
		Assert.assertEquals("You", a);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on replied msg in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user");
		test.info("Select replied msg");
		test.info("Click on it");
		test.info("EXPECTED RESULT ::  It should display replied msg ");	
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying replied msg ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("5");
	}
	@Test
	public void testcase0172() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("mahi");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='mahi']")).click();
		Thread.sleep(1000);
		Actions act = new Actions(driver);		
		WebElement a1 = driver.findElement(By.xpath("//div[@class='conversation-option-wrapper']"));
		act.moveToElement(a1).build().perform();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='conversation-option-button']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='conversation-delete-button conversation-option']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//span[@id='deleteMessageSendBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='deleteMessageSendBtn']")).click();
		Thread.sleep(500);
		String a3=driver.findElement(By.xpath("//input[@id='deleteConfirmationNoBtn']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='deleteConfirmationNoBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on delete with no button in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user");
		test.info("Select any msg");
		test.info("Click on dropdown of selected msg");
		test.info("Click on delete");
		test.info("Click on no button");
		test.info("EXPECTED RESULT ::  It should not delete the selected msgs ");	
		Assert.assertEquals(a, "DEL");
		test.pass(a);
		Assert.assertEquals(a3, "deleteConfirmationNoBtn");
		test.pass(a3);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deleting the selected msgs ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("6");
	}
	@Test
	public void testcase0173() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("mahi");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='mahi']")).click();
		Thread.sleep(1000);
		Actions act = new Actions(driver);		
		WebElement a1 = driver.findElement(By.xpath("//div[@class='conversation-option-wrapper']"));
		act.moveToElement(a1).build().perform();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='conversation-option-button']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='conversation-delete-button conversation-option']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//span[@id='deleteMessageSendBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='deleteMessageSendBtn']")).click();
		Thread.sleep(500);
		String a3=driver.findElement(By.xpath("//input[@id='deleteConfirmationYesBtn']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='deleteConfirmationYesBtn']")).click();
		Thread.sleep(500);
		String a2=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Assert.assertEquals("Message Deleted!", a2);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on delete with Yes button in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user");
		test.info("Select any msg");
		test.info("Click on dropdown of selected msg");
		test.info("Click on delete");
		test.info("Click on Yes button");
		test.info("EXPECTED RESULT ::  It should delete the selected msgs ");	
		Assert.assertEquals(a, "DEL");
		test.pass(a);
		Assert.assertEquals(a3, "deleteConfirmationYesBtn");
		test.pass(a3);
		System.out.println(a2);
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Message Deleted! ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("7");
	}
	@Test
	public void testcase0174() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("mahi");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='mahi']")).click();
		Thread.sleep(1000);
		Actions act = new Actions(driver);		
		WebElement a1 = driver.findElement(By.xpath("//div[@class='conversation-option-wrapper']"));
		act.moveToElement(a1).build().perform();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='conversation-option-button']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='conversation-delete-button conversation-option']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='deleteMessage_11939']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//span[@id='deleteMessageSendBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='deleteMessageSendBtn']")).click();
		Thread.sleep(500);
		String a3=driver.findElement(By.xpath("//input[@id='deleteConfirmationNoBtn']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='deleteConfirmationNoBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on delete with no button in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user");
		test.info("Select any msg");
		test.info("Click on dropdown of selected msg");
		test.info("Click on delete");
		test.info("Select the checkbox of msgs");
		test.info("Deselect the checkbox of selected msg");
		test.info("Click on no button");
		test.info("EXPECTED RESULT ::  It should not delete the selected msgs ");	
		Assert.assertEquals(a, "DEL");
		test.pass(a);
		Assert.assertEquals(a3, "deleteConfirmationNoBtn");
		test.pass(a3);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deleting the selected msgs ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("8");
	}
	@Test
	public void testcase0175() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("mahi");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='mahi']")).click();
		Thread.sleep(1000);
		Actions act = new Actions(driver);		
		WebElement a1 = driver.findElement(By.xpath("//div[@class='conversation-option-wrapper']"));
		act.moveToElement(a1).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@class='conversation-option-button']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='conversation-delete-button conversation-option']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='deleteMessage_11939']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//span[@id='deleteMessageSendBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='deleteMessageSendBtn']")).click();
		Thread.sleep(500);
		String a3=driver.findElement(By.xpath("//input[@id='deleteConfirmationYesBtn']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='deleteConfirmationYesBtn']")).click();
		Thread.sleep(500);
		String a2=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Assert.assertEquals("Messages Deleted!", a2);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on delete with Yes button in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user");
		test.info("Select any msg");
		test.info("Click on dropdown of selected msg");
		test.info("Click on delete");
		test.info("Select the checkbox of msgs");
		test.info("Deselect the checkbox of selected msg");
		test.info("Click on Yes button");
		test.info("EXPECTED RESULT ::  It should delete the selected msgs ");	
		Assert.assertEquals(a, "DEL");
		test.pass(a);
		Assert.assertEquals(a3, "deleteConfirmationYesBtn");
		test.pass(a3);
		System.out.println(a2);
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Messages Deleted! ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("9");
	}
	@Test
	public void testcase0176() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='Test']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='mahi']")).click();
		Thread.sleep(1000);
		Actions act = new Actions(driver);		
		WebElement a1 = driver.findElement(By.xpath("//div[@class='conversation-option-wrapper']"));
		act.moveToElement(a1).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@class='conversation-option-button']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='conversation-flag-button conversation-option']")).click();
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//span[@class='flag-conversation-label-icon']")).getText();
		Assert.assertEquals("", a);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on flag to msg in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user");
		test.info("Select any msg");
		test.info("Click on dropdown of selected msg");
		test.info("Click on flag");
		test.info("EXPECTED RESULT ::  It should display flag symbol to the selected msg ");	
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying flag symbol to the selected msg ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("10");
	}
	@Test
	public void testcase0177() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='mahi']")).click();
		Thread.sleep(1000);
		Actions act = new Actions(driver);		
		WebElement a1 = driver.findElement(By.xpath("//div[@class='conversation-option-wrapper']"));
		act.moveToElement(a1).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@class='conversation-option-button']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='conversation-flag-button conversation-option']")).click();
		Thread.sleep(500);
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//span[@class='flag-conversation-label-icon']")).getText();
		Assert.assertEquals("", a);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on flag to msg in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user");
		test.info("Select any msg");
		test.info("Click on dropdown of selected msg");
		test.info("Click on Unflag");
		test.info("EXPECTED RESULT ::  It should not display flag symbol to the selected msg ");	
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not displaying flag symbol to the selected msg ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("11");
	}
	@Test
	public void testcase0178() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='mahi']")).click();
		Thread.sleep(1000);
		Actions act = new Actions(driver);		
		WebElement a1 = driver.findElement(By.xpath("//div[@class='conversation-option-wrapper']"));
		act.moveToElement(a1).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@class='conversation-option-button']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='conversation-info-button conversation-option']")).click();
		Thread.sleep(500);
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//div[@class='user-text-message']")).getText();
		Assert.assertEquals("test", a);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on info to msg in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user");
		test.info("Select any msg");
		test.info("Click on dropdown of selected msg");
		test.info("Click on info");
		test.info("EXPECTED RESULT ::  It should display info to the selected msg ");	
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying info to the selected msg ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("12");
	}
	@Test
	public void testcase0179() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='mahi']")).click();
		Thread.sleep(1000);
		Actions act = new Actions(driver);		
		WebElement a1 = driver.findElement(By.xpath("//div[@class='conversation-option-wrapper']"));
		act.moveToElement(a1).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@class='conversation-option-button']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='conversation-info-button conversation-option']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@id='messageInfoModalCloseBtn']")).click();
		Thread.sleep(500);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on info and click on close button in info");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user");
		test.info("Select any msg");
		test.info("Click on dropdown of selected msg");
		test.info("Click on info");
		test.info("Click on close button");
		test.info("EXPECTED RESULT ::  It should display chat list page ");	
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying chat list page ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("13");
	}
	@Test
	public void testcase0180() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("siddhu");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='siddhu']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("(//span[@class='received-message-text'])[2]"));
		Actions a1=new Actions(driver);
		a1.contextClick(e).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li//a[@data-action='respond_later']")).click();
		Thread.sleep(500);
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//div[@class='respond-later-chat-icon']")).getAttribute("class");
		Assert.assertEquals("respond-later-chat-icon", a);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on info to msg in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user");
		test.info("Select any msg");
		test.info("Click on dropdown of selected msg");
		test.info("Click on respond later");
		test.info("EXPECTED RESULT ::  It should display respond later symbol to the selected msg ");	
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying respond later symbol to the selected msg ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("14");
	}
	@Test
	public void testcase0181() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("siddhu");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='siddhu']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("(//span[@class='received-message-text'])[2]"));
		Actions a1=new Actions(driver);
		a1.contextClick(e).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li//a[@data-action='respond_later']")).click();
		Thread.sleep(500);
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//div[@class='respond-later-chat-icon']")).getAttribute("class");
		Assert.assertEquals("respond-later-chat-icon", a);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on clear for respond later symbol");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user");
		test.info("Select any msg");
		test.info("Click on dropdown of selected msg");
		test.info("Click on clear");
		test.info("EXPECTED RESULT ::  It should not display respond later symbol ");	
		test.pass(a);
		System.out.println(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not displaying respond later symbol ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("15");
	}
	@Test
	public void testcase0182() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='mahi']")).click();
		Thread.sleep(1000);
		Actions act = new Actions(driver);		
		WebElement a1 = driver.findElement(By.xpath("//div[@class='conversation-option-wrapper']"));
		act.moveToElement(a1).build().perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@class='conversation-option-button']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='conversation-respond-later-button conversation-option disabled']")).click();
		Thread.sleep(500);
		Thread.sleep(500);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Assert.assertEquals("Not applicable for self message", a);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on respond later for self msg");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user");
		test.info("Select any msg");
		test.info("Click on dropdown of selected msg");
		test.info("Click on respond later");
		test.info("EXPECTED RESULT ::  It should not click on respond later for self msgs ");	
		System.out.println(a);
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  Not applicable for self message ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("16");
	}
	@Test
	public void testcase0183() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("mahi");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='mahi']")).click();
		Thread.sleep(1000);
		Actions act = new Actions(driver);		
		WebElement a1 = driver.findElement(By.xpath("//div[@class='conversation-option-wrapper']"));
		act.moveToElement(a1).build().perform();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='conversation-option-button']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='conversation-recall-button conversation-option']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@id='recallMessageSendBtn']")).click();
		Thread.sleep(500);
		String a = driver.findElement(By.xpath("//input[@id='recallConfirmationNoBtn']")).getAttribute("id");
		Assert.assertEquals("recallConfirmationNoBtn", a);
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='recallConfirmationNoBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on recall with no button in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user");
		test.info("Select any msg");
		test.info("Click on dropdown of selected msg");
		test.info("Click on recall");
		test.info("Select the checkbox of msgs");
		test.info("Deselect the checkbox of selected msg");
		test.info("Click on no button");
		test.info("EXPECTED RESULT ::  It should not delete the selected msgs ");	
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deleting the selected msgs ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("17");
	}
	@Test
	public void testcase0184() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("Test");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='Test']")).click();
		Thread.sleep(1000);
		Actions act = new Actions(driver);		
		WebElement a1 = driver.findElement(By.xpath("//div[@class='conversation-option-wrapper']"));
		act.moveToElement(a1).build().perform();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='conversation-option-button']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='conversation-recall-button conversation-option']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@id='recallMessageSendBtn']")).click();
		Thread.sleep(500);
		String a = driver.findElement(By.xpath("//input[@id='recallConfirmationYesBtn']")).getAttribute("id");
		Assert.assertEquals("recallConfirmationYesBtn", a);
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='recallConfirmationYesBtn']")).click();
		Thread.sleep(500);
		String b=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Assert.assertEquals("Message Recalled!", b);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on recall with yes button in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user");
		test.info("Select any msg");
		test.info("Click on dropdown of selected msg");
		test.info("Click on recall");
		test.info("Select the checkbox of msgs");
		test.info("Deselect the checkbox of selected msg");
		test.pass(a);
		test.info("Click on yes button");
		test.info("EXPECTED RESULT ::  It should recall the selected msgs ");	
		test.pass(b);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It should display Message recalled!");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("18");
	}
	@Test
	public void testcase0185() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("Test");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='Test']")).click();
		Thread.sleep(1000);
		Actions act = new Actions(driver);		
		WebElement a1 = driver.findElement(By.xpath("//div[@class='conversation-option-wrapper']"));
		act.moveToElement(a1).build().perform();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='conversation-option-button']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='conversation-recall-button conversation-option']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='recallMessage_11961']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@id='recallMessageSendBtn']")).click();
		Thread.sleep(500);
		String a = driver.findElement(By.xpath("//input[@id='recallConfirmationNoBtn']")).getAttribute("id");
		Assert.assertEquals("recallConfirmationNoBtn", a);
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='recallConfirmationNoBtn']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Multiple msgs recall with no button in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user");
		test.info("Select any msg");
		test.info("Click on dropdown of selected msg");
		test.info("Click on recall");
		test.info("Select the checkbox of msgs");
		test.info("Deselect the checkbox of selected msg");
		test.info("Click on no button");
		test.info("EXPECTED RESULT ::  It should not delete the selected msgs ");	
		test.pass(a);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not deleting the selected msgs ");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("17");
	}
	@Test
	public void testcase0186() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/lavanya/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8081/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='email']")).sendKeys("maneesh@tm.com");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).sendKeys("Test");
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@data-name='Test']")).click();
		Thread.sleep(1000);
		Actions act = new Actions(driver);		
		WebElement a1 = driver.findElement(By.xpath("//div[@class='conversation-option-wrapper']"));
		act.moveToElement(a1).build().perform();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@class='conversation-option-button']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='conversation-recall-button conversation-option']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//label[@for='recallMessage_11961']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//span[@id='recallMessageSendBtn']")).click();
		Thread.sleep(500);
		String a = driver.findElement(By.xpath("//input[@id='recallConfirmationYesBtn']")).getAttribute("id");
		Assert.assertEquals("recallConfirmationYesBtn", a);
		Thread.sleep(500);
		driver.findElement(By.xpath("//input[@id='recallConfirmationYesBtn']")).click();
		Thread.sleep(500);
		String b=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Assert.assertEquals("Message Recalled!", b);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Multiple msgs recall with yes button in user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: maneesh@tm.com");
		test.info("Password: 123456");
		test.info("Login:click on login");
		test.info("Click on user");
		test.info("Select any msg");
		test.info("Click on dropdown of selected msg");
		test.info("Click on recall");
		test.info("Select the checkbox of msgs");
		test.info("Deselect the checkbox of selected msg");
		test.pass(a);
		test.info("Click on yes button");
		test.info("EXPECTED RESULT ::  It should recall the selected msgs ");	
		test.pass(b);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It should display Message recalled!");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
		System.out.println("18");
	}
	
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
